### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  id: StartupNextInstanceEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  langs:
  - csharp
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  type: Class
  summary: "Udostępnia dane dla <xref uid=&quot;langword_csharp_My.Application.StartupNextInstance&quot; name=&quot;My.Application.StartupNextInstance&quot; href=&quot;&quot;> </xref> zdarzeń."
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>Zdarzenie wystąpi, gdy rozpoczyna się kolejne wystąpienie pojedyncze wystąpienie aplikacji za pomocą modelu aplikacji Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Aby uzyskać więcej informacji, zobacz [omówienie modelu aplikacji Visual Basic](~/add/includes/ajax-current-ext-md.md).       StartupNextInstanceEventArgs zawiera argumenty wiersza polecenia wystąpienia kolejnych aplikacji oraz wskazuje, czy pierwsze wystąpienie aplikacji powinny być przesunięte na pierwszy plan podczas zamykania programu obsługi wyjątków."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public class StartupNextInstanceEventArgs : EventArgs
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs&quot;> </xref> klasy."
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>Zdarzenie wystąpi, gdy rozpoczyna się kolejne wystąpienie pojedyncze wystąpienie aplikacji za pomocą modelu aplikacji Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Aby uzyskać więcej informacji, zobacz [omówienie modelu aplikacji Visual Basic](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>zawiera argumenty wiersza polecenia wystąpienia kolejnych aplikacji oraz wskazuje, czy pierwsze wystąpienie aplikacji powinny być przesunięte na pierwszy plan podczas zamykania programu obsługi wyjątków.</xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>"
  syntax:
    content: public StartupNextInstanceEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args, bool bringToForegroundFlag);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; obiekt, który zawiera argumenty wiersza polecenia wystąpienia kolejnych aplikacji."
    - id: bringToForegroundFlag
      type: System.Boolean
      description: "A <xref:System.Boolean>wskazująca, czy należy dostosować pierwsze wystąpienie aplikacji na pierwszym planie, podczas zamykania programu obsługi wyjątków.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  id: BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Wskazuje, czy należy dostosować pierwsze wystąpienie aplikacji na pierwszym planie, podczas zamykania programu obsługi wyjątków."
  remarks: "Model aplikacji Visual Basic sprawdza wartość tej właściwości po uruchomieniu programu obsługi <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>zdarzeń.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Jeśli właściwość BringToForeground jest `True`, pierwsze wystąpienie aplikacji jest przesunięte na pierwszy plan. W przeciwnym razie pierwsze wystąpienie aplikacji pozostaje, gdzie został. Aby uzyskać więcej informacji, zobacz [omówienie modelu aplikacji Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public bool BringToForeground { get; set; }
    return:
      type: System.Boolean
      description: "A <xref:System.Boolean>wskazująca, czy należy dostosować pierwsze wystąpienie aplikacji na pierwszym planie, podczas zamykania programu obsługi wyjątków.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Pobiera wystąpienia aplikacji kolejne argumenty wiersza polecenia."
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>Zdarzenie wystąpi, gdy rozpoczyna się kolejne wystąpienie pojedyncze wystąpienie aplikacji za pomocą modelu aplikacji Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Aby uzyskać więcej informacji, zobacz [omówienie modelu aplikacji Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; obiekt, który zawiera argumenty wiersza polecenia wystąpienia kolejnych aplikacji."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
