### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler
  id: StartupNextInstanceEventHandler
  langs:
  - csharp
  name: StartupNextInstanceEventHandler
  nameWithType: StartupNextInstanceEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler
  type: Delegate
  summary: "Reprezentuje metodę, która będzie obsługiwać <xref uid=&quot;langword_csharp_My.Application.StartupNextInstance&quot; name=&quot;My.Application.StartupNextInstance&quot; href=&quot;&quot;> </xref> zdarzeń."
  remarks: "W języku Visual Basic nie trzeba jawnie pracy z tym obiektem delegowanym. Aby uzyskać więcej informacji zobacz <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>"
  example:
  - "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance?displayProperty=fullName>  \n  \n [Overview of the Visual Basic Application Model](~/add/includes/ajax-current-ext-md.md)"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void StartupNextInstanceEventHandler(object sender, StartupNextInstanceEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
