### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  id: NoStartupFormException
  children:
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: NoStartupFormException
  nameWithType: NoStartupFormException
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  type: Class
  summary: "Ten wyjątek jest zgłaszany przez Model aplikacji Visual Basic podczas <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>właściwość nie została ustawiona.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>"
  remarks: "Model aplikacji Visual Basic wymaga, aby aplikacja <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>Właściwości przed uruchomieniem <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>metody.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> Jeśli nie ustawiono właściwości, Model aplikacji Visual Basic zgłasza wyjątek. Aby uzyskać więcej informacji, zobacz [Rozszerzanie modelu aplikacji Visual Basic](~/add/includes/ajax-current-ext-md.md).      > [!NOTE] > Informacji o ustawianiu formularz startowy przy użyciu **projektanta projektu**, zobacz [strona aplikacji, Projektant projektu (Visual Basic)](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class NoStartupFormException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> klasy."
  remarks: "Model aplikacji Visual Basic wymaga, aby aplikacja <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>Właściwości przed uruchomieniem <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>metody.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> Jeśli nie ustawiono właściwości, Model aplikacji Visual Basic zgłasza wyjątek. Aby uzyskać więcej informacji, zobacz [Rozszerzanie modelu aplikacji Visual Basic](~/add/includes/ajax-current-ext-md.md).       W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>.</xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>      |||   |-|-|   | Właściwość | Wartość |   | <xref:System.Exception.InnerException%2A>| Odwołanie o wartości null (`Nothing` w języku Visual Basic). |   | <xref:System.Exception.Message%2A>| Ciąg zlokalizowany komunikat o błędzie. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> klasy z powodu określonego błędu."
  remarks: "Zawartość `message` parametr ma na celu rozumiane przez człowieka. Element wywołujący tego konstruktora jest wymagana, aby upewnić się, że ten ciąg został zlokalizowany dla bieżącego ustawienia kulturowego systemu.       <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>dziedziczy <xref:System.Exception>.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException> Ten konstruktor ustawia właściwości <xref:System.Exception>obiektów, jak pokazano w poniższej tabeli.</xref:System.Exception>      |||   |-|-|   | Właściwość | Wartość |   | <xref:System.Exception.InnerException%2A>| Odwołanie o wartości null (`Nothing` w języku Visual Basic) |   | <xref:System.Exception.Message%2A>| `message` Ciąg. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Komunikat zawierający opis błędu."
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> z zserializowanymi danymi."
  remarks: "Ten konstruktor jest wywoływana podczas deserializacji do odtworzenia obiekt wyjątku przesyłane przez strumień."
  syntax:
    content: protected NoStartupFormException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> Obiekt przechowujący dane zserializowanego obiektu dotyczące zgłaszanego wyjątku."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>Obiekt zawierający informacje kontekstowe dotyczące źródła lub miejsca docelowego.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> z określonego komunikatu o błędzie i odwołania do wyjątek wewnętrzny będący przyczyną tego wyjątku."
  remarks: "Zawartość `message` parametr ma na celu rozumiane przez człowieka. Element wywołujący tego konstruktora jest wymagana, aby upewnić się, że ten ciąg został zlokalizowany dla bieżącego ustawienia kulturowego systemu.       Wyjątek zgłaszany bezpośrednio w wyniku poprzedniego wyjątku powinien zawierać odwołanie do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A>Właściwości.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Właściwość zwraca tę samą wartość, która została przekazana do konstruktora lub odwołanie o wartości null, jeśli <xref:System.Exception.InnerException%2A>Właściwości nie dostarcza do konstruktora wartości wyjątku wewnętrznego.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:System.ApplicationException>.</xref:System.ApplicationException>      |||   |-|-|   | Właściwość | Wartość |   | <xref:System.Exception.InnerException%2A>| `inner` Odwołania. |   | <xref:System.Exception.Message%2A>| `message` Ciąg. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>Obiekt opisujący błąd.</xref:System.String>"
    - id: inner
      type: System.Exception
      description: "<xref:System.Exception>Obiekt będący przyczyną bieżącego wyjątku.</xref:System.Exception> Jeśli <xref:System.Exception.InnerException*>parametr nie jest odwołanie o wartości null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> w języku Visual Basic), bieżący wyjątek jest zgłaszany w bloku catch, która obsługuje wyjątek wewnętrzny.</xref:System.Exception.InnerException*>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException
  nameWithType: NoStartupFormException.NoStartupFormException
