### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  id: BuiltInRole
  children:
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  langs:
  - csharp
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  type: Enum
  summary: "Wskazuje typ roli, aby sprawdzić podczas wywoływania metody <xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>metody.</xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>"
  remarks: "To wyliczenie zapewnia funkcje podobne do <xref:System.Security.Principal.WindowsBuiltInRole>wyliczenie.</xref:System.Security.Principal.WindowsBuiltInRole>       Te role reprezentują lokalnych grup systemu Windows, typowe większości instalacji systemu Windows."
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.ApplicationServices.BuiltInRoleConverter))]

      public enum BuiltInRole
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  id: AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Operatorzy kont Zarządzanie kontami użytkowników na komputerze lub w domenie."
  syntax:
    content: AccountOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  id: Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Administratorzy mają pełny i nieograniczony dostęp do komputera lub domeny."
  syntax:
    content: Administrator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  id: BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Operatorzy kopii zapasowych można zastąpić ograniczenia zabezpieczeń wyłącznie w celu tworzenia kopii zapasowej lub przywracanie plików."
  syntax:
    content: BackupOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  id: Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Systemy operacyjne gości są bardziej ograniczony użytkowników."
  syntax:
    content: Guest
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  id: PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Użytkownicy zaawansowani mają większość uprawnień administracyjnych z pewnymi ograniczeniami. W związku z tym użytkownicy zaawansowani może uruchamiać starsze aplikacje, oprócz certyfikowanych aplikacji."
  syntax:
    content: PowerUser
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  id: PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Operatorzy drukowania, może przejąć kontrolę nad drukarki."
  syntax:
    content: PrintOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  id: Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Replikatorów obsługuje replikację w domenie."
  syntax:
    content: Replicator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  id: SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Operatory system zarządzania określonego komputera."
  syntax:
    content: SystemOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  id: User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Użytkownicy będą mogli zmiany systemowe przypadkowym lub zamierzone. W związku z tym użytkownicy mogą uruchamiać aplikacje uwierzytelnione, ale nie większość starszych aplikacji."
  syntax:
    content: User
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
