### YamlMime:ManagedReference
items:
- uid: System.Configuration.DpapiProtectedConfigurationProvider
  id: DpapiProtectedConfigurationProvider
  children:
  - System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  - System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider
  fullName: System.Configuration.DpapiProtectedConfigurationProvider
  type: Class
  summary: "Udostępnia <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> obiekt, który używa ochrony danych systemu Windows API (DPAPI) do szyfrowania i odszyfrowywania danych konfiguracji."
  remarks: "DpapiProtectedConfigurationProvider pozwala chronić poufne informacje przechowywane w pliku konfiguracji przed nieautoryzowanym dostępem.       Aby użyć standardowego DpapiProtectedConfigurationProvider deklarowanie dostawcy i odpowiednie ustawienia w pliku konfiguracji zamiast tworzenia wystąpienia tej klasy. Zapoznaj się w następnym przykładzie.       Aby uzyskać więcej informacji o konfiguracji chronionych, zobacz [szyfrowania informacji przy użyciu chronione Konfiguracja](~/add/includes/ajax-current-ext-md.md).       DpapiProtectedConfigurationProvider używa wbudowanych usług kryptograficznych systemu Windows i mogą być skonfigurowane dla ochrony komputera lub określonego konta użytkownika. Ochrona komputera jest przydatne w przypadku anonimowych usługi, ale zapewnia obniżenie poziomu zabezpieczeń. Ochrona określonego konta użytkownika może być stosowana z usług, które działają z określona tożsamość użytkownika."
  example:
  - "The following example shows how to use the standard DpapiProtectedConfigurationProvider to protect or unprotect a configuration section.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n  \n The following configuration excerpts show the configuration section before and after the protection has been applied.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\" ?>  \n<configuration>  \n  <connectionStrings>  \n    <add name=\"NorthwindConnectionString\"   \n      connectionString=\"Data Source=webnetue2;Initial Catalog=Northwind;User ID=aspnet_test;Password=test\"  \n      providerName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n</configuration>  \n```  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <connectionStrings>  \n    <EncryptedData>  \n      <CipherData>                <CipherValue>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAcAMh0jIC1kigyFfd9AUZfQQAAAACAAAAAAADZgAAqAAAABAAAADQwbQ2DgIgIlqskE1RI9UpAAAAAASAAACgAAAAEAAAAAXlYBxi3jhM6wv4sxLhugsQAgAAgoReHZS2406dc/AyRDd6WuNr4ihHn6fbipd4tzHEmeuyS4o4fS4CmT3jMt/WjsP/kR7TF4ygwr2GG47podK79ECpVCZHAgctCauCYjE2Ls3iphKXy/pHic2o6aaClt/xPm+fb4OfODv6XjrJhJzGK2lqUPXkyJN1w2zwh6OVpDQF9N8vTyxL4eitp35/M5zYbW7e6VVAgYUOxlNxgCV5+jXpUKh/rPovopTD392u8KavqQFW1iu+gBPSPq/xeZNz+qYMKbUl+r4VTzBQg3fPlRxp1lNZmM2yRgUbkYPNaFb9ihS7GAg5/wZn8lLmThvq39eA0Vlp6hDE92iop885umELt0/NBKf5umQCqqz9EXXLbmmGc7qoLqTaYVuOmqx0LsvrJL0wSL1dSySCjmB/dNAtVUYgg02eWQNKyaLqnpMdCbTLLQ/oCKuNkL5OQ7t1yl5wQGjQhieIRzLtrMgpTSyaHbqDsRurp9Bc5mM078IAg1hXquQNKlJC/wiJ9kbHerFCbtuLGy/7nXVrFH91ud4U4ExCJEuhoTdmuql5kbqYd6Ye/bu2CftPni19nDkSJ8w4NoqMNKbK3Mi/Cd0o113HsVYlETMv1vlJWZWYP91PK9trixiY4E0G81c6IKITjHDrOJ9evdw2T1/TrvY6pzre3UXSJbFMDQVX6JoAxFk02SRZDKOZdRojeoX19lgrFAAAABzjlz3Qg2as3vn7MRQVxDfZucgE</CipherValue>  \n      </CipherData>  \n    </EncryptedData>  \n  </connectionStrings>  \n  <configProtectedData defaultProvider=\"RsaProtectedConfigurationProvider\">  \n    <providers>  \n      <clear />  \n      <add keyContainerName=\"NetFrameworkConfigurationKey\" cspProviderName=\"\"  \n        useMachineContainer=\"true\" useOAEP=\"false\" description=\"Uses RsaCryptoServiceProvider to encrypt and decrypt\"  \n        name=\"RsaProtectedConfigurationProvider\" type=\"System.Configuration.RsaProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n      <add useMachineProtection=\"true\" description=\"Uses CryptProtectData and CryptUnProtectData Windows APIs to encrypt and decrypt\"  \n        keyEntropy=\"\" name=\"DataProtectionConfigurationProvider\" type=\"System.Configuration.DpapiProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n    </providers>  \n  </configProtectedData>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class DpapiProtectedConfigurationProvider : System.Configuration.ProtectedConfigurationProvider'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  - System.Configuration.ProtectedConfigurationProvider
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.DpapiProtectedConfigurationProvider&quot;> </xref> przy użyciu ustawień domyślnych."
  remarks: "Konstruktor DpapiProtectedConfigurationProvider nie jest przeznaczona do użycia bezpośrednio w kodzie. Jest ona wywoływana przez system konfiguracji programu ASP.NET."
  syntax:
    content: public DpapiProtectedConfigurationProvider ();
    parameters: []
  overload: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Odszyfrowuje przekazany <xref href=&quot;System.Xml.XmlNode&quot;> </xref> obiektu."
  syntax:
    content: public override System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: "<xref href=&quot;System.Xml.XmlNode&quot;> </xref> Obiektu do odszyfrowania."
    return:
      type: System.Xml.XmlNode
      description: "Odszyfrowany <xref href=&quot;System.Xml.XmlNode&quot;> </xref> obiektu."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "<code>encryptedNode</code> does not have <xref:System.Xml.XmlNode.Name*> set to \"EncryptedData\" and <xref:System.Xml.XmlNodeType> set to <xref:System.Xml.XmlNodeType>.  \n  \n \\- or -  \n  \n <code>encryptedNode</code> does not have a child node named \"CipherData\" with a child node named \"CipherValue\".  \n  \n \\- or -  \n  \n The child node named \"CipherData\" is an empty node."
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Szyfruje przekazany <xref href=&quot;System.Xml.XmlNode&quot;> </xref> obiektu."
  syntax:
    content: public override System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: "<xref href=&quot;System.Xml.XmlNode&quot;> </xref> Obiektu do szyfrowania."
    return:
      type: System.Xml.XmlNode
      description: "Zaszyfrowane <xref href=&quot;System.Xml.XmlNode&quot;> </xref> obiektu."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  id: Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje dostawcę z ustawieniami domyślnymi."
  syntax:
    content: public override void Initialize (string name, System.Collections.Specialized.NameValueCollection configurationValues);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa dostawcy do użycia dla obiekt."
    - id: configurationValues
      type: System.Collections.Specialized.NameValueCollection
      description: "A <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> Kolekcja wartości używana podczas inicjowania obiektu."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "<code>configurationValues</code>zawiera ustawienia konfiguracji nierozpoznany."
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  id: UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera wartość wskazującą, czy <xref href=&quot;System.Configuration.DpapiProtectedConfigurationProvider&quot;> </xref> obiektu używa ochrony komputera lub określonego konta użytkownika."
  remarks: "Ochrona komputera jest przydatne w przypadku anonimowych usługi, ale zapewnia obniżenie poziomu zabezpieczeń. Ochrona określonego konta użytkownika może być stosowana z usług, które działają z określona tożsamość użytkownika."
  syntax:
    content: public bool UseMachineProtection { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <xref href=&quot;System.Configuration.DpapiProtectedConfigurationProvider&quot;> </xref> używa ochrony komputera. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Jeśli używa ochrony określonego konta użytkownika."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: System.Configuration.ProtectedConfigurationProvider
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize
  nameWithType: DpapiProtectedConfigurationProvider.Initialize
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
