### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs
  id: SelectingProviderEventArgs
  children:
  - System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  - System.Web.ApplicationServices.SelectingProviderEventArgs.User
  langs:
  - csharp
  name: SelectingProviderEventArgs
  nameWithType: SelectingProviderEventArgs
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs
  type: Class
  summary: "Udostępnia dane dla <xref href=&quot;System.Web.ApplicationServices.RoleService.SelectingProvider&quot;> </xref> zdarzeń."
  remarks: "Klasa SelectingProviderEventArgs zapewnia wartości <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>obsługi zdarzeń.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider> Możesz utworzyć <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>obsługi zdarzeń, aby wybrać dostawcę roli w czasie wykonywania.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>       <xref:System.Web.ApplicationServices.RoleService>Klasy zgłasza <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>zdarzeń podczas albo <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>metody lub <xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>metody <xref:System.Web.ApplicationServices.RoleService>nosi nazwę klasy.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> </xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A> </xref:System.Web.ApplicationServices.RoleService.SelectingProvider> </xref:System.Web.ApplicationServices.RoleService>       Możesz użyć <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A>właściwości do pobrania informacji dotyczących zalogowanego użytkownika.</xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A> Aby uzyskać informacje o rolach za pośrednictwem dostawcy roli innych niż domyślne, ustaw <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>właściwości nazwy dostawcy ról, które mają <xref:System.Web.ApplicationServices.RoleService>obiekt ma być używany.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the SelectingProviderEventArgs object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/t-system.web.application_0_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/t-system.web.application_0_1.asax)]"
  syntax:
    content: 'public class SelectingProviderEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  id: ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Pobiera lub Ustawia dostawcę roli używany do pobierania ról użytkownika."
  remarks: "Ustawienie dostawcy roli podczas za pomocą właściwości ProviderName <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>zdarzeń.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_3_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_3_1.asax)]"
  syntax:
    content: public string ProviderName { get; set; }
    return:
      type: System.String
      description: "Nazwa dostawcy roli, który jest używany do pobierania ról użytkownika."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  id: User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Pobiera uwierzytelnionego użytkownika."
  remarks: "Użyj właściwości użytkownika można pobrać informacji o użytkowniku podczas <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>zdarzeń.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_9_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_9_1.asax)]"
  syntax:
    content: public System.Security.Principal.IPrincipal User { get; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "Obiekt, który zawiera uwierzytelnionego użytkownika."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
