### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BuildProvider
  id: BuildProvider
  children:
  - System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.BuildProvider.Equals(System.Object)
  - System.Web.Configuration.BuildProvider.Extension
  - System.Web.Configuration.BuildProvider.GetHashCode
  - System.Web.Configuration.BuildProvider.Properties
  - System.Web.Configuration.BuildProvider.Type
  langs:
  - csharp
  name: BuildProvider
  nameWithType: BuildProvider
  fullName: System.Web.Configuration.BuildProvider
  type: Class
  summary: "Zapewnia funkcje do analizy określonego typu pliku oraz do generowania kodu podczas kompilacji dynamicznych zasobów. Ta klasa nie może być dziedziczona."
  syntax:
    content: 'public sealed class BuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: BuildProvider(String,String)
  nameWithType: BuildProvider.BuildProvider(String,String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy wystąpienie <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> klasy został zainicjowany w podanych wartości."
  syntax:
    content: public BuildProvider (string extension, string type);
    parameters:
    - id: extension
      type: System.String
      description: "Rozszerzenie pliku zasobu dynamicznego używany podczas kompilacji."
    - id: type
      type: System.String
      description: "Typ reprezentujący <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> wystąpienie do użycia podczas analizowania i kompilowania danego rozszerzenia."
  overload: System.Web.Configuration.BuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, czy obiekt dostawcy określonej kompilacji jest taki sam jak bieżący obiekt."
  remarks: "Serializator używa tej metody, aby określić, czy ten sam obiekt już istnieje w kolekcji nadrzędnej i określa, czy należy go serializować na niższym poziomie, jeśli nie został on odziedziczony."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "Obiekt dostawcy kompilacji do porównania z bieżącym obiektem."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli obiekty są równe; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.BuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Extension
  id: Extension
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia rozszerzenia pliku do mapowania na podczas kompilacji dynamicznych zasobów."
  syntax:
    content: public string Extension { get; set; }
    return:
      type: System.String
      description: "Ciąg określający rozszerzenie pliku do mapowania na podczas kompilacji dynamicznych zasobów."
  overload: System.Web.Configuration.BuildProvider.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Generuje wartość skrótu dla dostawcy kompilacji."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Liczba całkowita reprezentująca wartość skrótu dla dostawcy kompilacji."
  overload: System.Web.Configuration.BuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.BuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BuildProvider.Type
  id: Type
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustaw przecinkami klasy i zestawu kombinacja wskazującą <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> wystąpienie do użycia."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Rozdzielana przecinkami klasy zestawu połączenia i wskazujący <xref href=&quot;System.Web.Configuration.BuildProvider&quot;> </xref> wystąpienie do użycia."
  overload: System.Web.Configuration.BuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider(String,String)
  nameWithType: BuildProvider.BuildProvider(String,String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.BuildProvider.Extension
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.BuildProvider.Properties
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.BuildProvider.Type
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
- uid: System.Web.Configuration.BuildProvider.#ctor*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider
  nameWithType: BuildProvider.BuildProvider
- uid: System.Web.Configuration.BuildProvider.Equals*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals
  nameWithType: BuildProvider.Equals
- uid: System.Web.Configuration.BuildProvider.Extension*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: BuildProvider.GetHashCode
- uid: System.Web.Configuration.BuildProvider.Properties*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
- uid: System.Web.Configuration.BuildProvider.Type*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
