### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpModuleAction
  id: HttpModuleAction
  children:
  - System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  - System.Web.Configuration.HttpModuleAction.ElementProperty
  - System.Web.Configuration.HttpModuleAction.Name
  - System.Web.Configuration.HttpModuleAction.Properties
  - System.Web.Configuration.HttpModuleAction.Type
  langs:
  - csharp
  name: HttpModuleAction
  nameWithType: HttpModuleAction
  fullName: System.Web.Configuration.HttpModuleAction
  type: Class
  summary: "Konfiguruje <xref href=&quot;System.Web.Configuration.HttpModulesSection&quot;> </xref> modułów. Ta klasa nie może być dziedziczona."
  remarks: "Klasa HttpModuleAction umożliwia programowo modyfikacji i dostępu `add` elementu `httpModules` sekcji pliku konfiguracji.       Typ HttpModuleAction jest częścią grupy, która zawiera <xref:System.Web.Configuration.HttpModuleActionCollection>, kolekcji i <xref:System.Web.Configuration.HttpModulesSection>typów.</xref:System.Web.Configuration.HttpModulesSection> </xref:System.Web.Configuration.HttpModuleActionCollection>"
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `add` element of the `httpModules` section, which can also be accessed as members of the HttpModuleAction class.  \n  \n The following configuration file example shows how to specify values declaratively for the `httpModules` section.  \n  \n Refer to the [NIB: How to: Create and Configure an HTTP Module](http://msdn.microsoft.com/en-us/4174fd13-a9c4-4ff6-baa5-3f7d7fc73ef3) to see how to build and configure an HTTP module.  \n  \n```  \n<httpModules>  \n    <add name=\"TimerModule\"   \n      type=\"Samples.Aspnet.Configuration.RequestTimeInterval, RequestTimeInterval Version=1.0.1557.23158, Culture=neutral,  \n      PublicKeyToken=7bfb33146a87b52e, processorArchitecture=MSIL\"/>  \n</httpModules>  \n```  \n  \n The following code example shows how to use the HttpModuleAction class.  \n  \n [!code-vb[System.Web.Configuration.HttpModuleAction#1](~/add/codesnippet/visualbasic/t-system.web.configurati_4_1.vb)]\n [!code-cs[System.Web.Configuration.HttpModuleAction#1](~/add/codesnippet/csharp/t-system.web.configurati_4_1.cs)]"
  syntax:
    content: 'public sealed class HttpModuleAction : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: HttpModuleAction(String,String)
  nameWithType: HttpModuleAction.HttpModuleAction(String,String)
  fullName: System.Web.Configuration.HttpModuleAction.HttpModuleAction(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.HttpModuleAction&quot;> </xref> przy użyciu przekazanych parametrów."
  remarks: "Nazwa modułu jest alias, którego można użyć do skojarzenia z zdarzeń modułu obsługi zdarzeń. Wyszukuje ASP.NET DLL zestawu najpierw w katalogu \\bin prywatnych aplikacji, a następnie w globalnej pamięci podręcznej zestawów (GAC)."
  example:
  - "The following code example shows how to create an <xref:System.Web.Configuration.HttpModuleAction> object.  \n  \n [!code-vb[System.Web.Configuration.HttpModuleAction#3](~/add/codesnippet/visualbasic/4b984f09-d70f-4524-b4ce-_1.vb)]\n [!code-cs[System.Web.Configuration.HttpModuleAction#3](~/add/codesnippet/csharp/4b984f09-d70f-4524-b4ce-_1.cs)]"
  syntax:
    content: public HttpModuleAction (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa modułu."
    - id: type
      type: System.String
      description: "Rozdzielana przecinkami lista zawierająca nazwy typu modułu, a informacje o zestawie."
  overload: System.Web.Configuration.HttpModuleAction.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpModuleAction.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: ElementProperty
  nameWithType: HttpModuleAction.ElementProperty
  fullName: System.Web.Configuration.HttpModuleAction.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: "Do dodania."
  overload: System.Web.Configuration.HttpModuleAction.ElementProperty*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpModuleAction.Name
  id: Name
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: Name
  nameWithType: HttpModuleAction.Name
  fullName: System.Web.Configuration.HttpModuleAction.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia nazwę modułu."
  remarks: "Nazwa modułu jest używana do identyfikowania to <xref:System.Web.Configuration.HttpModuleAction>obiektu.</xref:System.Web.Configuration.HttpModuleAction>"
  example:
  - "The following code example shows how to use the Name property.  \n  \n [!code-vb[System.Web.Configuration.HttpModuleAction#4](~/add/codesnippet/visualbasic/p-system.web.configurati_193_1.vb)]\n [!code-cs[System.Web.Configuration.HttpModuleAction#4](~/add/codesnippet/csharp/p-system.web.configurati_193_1.cs)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Nazwa modułu."
  overload: System.Web.Configuration.HttpModuleAction.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpModuleAction.Properties
  id: Properties
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: Properties
  nameWithType: HttpModuleAction.Properties
  fullName: System.Web.Configuration.HttpModuleAction.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.HttpModuleAction.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpModuleAction.Type
  id: Type
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: Type
  nameWithType: HttpModuleAction.Type
  fullName: System.Web.Configuration.HttpModuleAction.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia typ modułu."
  remarks: "Można znaleźć zestawu zdefiniowane przez typ, ASP.NET wyszukuje DLL zestawu najpierw w katalogu \\bin prywatnych aplikacji, a następnie w pamięci podręcznej zestawów systemu."
  example:
  - "The following code example shows how to access the Type property.  \n  \n [!code-vb[System.Web.Configuration.HttpModuleAction#5](~/add/codesnippet/visualbasic/p-system.web.configurati_200_1.vb)]\n [!code-cs[System.Web.Configuration.HttpModuleAction#5](~/add/codesnippet/csharp/p-system.web.configurati_200_1.cs)]"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Rozdzielana przecinkami lista zawierająca nazwy typu modułu, a informacje o zestawie."
  overload: System.Web.Configuration.HttpModuleAction.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: HttpModuleAction(String,String)
  nameWithType: HttpModuleAction.HttpModuleAction(String,String)
  fullName: System.Web.Configuration.HttpModuleAction.HttpModuleAction(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpModuleAction.ElementProperty
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: ElementProperty
  nameWithType: HttpModuleAction.ElementProperty
  fullName: System.Web.Configuration.HttpModuleAction.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.HttpModuleAction.Name
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Name
  nameWithType: HttpModuleAction.Name
  fullName: System.Web.Configuration.HttpModuleAction.Name
- uid: System.Web.Configuration.HttpModuleAction.Properties
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Properties
  nameWithType: HttpModuleAction.Properties
  fullName: System.Web.Configuration.HttpModuleAction.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpModuleAction.Type
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Type
  nameWithType: HttpModuleAction.Type
  fullName: System.Web.Configuration.HttpModuleAction.Type
- uid: System.Web.Configuration.HttpModuleAction.#ctor*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: HttpModuleAction
  nameWithType: HttpModuleAction.HttpModuleAction
- uid: System.Web.Configuration.HttpModuleAction.ElementProperty*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: ElementProperty
  nameWithType: HttpModuleAction.ElementProperty
- uid: System.Web.Configuration.HttpModuleAction.Name*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Name
  nameWithType: HttpModuleAction.Name
- uid: System.Web.Configuration.HttpModuleAction.Properties*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Properties
  nameWithType: HttpModuleAction.Properties
- uid: System.Web.Configuration.HttpModuleAction.Type*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Type
  nameWithType: HttpModuleAction.Type
