### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MembershipSection
  id: MembershipSection
  children:
  - System.Web.Configuration.MembershipSection.#ctor
  - System.Web.Configuration.MembershipSection.DefaultProvider
  - System.Web.Configuration.MembershipSection.HashAlgorithmType
  - System.Web.Configuration.MembershipSection.Properties
  - System.Web.Configuration.MembershipSection.Providers
  - System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  langs:
  - csharp
  name: MembershipSection
  nameWithType: MembershipSection
  fullName: System.Web.Configuration.MembershipSection
  type: Class
  summary: "Definiuje ustawienia konfiguracji do obsługi infrastruktury do konfigurowania i zarządzania szczegóły członkostwa. Ta klasa nie może być dziedziczona."
  remarks: "Klasa MembershipSection umożliwia programowo modyfikacji i dostępu `membership` sekcji w pliku konfiguracji."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `membership` section, which can also be accessed as members of the MembershipSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `membership` section.  \n  \n```  \n<system.web>  \n  <membership   \n    defaultProvider=\"AspNetSqlMembershipProvider\"  \n    userIsOnlineTimeWindow=\"15\">  \n    <providers>  \n      <add   \n        name=\" AspNetSqlMembershipProvider\"  \n        type=\"System.Web.Security.SqlMembershipProvider, System.Web,   \n          Version=2.0.3600.0, Culture=neutral,   \n          PublicKeyToken=b03f5f7f11d50a3a\"  \n        connectionStringName=\"LocalSqlServer\"  \n        passwordAttemptThreshold=\"5\"  \n        passwordAttemptWindow=\"10\"  \n        enablePasswordRetrieval=\"false\"  \n        enablePasswordReset=\"true\"  \n        requiresQuestionAndAnswer=\"true\"  \n        applicationName=\"/\"  \n        requiresUniqueEmail=\"false\"  \n        passwordFormat=\"Hashed\"  \n        description=\"Stores and retrieves membership data from   \n          the local Microsoft SQL Server database.\"  \n      />  \n    </providers>  \n  </membership>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the MembershipSection class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#1](~/add/codesnippet/csharp/t-system.web.configurati_44_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_44_1.vb)]"
  syntax:
    content: 'public sealed class MembershipSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: MembershipSection()
  nameWithType: MembershipSection.MembershipSection()
  fullName: System.Web.Configuration.MembershipSection.MembershipSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.MembershipSection&quot;> </xref> klasy."
  remarks: "Konstruktor MembershipSection nie jest przeznaczona do użycia bezpośrednio w kodzie. Jest ona wywoływana przez system konfiguracji programu ASP.NET. Uzyskać wystąpienia <xref:System.Web.Configuration.MembershipSection>przy użyciu <xref:System.Configuration.Configuration.GetSection%2A>metody.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.MembershipSection>"
  syntax:
    content: public MembershipSection ();
    parameters: []
  overload: System.Web.Configuration.MembershipSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
  fullName: System.Web.Configuration.MembershipSection.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia nazwę domyślnego dostawcę, który jest używany do zarządzania rolami."
  remarks: "Właściwości DefaultProvider muszą być zgodne w nazwanej wartości `providers` podsekcji z `membership` sekcji pliku konfiguracji. Ciąg pusty (`&quot;&quot;`) nie jest prawidłową wartością dla właściwości DefaultProvider właściwości."
  example:
  - "The following code example demonstrates how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#2](~/add/codesnippet/csharp/p-system.web.configurati_239_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_239_1.vb)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "Nazwa dostawcy <xref:System.Web.Configuration.MembershipSection.Providers*>.</xref:System.Web.Configuration.MembershipSection.Providers*> Wartość domyślna to <xref uid=&quot;langword_csharp_AspNetSqlRoleProvider&quot; name=&quot;AspNetSqlRoleProvider&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.MembershipSection.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType
  id: HashAlgorithmType
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
  fullName: System.Web.Configuration.MembershipSection.HashAlgorithmType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia typ szyfrowania używany do informacji poufnych członkostwa."
  remarks: "W czasie wykonywania system członkostwa wiąże typu algorytmu mieszania odpowiednie, a następnie używa tego typu do szyfrowania informacji o członkostwie. Jeśli nie ustawiono właściwości HashAlgorithmType, systemu członkostwa domyślnie przyjmowana jest wartość <xref:System.Web.Configuration.MachineKeySection.Validation%2A>właściwości <xref:System.Web.Configuration.MachineKeySection>klasy.</xref:System.Web.Configuration.MachineKeySection> </xref:System.Web.Configuration.MachineKeySection.Validation%2A>"
  example:
  - "The following code example demonstrates how to use the HashAlgorithmType property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#3](~/add/codesnippet/csharp/p-system.web.configurati_135_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_135_1.vb)]"
  syntax:
    content: public string HashAlgorithmType { get; set; }
    return:
      type: System.String
      description: "Typ szyfrowania używany do szyfrowania informacji poufnych członkostwa."
  overload: System.Web.Configuration.MembershipSection.HashAlgorithmType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.Properties
  id: Properties
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: Properties
  nameWithType: MembershipSection.Properties
  fullName: System.Web.Configuration.MembershipSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.MembershipSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.Providers
  id: Providers
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: Providers
  nameWithType: MembershipSection.Providers
  fullName: System.Web.Configuration.MembershipSection.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> obiektu <xref href=&quot;System.Configuration.ProviderSettings&quot;> </xref> obiektów."
  remarks: "Dostawców członkostwa są składnikami, które zapewniają dostęp do członkostwa dla lokacji. Można określić dostawców członkostwa w `providers` podsekcji z `membership` sekcji pliku konfiguracji.       <xref:System.Web.Configuration.MembershipSection.DefaultProvider%2A>Właściwość zawiera nazwę dostawcy, który jest używany domyślnie.</xref:System.Web.Configuration.MembershipSection.DefaultProvider%2A>"
  example:
  - "The following code example demonstrates how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#5](~/add/codesnippet/csharp/p-system.web.configurati_90_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#5](~/add/codesnippet/visualbasic/p-system.web.configurati_90_1.vb)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "A <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> zawierający ustawień dostawcy, zdefiniowanych w <xref uid=&quot;langword_csharp_providers&quot; name=&quot;providers&quot; href=&quot;&quot;> </xref> podsekcji z <xref uid=&quot;langword_csharp_membership&quot; name=&quot;membership&quot; href=&quot;&quot;> </xref> sekcji pliku konfiguracji."
  overload: System.Web.Configuration.MembershipSection.Providers*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  id: UserIsOnlineTimeWindow
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
  fullName: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia długość czasu (w minutach) przed użytkownik jest już uznawany w trybie online."
  remarks: "Wartość właściwości UserIsOnlineTimeWindow jest obliczana na podstawie porównania bieżący czas minus właściwość UserIsOnlineTimeWindow <xref:System.Web.Security.MembershipUser.LastActivityDate%2A>wartość dla użytkownika.</xref:System.Web.Security.MembershipUser.LastActivityDate%2A>"
  example:
  - "The following code example demonstrates how to use the UserIsOnlineTimeWindow property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#4](~/add/codesnippet/csharp/p-system.web.configurati_39_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_39_1.vb)]"
  syntax:
    content: public TimeSpan UserIsOnlineTimeWindow { get; set; }
    return:
      type: System.TimeSpan
      description: "Długość czasu w minutach."
  overload: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.MembershipSection.#ctor
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: MembershipSection()
  nameWithType: MembershipSection.MembershipSection()
  fullName: System.Web.Configuration.MembershipSection.MembershipSection()
- uid: System.Web.Configuration.MembershipSection.DefaultProvider
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
  fullName: System.Web.Configuration.MembershipSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
  fullName: System.Web.Configuration.MembershipSection.HashAlgorithmType
- uid: System.Web.Configuration.MembershipSection.Properties
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Properties
  nameWithType: MembershipSection.Properties
  fullName: System.Web.Configuration.MembershipSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.MembershipSection.Providers
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Providers
  nameWithType: MembershipSection.Providers
  fullName: System.Web.Configuration.MembershipSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
  fullName: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.MembershipSection.#ctor*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: MembershipSection
  nameWithType: MembershipSection.MembershipSection
- uid: System.Web.Configuration.MembershipSection.DefaultProvider*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
- uid: System.Web.Configuration.MembershipSection.Properties*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Properties
  nameWithType: MembershipSection.Properties
- uid: System.Web.Configuration.MembershipSection.Providers*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Providers
  nameWithType: MembershipSection.Providers
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
