### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CertificateReferenceElement
  id: CertificateReferenceElement
  children:
  - System.ServiceModel.Configuration.CertificateReferenceElement.#ctor
  - System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  - System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  - System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  - System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  - System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  - System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  langs:
  - csharp
  name: CertificateReferenceElement
  nameWithType: CertificateReferenceElement
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement
  type: Class
  summary: "Reprezentuje ustawienia konfiguracji sprawdzania poprawności certyfikatu X.509. Ta klasa nie może być dziedziczona."
  syntax:
    content: 'public sealed class CertificateReferenceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: CertificateReferenceElement()
  nameWithType: CertificateReferenceElement.CertificateReferenceElement()
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.CertificateReferenceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.CertificateReferenceElement&quot;> </xref> klasy."
  syntax:
    content: public CertificateReferenceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: FindValue
  nameWithType: CertificateReferenceElement.FindValue
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia ciąg, który określa wartość do wyszukania w magazynie certyfikatów X.509."
  remarks: "Typ zawartych w tej właściwości musi spełniać wymagania określonego <xref:System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType%2A>wartość.</xref:System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType%2A> Wartość domyślna to ciąg pusty."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "Wartość do wyszukania w magazynie certyfikatów X.509."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  id: IsChainIncluded
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: IsChainIncluded
  nameWithType: CertificateReferenceElement.IsChainIncluded
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia wartość logiczna określająca, czy sprawdzanie poprawności jest wykonywane przy użyciu łańcucha certyfikatów."
  syntax:
    content: public bool IsChainIncluded { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli łańcuch certyfikatów jest używany podczas weryfikacji; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: Properties
  nameWithType: CertificateReferenceElement.Properties
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: CertificateReferenceElement.StoreLocation
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia wartość, która określa lokalizację magazynu certyfikatu klienta można użyć do weryfikacji certyfikatu serwera."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref> , który określa lokalizację magazynu certyfikatu, klient może używać do weryfikacji certyfikatu serwera. Wartość domyślna to <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: StoreName
  nameWithType: CertificateReferenceElement.StoreName
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia nazwę magazynu certyfikatu X.509 do otwarcia."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> zawierający nazwę magazynu certyfikatu X.509 do otwarcia."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: CertificateReferenceElement.X509FindType
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia typ wyszukiwania X.509 w celu wykonania."
  remarks: "Typ zawarty w <xref:System.ServiceModel.Configuration.CertificateReferenceElement.FindValue%2A>muszą spełniać wymagania dotyczące tej właściwości.</xref:System.ServiceModel.Configuration.CertificateReferenceElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "<xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> Zawierający typ wyszukiwania X.509 w celu wykonania."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: CertificateReferenceElement()
  nameWithType: CertificateReferenceElement.CertificateReferenceElement()
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.CertificateReferenceElement()
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: FindValue
  nameWithType: CertificateReferenceElement.FindValue
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: IsChainIncluded
  nameWithType: CertificateReferenceElement.IsChainIncluded
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: Properties
  nameWithType: CertificateReferenceElement.Properties
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreLocation
  nameWithType: CertificateReferenceElement.StoreLocation
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreName
  nameWithType: CertificateReferenceElement.StoreName
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: X509FindType
  nameWithType: CertificateReferenceElement.X509FindType
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: CertificateReferenceElement
  nameWithType: CertificateReferenceElement.CertificateReferenceElement
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: FindValue
  nameWithType: CertificateReferenceElement.FindValue
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: IsChainIncluded
  nameWithType: CertificateReferenceElement.IsChainIncluded
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.Properties*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: Properties
  nameWithType: CertificateReferenceElement.Properties
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreLocation
  nameWithType: CertificateReferenceElement.StoreLocation
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreName
  nameWithType: CertificateReferenceElement.StoreName
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: X509FindType
  nameWithType: CertificateReferenceElement.X509FindType
