### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlObjectReaderSettings
  id: XamlObjectReaderSettings
  children:
  - System.Xaml.XamlObjectReaderSettings.#ctor
  - System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  langs:
  - csharp
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings
  fullName: System.Xaml.XamlObjectReaderSettings
  type: Class
  summary: "Określa reguły przetwarzania ustawień opcji dla <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref>."
  syntax:
    content: 'public class XamlObjectReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Xaml.XamlObjectReaderSettings&quot;> </xref> klasy."
  syntax:
    content: public XamlObjectReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlObjectReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  id: RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Pobiera lub ustawia wartość określającą, czy składniki zapisywania wykorzystujące skojarzony <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref> dla kontekstu należy korzystać z projektanta ustawień w celu zapisywania zawartości jawnie."
  remarks: "To ustawienie jest poddawany kwerendzie wewnętrznie. Ma to wpływ na następujące zachowanie dotyczące kontekstu który <xref:System.Xaml.XamlObjectReader>przekazuje do dowolnego <xref:System.Xaml.XamlWriter>:-zachowanie RequireExplicitContentVisibility dotyczy tylko właściwości gdzie <xref:System.Xaml.XamlMember.IsWritePublic%2A>jest `false`i kiedy `ShouldSerialize` wzorzec jest niedostępna dla wartości właściwości.</xref:System.Xaml.XamlMember.IsWritePublic%2A> </xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlObjectReader>      — Jeśli instrukcja w pierwszym punktem punktor ma wartość true i jest RequireExplicitContentVisibility `true`, a następnie projektanta ustawienia określają, czy właściwość zapisuje dane wyjściowe jako zawartość, czy właściwość jest uznawany za niejawne. Dostęp do ustawień projektanta jest za pośrednictwem wewnętrznego interfejsów API w usługach programu .NET Framework XAML i opierają się na odczyt <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>z zestawów kopii.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute> W takim przypadku wewnętrzne kodu sprawdza, czy wartość <xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName>i zapisuje dane wyjściowe do właściwości.</xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName> W przeciwnym razie zawartość zostanie uznane za niejawnej.      — W przypadku instrukcji w pierwszym punkcie `true`, jest RequireExplicitContentVisibility i `false`, właściwość zawsze zapisuje dane wyjściowe i <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>z kopii zestawy nie ma znaczenia.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>"
  syntax:
    content: public bool RequireExplicitContentVisibility { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>określenie zapisywania, które używają tego kontekstu powinny używać Projektanta ustawień do zapisu, wszystkie dane wyjściowe zawartości w przypadkach, w których zgłasza <xref:System.Xaml.XamlMember.IsWritePublic*> <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Jeśli projektanta ustawień należy ją ignorować.</xref:System.Xaml.XamlMember.IsWritePublic*>"
  overload: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlObjectReaderSettings.#ctor*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
