### YamlMime:ManagedReference
items:
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  id: ApplicationPartitionCollection
  children:
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  langs:
  - csharp
  name: ApplicationPartitionCollection
  nameWithType: ApplicationPartitionCollection
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  type: Class
  summary: "Klasa ApplicationPartitionCollection jest tylko do odczytu kolekcji, która zawiera <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiektów."
  syntax:
    content: 'public class ApplicationPartitionCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  id: Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: Contains(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.Contains(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(ApplicationPartition)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Określa, czy określony <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiekt jest w tej kolekcji."
  syntax:
    content: public bool Contains (System.DirectoryServices.ActiveDirectory.ApplicationPartition applicationPartition);
    parameters:
    - id: applicationPartition
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: "<xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> Obiektu do wyszukania w tej kolekcji."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> znajduje się w tej kolekcji, w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationPartition</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  id: CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: CopyTo(ApplicationPartition[],Int32)
  nameWithType: ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Kopiuje wszystkie <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiektów w tej kolekcji do określonej tablicy, zaczynając od określonego indeksu tablicy docelowej."
  syntax:
    content: public void CopyTo (System.DirectoryServices.ActiveDirectory.ApplicationPartition[] applicationPartitions, int index);
    parameters:
    - id: applicationPartitions
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
      description: "Tablica <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiektów, które otrzymuje elementów tej kolekcji."
    - id: index
      type: System.Int32
      description: "Liczony od zera indeks w `applicationPartitions` gdy ta metoda rozpoczyna się kopiowanie tej kolekcji."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo*
  exceptions:
  - type: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    commentId: T:System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    description: "Wywołanie usługi katalogowej podstawowej zwróciło błąd."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Tablica docelowa nie jest wystarczająco duży, zależnie od rozmiaru kolekcji źródłowej i <code> index </code> określony."
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationPartitions</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code> index </code> Jest spoza zakresu tablicy docelowej."
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  id: IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: IndexOf(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Zwraca pierwsze wystąpienie określonego <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiektu w tej kolekcji."
  syntax:
    content: public int IndexOf (System.DirectoryServices.ActiveDirectory.ApplicationPartition applicationPartition);
    parameters:
    - id: applicationPartition
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: "<xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> Obiektu do wyszukania w tej kolekcji."
    return:
      type: System.Int32
      description: "Liczony od zera indeks pierwszego zgodnego elementu. -1, jeśli nie członek tej kolekcji nie jest taka sama jak <code> applicationPartition </code>."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf*
  exceptions:
  - type: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    commentId: T:System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    description: "Wywołanie usługi katalogowej podstawowej zwróciło błąd."
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationPartition</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ApplicationPartitionCollection.Item(Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(Int32)
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Pobiera <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiektu w tej kolekcji."
  syntax:
    content: public System.DirectoryServices.ActiveDirectory.ApplicationPartition this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "Liczony od zera indeks <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> obiekt do pobrania."
    return:
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: "<xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> Obiektu, który istnieje w określonym indeksie."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code> index </code> Jest poza zakresem kolekcji."
  platform:
  - net462
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ActiveDirectoryOperationException
  nameWithType: ActiveDirectoryOperationException
  fullName: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Contains(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.Contains(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(ApplicationPartition)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: CopyTo(ApplicationPartition[],Int32)
  nameWithType: ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
  spec.csharp:
  - uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
    name: ApplicationPartition
    nameWithType: ApplicationPartition
    fullName: ApplicationPartition[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: IndexOf(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(ApplicationPartition)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ApplicationPartitionCollection.Item(Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(Int32)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Contains
  nameWithType: ApplicationPartitionCollection.Contains
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: CopyTo
  nameWithType: ApplicationPartitionCollection.CopyTo
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: IndexOf
  nameWithType: ApplicationPartitionCollection.IndexOf
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Item
  nameWithType: ApplicationPartitionCollection.Item
