### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueFileSectionHandler
  id: NameValueFileSectionHandler
  children:
  - System.Configuration.NameValueFileSectionHandler.#ctor
  - System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler
  fullName: System.Configuration.NameValueFileSectionHandler
  type: Class
  summary: "Zapewnia dostęp do pliku konfiguracji. Ten typ obsługuje infrastrukturę programu .NET Framework konfiguracji i nie jest przeznaczona do użycia bezpośrednio w kodzie."
  remarks: "`file` Atrybutu `<appSettings>` sekcji Określa ścieżkę względną do pliku zewnętrznego, który zawiera niestandardowe ustawienia konfiguracji aplikacji. Informacje zawarte w pliku pełnienie `<appSettings>` sekcji w pliku konfiguracji. Plik jest dostępny za pomocą klasy NameValueFileSectionHandler. Element główny pliku musi odpowiadać sekcji odwołujące się do niego."
  syntax:
    content: 'public class NameValueFileSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.NameValueFileSectionHandler&quot;> </xref> klasy."
  syntax:
    content: public NameValueFileSectionHandler ();
    parameters: []
  overload: System.Configuration.NameValueFileSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Tworzy nowy program obsługi konfiguracji i dodaje go do kolekcji modułu obsługi sekcji, na podstawie określonych parametrów."
  remarks: "`parent` Parametr obiektu zachowuje się jak ustawienia konfiguracji w odpowiedniej sekcji konfiguracji nadrzędnej. `configContext` Parametr obiektu jest ścieżką wirtualną, dla którego program obsługi sekcji konfiguracji oblicza wartości konfiguracji. Zazwyczaj ten parametr jest zarezerwowany i `null`. `section` Jest parametr <xref:System.Xml.XmlNode>zawierający informacje o konfiguracji, które mają być obsługiwane.</xref:System.Xml.XmlNode> `section` Parametru zapewnia bezpośredni dostęp do zawartości XML sekcji konfiguracji."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Obiekt nadrzędny."
    - id: configContext
      type: System.Object
      description: "Obiekt kontekstu konfiguracji."
    - id: section
      type: System.Xml.XmlNode
      description: "Węzeł XML sekcji."
    return:
      type: System.Object
      description: "Obiekt konfiguracji."
  overload: System.Configuration.NameValueFileSectionHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute of <code>section</code> exists but cannot be loaded.  \n  \n \\- or -  \n  \n The <xref uid=\"langword_csharp_name\" name=\"name\" href=\"\"></xref> attribute of <code>section</code> does not match the root element of the file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.NameValueFileSectionHandler.#ctor*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler
- uid: System.Configuration.NameValueFileSectionHandler.Create*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create
  nameWithType: NameValueFileSectionHandler.Create
