### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpConfigurationContext
  id: HttpConfigurationContext
  children:
  - System.Web.Configuration.HttpConfigurationContext.VirtualPath
  langs:
  - csharp
  name: HttpConfigurationContext
  nameWithType: HttpConfigurationContext
  fullName: System.Web.Configuration.HttpConfigurationContext
  type: Class
  summary: "Udostępnia informacje o kontekście bieżącego do obsługi sekcji konfiguracji w aplikacji ASP.NET."
  remarks: "Informacje o kontekście dostarczonych przez tę klasę jest dla bieżącego żądania HTTP."
  syntax:
    content: public class HttpConfigurationContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  id: VirtualPath
  parent: System.Web.Configuration.HttpConfigurationContext
  langs:
  - csharp
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
  fullName: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera ścieżkę wirtualną do pliku konfiguracji Web.config."
  syntax:
    content: public string VirtualPath { get; }
    return:
      type: System.String
      description: "Ścieżka wirtualna do pliku Web.config. <xref uid=&quot;langword_csharp_Null&quot; name=&quot;Null&quot; href=&quot;&quot;></xref>podczas obliczania Machine.config; ciąg pusty (&quot;&quot;) podczas obliczania głównego pliku Web.config dla witryny."
  overload: System.Web.Configuration.HttpConfigurationContext.VirtualPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath
  parent: System.Web.Configuration.HttpConfigurationContext
  isExternal: false
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
  fullName: System.Web.Configuration.HttpConfigurationContext.VirtualPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpConfigurationContext.VirtualPath*
  parent: System.Web.Configuration.HttpConfigurationContext
  isExternal: false
  name: VirtualPath
  nameWithType: HttpConfigurationContext.VirtualPath
