### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PagesEnableSessionState
  id: PagesEnableSessionState
  children:
  - System.Web.Configuration.PagesEnableSessionState.False
  - System.Web.Configuration.PagesEnableSessionState.ReadOnly
  - System.Web.Configuration.PagesEnableSessionState.True
  langs:
  - csharp
  name: PagesEnableSessionState
  nameWithType: PagesEnableSessionState
  fullName: System.Web.Configuration.PagesEnableSessionState
  type: Enum
  summary: "Używany do określenia stanu sesji aktywacji dla pojedynczej strony sieci Web lub całej aplikacji sieci Web."
  remarks: "To wyliczenie określa aktywacji stanu sesji dla całej aplikacji sieci Web. Ta wartość może być używana w `pages` sekcji pliku konfiguracji, aby wpływają na wszystkie strony .aspx w zakresie pliku konfiguracji aplikacji sieci Web. <xref:System.Web.Configuration.PagesSection>Typu zezwala na dostęp programistyczny umożliwiający `pages` sekcji konfiguracyjnej.</xref:System.Web.Configuration.PagesSection>"
  example:
  - "The following configuration file excerpt shows how to declaratively use values of the PagesEnableSessionState enumeration to specify whether the session state is enabled.  \n  \n```  \n<system.web>  \n  <pages enableSessionState=\"true\" />  \n</system.web>  \n  \n```  \n  \n The following code example shows how to use the PagesEnableSessionState enumeration with the <xref:System.Web.Configuration.PagesSection> type.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#14](~/add/codesnippet/csharp/t-system.web.configurati_56_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#14](~/add/codesnippet/visualbasic/t-system.web.configurati_56_1.vb)]"
  syntax:
    content: public enum PagesEnableSessionState
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.PagesEnableSessionState.False
  id: "False"
  parent: System.Web.Configuration.PagesEnableSessionState
  langs:
  - csharp
  name: "False"
  nameWithType: PagesEnableSessionState.False
  fullName: System.Web.Configuration.PagesEnableSessionState.False
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Stan sesji jest wyłączony."
  syntax:
    content: "False"
    return:
      type: System.Web.Configuration.PagesEnableSessionState
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PagesEnableSessionState.ReadOnly
  id: ReadOnly
  parent: System.Web.Configuration.PagesEnableSessionState
  langs:
  - csharp
  name: ReadOnly
  nameWithType: PagesEnableSessionState.ReadOnly
  fullName: System.Web.Configuration.PagesEnableSessionState.ReadOnly
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Stan sesji jest włączony, ale nie do zapisania."
  syntax:
    content: ReadOnly
    return:
      type: System.Web.Configuration.PagesEnableSessionState
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PagesEnableSessionState.True
  id: "True"
  parent: System.Web.Configuration.PagesEnableSessionState
  langs:
  - csharp
  name: "True"
  nameWithType: PagesEnableSessionState.True
  fullName: System.Web.Configuration.PagesEnableSessionState.True
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Stan sesji jest włączony."
  syntax:
    content: "True"
    return:
      type: System.Web.Configuration.PagesEnableSessionState
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.PagesEnableSessionState.False
  parent: System.Web.Configuration.PagesEnableSessionState
  isExternal: false
  name: "False"
  nameWithType: PagesEnableSessionState.False
  fullName: System.Web.Configuration.PagesEnableSessionState.False
- uid: System.Web.Configuration.PagesEnableSessionState
  parent: System.Web.Configuration
  isExternal: false
  name: PagesEnableSessionState
  nameWithType: PagesEnableSessionState
  fullName: System.Web.Configuration.PagesEnableSessionState
- uid: System.Web.Configuration.PagesEnableSessionState.ReadOnly
  parent: System.Web.Configuration.PagesEnableSessionState
  isExternal: false
  name: ReadOnly
  nameWithType: PagesEnableSessionState.ReadOnly
  fullName: System.Web.Configuration.PagesEnableSessionState.ReadOnly
- uid: System.Web.Configuration.PagesEnableSessionState.True
  parent: System.Web.Configuration.PagesEnableSessionState
  isExternal: false
  name: "True"
  nameWithType: PagesEnableSessionState.True
  fullName: System.Web.Configuration.PagesEnableSessionState.True
