### YamlMime:ManagedReference
items:
- uid: System.Web.PreApplicationStartMethodAttribute
  id: PreApplicationStartMethodAttribute
  children:
  - System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  - System.Web.PreApplicationStartMethodAttribute.MethodName
  - System.Web.PreApplicationStartMethodAttribute.Type
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute
  type: Class
  summary: "Obsługuje rozszerzonych uruchamiania aplikacji."
  remarks: "-Nie ma żadnej gwarancji kolejności, w którym są wywoływane metody rozpoczęcia zdefiniowany w zestawie aplikacji. W związku z tym każda metoda zarejestrowanych start powinny być kodowane działanie w izolacji i nie należy uwzględniać efekty uboczne z innych metod zarejestrowanych start.       Aby uzyskać więcej informacji o korzystaniu z atrybutów, zobacz [atrybutów](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple=true)]

      public sealed class PreApplicationStartMethodAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  id: '#ctor(System.Type,System.String)'
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.PreApplicationStartMethodAttribute&quot;> </xref> klasy."
  remarks: "Metoda odwołuje się `methodName` parametrów muszą być publiczne i może być metodą wystąpienia lub metody statycznej."
  syntax:
    content: public PreApplicationStartMethodAttribute (Type type, string methodName);
    parameters:
    - id: type
      type: System.Type
      description: "Obiekt, który opisuje typ metody uruchamiania."
    - id: methodName
      type: System.String
      description: "Podpis pusty parametr, który nie ma wartości zwracanych."
  overload: System.Web.PreApplicationStartMethodAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  id: MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Pobiera metody uruchamiania skojarzone."
  syntax:
    content: public string MethodName { get; }
    return:
      type: System.String
      description: "Ciąg zawierający nazwę metody uruchamiania skojarzone."
  overload: System.Web.PreApplicationStartMethodAttribute.MethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  id: Type
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Pobiera typ, który jest zwracany przez metodę uruchamiania skojarzone."
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: "Obiekt, który opisuje typ metody uruchamiania."
  overload: System.Web.PreApplicationStartMethodAttribute.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
