### YamlMime:ManagedReference
items:
- uid: System.Xml.Xsl.XsltSettings
  id: XsltSettings
  children:
  - System.Xml.Xsl.XsltSettings.#ctor
  - System.Xml.Xsl.XsltSettings.#ctor(System.Boolean,System.Boolean)
  - System.Xml.Xsl.XsltSettings.Default
  - System.Xml.Xsl.XsltSettings.EnableDocumentFunction
  - System.Xml.Xsl.XsltSettings.EnableScript
  - System.Xml.Xsl.XsltSettings.TrustedXslt
  langs:
  - csharp
  name: XsltSettings
  nameWithType: XsltSettings
  fullName: System.Xml.Xsl.XsltSettings
  type: Class
  summary: "Określa funkcje XSLT do obsługi podczas wykonywania arkusz stylów XSLT."
  remarks: "Osadzone blokad skryptów i XSLT `document()` funkcji są opcjonalne funkcje w <xref:System.Xml.Xsl.XslCompiledTransform>klasie.</xref:System.Xml.Xsl.XslCompiledTransform> Te funkcje są domyślnie wyłączone. Klasa XsltSettings Określa, która z tych opcjonalnych funkcji do obsługi. Funkcje są włączone lub wyłączone za pomocą właściwości klasy. Obiekt XsltSettings są następnie przekazywane do <xref:System.Xml.Xsl.XslCompiledTransform.Load%2A?displayProperty=fullName>metody.</xref:System.Xml.Xsl.XslCompiledTransform.Load%2A?displayProperty=fullName>      > [!IMPORTANT] > Arkuszy stylów XSLT może zawierać odwołania do innych plików oraz osadzonych blokach skryptu. Złośliwy użytkownik może wykorzystać to poprzez dostarczanie danych lub arkusze stylów, który po wykonaniu może spowodować systemu do przetwarzania, dopóki komputer ma za mało zasobów. Nie należy włączać obsługi skryptów lub `document()` działać, chyba że arkusza stylów pochodzi z zaufanego źródła. Jeśli nie można zweryfikować źródła arkusza stylów lub arkusz stylów nie pochodzi z zaufanego źródła, należy użyć wartości domyślnych XSLT."
  example:
  - "The following example loads a style sheet and enables XSLT script support.  \n  \n [!code-vb[XslCompiledTransform.Load#6](~/add/codesnippet/visualbasic/t-system.xml.xsl.xsltset_1.vb)]\n [!code-cs[XslCompiledTransform.Load#6](~/add/codesnippet/csharp/t-system.xml.xsl.xsltset_1.cs)]"
  syntax:
    content: public sealed class XsltSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xml.Xsl.XsltSettings.#ctor
  id: '#ctor'
  parent: System.Xml.Xsl.XsltSettings
  langs:
  - csharp
  name: XsltSettings()
  nameWithType: XsltSettings.XsltSettings()
  fullName: System.Xml.Xsl.XsltSettings.XsltSettings()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Xsl
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Xml.Xsl.XsltSettings&quot;> </xref> klasy przy użyciu ustawień domyślnych."
  remarks: "Nowe <xref:System.Xml.Xsl.XsltSettings>obiekt nie obsługuje XSLT `document()` funkcji lub blokach skryptu osadzonych.</xref:System.Xml.Xsl.XsltSettings>      > [!IMPORTANT] > XSLT powinna być włączona obsługa skryptów tylko wtedy, gdy wymagana jest obsługa skryptów, podczas pracy w pełni zaufanym środowisku. Po włączeniu `document()` funkcji, można ograniczyć zasoby, które mogą być udostępniane przez przekazanie <xref:System.Xml.XmlSecureResolver>do obiektu <xref:System.Xml.Xsl.XslCompiledTransform.Transform%2A>metody.</xref:System.Xml.Xsl.XslCompiledTransform.Transform%2A> </xref:System.Xml.XmlSecureResolver>"
  syntax:
    content: public XsltSettings ();
    parameters: []
  overload: System.Xml.Xsl.XsltSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Xsl.XsltSettings.#ctor(System.Boolean,System.Boolean)
  id: '#ctor(System.Boolean,System.Boolean)'
  parent: System.Xml.Xsl.XsltSettings
  langs:
  - csharp
  name: XsltSettings(Boolean,Boolean)
  nameWithType: XsltSettings.XsltSettings(Boolean,Boolean)
  fullName: System.Xml.Xsl.XsltSettings.XsltSettings(Boolean,Boolean)
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Xsl
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Xml.Xsl.XsltSettings&quot;> </xref> klasy z określonymi ustawieniami."
  remarks: >-
    > [!IMPORTANT]

    >  XSLT scripting should be enabled only if you require script support and you are working in a fully trusted environment. If you enable the `document()` function, you can restrict the resources that can be accessed by passing an <xref:System.Xml.XmlSecureResolver> object to the <xref:System.Xml.Xsl.XslCompiledTransform.Transform%2A> method.
  example:
  - "The following example loads a style sheet and enables XSLT script support.  \n  \n [!code-vb[XslCompiledTransform.Load#6](~/add/codesnippet/visualbasic/m-system.xml.xsl.xsltset_1.vb)]\n [!code-cs[XslCompiledTransform.Load#6](~/add/codesnippet/csharp/m-system.xml.xsl.xsltset_1.cs)]"
  syntax:
    content: public XsltSettings (bool enableDocumentFunction, bool enableScript);
    parameters:
    - id: enableDocumentFunction
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Aby włączyć obsługę XSLT `document()` funkcji; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: enableScript
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Aby włączyć obsługę bloki osadzonych skryptów; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Xsl.XsltSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Xsl.XsltSettings.Default
  id: Default
  parent: System.Xml.Xsl.XsltSettings
  langs:
  - csharp
  name: Default
  nameWithType: XsltSettings.Default
  fullName: System.Xml.Xsl.XsltSettings.Default
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Xsl
  summary: "Pobiera <xref href=&quot;System.Xml.Xsl.XsltSettings&quot;> </xref> obiektu przy użyciu ustawień domyślnych. Obsługa XSLT `document()` funkcji i osadzonych skryptów jest wyłączona, bloki."
  remarks: ''
  example:
  - "The following example loads a style sheet with default XSLT settings.  \n  \n [!code-vb[XslCompiledTransform.Load#7](~/add/codesnippet/visualbasic/p-system.xml.xsl.xsltset_1_1.vb)]\n [!code-cs[XslCompiledTransform.Load#7](~/add/codesnippet/csharp/p-system.xml.xsl.xsltset_1_1.cs)]"
  syntax:
    content: public static System.Xml.Xsl.XsltSettings Default { get; }
    return:
      type: System.Xml.Xsl.XsltSettings
      description: "<xref href=&quot;System.Xml.Xsl.XsltSettings&quot;> </xref> Obiekt z <> </> *> i <> </> *> właściwości <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Xsl.XsltSettings.Default*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Xsl.XsltSettings.EnableDocumentFunction
  id: EnableDocumentFunction
  parent: System.Xml.Xsl.XsltSettings
  langs:
  - csharp
  name: EnableDocumentFunction
  nameWithType: XsltSettings.EnableDocumentFunction
  fullName: System.Xml.Xsl.XsltSettings.EnableDocumentFunction
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Xsl
  summary: "Pobiera lub ustawia wartość wskazującą, czy włączyć obsługę XSLT `document()` funkcji."
  remarks: >-
    > [!IMPORTANT]

    >  If you enable the `document()` function, you can restrict the resources that can be accessed by passing an <xref:System.Xml.XmlSecureResolver> object to the <xref:System.Xml.Xsl.XslCompiledTransform.Transform%2A> method.
  syntax:
    content: public bool EnableDocumentFunction { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>do obsługi XSLT `document()` funkcji; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Xsl.XsltSettings.EnableDocumentFunction*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Xsl.XsltSettings.EnableScript
  id: EnableScript
  parent: System.Xml.Xsl.XsltSettings
  langs:
  - csharp
  name: EnableScript
  nameWithType: XsltSettings.EnableScript
  fullName: System.Xml.Xsl.XsltSettings.EnableScript
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Xsl
  summary: "Pobiera lub ustawia wartość wskazującą, czy włączyć obsługę blokach skryptu osadzonych."
  remarks: >-
    > [!IMPORTANT]

    >  XSLT scripting should be enabled only if you require script support and you are working in a fully trusted environment.
  syntax:
    content: public bool EnableScript { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>do obsługi blokach skryptu w arkuszach stylów XSLT; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Xsl.XsltSettings.EnableScript*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Xsl.XsltSettings.TrustedXslt
  id: TrustedXslt
  parent: System.Xml.Xsl.XsltSettings
  langs:
  - csharp
  name: TrustedXslt
  nameWithType: XsltSettings.TrustedXslt
  fullName: System.Xml.Xsl.XsltSettings.TrustedXslt
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Xsl
  summary: "Pobiera <xref href=&quot;System.Xml.Xsl.XsltSettings&quot;> </xref> obiekt, który umożliwia obsługę XSLT `document()` funkcji i bloki osadzony skrypt."
  remarks: >-
    > [!IMPORTANT]

    >  XSLT scripting should be enabled only if you require script support and you are working in a fully trusted environment. If you enable the `document()` function, you can restrict the resources that can be accessed by passing an <xref:System.Xml.XmlSecureResolver> object to the <xref:System.Xml.Xsl.XslCompiledTransform.Transform%2A> method.
  example:
  - "The following example loads a style sheet with support for the XSLT `document()` function and embedded script blocks features enabled.  \n  \n [!code-vb[XslCompiledTransform.Load#8](~/add/codesnippet/visualbasic/p-system.xml.xsl.xsltset_0_1.vb)]\n [!code-cs[XslCompiledTransform.Load#8](~/add/codesnippet/csharp/p-system.xml.xsl.xsltset_0_1.cs)]"
  syntax:
    content: public static System.Xml.Xsl.XsltSettings TrustedXslt { get; }
    return:
      type: System.Xml.Xsl.XsltSettings
      description: "<xref href=&quot;System.Xml.Xsl.XsltSettings&quot;> </xref> Obiekt z <> </> *> i <> </> *> właściwości <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Xsl.XsltSettings.TrustedXslt*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xml.Xsl.XsltSettings.#ctor
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: XsltSettings()
  nameWithType: XsltSettings.XsltSettings()
  fullName: System.Xml.Xsl.XsltSettings.XsltSettings()
- uid: System.Xml.Xsl.XsltSettings.#ctor(System.Boolean,System.Boolean)
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: XsltSettings(Boolean,Boolean)
  nameWithType: XsltSettings.XsltSettings(Boolean,Boolean)
  fullName: System.Xml.Xsl.XsltSettings.XsltSettings(Boolean,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Xsl.XsltSettings.Default
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: Default
  nameWithType: XsltSettings.Default
  fullName: System.Xml.Xsl.XsltSettings.Default
- uid: System.Xml.Xsl.XsltSettings
  parent: System.Xml.Xsl
  isExternal: false
  name: XsltSettings
  nameWithType: XsltSettings
  fullName: System.Xml.Xsl.XsltSettings
- uid: System.Xml.Xsl.XsltSettings.EnableDocumentFunction
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: EnableDocumentFunction
  nameWithType: XsltSettings.EnableDocumentFunction
  fullName: System.Xml.Xsl.XsltSettings.EnableDocumentFunction
- uid: System.Xml.Xsl.XsltSettings.EnableScript
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: EnableScript
  nameWithType: XsltSettings.EnableScript
  fullName: System.Xml.Xsl.XsltSettings.EnableScript
- uid: System.Xml.Xsl.XsltSettings.TrustedXslt
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: TrustedXslt
  nameWithType: XsltSettings.TrustedXslt
  fullName: System.Xml.Xsl.XsltSettings.TrustedXslt
- uid: System.Xml.Xsl.XsltSettings.#ctor*
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: XsltSettings
  nameWithType: XsltSettings.XsltSettings
- uid: System.Xml.Xsl.XsltSettings.Default*
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: Default
  nameWithType: XsltSettings.Default
- uid: System.Xml.Xsl.XsltSettings.EnableDocumentFunction*
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: EnableDocumentFunction
  nameWithType: XsltSettings.EnableDocumentFunction
- uid: System.Xml.Xsl.XsltSettings.EnableScript*
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: EnableScript
  nameWithType: XsltSettings.EnableScript
- uid: System.Xml.Xsl.XsltSettings.TrustedXslt*
  parent: System.Xml.Xsl.XsltSettings
  isExternal: false
  name: TrustedXslt
  nameWithType: XsltSettings.TrustedXslt
