### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AssemblyInfo
  id: AssemblyInfo
  children:
  - System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  - System.Web.Configuration.AssemblyInfo.Assembly
  - System.Web.Configuration.AssemblyInfo.Properties
  langs:
  - csharp
  name: AssemblyInfo
  nameWithType: AssemblyInfo
  fullName: System.Web.Configuration.AssemblyInfo
  type: Class
  summary: "Odwołuje się do zestawu powiązać podczas kompilacji dynamicznych zasobów. Ta klasa nie może być dziedziczona."
  remarks: "W przypadku kompilowania kodu poszczególnych modułów kodu ASP.NET automatycznie łączy zestawów do zasobu. Obiekt AssemblyInfo odwołuje się do zestawu. Zestaw jest kolekcją typów i zasobów, które są przeznaczone do współpracują ze sobą i utworzenia jednostki logicznej funkcji. Środowisko uruchomieniowe języka wspólnego zestawu zapewnia informacje potrzebne do identyfikowania implementacji typu. Do środowiska wykonawczego typ nie istnieje poza kontekstem zestawu.       Zestawy połączonych często są wyświetlane w `assemblies` węzła `compilation` sekcji konfiguracji. Ponadto zestawy mogą być ręcznie dodawane do zasobu kodu podczas dodatkowe funkcje dla aplikacji są potrzebne."
  syntax:
    content: 'public sealed class AssemblyInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: AssemblyInfo(String)
  nameWithType: AssemblyInfo.AssemblyInfo(String)
  fullName: System.Web.Configuration.AssemblyInfo.AssemblyInfo(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy wystąpienie <xref href=&quot;System.Web.Configuration.AssemblyInfo&quot;> </xref> klasy."
  remarks: "Jeśli <xref:System.Web.Configuration.AssemblyInfo>nie zainicjowano wystąpienia z informacji o zestawie, jest zgłaszany wyjątek.</xref:System.Web.Configuration.AssemblyInfo>"
  example:
  - "The following code example demonstrates how to create an <xref:System.Web.Configuration.AssemblyInfo> object. This code example is part of a larger example provided for the <xref:System.Web.Configuration.AssemblyCollection> class.  \n  \n [!code-vb[System.Web.Configuration.AssemblyCollection#2](~/add/codesnippet/visualbasic/m-system.web.configurati_4_1.vb)]\n [!code-cs[System.Web.Configuration.AssemblyCollection#2](~/add/codesnippet/csharp/m-system.web.configurati_4_1.cs)]"
  syntax:
    content: public AssemblyInfo (string assemblyName);
    parameters:
    - id: assemblyName
      type: System.String
      description: "Określa kombinację nazwy zestawu przecinkami składające się z wersji, kultury i tokeny klucza publicznego."
  overload: System.Web.Configuration.AssemblyInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AssemblyInfo.Assembly
  id: Assembly
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: System.Web.Configuration.AssemblyInfo.Assembly
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia odwołanie do zestawu do użycia podczas kompilacji dynamicznych zasobów."
  remarks: "Przeszukuje najpierw ASP.NET DLL zestawu w prywatnej katalogu Bin aplikacji, a następnie w pamięci podręcznej zestawów systemu."
  syntax:
    content: public string Assembly { get; set; }
    return:
      type: System.String
      description: "Wartość rozdzielaną przecinkami ciąg określenie wersji, kultury i tokeny klucza publicznego zestawu."
  overload: System.Web.Configuration.AssemblyInfo.Assembly*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AssemblyInfo.Properties
  id: Properties
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: System.Web.Configuration.AssemblyInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.AssemblyInfo.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: AssemblyInfo(String)
  nameWithType: AssemblyInfo.AssemblyInfo(String)
  fullName: System.Web.Configuration.AssemblyInfo.AssemblyInfo(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.AssemblyInfo.Assembly
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: System.Web.Configuration.AssemblyInfo.Assembly
- uid: System.Web.Configuration.AssemblyInfo.Properties
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: System.Web.Configuration.AssemblyInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AssemblyInfo.#ctor*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: AssemblyInfo
  nameWithType: AssemblyInfo.AssemblyInfo
- uid: System.Web.Configuration.AssemblyInfo.Assembly*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
- uid: System.Web.Configuration.AssemblyInfo.Properties*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Properties
  nameWithType: AssemblyInfo.Properties
