### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: "Hermetyzuje informacje o kontekście, który jest skojarzony z <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> obiektu. Ta klasa nie może być dziedziczona."
  remarks: "Obiekt ContextInformation zawiera środowiska szczegółowe informacje dotyczące elementu konfiguracji. Na przykład można użyć <xref:System.Configuration.ContextInformation.IsMachineLevel%2A>Umożliwia określenie, czy <xref:System.Configuration.ConfigurationElement>została ustawiona w pliku Machine.config lub w hierarchii, w której można określić <xref:System.Configuration.ConfigurationElement>należy za pomocą <xref:System.Configuration.ContextInformation.HostingContext%2A>Właściwości.</xref:System.Configuration.ContextInformation.HostingContext%2A> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ContextInformation.IsMachineLevel%2A>"
  example:
  - "The following code example demonstrates how to use the ContextInformation type.  \n  \n [!code-vb[System.Configuration.ContextInformation#1](~/add/codesnippet/visualbasic/t-system.configuration.c_0_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#1](~/add/codesnippet/csharp/t-system.configuration.c_0_1.cs)]"
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Udostępnia obiekt zawierający informacje o sekcji konfiguracji na podstawie nazwy określonej sekcji."
  remarks: "Podczas określania sekcji w konfiguracji, należy pamiętać, że nazwa sekcji konfiguracji z uwzględnieniem wielkości liter."
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "Nazwa sekcji konfiguracji."
    return:
      type: System.Object
      description: "Obiekt zawierający sekcji określony w konfiguracji."
  overload: System.Configuration.ContextInformation.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera kontekst środowiska, w których właściwość konfiguracyjna jest oceniane."
  remarks: "Możliwa wartość HostingContext jest <xref:System.Web.Configuration.WebContext>, <xref:System.Configuration.ExeContext>, lub `null`.</xref:System.Configuration.ExeContext> </xref:System.Web.Configuration.WebContext>"
  example:
  - "The following code example demonstrates how to use the HostingContext property.  \n  \n [!code-vb[System.Configuration.ContextInformation#3](~/add/codesnippet/visualbasic/p-system.configuration.c_46_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#3](~/add/codesnippet/csharp/p-system.configuration.c_46_1.cs)]"
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: "Obiekt określający środowisko, w których właściwość konfiguracyjna jest oceniane."
  overload: System.Configuration.ContextInformation.HostingContext*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera wartość określającą, czy właściwości konfiguracji jest oceniana na poziomie konfiguracji komputera."
  remarks: "Gdy jest zwrócona wartość IsMachineLevel `false`, użyj <xref:System.Configuration.ContextInformation.HostingContext%2A>Właściwości w celu określenia poziomu w hierarchii konfiguracji.</xref:System.Configuration.ContextInformation.HostingContext%2A>"
  example:
  - "The following code example demonstrates how to use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.  \n  \n [!code-vb[System.Configuration.ContextInformation#2](~/add/codesnippet/visualbasic/p-system.configuration.c_7_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#2](~/add/codesnippet/csharp/p-system.configuration.c_7_1.cs)]"
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli właściwości konfiguracji jest oceniana na poziomie konfiguracji komputera; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ContextInformation.IsMachineLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ContextInformation.GetSection*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection
  nameWithType: ContextInformation.GetSection
- uid: System.Configuration.ContextInformation.HostingContext*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
