### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelLogLevel
  id: ProcessModelLogLevel
  children:
  - System.Web.Configuration.ProcessModelLogLevel.All
  - System.Web.Configuration.ProcessModelLogLevel.Errors
  - System.Web.Configuration.ProcessModelLogLevel.None
  langs:
  - csharp
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
  type: Enum
  summary: "Określa typy zdarzeń, które mają być rejestrowane w dzienniku zdarzeń."
  remarks: "Wyliczenie ProcessModelLogLevel zawiera wartości do użycia podczas ustawiania <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>Właściwości.</xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>       Wartość domyślna to błędy."
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/csharp/t-system.web.configurati_95_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/visualbasic/t-system.web.configurati_95_1.vb)]"
  syntax:
    content: public enum ProcessModelLogLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  id: All
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że wszystkie przetwarzania zdarzeń są rejestrowane. To pole jest stałą."
  remarks: "Użyj tej opcji, jeśli chcesz eksplorować możliwych błędów, aplikacja może wydawać bez żadnego filtrowania. Ta opcja jest przydatna podczas kompilowanie i debugowanie fazy."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  id: Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że zamknięć, zamknięcia limit pamięci i zamknięcia zakleszczenia są rejestrowane. To pole jest stałą."
  remarks: "Jest to wartość domyślna."
  syntax:
    content: Errors
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że zdarzenia nie są rejestrowane. To pole jest stałą."
  remarks: "Możesz użyć tej opcji dla przetestowane i wdrożone aplikacje."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
- uid: System.Web.Configuration.ProcessModelLogLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
