### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCookiesSection
  id: HttpCookiesSection
  children:
  - System.Web.Configuration.HttpCookiesSection.#ctor
  - System.Web.Configuration.HttpCookiesSection.Domain
  - System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  - System.Web.Configuration.HttpCookiesSection.Properties
  - System.Web.Configuration.HttpCookiesSection.RequireSSL
  langs:
  - csharp
  name: HttpCookiesSection
  nameWithType: HttpCookiesSection
  fullName: System.Web.Configuration.HttpCookiesSection
  type: Class
  summary: "Konfiguruje właściwości plików cookie używany przez aplikację sieci Web."
  remarks: "Klasa HttpCookiesSection umożliwia programowo modyfikacji i dostępu `httpCookies` sekcji pliku konfiguracji.       Definiuje ustawienia stosowane domyślnie do wszystkich plików cookie wystawiony przez aplikację, chyba że kod wystawianie pliku cookie zastępuje te.       Jednym z celów z `httpCookies` elementów jest obsługują `HttpOnly` plików cookie. `HttpOnly`pliki cookie (plików cookie z `HttpOnly` atrybut) wprowadzono w programie Internet Explorer 6 w celu zmniejszenia ryzyka skryptów między witrynami. `HttpOnly` Atrybutu uniemożliwia plików cookie uzyskiwany za pomocą skryptu po stronie klienta. Wszelkie informacje zawarte w `HttpOnly` plik cookie jest mniej prawdopodobne ujawniane haker lub złośliwych witryn sieci Web. Aby uzyskać więcej informacji Wyszukaj MSDN (msdn.microsoft.com) &quot;HttpOnly.&quot;      > [!NOTE] > HttpCookiesSection może odczytywać i zapisywać informacje od i do sekcji pliku konfiguracji zgodnie z sekcji właściwości, <xref:System.Configuration.SectionInformation.AllowDefinition%2A>której wartość jest <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> pokrewne"
  example:
  - "The following code example shows how to obtain the HttpCookiesSection object from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_7_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#1](~/add/codesnippet/csharp/t-system.web.configurati_7_1.cs)]"
  syntax:
    content: 'public sealed class HttpCookiesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: HttpCookiesSection()
  nameWithType: HttpCookiesSection.HttpCookiesSection()
  fullName: System.Web.Configuration.HttpCookiesSection.HttpCookiesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.HttpCookiesSection&quot;> </xref> klasy."
  remarks: "Ten konstruktor nie jest przeznaczony do użycia bezpośrednio w kodzie. Jest ona wywoływana przez system konfiguracji programu ASP.NET. Uzyskać wystąpienia <xref:System.Web.Configuration.HttpCookiesSection>przy użyciu <xref:System.Configuration.Configuration.GetSection%2A>metody.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HttpCookiesSection>"
  syntax:
    content: public HttpCookiesSection ();
    parameters: []
  overload: System.Web.Configuration.HttpCookiesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.Domain
  id: Domain
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: Domain
  nameWithType: HttpCookiesSection.Domain
  fullName: System.Web.Configuration.HttpCookiesSection.Domain
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia nazwę domeny pliku cookie."
  remarks: ''
  example:
  - "The following code example shows how to use the Domain property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_9_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#2](~/add/codesnippet/csharp/p-system.web.configurati_9_1.cs)]"
  syntax:
    content: public string Domain { get; set; }
    return:
      type: System.String
      description: "Nazwa domeny pliku cookie."
  overload: System.Web.Configuration.HttpCookiesSection.Domain*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  id: HttpOnlyCookies
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
  fullName: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia wartość wskazującą czy obsługę przeglądarki <xref uid=&quot;langword_csharp_HttpOnly&quot; name=&quot;HttpOnly&quot; href=&quot;&quot;> </xref> plik cookie jest włączona."
  remarks: "`httpCookies` Obsługuje element `HttpOnly` plików cookie. `HttpOnly`pliki cookie (plików cookie z `HttpOnly` atrybut) wprowadzono w programie Internet Explorer 6 w celu zmniejszenia ryzyka skryptów między witrynami. `HttpOnly` Atrybutu uniemożliwia plików cookie uzyskiwany za pomocą skryptu po stronie klienta. Wszelkie informacje zawarte w `HttpOnly` plik cookie jest mniej prawdopodobne ujawniane haker lub złośliwych witryn sieci Web. Aby uzyskać więcej informacji Wyszukaj MSDN (msdn.microsoft.com) &quot;HttpOnly.&quot;"
  example:
  - "The following code example shows how to use the HttpOnlyCookies property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_227_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#4](~/add/codesnippet/csharp/p-system.web.configurati_227_1.cs)]"
  syntax:
    content: public bool HttpOnlyCookies { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli obsługa <xref uid=&quot;langword_csharp_HttpOnly&quot; name=&quot;HttpOnly&quot; href=&quot;&quot;> </xref> pliki cookie są włączone; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpCookiesSection.Properties
  fullName: System.Web.Configuration.HttpCookiesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.HttpCookiesSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL
  id: RequireSSL
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
  fullName: System.Web.Configuration.HttpCookiesSection.RequireSSL
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia wartość wskazującą, czy wymagane jest komunikacji Secure Sockets Layer (SSL)."
  remarks: "Właściwość parametru RequireSSL Włącza lub wyłącza dane wyjściowe zgodnie z opisem w dokumencie RFC 2109 atrybutu bezpiecznego pliku cookie. Gdy jest używany przez przeglądarki zgodne, plik cookie będą wysyłane tylko ponownie przy użyciu połączenia przy użyciu protokołu SSL/TLS. Wartość domyślna to `false`."
  example:
  - "The following code example shows how to use the RequireSSL property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_82_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#3](~/add/codesnippet/csharp/p-system.web.configurati_82_1.cs)]"
  syntax:
    content: public bool RequireSSL { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli włączony jest protokół SSL; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.HttpCookiesSection.RequireSSL*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpCookiesSection.#ctor
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpCookiesSection()
  nameWithType: HttpCookiesSection.HttpCookiesSection()
  fullName: System.Web.Configuration.HttpCookiesSection.HttpCookiesSection()
- uid: System.Web.Configuration.HttpCookiesSection.Domain
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Domain
  nameWithType: HttpCookiesSection.Domain
  fullName: System.Web.Configuration.HttpCookiesSection.Domain
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
  fullName: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpCookiesSection.Properties
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Properties
  nameWithType: HttpCookiesSection.Properties
  fullName: System.Web.Configuration.HttpCookiesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
  fullName: System.Web.Configuration.HttpCookiesSection.RequireSSL
- uid: System.Web.Configuration.HttpCookiesSection.#ctor*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpCookiesSection
  nameWithType: HttpCookiesSection.HttpCookiesSection
- uid: System.Web.Configuration.HttpCookiesSection.Domain*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Domain
  nameWithType: HttpCookiesSection.Domain
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
- uid: System.Web.Configuration.HttpCookiesSection.Properties*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Properties
  nameWithType: HttpCookiesSection.Properties
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
