### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidatorAttribute
  id: StringValidatorAttribute
  children:
  - System.Configuration.StringValidatorAttribute.#ctor
  - System.Configuration.StringValidatorAttribute.InvalidCharacters
  - System.Configuration.StringValidatorAttribute.MaxLength
  - System.Configuration.StringValidatorAttribute.MinLength
  - System.Configuration.StringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute
  fullName: System.Configuration.StringValidatorAttribute
  type: Class
  summary: "Deklaratywnie nakazuje programu .NET Framework do sprawdzania poprawności ciąg we właściwości konfiguracji. Ta klasa nie może być dziedziczona."
  remarks: "StringValidatorAttribute służy do dekoracji właściwości konfiguracji. Jest to nakazać programowi .NET Framework do sprawdzania poprawności przy użyciu właściwości <xref:System.Configuration.StringValidator>i przekazywania do niej wartości parametrów decorating.</xref:System.Configuration.StringValidator>       Obiekty StringValidatorAttribute może dotyczyć tylko dla typów właściwości."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the StringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/t-system.configuration.s_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/t-system.configuration.s_1_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class StringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.StringValidatorAttribute&quot;> </xref> klasy."
  remarks: "Ten konstruktor służy oparte na atrybutach modelu do upewnij się, że wartość przypisana do właściwości elementu konfiguracji jest typu string."
  example:
  - "The following example shows how to use the StringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/visualbasic/m-system.configuration.s_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/csharp/m-system.configuration.s_2_1.cs)]"
  syntax:
    content: public StringValidatorAttribute ();
    parameters: []
  overload: System.Configuration.StringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  id: InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia dla właściwości nieprawidłowe znaki."
  remarks: ''
  example:
  - "The following example shows how to use the InvalidCharacters property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_15_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_15_1.cs)]"
  syntax:
    content: public string InvalidCharacters { get; set; }
    return:
      type: System.String
      description: "Ciąg, który zawiera zestaw znaków, które nie są dozwolone dla właściwości."
  overload: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  id: MaxLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia maksymalną długość dozwoloną dla ciągu można przypisać do właściwości."
  remarks: ''
  example:
  - "The following example shows how to use the MaxLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_8_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_8_1.cs)]"
  syntax:
    content: public int MaxLength { get; set; }
    return:
      type: System.Int32
      description: "Liczba całkowita, która określa maksymalną dopuszczalną długość ciągu można przypisać do właściwości."
  overload: System.Configuration.StringValidatorAttribute.MaxLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wybrana wartość jest mniejsza niż <xref:System.Configuration.StringValidatorAttribute.MinLength*>.</xref:System.Configuration.StringValidatorAttribute.MinLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MinLength
  id: MinLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia minimalny dozwolony dla ciągu można przypisać do właściwości."
  remarks: ''
  example:
  - "The following example shows how to use the MinLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_12_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_12_1.cs)]"
  syntax:
    content: public int MinLength { get; set; }
    return:
      type: System.Int32
      description: "Liczba całkowita, która wskazuje dozwolonych minimalną długość ciągu można przypisać do właściwości."
  overload: System.Configuration.StringValidatorAttribute.MinLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wybrana wartość jest większa niż <xref:System.Configuration.StringValidatorAttribute.MaxLength*>.</xref:System.Configuration.StringValidatorAttribute.MaxLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera wystąpienie elementu <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> klasy."
  remarks: "Właściwość ValidatorInstance służy do sprawdzania poprawności ciąg przez wywołanie jego <xref:System.Configuration.StringValidator.Validate%2A>metody.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/visualbasic/p-system.configuration.s_4_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/csharp/p-system.configuration.s_4_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Bieżącej <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> ustawienia w <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> wystąpienie modułu sprawdzania poprawności."
  overload: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.StringValidatorAttribute.#ctor
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidatorAttribute.MinLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.StringValidatorAttribute.#ctor*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute.StringValidatorAttribute
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
- uid: System.Configuration.StringValidatorAttribute.MaxLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
- uid: System.Configuration.StringValidatorAttribute.MinLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
