### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProvider
  id: SettingsProvider
  children:
  - System.Configuration.SettingsProvider.#ctor
  - System.Configuration.SettingsProvider.ApplicationName
  - System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  - System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  langs:
  - csharp
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
  type: Class
  summary: "Działa jako klasę podstawową dla wyprowadzanie ustawień niestandardowych dostawców w Architektura ustawień aplikacji."
  remarks: "Dostawca ustawień definiuje mechanizm przechowywania danych konfiguracji używanych w Architektura ustawień aplikacji. .NET Framework zawiera jeden domyślny dostawca ustawień, <xref:System.Configuration.LocalFileSettingsProvider>, która przechowuje dane konfiguracyjne do lokalnego systemu plików.</xref:System.Configuration.LocalFileSettingsProvider> Jednak mechanizmów alternatywny magazynu można utworzyć przez tworzenia klasy pochodnej z klasy abstrakcyjnej klasy SettingsProvider. Dostawcy, który używa klasy otoki jest określany przez dekoracji klasy otoki z <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> Jeśli ten atrybut nie jest określona, domyślnie <xref:System.Configuration.LocalFileSettingsProvider>, jest używany.</xref:System.Configuration.LocalFileSettingsProvider>       Podczas tworzenia niestandardowych ustawień dostawcy, co najmniej, należy podać implementacji dla trzy metody tej klasy,: <xref:System.Configuration.SettingsProvider.GetPropertyValues%2A>, <xref:System.Configuration.SettingsProvider.SetPropertyValues%2A>a <xref:System.Configuration.SettingsProvider.ApplicationName%2A>.</xref:System.Configuration.SettingsProvider.ApplicationName%2A> </xref:System.Configuration.SettingsProvider.SetPropertyValues%2A> </xref:System.Configuration.SettingsProvider.GetPropertyValues%2A>       Dla aplikacji klienckich, można dodać więcej standardowe funkcje do niestandardowego dostawcy również zaimplementowanie <xref:System.Configuration.IApplicationSettingsProvider>interfejsu.</xref:System.Configuration.IApplicationSettingsProvider> Ten interfejs odzwierciedla metod w <xref:System.Configuration.ApplicationSettingsBase>klasy, która głównie włącza obsługę przechowywania wersji.</xref:System.Configuration.ApplicationSettingsBase>       Zazwyczaj należy projektować dostawców ustawień jako pojedynczego wystąpienia Aby uniknąć rywalizacji magazynu. Dostawców należy również wątkowo, ponieważ one nie można wywołać jednocześnie z wielu wystąpień otoki w domenie aplikacji jednej lub wielu aplikacji w różnych domenach.       Co najmniej dostawcy ustawień musi rozpoznać trzy atrybuty —<xref:System.Configuration.ApplicationScopedSettingAttribute>, <xref:System.Configuration.UserScopedSettingAttribute>i <xref:System.Configuration.DefaultSettingValueAttribute>.</xref:System.Configuration.DefaultSettingValueAttribute> </xref:System.Configuration.UserScopedSettingAttribute> </xref:System.Configuration.ApplicationScopedSettingAttribute> Aby uzyskać pełną listę atrybutów, które mogą być stosowane do ustawień aplikacji, zobacz [atrybuty ustawień aplikacji](~/add/includes/ajax-current-ext-md.md). Ustawienia niestandardowego dostawcy powinna być rozpoznawana atrybuty stosowane do ustawienia właściwości w następujący sposób: 1.  Jeśli dostawca można wykonać żądania niejawnego przez atrybut, oczywiście go należy zrobić.      2.  Jeśli dostawca nie może zrealizować żądania, jego należy go zignorować trybie dyskretnym.      3.  Jeśli konflikt dwóch lub więcej właściwości; na przykład właściwość jest oznaczone zarówno <xref:System.Configuration.ApplicationScopedSettingAttribute>i <xref:System.Configuration.UserScopedSettingAttribute>; dostawca powinien zgłosić <xref:System.Configuration.ConfigurationException>.</xref:System.Configuration.ConfigurationException> </xref:System.Configuration.UserScopedSettingAttribute> </xref:System.Configuration.ApplicationScopedSettingAttribute>"
  syntax:
    content: 'public abstract class SettingsProvider : System.Configuration.Provider.ProviderBase'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: SettingsProvider()
  nameWithType: SettingsProvider.SettingsProvider()
  fullName: System.Configuration.SettingsProvider.SettingsProvider()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje wystąpienie klasy <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> klasy."
  remarks: "Jest to domyślny Konstruktor chroniony dla tej klasy abstrakcyjnej. Pochodne ustawień niestandardowych dostawców nie są wymagane do ponieważ jawny Konstruktor <xref:System.Configuration.Provider.ProviderBase.Initialize%2A>metody przeważnie wykonuje wszystkie inicjowania.</xref:System.Configuration.Provider.ProviderBase.Initialize%2A>       Kod klienta zazwyczaj nie bezpośrednio utworzyć wystąpienia dostawcy ustawień; Zamiast tego użyj poniższej procedury można znaleźć dostawcy, ustawienia określone ustawienia właściwości: 1.  Wywołanie <xref:System.ComponentModel.Component.GetService%2A>metody dla bieżącego <xref:System.ComponentModel.Component>lub <xref:System.ComponentModel.ISite>zwraca odwołanie do bieżącego <xref:System.Configuration.ISettingsProviderService>.</xref:System.Configuration.ISettingsProviderService> </xref:System.ComponentModel.ISite> </xref:System.ComponentModel.Component> </xref:System.ComponentModel.Component.GetService%2A>      2.  Wywołanie <xref:System.Configuration.ISettingsProviderService.GetSettingsProvider%2A>metody <xref:System.Configuration.ISettingsProviderService>pobierane w pierwszym kroku do zwrócenia dostawcy ustawień.</xref:System.Configuration.ISettingsProviderService> </xref:System.Configuration.ISettingsProviderService.GetSettingsProvider%2A>"
  syntax:
    content: protected SettingsProvider ();
    parameters: []
  overload: System.Configuration.SettingsProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.ApplicationName
  id: ApplicationName
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
  fullName: System.Configuration.SettingsProvider.ApplicationName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera lub ustawia nazwę aktualnie uruchomionej aplikacji."
  remarks: "Właściwość ApplicationName i <xref:System.Configuration.Provider.ProviderBase.Name%2A>Właściwości pomoc, aby usunąć niejednoznaczność podobnie właściwości o nazwie ustawienia w innych aplikacjach.</xref:System.Configuration.Provider.ProviderBase.Name%2A>"
  syntax:
    content: public abstract string ApplicationName { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>zawierający skróconą nazwę aplikacji, która nie zawiera pełną ścieżkę lub rozszerzenie, na przykład, `SimpleAppSettings`.</xref:System.String>"
  overload: System.Configuration.SettingsProvider.ApplicationName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  id: GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  nameWithType: SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Zwraca kolekcję ustawień wartości właściwości określonej wystąpienia i ustawień właściwości grupy aplikacji."
  remarks: "Metoda GetPropertyValues musi zostać wdrożona do obsługi ustawienia specjalne, te oznaczonych <xref:System.Configuration.SpecialSettingAttribute>, jak również uzgodnienia aplikacji i ustawień użytkowników.</xref:System.Configuration.SpecialSettingAttribute>"
  syntax:
    content: public abstract System.Configuration.SettingsPropertyValueCollection GetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection collection);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> opisujący sposób użycia bieżącej aplikacji."
    - id: collection
      type: System.Configuration.SettingsPropertyCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyCollection&quot;> </xref> zawierający grupę właściwość ustawienia, których wartości mają zostać pobrane."
    return:
      type: System.Configuration.SettingsPropertyValueCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyValueCollection&quot;> </xref> zawierające wartości dla określonych ustawień właściwości grupy."
  overload: System.Configuration.SettingsProvider.GetPropertyValues*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  id: SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  nameWithType: SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  fullName: System.Configuration.SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Ustawia wartości określonej grupy ustawień właściwości."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase>zawiera <xref:System.Configuration.ApplicationSettingsBase.Save%2A>metodę, która jest wywoływana, aby utrwalić wartości wszystkich właściwości ustawień.</xref:System.Configuration.ApplicationSettingsBase.Save%2A></xref:System.Configuration.ApplicationSettingsBase> Ta metoda wylicza wszystkich dostawców ustawień skojarzonych z jego właściwości ustawień i wywołuje metodę SetPropertyValues dla każdego <xref:System.Configuration.SettingsProvider>do wykonania tej operacji serializacji rzeczywiste.</xref:System.Configuration.SettingsProvider>       Metoda SetPropertyValues powinny zostać wdrożone z myślą o bezpieczeństwie: — tylko w pełni zaufany kod powinien mieć możliwość zaktualizowania ustawień aplikacji. Częściowo zaufany kod powinien mieć możliwość zaktualizować tylko ustawienia aplikacji użytkownika. Kodzie niezaufanym nie zwykle można zaktualizować ustawień aplikacji.      — Przydziały użycie należy rozważyć w celu ochrony przed atakami zasobów przez częściowo zaufane aplikacje."
  syntax:
    content: public abstract void SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection collection);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> opisujące bieżącego użycia aplikacji."
    - id: collection
      type: System.Configuration.SettingsPropertyValueCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyValueCollection&quot;> </xref> reprezentująca grupę ustawień właściwości można ustawić."
  overload: System.Configuration.SettingsProvider.SetPropertyValues*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.SettingsProvider.#ctor
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SettingsProvider()
  nameWithType: SettingsProvider.SettingsProvider()
  fullName: System.Configuration.SettingsProvider.SettingsProvider()
- uid: System.Configuration.SettingsProvider.ApplicationName
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
  fullName: System.Configuration.SettingsProvider.ApplicationName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  nameWithType: SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
- uid: System.Configuration.SettingsPropertyValueCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyValueCollection
  nameWithType: SettingsPropertyValueCollection
  fullName: System.Configuration.SettingsPropertyValueCollection
- uid: System.Configuration.SettingsContext
  parent: System.Configuration
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
- uid: System.Configuration.SettingsPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyCollection
  nameWithType: SettingsPropertyCollection
  fullName: System.Configuration.SettingsPropertyCollection
- uid: System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  nameWithType: SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  fullName: System.Configuration.SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
- uid: System.Configuration.SettingsProvider.#ctor*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider.SettingsProvider
- uid: System.Configuration.SettingsProvider.ApplicationName*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
- uid: System.Configuration.SettingsProvider.GetPropertyValues*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: GetPropertyValues
  nameWithType: SettingsProvider.GetPropertyValues
- uid: System.Configuration.SettingsProvider.SetPropertyValues*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SetPropertyValues
  nameWithType: SettingsProvider.SetPropertyValues
