### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebConfigurationFileMap
  id: WebConfigurationFileMap
  children:
  - System.Web.Configuration.WebConfigurationFileMap.#ctor
  - System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  - System.Web.Configuration.WebConfigurationFileMap.Clone
  - System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  langs:
  - csharp
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap
  fullName: System.Web.Configuration.WebConfigurationFileMap
  type: Class
  summary: "Definiuje mapowania pliku konfiguracji dla aplikacji sieci Web. Ta klasa nie może być dziedziczona."
  remarks: "Klasa WebConfigurationFileMap jest używana do określania hierarchii pliku konfiguracji sieci Web. Domyślnie system konfiguracji używa metabazy usług IIS w celu określenia hierarchii plików sieci Web. Jeśli nie zainstalowano usług IIS lub aplikacja jest przeznaczony dla wersji programu .NET Framework, która nie jest w najnowszej wersji, który jest zainstalowany na serwerze, klasa WebConfigurationFileMap umożliwia zdefiniowanie niestandardowego hierarchii.       Klasa WebConfigurationFileMap można określić pojedynczą ścieżkę lub wiele ścieżek związane z plików konfiguracyjnych."
  syntax:
    content: 'public sealed class WebConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klasy."
  syntax:
    content: public WebConfigurationFileMap ();
    parameters: []
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> przy użyciu nazwy pliku konfiguracji określonej maszyny."
  remarks: "Ten konstruktor jest używany podczas przeznaczona dla wersji [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] wcześniejsza niż najnowsze jest zainstalowany na komputerze. Metoda można określić plik konfiguracji maszyny, która jest odpowiednia do wersji [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] , który ma być przeznaczona dla.      > [!NOTE] > Nawet konstruktora akceptuje tylko ścieżkę do pliku Machine.config, system konfiguracji również odczyta głównego pliku Web.config w tym samym katalogu której istnieje w pliku Machine.config."
  syntax:
    content: public WebConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "Nazwa pliku konfiguracji komputera z pełną ścieżkę fizyczną (na przykład `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  id: Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klasy z taką samą wartość jak istniejącego wystąpienia."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "Nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klasy."
  overload: System.Web.Configuration.WebConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  id: VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera kolekcję listy katalogów wirtualnych dla aplikacji sieci Web."
  remarks: "Katalogi wirtualne aplikacji sieci Web nie może być niekoniecznie mapowany na katalogi fizyczne na serwerze. <xref:System.Web.Configuration.VirtualDirectoryMapping>Klasa jest niezależne od usług IIS.</xref:System.Web.Configuration.VirtualDirectoryMapping>"
  syntax:
    content: public System.Web.Configuration.VirtualDirectoryMappingCollection VirtualDirectories { get; }
    return:
      type: System.Web.Configuration.VirtualDirectoryMappingCollection
      description: "Kolekcja <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> obiektów."
  overload: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
- uid: System.Web.Configuration.VirtualDirectoryMappingCollection
  parent: System.Web.Configuration
  isExternal: false
  name: VirtualDirectoryMappingCollection
  nameWithType: VirtualDirectoryMappingCollection
  fullName: System.Web.Configuration.VirtualDirectoryMappingCollection
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: WebConfigurationFileMap.Clone
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
