### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Compiler
  id: Compiler
  children:
  - System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  - System.Web.Configuration.Compiler.CompilerOptions
  - System.Web.Configuration.Compiler.Extension
  - System.Web.Configuration.Compiler.Language
  - System.Web.Configuration.Compiler.Properties
  - System.Web.Configuration.Compiler.Type
  - System.Web.Configuration.Compiler.WarningLevel
  langs:
  - csharp
  name: Compiler
  nameWithType: Compiler
  fullName: System.Web.Configuration.Compiler
  type: Class
  summary: "Definiuje kompilatora, która jest używana do obsługi infrastruktury kompilacji aplikacji sieci Web. Ta klasa nie może być dziedziczona."
  remarks: "Klasa kompilatora umożliwia do uzyskania programowego dostępu do elementu konfiguracji kompilatora."
  syntax:
    content: 'public sealed class Compiler : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy wystąpienie <xref href=&quot;System.Web.Configuration.Compiler&quot;> </xref> został zainicjowany w podanych wartości."
  syntax:
    content: public Compiler (string compilerOptions, string extension, string language, string type, int warningLevel);
    parameters:
    - id: compilerOptions
      type: System.String
      description: "Zawiera listę dodatkowych opcji specyficznych dla kompilatora do przekazania podczas kompilacji."
    - id: extension
      type: System.String
      description: "Zawiera listę rozszerzeń nazw plików używane do dynamicznego plików z kodem oddzielonych średnikami. Na przykład &quot;.cs&quot;."
    - id: language
      type: System.String
      description: "Zawiera listę rozdzielonych średnikami języki używane w plikach kompilacji dynamicznej. Na przykład &quot;c# cs; csharp&quot;."
    - id: type
      type: System.String
      description: "Określa kombinację przecinkami klasy/zestawu wskazującą klasy .NET Framework."
    - id: warningLevel
      type: System.Int32
      description: "Określa poziomy ostrzeżeń kompilatora."
  overload: System.Web.Configuration.Compiler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.CompilerOptions
  id: CompilerOptions
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera listę opcji specyficznych dla kompilatora do użycia podczas kompilacji."
  syntax:
    content: public string CompilerOptions { get; }
    return:
      type: System.String
      description: "Wartość określająca opcji specyficznych dla kompilatora, aby podczas kompilacji. To nie jest zestawem scalone, ale raczej zastępuje wszelkie wartości wcześniej zdefiniowanego w starszych pozycje konfiguracji."
  overload: System.Web.Configuration.Compiler.CompilerOptions*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Extension
  id: Extension
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera listę rozszerzeń nazw plików używane do dynamicznego plików z kodem."
  remarks: "Jeśli lista rozszerzeń nazw plików zawiera więcej niż jedno rozszerzenie, lista jest oddzielonych średnikami."
  syntax:
    content: public string Extension { get; }
    return:
      type: System.String
      description: "Wartość określającą rozszerzeń nazw plików używane do dynamicznego plików z kodem, pliki w katalogu kodu i inne odwołania do plików."
  overload: System.Web.Configuration.Compiler.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Language
  id: Language
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera listę języków do użycia w plikach kompilacji dynamicznej programowania."
  remarks: "Jeśli lista języków programowania obejmuje więcej niż jednym języku, lista jest oddzielonych średnikami."
  syntax:
    content: public string Language { get; }
    return:
      type: System.String
      description: "Wartość określająca języków programowania, używany w plikach kompilacji dynamicznej."
  overload: System.Web.Configuration.Compiler.Language*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Properties
  id: Properties
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.Compiler.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Type
  id: Type
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera nazwę typu kompilatora dostawcy języka dla plikach kompilacji dynamicznej."
  remarks: "Określa nazwę typu dostawcy języka, w tym nazwę zestawu zawierającego implementację dostawcy."
  syntax:
    content: public string Type { get; }
    return:
      type: System.String
      description: "Wartość określająca nazwę typu kompilatora języka używany w plikach kompilacji dynamicznej."
  overload: System.Web.Configuration.Compiler.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.WarningLevel
  id: WarningLevel
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera poziom ostrzeżeń kompilatora."
  remarks: "Określa domyślny poziom ostrzeżeń kompilatora; Określa poziom, jaką dostawcy języka traktuje kompilacja ostrzeżenia jako błędy."
  syntax:
    content: public int WarningLevel { get; }
    return:
      type: System.Int32
      description: "Wartość określająca poziom ostrzeżeń kompilatora."
  overload: System.Web.Configuration.Compiler.WarningLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.Compiler.CompilerOptions
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Compiler.Type
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
- uid: System.Web.Configuration.Compiler.#ctor*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler
  nameWithType: Compiler.Compiler
- uid: System.Web.Configuration.Compiler.CompilerOptions*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
- uid: System.Web.Configuration.Compiler.Type*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
