### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  id: ValidatingPropertiesEventArgs
  children:
  - System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  - System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  langs:
  - csharp
  name: ValidatingPropertiesEventArgs
  nameWithType: ValidatingPropertiesEventArgs
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  type: Class
  summary: "Udostępnia dane dla <xref href=&quot;System.Web.ApplicationServices.ProfileService.ValidatingProperties&quot;> </xref> zdarzeń."
  remarks: "Utwórz program obsługi zdarzeń dla <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>zdarzeń, aby dostosować poprawności wartości właściwości profilu.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>Zdarzenie jest zgłaszane, gdy są ustawione właściwości profilu dla użytkownika.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> Jeśli wszystkie wartości właściwości wystąpi niepowodzenie weryfikacji, dodaj je do kolekcji w <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>Właściwości.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> <xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>Metoda zwraca kolekcję w <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>Właściwości, dzięki czemu można określić właściwości, które nie przeszedł sprawdzania poprawności.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> </xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> event. When the value passed for `FirstName` property is empty or `null`, the `FirstName` property is added to the <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> collection.  \n  \n [!code-vb[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/visualbasic/t-system.web.application_2_1.asax)]\n [!code-cs[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/csharp/t-system.web.application_2_1.asax)]"
  syntax:
    content: 'public class ValidatingPropertiesEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  id: FailedProperties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  langs:
  - csharp
  name: FailedProperties
  nameWithType: ValidatingPropertiesEventArgs.FailedProperties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Pobiera kolekcję zawierającą właściwości profilu, których nie powiodła się weryfikacja."
  remarks: "Właściwość FailedProperties zawiera kolekcję nazwy właściwości, których nie powiodła się weryfikacja. W przypadku utworzenia programu obsługi zdarzeń dla <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>zdarzeń, Dodaj nazwy właściwości, które niepowodzenie sprawdzania poprawności do kolekcji we właściwości FailedProperties.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> <xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>— Metoda zwraca kolekcję we właściwości FailedProperties, dzięki czemu można określić właściwości, które nie przeszedł sprawdzania poprawności.</xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> event. When the value passed for `FirstName` property is empty or `null`, the `FirstName` property is added to the FailedProperties collection.  \n  \n [!code-vb[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/visualbasic/p-system.web.application_7_1.asax)]\n [!code-cs[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/csharp/p-system.web.application_7_1.asax)]"
  syntax:
    content: public System.Collections.ObjectModel.Collection<string> FailedProperties { get; }
    return:
      type: System.Collections.ObjectModel.Collection{System.String}
      description: "Właściwości profilu, których nie powiodła się weryfikacja."
  overload: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  id: Properties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  langs:
  - csharp
  name: Properties
  nameWithType: ValidatingPropertiesEventArgs.Properties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Pobiera kolekcję nazwy i wartości właściwości profilu, aby sprawdzić poprawność."
  remarks: "Zwraca właściwości właściwości <xref:System.Collections.IDictionary>obiekt, który zawiera nazwy i wartości właściwości profilu, aby ustawić dla użytkownika.</xref:System.Collections.IDictionary> W przypadku utworzenia programu obsługi zdarzeń dla <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>zdarzeń, można pobrać właściwości można sprawdzić poprawności właściwości właściwości.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> Jeśli wszystkie wartości wystąpi niepowodzenie weryfikacji, dodaj je do <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>Właściwości.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> <xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>Metoda zwraca kolekcję w <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>Właściwości, dzięki czemu można określić właściwości, które nie przeszedł sprawdzania poprawności.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> </xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> event. When the value passed for `FirstName` property is empty or `null`, the `FirstName` property is added to the <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> collection.  \n  \n [!code-vb[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/visualbasic/p-system.web.application_8_1.asax)]\n [!code-cs[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/csharp/p-system.web.application_8_1.asax)]"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,object> Properties { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: "Nazwy i wartości właściwości profilu, aby sprawdzić poprawność."
  overload: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: FailedProperties
  nameWithType: ValidatingPropertiesEventArgs.FailedProperties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
- uid: System.Collections.ObjectModel.Collection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: Collection<String>
  nameWithType: Collection<String>
  fullName: System.Collections.ObjectModel.Collection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.Collection`1
    name: Collection
    nameWithType: Collection
    fullName: Collection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: Properties
  nameWithType: ValidatingPropertiesEventArgs.Properties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,Object>
  nameWithType: IDictionary<String,Object>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Object>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.Object>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: Object
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties*
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: FailedProperties
  nameWithType: ValidatingPropertiesEventArgs.FailedProperties
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties*
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: Properties
  nameWithType: ValidatingPropertiesEventArgs.Properties
