### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorBase
  id: ConfigurationValidatorBase
  children:
  - System.Configuration.ConfigurationValidatorBase.#ctor
  - System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  - System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  langs:
  - csharp
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
  type: Class
  summary: "Działa jako klasę podstawową dla wyprowadzanie klasy sprawdzania poprawności, dzięki czemu można zweryfikować wartości obiektu."
  remarks: "Klasa ConfigurationValidatorBase jest używana do tworzenia niestandardowego modułu weryfikacji. Niestandardowego modułu weryfikacji można sprawdzić wartości obiektu."
  syntax:
    content: public abstract class ConfigurationValidatorBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje wystąpienie klasy <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> klasy."
  syntax:
    content: protected ConfigurationValidatorBase ();
    parameters: []
  overload: System.Configuration.ConfigurationValidatorBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Określa, czy obiekt może być weryfikowane na podstawie typu."
  syntax:
    content: public virtual bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Typ obiektu."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <code> type </code> odpowiada oczekiwanej wartości parametru <xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;> </xref>; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationValidatorBase.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Określa, czy wartość obiektu jest nieprawidłowy."
  remarks: "Obiekt pochodną <xref:System.Configuration.ConfigurationValidatorBase>Klasa zawiera kryteriów niezbędnych do weryfikacji obiektu.</xref:System.Configuration.ConfigurationValidatorBase> Kryteria są ustalone podczas tworzenia wystąpienia klasy pochodnej. Obiekt do sprawdzania poprawności został przekazany jako parametr metody sprawdzania poprawności."
  syntax:
    content: public abstract void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Wartość obiektu."
  overload: System.Configuration.ConfigurationValidatorBase.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
- uid: System.Configuration.ConfigurationValidatorBase.#ctor*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate
  nameWithType: ConfigurationValidatorBase.CanValidate
- uid: System.Configuration.ConfigurationValidatorBase.Validate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate
  nameWithType: ConfigurationValidatorBase.Validate
