### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement
  id: X509PeerCertificateElement
  children:
  - System.ServiceModel.Configuration.X509PeerCertificateElement.#ctor
  - System.ServiceModel.Configuration.X509PeerCertificateElement.Copy(System.ServiceModel.Configuration.X509PeerCertificateElement)
  - System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue
  - System.ServiceModel.Configuration.X509PeerCertificateElement.Properties
  - System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation
  - System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName
  - System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType
  langs:
  - csharp
  name: X509PeerCertificateElement
  nameWithType: X509PeerCertificateElement
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement
  type: Class
  summary: "Reprezentuje element konfiguracji, który określa certyfikat używany przez element równorzędny. Ta klasa nie może być dziedziczona."
  remarks: ''
  example:
  - <xref:System.ServiceModel.Security.X509PeerCertificateAuthentication>
  syntax:
    content: 'public sealed class X509PeerCertificateElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: X509PeerCertificateElement()
  nameWithType: X509PeerCertificateElement.X509PeerCertificateElement()
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.X509PeerCertificateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.X509PeerCertificateElement&quot;> </xref> klasy."
  syntax:
    content: public X509PeerCertificateElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.Copy(System.ServiceModel.Configuration.X509PeerCertificateElement)
  id: Copy(System.ServiceModel.Configuration.X509PeerCertificateElement)
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: Copy(X509PeerCertificateElement)
  nameWithType: X509PeerCertificateElement.Copy(X509PeerCertificateElement)
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.Copy(X509PeerCertificateElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Kopiuje zawartość elementu określoną konfigurację do tego elementu konfiguracji."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509PeerCertificateElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509PeerCertificateElement
      description: "Element konfiguracji ma zostać skopiowany."
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Plik konfiguracji jest tylko do odczytu."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509PeerCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia ciąg, który określa wartość do wyszukania w magazynie certyfikatów X.509."
  remarks: "Typ zawartych w tej właściwości musi spełniać wymagania określonego <xref:System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType%2A>wartość.</xref:System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType%2A> Wartość domyślna to ciąg pusty."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "Wartość do wyszukania w magazynie certyfikatów X.509."
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509PeerCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509PeerCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia wartość, która określa lokalizację magazynu certyfikatów, których klient może używać do weryfikacji certyfikatu elementu równorzędnego."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;></xref>. Wartość domyślna to <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509PeerCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia nazwę magazynu certyfikatu X.509 do otwarcia."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> zawierający nazwę magazynu certyfikatu X.509 do otwarcia."
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509PeerCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia typ wyszukiwania X.509 w celu wykonania."
  remarks: "Typ zawarty w <xref:System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue%2A>muszą spełniać wymagania dotyczące tej właściwości.</xref:System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> , który określa typ wyszukiwania X.509 w celu wykonania."
  overload: System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.#ctor
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: X509PeerCertificateElement()
  nameWithType: X509PeerCertificateElement.X509PeerCertificateElement()
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.X509PeerCertificateElement()
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.Copy(System.ServiceModel.Configuration.X509PeerCertificateElement)
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: Copy(X509PeerCertificateElement)
  nameWithType: X509PeerCertificateElement.Copy(X509PeerCertificateElement)
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.Copy(X509PeerCertificateElement)
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509PeerCertificateElement
  nameWithType: X509PeerCertificateElement
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509PeerCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.Properties
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509PeerCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509PeerCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509PeerCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509PeerCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.#ctor*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: X509PeerCertificateElement
  nameWithType: X509PeerCertificateElement.X509PeerCertificateElement
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.Copy*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: Copy
  nameWithType: X509PeerCertificateElement.Copy
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.FindValue*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509PeerCertificateElement.FindValue
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.Properties*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509PeerCertificateElement.Properties
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509PeerCertificateElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.StoreName*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509PeerCertificateElement.StoreName
- uid: System.ServiceModel.Configuration.X509PeerCertificateElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509PeerCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509PeerCertificateElement.X509FindType
