### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "Określa, czy dostawca ustawień należy wyłączyć wszelka logika, które pobiera wywoływane po wykryciu uaktualnienie aplikacji. Ta klasa nie może być dziedziczona."
  remarks: "Aby utworzyć dostawcy ustawień pełni funkcjonalnej aplikacji, który obsługuje przechowywanie wersji aplikacji, dostawca musi implementować <xref:System.Configuration.IApplicationSettingsProvider>interfejsu.</xref:System.Configuration.IApplicationSettingsProvider> Jeden z elementów członkowskich w tym interfejsie <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>wywoływana jest metoda, aby powiadomić dostawcy zainstalowanie nowej wersji aplikacji.</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> W odpowiedzi dostawca oczekuje się, wykonaj odpowiednią akcję, zwykle migracja poza ustawienia aplikacji.       NoSettingsVersionUpgradeAttribute informuje o dostawcy, aby pominąć uaktualnienia logiki skojarzonej z bieżącej klasy ustawienia. W związku z tym wartość poprzedniej wersji tej grupy właściwości nie można migrować do nowej instalacji.      > [!NOTE] > Ten atrybut można stosować do poszczególnych aplikacji ustawienia właściwości."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.NoSettingsVersionUpgradeAttribute&quot;> </xref> klasy."
  remarks: "To jest dostarczane przez kompilator domyślnego konstruktora dla <xref:System.Configuration.NoSettingsVersionUpgradeAttribute>klasy.</xref:System.Configuration.NoSettingsVersionUpgradeAttribute>"
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
