### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSFederationHttpSecurity
  id: WSFederationHttpSecurity
  children:
  - System.ServiceModel.WSFederationHttpSecurity.#ctor
  - System.ServiceModel.WSFederationHttpSecurity.Message
  - System.ServiceModel.WSFederationHttpSecurity.Mode
  - System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  langs:
  - csharp
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity
  fullName: System.ServiceModel.WSFederationHttpSecurity
  type: Class
  summary: "Określa ustawienia zabezpieczeń dla <xref href=&quot;System.ServiceModel.WSFederationHttpBinding&quot;> </xref>. Ta klasa nie może być dziedziczona."
  remarks: "Ta klasa określa rodzaj zabezpieczeń ma zostać zastosowany do `wsFederationHttpBinding` wiązanie i ustawienia zabezpieczeń."
  syntax:
    content: public sealed class WSFederationHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: System.ServiceModel.WSFederationHttpSecurity.WSFederationHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.WSFederationHttpSecurity&quot;> </xref> klasy."
  syntax:
    content: public WSFederationHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSFederationHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: System.ServiceModel.WSFederationHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Wskazuje ustawienia zabezpieczeń wiadomości dla <xref href=&quot;System.ServiceModel.WSFederationHttpBinding&quot;> </xref>."
  remarks: "Obiekt zwrócony określa właściwości szczegółowe zabezpieczenia na poziomie komunikatu `wsFederationHttpBinding`."
  example:
  - "The following code shows how to access this property and use it to set properties of the `wsFederationHttpBinding`.  \n  \n [!code-vb[WSFederationHttpSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_6_1.vb)]\n [!code-cs[WSFederationHttpSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ws_6_1.cs)]"
  syntax:
    content: public System.ServiceModel.FederatedMessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.FederatedMessageSecurityOverHttp
      description: "A <xref href=&quot;System.ServiceModel.FederatedMessageSecurityOverHttp&quot;></xref> value."
  overload: System.ServiceModel.WSFederationHttpSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: System.ServiceModel.WSFederationHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Pobiera lub ustawia typ zabezpieczenia do zastosowania."
  remarks: "Zwrócony element członkowski wyliczenia określa ogólne typu zabezpieczeń ma być stosowany.       Dozwolone wartości to <xref:System.ServiceModel.WSFederationHttpSecurityMode>i <xref:System.ServiceModel.WSFederationHttpSecurityMode>.</xref:System.ServiceModel.WSFederationHttpSecurityMode> </xref:System.ServiceModel.WSFederationHttpSecurityMode>       W <xref:System.ServiceModel.WSFederationHttpSecurityMode>Tryb zabezpieczeń, komunikat jest wysyłany za pośrednictwem protokołu HTTP i zabezpieczenia komunikatów SOAP jest używany do ochrony wiadomości.</xref:System.ServiceModel.WSFederationHttpSecurityMode> Klient uwierzytelniania oparte na wystawionego tokenu uzyskane z usługi tokenu zabezpieczającego. Uwierzytelnianie serwera jest oparta na certyfikat serwera.       W <xref:System.ServiceModel.WSFederationHttpSecurityMode>Tryb zabezpieczeń, komunikat jest wysyłany przy użyciu protokołu HTTPS.</xref:System.ServiceModel.WSFederationHttpSecurityMode> Uwierzytelnianie klienta odbywa się przy tym wystawionego tokenu uzyskane z usługi tokenu zabezpieczającego w wiadomości protokołu SOAP. Uwierzytelnianie serwera, w zależności od certyfikatu serwera jest wykonywane w ramach konfigurowania połączenia HTTPS."
  example:
  - "The following code shows how to set this property.  \n  \n [!code-vb[WSFederationHttpSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_5_1.vb)]\n [!code-cs[WSFederationHttpSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ws_5_1.cs)]"
  syntax:
    content: public System.ServiceModel.WSFederationHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSFederationHttpSecurityMode
      description: "A <xref href=&quot;System.ServiceModel.WSFederationHttpSecurityMode&quot;></xref>. Wartość domyślna to <xref href=&quot;System.ServiceModel.WSFederationHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.WSFederationHttpSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Zwraca wartość wskazującą, czy <xref:System.ServiceModel.WSFederationHttpSecurity.Message*>Właściwości została zmieniona z jej wartości domyślnej i powinny być serializowane.</xref:System.ServiceModel.WSFederationHttpSecurity.Message*>"
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <xref:System.ServiceModel.WSFederationHttpSecurity.Message*>wartość właściwości powinny być serializowane; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSFederationHttpSecurity.Message*>"
  overload: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSFederationHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Zwraca wartość wskazującą, czy <xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>Właściwości została zmieniona z jej wartości domyślnej i powinny być serializowane.</xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>"
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>wartość właściwości powinny być serializowane; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSFederationHttpSecurity.Mode*>"
  overload: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: System.ServiceModel.WSFederationHttpSecurity.WSFederationHttpSecurity()
- uid: System.ServiceModel.WSFederationHttpSecurity.Message
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: System.ServiceModel.WSFederationHttpSecurity.Message
- uid: System.ServiceModel.FederatedMessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: FederatedMessageSecurityOverHttp
  nameWithType: FederatedMessageSecurityOverHttp
  fullName: System.ServiceModel.FederatedMessageSecurityOverHttp
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: System.ServiceModel.WSFederationHttpSecurity.Mode
- uid: System.ServiceModel.WSFederationHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSFederationHttpSecurityMode
  nameWithType: WSFederationHttpSecurityMode
  fullName: System.ServiceModel.WSFederationHttpSecurityMode
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSFederationHttpSecurity.#ctor*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity
- uid: System.ServiceModel.WSFederationHttpSecurity.Message*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
- uid: System.ServiceModel.WSFederationHttpSecurity.Mode*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSFederationHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSFederationHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSFederationHttpSecurity.ShouldSerializeMode
