### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  id: BaseAddressPrefixFilterElement
  children:
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  type: Class
  summary: "Reprezentuje element konfiguracji, który określa przekazywanym przez filtr, który zapewnia mechanizm wyboru odpowiednich powiązań internetowych usług informacyjnych odnośnie do hostowania [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] aplikacji w usługach IIS. Ta klasa nie może być dziedziczona."
  remarks: "Prefiks dostawcę filtru mechanizm usługi do powiązania do określonego identyfikatora URI. Umożliwia ona obsługiwać wiele aplikacji o różnych adresu podstawowego dla tego samego schematu w tej samej lokacji.       Witryny sieci Web usług IIS są kontenerami dla aplikacji wirtualnych, które zawierają katalogów wirtualnych. Za pomocą co najmniej jednego powiązania usługi IIS można uzyskać dostępu do aplikacji w lokacji. Informacje Podaj powiązania usługi IIS: Protokół powiązania i informacje o wiązaniu. Powiązanie protokołu (np. HTTP) definiuje schemat, przez który dane są przesyłane i powiązanie informacji (np. adres IP, portu, nagłówka hosta) zawiera dane używane do uzyskania dostępu do witryny.       Usługi IIS obsługują określania wielokrotne powiązania usługi IIS dla każdej witryny, co prowadzi do wielu adresów bazowych dla każdego schematu. Ponieważ [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] usługi hostowanej przez witrynę umożliwia powiązanie, aby tylko jeden adres podstawowy dla każdego schematu, możesz użyć funkcji filtrowania prefiks wybierz wymagany adres podstawowy usługi hostowanej.  Przychodzące adres podstawowy, dostarczone przez usługi IIS, są filtrowane z filtru listy opcjonalny prefiks.       Na przykład witryna może zawierać następujący adres podstawowy ```   http://testl.fabrikam.com/Service.svc   http://test2.fabrikam.com/Service.svc   ``` następującego pliku konfiguracji można użyć do określenia filtru prefiks na poziomie elementu appdomain.      ```   <system.serviceModel>     <serviceHostingEnvironment>        <baseAddressPrefixFilters>           <add prefix=”net.tcp://test1.fabrikam.com:8000”/>           <add prefix=”http://test2.fabrikam.com:9000”/>       </baseAddressPrefixFilters>     </serviceHostingEnvironment>   </system.serviceModel>   ```W tym przykładzie `net.tcp://test1.fabrikam.com:8000` i `http://test2.fabrikam.com:9000` są tylko podstawowy adres ich systemów, które mogą być przekazywane.       Domyślnie jeśli nie określono prefiksu, wszystkie adresy są przekazywane. Określenie prefiksu spowoduje tylko pasujących adres podstawowy schemat przekazywane.      > [!NOTE] > Filtru nie obsługuje żadnych symboli wieloznacznych. Ponadto baseAddresses dostarczonych przez usługi IIS może być adresy powiązany z innych systemów, które nie znajduje się w `baseAddressPrefixFilters` listy. Tych adresów nie są odfiltrowywane."
  syntax:
    content: 'public sealed class BaseAddressPrefixFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> klasy."
  syntax:
    content: public BaseAddressPrefixFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  id: '#ctor(System.Uri)'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> klasy z określonym identyfikatorem URI."
  syntax:
    content: public BaseAddressPrefixFilterElement (Uri prefix);
    parameters:
    - id: prefix
      type: System.Uri
      description: "Filtr, który powoduje, że usługa do nasłuchiwania na wszystkie identyfikatory URI rozpoczynające się od tego określonego prefiksu."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia prefiks, który jest używany do dopasowywania część adresu podstawowego."
  syntax:
    content: public Uri Prefix { get; set; }
    return:
      type: System.Uri
      description: "Identyfikator URI, który jest używany do dopasowywania część adresu podstawowego."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
