### YamlMime:ManagedReference
items:
- uid: System.Configuration.IgnoreSectionHandler
  id: IgnoreSectionHandler
  children:
  - System.Configuration.IgnoreSectionHandler.#ctor
  - System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler
  fullName: System.Configuration.IgnoreSectionHandler
  type: Class
  summary: "Zawiera definicję modułu obsługi sekcji starszych dla sekcji konfiguracji, które nie są obsługiwane przez <xref href=&quot;System.Configuration&quot;> </xref> typów."
  remarks: "System konfiguracji całkowicie analizuje pliki konfiguracji do zbierania informacji o konfiguracji i zgłasza wyjątki po napotkaniu sekcji konfiguracyjnych, które nie mają odpowiadającego mu wpisu w `configSections` sekcji.       Dla tych sekcji, które nie są obsługiwane przez <xref:System.Configuration>typów, nowy typ otoki <xref:System.Configuration.IgnoreSection>podano.</xref:System.Configuration.IgnoreSection> </xref:System.Configuration> Ma to zapobiec wyjątków podczas analizowania pliku konfiguracji.       Do celów starszych dostępne są również IgnoreSectionHandler."
  syntax:
    content: 'public class IgnoreSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.IgnoreSectionHandler&quot;> </xref> klasy."
  syntax:
    content: public IgnoreSectionHandler ();
    parameters: []
  overload: System.Configuration.IgnoreSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Tworzy nowy program obsługi konfiguracji i dodaje obiekt określonej konfiguracji do kolekcji modułu obsługi sekcji."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Ustawienia konfiguracji w odpowiedniej sekcji konfiguracji nadrzędnej."
    - id: configContext
      type: System.Object
      description: "Ścieżka wirtualna, dla którego program obsługi sekcji konfiguracji oblicza wartości konfiguracji. Zazwyczaj ten parametr jest zarezerwowany i <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
    - id: section
      type: System.Xml.XmlNode
      description: "<xref href=&quot;System.Xml.XmlNode&quot;> </xref> Zawierający informacje o konfiguracji, które mają być obsługiwane. Zapewnia bezpośredni dostęp do zawartości XML sekcji konfiguracji."
    return:
      type: System.Object
      description: "Obiekt programu obsługi konfiguracji utworzony."
  overload: System.Configuration.IgnoreSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IgnoreSectionHandler.#ctor*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler
- uid: System.Configuration.IgnoreSectionHandler.Create*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create
  nameWithType: IgnoreSectionHandler.Create
