### YamlMime:ManagedReference
items:
- uid: System.Configuration.UriSection
  id: UriSection
  children:
  - System.Configuration.UriSection.#ctor
  - System.Configuration.UriSection.Idn
  - System.Configuration.UriSection.IriParsing
  - System.Configuration.UriSection.Properties
  - System.Configuration.UriSection.SchemeSettings
  langs:
  - csharp
  name: UriSection
  nameWithType: UriSection
  fullName: System.Configuration.UriSection
  type: Class
  summary: "Reprezentuje sekcję identyfikatora Uri w pliku konfiguracji."
  remarks: "Istniejące <xref:System.Uri?displayProperty=fullName>klasa została rozszerzona, aby zapewnić obsługę międzynarodowej identyfikatory zasobów (IRI) oraz międzynarodowych nazw domen.</xref:System.Uri?displayProperty=fullName> Bieżąca liczba użytkowników nie będą widzieć wszystkie zmiany z zachowaniem .NET Framework 2.0, chyba że umożliwiają one specjalnie IRI i IDN. Dzięki temu zgodność aplikacji we wcześniejszych wersjach programu .NET Framework.       Za pomocą klasy UriSection można pobrać ustawień konfiguracyjnych dla IRI i IDN."
  syntax:
    content: 'public sealed class UriSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Configuration.UriSection.#ctor
  id: '#ctor'
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: UriSection()
  nameWithType: UriSection.UriSection()
  fullName: System.Configuration.UriSection.UriSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.UriSection&quot;> </xref> klasy."
  remarks: "Istniejące <xref:System.Uri?displayProperty=fullName>klasa została rozszerzona, aby zapewnić obsługę międzynarodowej identyfikatory zasobów (IRI) oraz międzynarodowych nazw domen.</xref:System.Uri?displayProperty=fullName> Bieżąca liczba użytkowników nie będą widzieć wszystkie zmiany z zachowaniem .NET Framework 2.0, chyba że umożliwiają one specjalnie IRI i IDN. Dzięki temu zgodność aplikacji we wcześniejszych wersjach programu .NET Framework.       Ustawienia konfiguracji dla IRI i IDN można pobrać przy użyciu <xref:System.Configuration.UriSection>klasy.</xref:System.Configuration.UriSection>       Aby uzyskać więcej informacji na temat obsługi IRI zobacz sekcję uwag dla <xref:System.Uri?displayProperty=fullName>klasy.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public UriSection ();
    parameters: []
  overload: System.Configuration.UriSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.Idn
  id: Idn
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: Idn
  nameWithType: UriSection.Idn
  fullName: System.Configuration.UriSection.Idn
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> obiekt, który zawiera ustawienia konfiguracji dla międzynarodowej domeny nazwę (IDN) przetwarzania w &lt;xref:System.Uri?displayProperty=fullName&gt; klasy."
  remarks: "Istniejące <xref:System.Uri?displayProperty=fullName>klasa została rozszerzona, aby zapewnić obsługę międzynarodowej identyfikatory zasobów (IRI) oraz międzynarodowych nazw domen.</xref:System.Uri?displayProperty=fullName> Bieżąca liczba użytkowników nie będą widzieć wszystkie zmiany z zachowaniem .NET Framework 2.0, chyba że umożliwiają one specjalnie IRI i IDN. Dzięki temu zgodność aplikacji we wcześniejszych wersjach programu .NET Framework.       Ustawienia konfiguracji dla IRI i IDN można pobrać przy użyciu <xref:System.Configuration.UriSection>klasy.</xref:System.Configuration.UriSection> Zwraca właściwości Idn ustawienia konfiguracji dla IDN przetwarzania w <xref:System.Uri?displayProperty=fullName>klasie.</xref:System.Uri?displayProperty=fullName>       Przetwarzanie IRI musi być włączona dla przetwarzania w celu umożliwienia IDN. Po wyłączeniu przetwarzania IRI przetwarzania IDN zostanie ustawiona do ustawienie domyślne, których zachowanie programu .NET Framework 2.0 jest używany dla zgodności i nazwy IDN nie są używane.       Atrybut międzynarodowych nazw domen (IDN) tylko formanty przetwarzania IDN. Domyślnie odbywa się wszystkie inne IRI przetwarzania (na przykład normalizacji znaków).       Ustawienie konfiguracji <xref:System.Configuration.IdnElement>zostaną odczytane raz po pierwszym <xref:System.Uri?displayProperty=fullName>klasy jest tworzony.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IdnElement> Zmiany ustawień konfiguracji po tym czasie są ignorowane.       Aby uzyskać więcej informacji na temat obsługi IRI zobacz sekcję uwag dla <xref:System.Uri?displayProperty=fullName>klasy.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public System.Configuration.IdnElement Idn { get; }
    return:
      type: System.Configuration.IdnElement
      description: "Ustawienia konfiguracji dla międzynarodowej domeny nazwę (IDN) przetwarzania w &lt;xref:System.Uri?displayProperty=fullName&gt; klasy."
  overload: System.Configuration.UriSection.Idn*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.IriParsing
  id: IriParsing
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: IriParsing
  nameWithType: UriSection.IriParsing
  fullName: System.Configuration.UriSection.IriParsing
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera <xref href=&quot;System.Configuration.IriParsingElement&quot;> </xref> obiekt, który zawiera ustawienia konfiguracji dotyczące analizowania międzynarodowej identyfikatory zasobów (IRI) &lt;xref:System.Uri?displayProperty=fullName&gt; klasy."
  remarks: "Istniejące <xref:System.Uri?displayProperty=fullName>klasa została rozszerzona, aby zapewnić obsługę międzynarodowej identyfikatory zasobów (IRI) oraz międzynarodowych nazw domen.</xref:System.Uri?displayProperty=fullName> Bieżąca liczba użytkowników nie będą widzieć wszystkie zmiany z zachowaniem .NET Framework 2.0, chyba że umożliwiają one specjalnie IRI i IDN. Dzięki temu zgodność aplikacji we wcześniejszych wersjach programu .NET Framework.       Ustawienia konfiguracji dla IRI i IDN można pobrać przy użyciu <xref:System.Configuration.UriSection>klasy.</xref:System.Configuration.UriSection> Właściwość IriParsing zwraca ustawienia konfiguracji do analizowania IRI w <xref:System.Uri?displayProperty=fullName>klasie.</xref:System.Uri?displayProperty=fullName>       Przetwarzanie IRI musi być włączona dla przetwarzania w celu umożliwienia IDN. Po wyłączeniu przetwarzania IRI przetwarzania IDN zostanie ustawiona do ustawienie domyślne, których zachowanie programu .NET Framework 2.0 jest używany dla zgodności i nazwy IDN nie są używane.       Atrybut międzynarodowych nazw domen (IDN) tylko formanty przetwarzania IDN. Domyślnie odbywa się wszystkie inne IRI przetwarzania (na przykład normalizacji znaków).       Ustawienie konfiguracji <xref:System.Configuration.IriParsingElement>zostaną odczytane raz po pierwszym <xref:System.Uri?displayProperty=fullName>klasy jest tworzony.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Zmiany ustawień konfiguracji po tym czasie są ignorowane.       Aby uzyskać więcej informacji na temat obsługi IRI zobacz sekcję uwag dla <xref:System.Uri?displayProperty=fullName>klasy.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public System.Configuration.IriParsingElement IriParsing { get; }
    return:
      type: System.Configuration.IriParsingElement
      description: "Ustawienie konfiguracji dotyczące analizowania międzynarodowej identyfikatory zasobów (IRI) &lt;xref:System.Uri?displayProperty=fullName&gt; klasy."
  overload: System.Configuration.UriSection.IriParsing*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.Properties
  id: Properties
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: Properties
  nameWithType: UriSection.Properties
  fullName: System.Configuration.UriSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Configuration.UriSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.UriSection.SchemeSettings
  id: SchemeSettings
  parent: System.Configuration.UriSection
  langs:
  - csharp
  name: SchemeSettings
  nameWithType: UriSection.SchemeSettings
  fullName: System.Configuration.UriSection.SchemeSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera <xref href=&quot;System.Configuration.SchemeSettingElementCollection&quot;> </xref> obiekt, który zawiera ustawienia konfiguracji dla schematu analizowania &lt;xref:System.Uri?displayProperty=fullName&gt; klasy."
  remarks: "Właściwość SchemeSettings nie jest rodzajowa. Tylko genericUriParserOptions = &quot;DontUnescapePathDotsAndSlashes&quot; ustawienia konfiguracji są obsługiwane schematy HTTP i HTTPS. Wszystkie inne ustawienia są ignorowane."
  syntax:
    content: public System.Configuration.SchemeSettingElementCollection SchemeSettings { get; }
    return:
      type: System.Configuration.SchemeSettingElementCollection
      description: "Ustawienia konfiguracji dla schematu analizowania &lt;xref:System.Uri?displayProperty=fullName&gt; — klasa"
  overload: System.Configuration.UriSection.SchemeSettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.UriSection.#ctor
  parent: System.Configuration.UriSection
  isExternal: false
  name: UriSection()
  nameWithType: UriSection.UriSection()
  fullName: System.Configuration.UriSection.UriSection()
- uid: System.Configuration.UriSection.Idn
  parent: System.Configuration.UriSection
  isExternal: false
  name: Idn
  nameWithType: UriSection.Idn
  fullName: System.Configuration.UriSection.Idn
- uid: System.Configuration.IdnElement
  parent: System.Configuration
  isExternal: false
  name: IdnElement
  nameWithType: IdnElement
  fullName: System.Configuration.IdnElement
- uid: System.Configuration.UriSection.IriParsing
  parent: System.Configuration.UriSection
  isExternal: false
  name: IriParsing
  nameWithType: UriSection.IriParsing
  fullName: System.Configuration.UriSection.IriParsing
- uid: System.Configuration.IriParsingElement
  parent: System.Configuration
  isExternal: false
  name: IriParsingElement
  nameWithType: IriParsingElement
  fullName: System.Configuration.IriParsingElement
- uid: System.Configuration.UriSection.Properties
  parent: System.Configuration.UriSection
  isExternal: false
  name: Properties
  nameWithType: UriSection.Properties
  fullName: System.Configuration.UriSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.UriSection.SchemeSettings
  parent: System.Configuration.UriSection
  isExternal: false
  name: SchemeSettings
  nameWithType: UriSection.SchemeSettings
  fullName: System.Configuration.UriSection.SchemeSettings
- uid: System.Configuration.SchemeSettingElementCollection
  parent: System.Configuration
  isExternal: false
  name: SchemeSettingElementCollection
  nameWithType: SchemeSettingElementCollection
  fullName: System.Configuration.SchemeSettingElementCollection
- uid: System.Configuration.UriSection.#ctor*
  parent: System.Configuration.UriSection
  isExternal: false
  name: UriSection
  nameWithType: UriSection.UriSection
- uid: System.Configuration.UriSection.Idn*
  parent: System.Configuration.UriSection
  isExternal: false
  name: Idn
  nameWithType: UriSection.Idn
- uid: System.Configuration.UriSection.IriParsing*
  parent: System.Configuration.UriSection
  isExternal: false
  name: IriParsing
  nameWithType: UriSection.IriParsing
- uid: System.Configuration.UriSection.Properties*
  parent: System.Configuration.UriSection
  isExternal: false
  name: Properties
  nameWithType: UriSection.Properties
- uid: System.Configuration.UriSection.SchemeSettings*
  parent: System.Configuration.UriSection
  isExternal: false
  name: SchemeSettings
  nameWithType: UriSection.SchemeSettings
