### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerSecuritySettings
  id: PeerSecuritySettings
  children:
  - System.ServiceModel.PeerSecuritySettings.#ctor
  - System.ServiceModel.PeerSecuritySettings.Mode
  - System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  - System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  - System.ServiceModel.PeerSecuritySettings.Transport
  langs:
  - csharp
  name: PeerSecuritySettings
  nameWithType: PeerSecuritySettings
  fullName: System.ServiceModel.PeerSecuritySettings
  type: Class
  summary: "Zawiera ustawienia zabezpieczenia skojarzone z równorzędnym kanałem, takich jak typ uwierzytelniania i zabezpieczenia używany do transportu wiadomości."
  syntax:
    content: public sealed class PeerSecuritySettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: PeerSecuritySettings()
  nameWithType: PeerSecuritySettings.PeerSecuritySettings()
  fullName: System.ServiceModel.PeerSecuritySettings.PeerSecuritySettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Inicjuje nowe wystąpienie domyślnego <xref href=&quot;System.ServiceModel.PeerSecuritySettings&quot;> </xref> klasy."
  syntax:
    content: public PeerSecuritySettings ();
    parameters: []
  overload: System.ServiceModel.PeerSecuritySettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.Mode
  id: Mode
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: System.ServiceModel.PeerSecuritySettings.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Pobiera i ustawia wartość, która wskazuje tryb zabezpieczeń kanał elementu równorzędnego."
  syntax:
    content: public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: "<xref:System.ServiceModel.SecurityMode>Wartość wyliczenia wskazująca trybu zabezpieczeń dla kanału równorzędnego.</xref:System.ServiceModel.SecurityMode>"
  overload: System.ServiceModel.PeerSecuritySettings.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Określona wartość nie jest wartością wyliczenia z<xref:System.ServiceModel.SecurityMode></xref:System.ServiceModel.SecurityMode>"
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: PeerSecuritySettings.ShouldSerializeMode()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Pobiera wartość wskazującą, czy informacje o trybie zabezpieczeń powinny być serializowane."
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "Zwraca <xref:System.Boolean>, który określa <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref> Jeśli powinny być Serializowane informacje tryb zabezpieczeń, a <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Jeśli nie powinien podlegać serializacji..</xref:System.Boolean>"
  overload: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Pobiera wartość wskazującą, czy powinno być Serializowane informacje transportu."
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "Zwraca <xref:System.Boolean>, który określa <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref> Jeśli powinny być Serializowane informacje o transporcie, i <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Jeśli nie powinien podlegać serializacji..</xref:System.Boolean>"
  overload: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerSecuritySettings.Transport
  id: Transport
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: System.ServiceModel.PeerSecuritySettings.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Pobiera wartość wskazującą, ustawienia zabezpieczeń dla transportu wiadomości przesyłane przez kanał elementu równorzędnego."
  remarks: "Ta właściwość jest ustawiona tylko wtedy, gdy <xref:System.ServiceModel.PeerSecuritySettings.Mode%2A>jest równa <xref:System.ServiceModel.SecurityMode>lub <xref:System.ServiceModel.SecurityMode>.</xref:System.ServiceModel.SecurityMode> </xref:System.ServiceModel.SecurityMode> </xref:System.ServiceModel.PeerSecuritySettings.Mode%2A>"
  syntax:
    content: public System.ServiceModel.PeerTransportSecuritySettings Transport { get; set; }
    return:
      type: System.ServiceModel.PeerTransportSecuritySettings
      description: "<xref href=&quot;System.ServiceModel.PeerTransportSecuritySettings&quot;></xref>zawiera ustawienia zabezpieczeń transportu dla kanału równorzędnego."
  overload: System.ServiceModel.PeerSecuritySettings.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.PeerSecuritySettings.#ctor
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: PeerSecuritySettings()
  nameWithType: PeerSecuritySettings.PeerSecuritySettings()
  fullName: System.ServiceModel.PeerSecuritySettings.PeerSecuritySettings()
- uid: System.ServiceModel.PeerSecuritySettings.Mode
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: System.ServiceModel.PeerSecuritySettings.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: true
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: PeerSecuritySettings.ShouldSerializeMode()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport()
  fullName: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport()
- uid: System.ServiceModel.PeerSecuritySettings.Transport
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: System.ServiceModel.PeerSecuritySettings.Transport
- uid: System.ServiceModel.PeerTransportSecuritySettings
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings
  fullName: System.ServiceModel.PeerTransportSecuritySettings
- uid: System.ServiceModel.PeerSecuritySettings.#ctor*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: PeerSecuritySettings
  nameWithType: PeerSecuritySettings.PeerSecuritySettings
- uid: System.ServiceModel.PeerSecuritySettings.Mode*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: PeerSecuritySettings.ShouldSerializeMode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport
- uid: System.ServiceModel.PeerSecuritySettings.Transport*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
