### YamlMime:ManagedReference
items:
- uid: System.Configuration.IConfigurationSectionHandler
  id: IConfigurationSectionHandler
  children:
  - System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IConfigurationSectionHandler
  nameWithType: IConfigurationSectionHandler
  fullName: System.Configuration.IConfigurationSectionHandler
  type: Interface
  summary: "Obsługuje dostęp do niektórych sekcji konfiguracyjnych."
  remarks: "**Ważne** IConfigurationSectionHandler jest przestarzała w programie .NET Framework 2.0 lub nowszej. Jednak ponieważ jest używana wewnętrznie, została zachowana. Na przykład można znaleźć [porady: Tworzenie niestandardowej konfiguracji sekcje przy użyciu IConfigurationSectionHandler](~/add/includes/ajax-current-ext-md.md). Jeśli używasz poprzedni przykład, skompiluj go z .NET Framework w wersji 1.0 lub 1.1.       W programie .NET Framework w wersji 2.0 i powyżej, możesz zamiast tego muszą pochodzić od <xref:System.Configuration.ConfigurationSection>klasy do zaimplementowania modułu obsługi sekcji konfiguracji pokrewnych.</xref:System.Configuration.ConfigurationSection> Na przykład można znaleźć [porady: Tworzenie niestandardowej konfiguracji sekcje przy użyciu elementu ConfigurationSection](~/add/includes/ajax-current-ext-md.md).       Wystąpienia klasy IConfigurationSectionHandler musi być wątku bezpieczne i bezstanowe. <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>Metoda musi być wywoływana przez wiele wątków jednocześnie.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>       Ponadto obiekt konfiguracji wygenerowane przez <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>Metoda musi być wątku bezpieczne i modyfikować.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> Ponieważ obiektów konfiguracji są buforowane przez system konfiguracji, to nie należy modyfikować argument nadrzędnej <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metody.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> Na przykład jeśli wartość zwracana <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>jest mała zmiana elementu nadrzędnego, należy rzeczywiste zmiany w klonowania elementu nadrzędnego nie oryginału.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>"
  syntax:
    content: public interface IConfigurationSectionHandler
  implements: []
  platform:
  - net462
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Tworzy program obsługi sekcji konfiguracji."
  remarks: "Wystąpienia <xref:System.Configuration.IConfigurationSectionHandler>klasy musi być wątku bezpieczne i bezstanowe.</xref:System.Configuration.IConfigurationSectionHandler> Metoda Create musi być z wiele wątków jednocześnie.       Ponadto obiekt konfiguracji generowany przez metody Create musi być wątku bezpieczne i modyfikować. Ponieważ obiektów konfiguracji są buforowane przez system konfiguracji, należy nie zmodyfikować argument nadrzędnego do utworzenia. Na przykład wartość zwracana Utwórz jest tylko małych modyfikacji elementu nadrzędnego, muszą być wprowadzane w klonowania elementu nadrzędnego nie oryginału właściwych modyfikacji."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Obiekt nadrzędny."
    - id: configContext
      type: System.Object
      description: "Obiekt kontekstu konfiguracji."
    - id: section
      type: System.Xml.XmlNode
      description: "Węzeł XML sekcji."
    return:
      type: System.Object
      description: "Obiekt programu obsługi sekcji utworzony."
  overload: System.Configuration.IConfigurationSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IConfigurationSectionHandler.Create*
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create
  nameWithType: IConfigurationSectionHandler.Create
