### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationType
  id: ManagementConfigurationType
  children:
  - System.Management.Instrumentation.ManagementConfigurationType.Apply
  - System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  langs:
  - csharp
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
  type: Enum
  summary: "Reprezentuje zachowania możliwe zatwierdzania właściwości odczytu/zapisu. Jest on używany jako wartość parametru <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationAttribute&quot;> </xref> atrybutu.       Uwaga: do bibliotek WMI .NET są teraz wziąć pod uwagę stanu końcowego, a nie dalszy rozwój, ulepszenia lub aktualizacje będą dostępne dla problemy związane z zabezpieczeniami wpływu na te biblioteki. [API MI](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) powinna być używana do wszystkich nowych wdrożeń."
  remarks: "Ten atrybut jest używany jako wartość parametru <xref:System.Management.Instrumentation.ManagementConfigurationAttribute>tylko wtedy, gdy atrybut <xref:System.Management.Instrumentation.ManagementCommitAttribute>atrybut służy do identyfikowania metodę uruchomienia można przekazać wartości.</xref:System.Management.Instrumentation.ManagementCommitAttribute> </xref:System.Management.Instrumentation.ManagementConfigurationAttribute> W przeciwnym razie wartości właściwości odczytu/zapisu są stosowane automatycznie."
  syntax:
    content: public enum ManagementConfigurationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  id: Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Ustaw wartości efekty tylko wtedy, gdy zatwierdzenie jest wywoływane."
  syntax:
    content: Apply
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  id: OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Zestaw wartości są natychmiast stosowane."
  syntax:
    content: OnCommit
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
