### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  id: MsmqIntegrationSecurity
  children:
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  langs:
  - csharp
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  type: Class
  summary: "Klasa MsmqIntegrationSecurity hermetyzuje ustawienia zabezpieczeń transportu kanał integracji usługi kolejkowania komunikatów (MSMQ)."
  remarks: "Kanał integracji usługi kolejkowania komunikatów umożliwia [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] aplikacjom komunikowanie się z istniejącymi aplikacjami usługi kolejkowania komunikatów."
  syntax:
    content: public sealed class MsmqIntegrationSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity&quot;> </xref>."
  syntax:
    content: public MsmqIntegrationSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  id: Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Pobiera lub ustawia <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> skojarzonego z kanał integracji usługi kolejkowania komunikatów (MSMQ)."
  remarks: '<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>to wyliczenie zawiera następujące wartości: <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>i <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> </xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode></xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> Wartość domyślna to <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>'
  syntax:
    content: public System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
      description: "<xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> Skojarzonego z kanał integracji usługi kolejkowania komunikatów."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  id: Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Pobiera <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> skojarzonego z kanał integracji usługi kolejkowania komunikatów (MSMQ)."
  remarks: "<xref:System.ServiceModel.MsmqTransportSecurity>hermetyzuje ustawienia zabezpieczeń dla transport integracji usługi kolejkowania komunikatów.</xref:System.ServiceModel.MsmqTransportSecurity> Ustawienia są takie same, Integracja usługi kolejkowania komunikatów i umieszczonych w kolejce transportów. <xref:System.ServiceModel.MsmqTransportSecurity>Służy do ustawiania trybu uwierzytelniania, algorytmów szyfrowania, Secure Hash Algorithm i poziom ochrony.</xref:System.ServiceModel.MsmqTransportSecurity>"
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> Skojarzonego z kanał integracji usługi kolejkowania komunikatów."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
  parent: System.ServiceModel.MsmqIntegration
  isExternal: false
  name: MsmqIntegrationSecurityMode
  nameWithType: MsmqIntegrationSecurityMode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
