### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  id: FederationConfigurationCreatedEventArgs
  children:
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  type: Class
  summary: "Udostępnia dane dla <xref href=&quot;System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated&quot;> </xref> zdarzeń."
  remarks: "<xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName>Zdarzenie jest wywoływane, gdy pierwszy moduł HTTP w aplikacji sieci web odwołuje się do <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName>Właściwości.</xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName> </xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> Pierwszym dostępie tego przyczyny właściwość <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>obiektu utworzone i zainicjowane z konfiguracji.</xref:System.IdentityModel.Services.Configuration.FederationConfiguration> <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName>Następnie zdarzenia.</xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> Można uzyskać dostępu do nowo utworzony <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>obiekt, za pomocą <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName>Właściwości programu obsługi zdarzeń w celu zbadania lub zmodyfikuj go.</xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>"
  syntax:
    content: 'public class FederationConfigurationCreatedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  id: '#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)'
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs&quot;> </xref> klasy z obiektu konfiguracji określona Federacja."
  remarks: "Inicjuje <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A>Właściwości określonym przez obiekt konfiguracji Federacji `config`.</xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A>"
  syntax:
    content: public FederationConfigurationCreatedEventArgs (System.IdentityModel.Services.Configuration.FederationConfiguration config);
    parameters:
    - id: config
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "Obiekt konfiguracji federacji. A <xref href=&quot;System.IdentityModel.Services.Configuration.FederationConfiguration&quot;> </xref> obiektu zawiera właściwości można skonfigurować moduł uwierzytelniania protokołu WS-Federation (<xref href=&quot;System.IdentityModel.Services.WSFederationAuthenticationModule&quot;></xref>) i moduł uwierzytelniania sesji (<xref href=&quot;System.IdentityModel.Services.SessionAuthenticationModule&quot;></xref>) w aplikacji sieci web."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  id: FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Pobiera lub ustawia obiekt konfiguracji federacyjnego, który został zainicjowany z pliku konfiguracji."
  remarks: "<xref:System.IdentityModel.Services.Configuration.FederationConfiguration>Obiektu zawiera właściwości można skonfigurować moduł uwierzytelniania protokołu WS-Federation (<xref:System.IdentityModel.Services.WSFederationAuthenticationModule>) i moduł uwierzytelniania sesji (<xref:System.IdentityModel.Services.SessionAuthenticationModule>) w aplikacji sieci web.</xref:System.IdentityModel.Services.SessionAuthenticationModule> </xref:System.IdentityModel.Services.WSFederationAuthenticationModule> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>       Aby zmodyfikować ustawienia konfiguracji, można ustawić właściwości na <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>obiektu, do którego odwołuje się przez tę właściwość, lub zapewniają nowe <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>obiektu.</xref:System.IdentityModel.Services.Configuration.FederationConfiguration> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>"
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfiguration FederationConfiguration { get; set; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "Obiekt konfiguracji federacyjnego, który został zainicjowany z konfiguracji."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
- uid: System.IdentityModel.Services.Configuration.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
