### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.DefaultSettingsSection
  id: DefaultSettingsSection
  children:
  - System.Transactions.Configuration.DefaultSettingsSection.#ctor
  - System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  - System.Transactions.Configuration.DefaultSettingsSection.Properties
  - System.Transactions.Configuration.DefaultSettingsSection.Timeout
  langs:
  - csharp
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection
  fullName: System.Transactions.Configuration.DefaultSettingsSection
  type: Class
  summary: "Reprezentuje sekcję XML w pliku konfiguracji, który zawiera wartości domyślne transakcji. Ta klasa nie może być dziedziczona."
  remarks: ''
  example:
  - "An example configuration file used by your transaction application can be as follows,  \n  \n `<configuration>`  \n  \n `<system.transactions>`  \n  \n `<defaultSettings distributedTransactionManagerName=\"F04M25\" timeout=\"02:00:00\"/>`  \n  \n `<machineSettings maxTimeout=\"02:00:00\"/>`  \n  \n `</system.transactions>`  \n  \n `</configuration>`  \n  \n This example specifies the default values of a transaction. Specifically, it sets the the computer name of the Distributed Transaction Coordinator (MSDTC) that is responsible for coordinating all distributed transactions started locally, and the default time after which a transaction times out. In addition, it specifies a setting that can only be modified at the machine level, which is the maximum amount of time allowed before a transaction times out."
  syntax:
    content: 'public sealed class DefaultSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: DefaultSettingsSection()
  nameWithType: DefaultSettingsSection.DefaultSettingsSection()
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DefaultSettingsSection()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref> klasy."
  syntax:
    content: public DefaultSettingsSection ();
    parameters: []
  overload: System.Transactions.Configuration.DefaultSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  id: DistributedTransactionManagerName
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Pobiera nazwę menedżera transakcji."
  remarks: "Ta właściwość zawiera nazwę komputera, na której działa koordynator transakcji rozproszonych (MSDTC) firmy Microsoft i jest odpowiedzialny za koordynację wszystkich transakcji rozproszonej, uruchamiane lokalnie.       Można ustawić wartość tej właściwości, aby włączyć menedżerowie transakcji zdalnym w obszarze <xref:System.Transactions>.</xref:System.Transactions> Jeśli ta właściwość jest `null` lub zawiera pusty ciąg, Menedżera transakcji lokalnej jest używany jako menedżera transakcji zdalnych. Jeśli ta właściwość jest ustawiona na wartość inną niż domyślna pusty ciąg, należy zainstalować system Windows Server 2003 Service Pack 1. W przeciwnym razie wszelkie operacje transakcyjne kończy się niepowodzeniem z <xref:System.NotSupportedException>.</xref:System.NotSupportedException> Transakcji, która ma być zarządzany przez MSDTC eskalacji używa lokalnej usługi MSDTC, ale zamiast tego użyj na maszynie, określonej przez tę właściwość. Jeśli z jakiegokolwiek powodu niedostępności Menedżera transakcji, jest zwracany wyjątek.       Ta właściwość nie jest rozróżniana wielkość liter i powinien zawierać tylko krótką nazwę komputera.  Nie akceptuje nazwy FQDN, nazwy localhost ani adresów IP. Jeśli ta właściwość zawiera nieprawidłową zdalnego nazwę komputera, jest zgłaszany wyjątek &quot;nie można odczytać informacji o konfiguracji&quot;.       Należy mieć odpowiednich uprawnień do użycia ze zdalną usługą MSDTC. Aby uzyskać więcej informacji na temat konfigurowania ustawień zabezpieczeń usługi DTC, zobacz [MSDTC konfigurowania właściwości zabezpieczeń](http://msdn.microsoft.com/library/cossdk/html/2627a956-60b3-4d26-bc04-e0676ec97786.asp?frame=true) tematu."
  syntax:
    content: public string DistributedTransactionManagerName { get; set; }
    return:
      type: System.String
      description: "Nazwa menedżera transakcji. Wartość domyślna to ciąg pusty."
  overload: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "Próba ustawienia tej właściwości nazwy FQDN lub adresów IP."
  - type: System.Transactions.TransactionAbortedException
    commentId: T:System.Transactions.TransactionAbortedException
    description: "Próba ustawienia tej właściwości localhost."
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties
  id: Properties
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Properties
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Transactions.Configuration.DefaultSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  id: Timeout
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Pobiera lub ustawia domyślny czas, po którym limitu czasu transakcji."
  remarks: "Ta właściwość pobiera wartość domyślną wartość limitu czasu w pliku konfiguracji. Jest automatycznie dostosowywany przez <xref:System.Transactions.Configuration.MachineSettingsSection.MaxTimeout%2A>wartość w czasie wykonywania.</xref:System.Transactions.Configuration.MachineSettingsSection.MaxTimeout%2A>       Wartość 00:00:00 (lub zero) jest interpretowana jako nieskończoność."
  syntax:
    content: public TimeSpan Timeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>obiektu.</xref:System.TimeSpan> Właściwość domyślna to 00:01:00."
  overload: System.Transactions.Configuration.DefaultSettingsSection.Timeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Próba ustawienia tej właściwości wartości ujemnej."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.Transactions.TransactionAbortedException
  parent: System.Transactions
  isExternal: false
  name: TransactionAbortedException
  nameWithType: TransactionAbortedException
  fullName: System.Transactions.TransactionAbortedException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DefaultSettingsSection()
  nameWithType: DefaultSettingsSection.DefaultSettingsSection()
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DefaultSettingsSection()
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Timeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection.DefaultSettingsSection
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
