### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Określa, że grupa ustawień aplikacji lub właściwości zawiera różne wartości dla poszczególnych użytkowników aplikacji. Ta klasa nie może być dziedziczona."
  remarks: "Właściwości ustawień aplikacji ma zakres, w którym jest oparty na poziomie użytkownika lub aplikacji. Jak oznacza kategorie właściwości z zakresu aplikacji przedstawia wartości jednolitego wszyscy użytkownicy aplikacji, natomiast zakresu użytkownika właściwości są wyposażone w dedykowane wartości dla poszczególnych użytkowników aplikacji.       UserScopedSettingAttribute wskazuje, że właściwość należy traktować jako ustawienie poziomu użytkownika, że decyzje dotyczące odpowiedniego magazynu należy odpowiednio przez dostawcę ustawień.       Atrybut zakres jest wymagany dla każdej właściwości ustawień aplikacji. Jeśli właściwość nie jest stosowany przy użyciu jednej <xref:System.Configuration.ApplicationScopedSettingAttribute>ani UserScopedSettingAttribute, właściwość jest ignorowana przez dostawcę ustawień — nie jest serializowany.</xref:System.Configuration.ApplicationScopedSettingAttribute> Nieprawidłowy, jest jednak zastosowanie obu atrybutów w tej samej właściwości ustawień. Takie próba spowoduje, że <xref:System.Configuration.ConfigurationErrorsException>zostanie wygenerowany.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> klasy."
  remarks: "Każda właściwość ustawienia aplikacji muszą być stosowane z atrybutem pojedynczy zakres, w celu rozpoznana, a serializowany przez dostawcę ustawień."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
