### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Ułatwia odczytu w <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref> sekcji pliku konfiguracji i tworzenia wystąpienia <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> klasy, który zawiera informacje o możliwości dla przeglądarki klienta."
  remarks: "Klasa HttpCapabilitiesSectionHandler i odpowiadający mu `<browserCaps>` sekcji konfiguracji są przestarzałe w programie .NET Framework w wersji 2.0. Preferowaną metodą zarządzania możliwości przeglądarki jest za pomocą plików definicji przeglądarki, które są kompilowane do użycia przez <xref:System.Web.Configuration.BrowserCapabilitiesFactory>klasę.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> Celem obu metod konfiguracji polega na generowaniu wystąpienia <xref:System.Web.HttpBrowserCapabilities>klasy, która miała dostęp do <xref:System.Web.HttpRequest.Browser%2A>właściwości <xref:System.Web.HttpRequest>klasy.</xref:System.Web.HttpRequest> </xref:System.Web.HttpRequest.Browser%2A> </xref:System.Web.HttpBrowserCapabilities>       Przy użyciu przeglądarki plików definicji do przechowywania możliwości przeglądarki zapewnia zalet w porównaniu z alternatywnej. Ponieważ informacje definicji przeglądarki jest analizowana z pliku konfiguracji XML i kompilowane do klasy wcześniejsze, zapewnia wyższą wydajność. Pliki definicji przeglądarki również są łatwiejsze w obsłudze:-definicje są hierarchiczne i w związku z tym polegać mniej na wyrażenia regularne do określania możliwości przeglądarki.      -Definicje można organizować w wielu plikach, ułatwiając zarządzanie.      -Definicje można zdefiniować na dowolnym poziomie zarówno na poziomie pliku Machine.config lub określonych aplikacji. Eliminuje to potrzebę skopiować cały zestaw definicje na potrzeby zastępowanie możliwości dla określonej przeglądarki."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref> klasy."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy wystąpienie <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> klasy, który zawiera informacje o możliwości dla przeglądarki klienta."
  remarks: "Ta klasa dziedziczy jego danych definicji przeglądarki z `<browserCaps>` sekcji konfiguracji. W tej sekcji jest przestarzała w programie .NET Framework w wersji 2.0."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Konfiguracja węzła nadrzędnego."
    - id: configurationContext
      type: System.Object
      description: "Kontekst konfiguracji bieżącego pliku konfiguracji."
    - id: section
      type: System.Xml.XmlNode
      description: "Sekcji pliku konfiguracji, który zawiera informacje."
    return:
      type: System.Object
      description: "Wystąpienie <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> zawierający informacje o możliwości dla przeglądarki klienta."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
