### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  id: PeerApplicationRegistrationType
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  langs:
  - csharp
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  type: Enum
  summary: "Określa typ rejestracji w celu przeprowadzenia <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> lub <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> rejestracji."
  remarks: "Rejestrowanie <xref:System.Net.PeerToPeer.Collaboration.PeerApplication>umożliwia odbieranie <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>żądania zaproszenie.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> </xref:System.Net.PeerToPeer.Collaboration.PeerApplication> Usługa lub aplikacja wykonuje rejestracji musi mieć uprawnienia, aby to zrobić, ponieważ wymaga dostępu do <xref:System.Net.PeerToPeer.Collaboration.ContactManager>i innych zasobów, takich jak użytkownicy, aplikacji i usług na komputerze zdalnym.</xref:System.Net.PeerToPeer.Collaboration.ContactManager>"
  syntax:
    content: public enum PeerApplicationRegistrationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  id: AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> Lub <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> jest rejestrowana wszystkie elementy równorzędne hosta aplikacji"
  syntax:
    content: AllUsers
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  id: CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Aplikacja lub obiekt jest rejestrowana tylko dla użytkownika skojarzonego z węzłem równorzędnym wywoływania"
  syntax:
    content: CurrentUser
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
