### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.SmtpSection
  id: SmtpSection
  children:
  - System.Net.Configuration.SmtpSection.#ctor
  - System.Net.Configuration.SmtpSection.DeliveryFormat
  - System.Net.Configuration.SmtpSection.DeliveryMethod
  - System.Net.Configuration.SmtpSection.From
  - System.Net.Configuration.SmtpSection.Network
  - System.Net.Configuration.SmtpSection.Properties
  - System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  langs:
  - csharp
  name: SmtpSection
  nameWithType: SmtpSection
  fullName: System.Net.Configuration.SmtpSection
  type: Class
  summary: "Reprezentuje sekcję SMTP w <xref uid=&quot;langword_csharp_System.Net&quot; name=&quot;System.Net&quot; href=&quot;&quot;> </xref> pliku konfiguracji."
  remarks: "Ta klasa udostępnia programowy dostęp do informacji, które mogą być przechowywane w plikach konfiguracji, które są używane przez klasy, które obsługują SMTP w <xref:System.Net.Mail>przestrzeni nazw.</xref:System.Net.Mail>"
  syntax:
    content: 'public sealed class SmtpSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: SmtpSection()
  nameWithType: SmtpSection.SmtpSection()
  fullName: System.Net.Configuration.SmtpSection.SmtpSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Net.Configuration.SmtpSection&quot;> </xref> klasy."
  syntax:
    content: public SmtpSection ();
    parameters: []
  overload: System.Net.Configuration.SmtpSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat
  id: DeliveryFormat
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
  fullName: System.Net.Configuration.SmtpSection.DeliveryFormat
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera lub ustawia format dostarczania dla wysyłania wychodzącej poczty e-mail przy użyciu transportu protokołu SMTP (Simple Mail)."
  syntax:
    content: public System.Net.Mail.SmtpDeliveryFormat DeliveryFormat { get; set; }
    return:
      type: System.Net.Mail.SmtpDeliveryFormat
      description: "Returns <xref href=&quot;System.Net.Mail.SmtpDeliveryFormat&quot;></xref>.       Format dostarczania na potrzeby wysyłania wychodzącej poczty e-mail za pomocą protokołu SMTP."
  overload: System.Net.Configuration.SmtpSection.DeliveryFormat*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod
  id: DeliveryMethod
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
  fullName: System.Net.Configuration.SmtpSection.DeliveryMethod
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera lub Ustawia metodę dostarczania transportu protokołu SMTP (Simple Mail). Domyślną metodą dostarczania jest <xref href=&quot;System.Net.Mail.SmtpDeliveryMethod&quot;> </xref>."
  remarks: "Prawidłowe wartości dla tej właściwości to <xref:System.Net.Mail.SmtpDeliveryMethod>, <xref:System.Net.Mail.SmtpDeliveryMethod>i <xref:System.Net.Mail.SmtpDeliveryMethod>.</xref:System.Net.Mail.SmtpDeliveryMethod> </xref:System.Net.Mail.SmtpDeliveryMethod> </xref:System.Net.Mail.SmtpDeliveryMethod> Te wartości można skonfigurować elementy podrzędne i mieć w odpowiedniej sekcji `System.Net` pliku konfiguracji. Wszystkie sekcje są formatu — z uwzględnieniem wielkości liter, aby umożliwić użytkownikom zgodna metoda dostarczania z odpowiadających im nazw sekcji."
  syntax:
    content: public System.Net.Mail.SmtpDeliveryMethod DeliveryMethod { get; set; }
    return:
      type: System.Net.Mail.SmtpDeliveryMethod
      description: "Ciąg, który reprezentuje metodę dostarczania SMTP."
  overload: System.Net.Configuration.SmtpSection.DeliveryMethod*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.From
  id: From
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: From
  nameWithType: SmtpSection.From
  fullName: System.Net.Configuration.SmtpSection.From
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera lub ustawia wartość domyślną, która wskazuje nadawcy wiadomości e-mail."
  syntax:
    content: public string From { get; set; }
    return:
      type: System.String
      description: "Ciąg reprezentujący wartość domyślną, wskazując nadawcy wiadomości e-mail."
  overload: System.Net.Configuration.SmtpSection.From*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.Network
  id: Network
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: Network
  nameWithType: SmtpSection.Network
  fullName: System.Net.Configuration.SmtpSection.Network
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera element konfiguracji, która kontroluje ustawienia sieciowe używane przez transportu protokołu SMTP (Simple Mail). plik. <xref href=&quot;System.Net.Configuration.SmtpNetworkElement&quot;></xref>."
  syntax:
    content: public System.Net.Configuration.SmtpNetworkElement Network { get; }
    return:
      type: System.Net.Configuration.SmtpNetworkElement
      description: "A <xref href=&quot;System.Net.Configuration.SmtpNetworkElement&quot;></xref> object.       Element konfiguracji, która kontroluje ustawienia sieciowe używane przez SMTP."
  overload: System.Net.Configuration.SmtpSection.Network*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.Properties
  id: Properties
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: Properties
  nameWithType: SmtpSection.Properties
  fullName: System.Net.Configuration.SmtpSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Net.Configuration.SmtpSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  id: SpecifiedPickupDirectory
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
  fullName: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera katalog podnoszenia, który będzie używany przez klienta SMPT."
  remarks: "Wskazuje, że katalogu określonego przez <xref:System.Net.Mail.SmtpClient.PickupDirectoryLocation%2A>będzie używany jako katalog podnoszenia SMTP.</xref:System.Net.Mail.SmtpClient.PickupDirectoryLocation%2A> Jeśli klient SMTP nie można zapisać w katalogu pośrednim wyjątek lokalizacji We/Wy jest generowany przez <xref:System.Net.Mail.SmtpClient.Send%2A>.</xref:System.Net.Mail.SmtpClient.Send%2A> Katalogu nie można utworzyć, jeśli nie istnieje. Poświadczeń aktualnie uruchomionej wątku lub procesu będą używane do dostępu do katalogu."
  syntax:
    content: public System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement SpecifiedPickupDirectory { get; }
    return:
      type: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
      description: "A <xref href=&quot;System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement&quot;> </xref> obiekt, który określa folder katalogu podnoszenia."
  overload: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.SmtpSection.#ctor
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SmtpSection()
  nameWithType: SmtpSection.SmtpSection()
  fullName: System.Net.Configuration.SmtpSection.SmtpSection()
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
  fullName: System.Net.Configuration.SmtpSection.DeliveryFormat
- uid: System.Net.Mail.SmtpDeliveryFormat
  parent: System.Net.Mail
  isExternal: false
  name: SmtpDeliveryFormat
  nameWithType: SmtpDeliveryFormat
  fullName: System.Net.Mail.SmtpDeliveryFormat
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
  fullName: System.Net.Configuration.SmtpSection.DeliveryMethod
- uid: System.Net.Mail.SmtpDeliveryMethod
  parent: System.Net.Mail
  isExternal: false
  name: SmtpDeliveryMethod
  nameWithType: SmtpDeliveryMethod
  fullName: System.Net.Mail.SmtpDeliveryMethod
- uid: System.Net.Configuration.SmtpSection.From
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: From
  nameWithType: SmtpSection.From
  fullName: System.Net.Configuration.SmtpSection.From
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.SmtpSection.Network
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Network
  nameWithType: SmtpSection.Network
  fullName: System.Net.Configuration.SmtpSection.Network
- uid: System.Net.Configuration.SmtpNetworkElement
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpNetworkElement
  nameWithType: SmtpNetworkElement
  fullName: System.Net.Configuration.SmtpNetworkElement
- uid: System.Net.Configuration.SmtpSection.Properties
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Properties
  nameWithType: SmtpSection.Properties
  fullName: System.Net.Configuration.SmtpSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
  fullName: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpSpecifiedPickupDirectoryElement
  nameWithType: SmtpSpecifiedPickupDirectoryElement
  fullName: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
- uid: System.Net.Configuration.SmtpSection.#ctor*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SmtpSection
  nameWithType: SmtpSection.SmtpSection
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
- uid: System.Net.Configuration.SmtpSection.From*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: From
  nameWithType: SmtpSection.From
- uid: System.Net.Configuration.SmtpSection.Network*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Network
  nameWithType: SmtpSection.Network
- uid: System.Net.Configuration.SmtpSection.Properties*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Properties
  nameWithType: SmtpSection.Properties
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
