### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "Określa, jak znaki Unicode będą interpretowane przez <xref:System.Net.WebUtility.HtmlDecode*>metody.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "Aby uzyskać więcej informacji na temat sposobu powinni znaków Unicode mają być kodowane w formacie HTML, zobacz [przy użyciu znaki specjalne w kodzie znaczników oraz CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Automatyczne zachowanie. Zachowanie dekodowania zależy od bieżącej aplikacji docelowej Framework. Aby uzyskać [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] i później, Unicode kodowania dekodowania jest strict."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Zachowanie zgodne. Określa, że dane przychodzące nie jest sprawdzane poprawności przed trwa zdekodowane. Na przykład wejściowy ciąg &quot;&amp;amp; #xD84C;&quot; może zdekodować jako U + D84C, czyli niesparowane dwuskładnikowego. Ponadto dekoder nie zrozumieć punktów kodu w tej roli, chyba że są one tak reprezentowane jako kodowany w formacie HTML surogatami została inputstring &quot;&amp;#144308;&quot; spowoduje powstanie ciągu wyjściowego &quot;&amp;#144308;&quot;."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Zachowanie utracić. Podobnie jak zgodność, nie istnieją procedury kontroli ważności, ale dekoder również rozumie punktów kodu. Ciąg wejściowy &quot;&amp;#144308;&quot; będzie prawidłowo zdekodować do znaku U +&233;B4. Ten przełącznik ma zapewnić współdziałanie maksymalną podczas dekoder nie może ustalić, który używa dostawcy można wygenerować ciągu zakodowanego format."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Zachowanie strict. Określa, czy przychodzące dane zakodowane jest sprawdzany pod kątem poprawności przed trwa zdekodować. Na przykład wejściowy ciąg &quot;&amp;#144308;&quot; może zdekodować jako U +&233;B4, ale wejściowy ciąg &quot;&amp;#xD84C;&amp; #xDFB4;&quot;nie powiedzie się prawidłowo zdekodować. Już zdekodować danych w ciągu nie jest sprawdzana poprawność. Na przykład ciąg wejściowy &quot;\\ud800&quot; spowoduje ciągu wyjściowego &quot;\\ud800&quot;, zgodnie z surogatu już zdekodować jest pomijana podczas dekodowania, nawet jeśli komputer jest nieparzysty."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
