### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig
  id: ClientRemotingConfig
  children:
  - System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  - System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  langs:
  - csharp
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig
  type: Class
  summary: "Definiuje statycznego <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>metodę umożliwiającą utworzenie pliku konfiguracji klienta usług zdalnych dla klienta biblioteki typów.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>"
  remarks: "<xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>Metoda jest używana przez <xref:System.EnterpriseServices.Internal.Publish>klasy podczas generowania interfejsu COM z biblioteki typów klienta (z rozszerzeniem .tlb).</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> <xref:System.EnterpriseServices.Internal.Publish>Klasy publikuje interfejsy modelu COM w aplikacji z obsługą protokołu SOAP modelu COM +.</xref:System.EnterpriseServices.Internal.Publish> Jeden z parametrów metody jest nazwą zestawu, który zawiera typowe języka wspólnego (CLR) metadanych który <xref:System.EnterpriseServices.Internal.Publish>został już wygenerowany dla klienta biblioteki typów.</xref:System.EnterpriseServices.Internal.Publish>       <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>nie trzeba jej wywołać bezpośrednio.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> Zamiast tego wywołać <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>metody <xref:System.EnterpriseServices.Internal.Publish>klasy.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       ClientRemotingConfig jest używana wewnętrznie przez program .NET Framework. Nie trzeba użyć klasy bezpośrednio w kodzie."
  syntax:
    content: public class ClientRemotingConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.EnterpriseServices.Internal.ClientRemotingConfig&quot;> </xref> klasy."
  syntax:
    content: public ClientRemotingConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Tworzy plik konfiguracji klienta usług zdalnych dla biblioteki typów klienta w aplikacji z obsługą protokołu SOAP modelu COM +."
  remarks: "Statyczna metoda zapisu jest wywoływana przez <xref:System.EnterpriseServices.Internal.Publish>klasy podczas generowania interfejsu COM z biblioteki typów klienta (z rozszerzeniem .tlb).</xref:System.EnterpriseServices.Internal.Publish> <xref:System.EnterpriseServices.Internal.Publish>Klasy publikuje interfejsy modelu COM w aplikacji z obsługą protokołu SOAP modelu COM +.</xref:System.EnterpriseServices.Internal.Publish>       Zapisu nie musi być wywoływana bezpośrednio. Zamiast tego wywołać <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>metody <xref:System.EnterpriseServices.Internal.Publish>klasy.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       `BaseUrl` i `VRoot` wartości parametrów są łączone (separatorem ścieżki, w razie potrzeby) do formularza elementu klienta `URL` wartość atrybutu.       `AssemblyName` Zestawu zawierającego metadanych CLR określa parametr który <xref:System.EnterpriseServices.Internal.Publish>za pomocą <xref:System.EnterpriseServices.Internal.GenerateMetadata>klasy, został już wygenerowany dla klienta biblioteki typów.</xref:System.EnterpriseServices.Internal.GenerateMetadata> </xref:System.EnterpriseServices.Internal.Publish>"
  syntax:
    content: public static bool Write (string DestinationDirectory, string VRoot, string BaseUrl, string AssemblyName, string TypeName, string ProgId, string Mode, string Transport);
    parameters:
    - id: DestinationDirectory
      type: System.String
      description: "Folder, w którym można utworzyć pliku konfiguracji."
    - id: VRoot
      type: System.String
      description: "Nazwa wirtualnego katalogu głównego."
    - id: BaseUrl
      type: System.String
      description: "Podstawowy adres URL zawierający wirtualnego katalogu głównego."
    - id: AssemblyName
      type: System.String
      description: "Wyświetlana nazwa zestawu zawierającego wspólnych języka wspólnego (CLR) metadanych odpowiadający biblioteki typów."
    - id: TypeName
      type: System.String
      description: "Pełna nazwa zestawu zawierającego metadanych CLR odpowiadający biblioteki typów."
    - id: ProgId
      type: System.String
      description: "Identyfikator programowy klasy."
    - id: Mode
      type: System.String
      description: "Tryb aktywacji."
    - id: Transport
      type: System.String
      description: "Nie jest używany. Określ <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> dla tego parametru."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli pomyślnie utworzono plik konfiguracji klienta usługi zdalne; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig.ClientRemotingConfig
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write
  nameWithType: ClientRemotingConfig.Write
