### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  id: ApplicationChangedEventArgs
  children:
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  langs:
  - csharp
  name: ApplicationChangedEventArgs
  nameWithType: ApplicationChangedEventArgs
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  type: Class
  summary: "Informacje uprawniający do metody wywołania zwrotnego po <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication.ApplicationChanged&quot;> </xref> zdarzenie."
  remarks: "<xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged>Zdarzenie jest wywoływane podczas: - elementu równorzędnego uruchamia aplikację w ramach współpracy - elementu równorzędnego kończy się aplikacji w ramach współpracy - <xref:System.Net.PeerToPeer.Collaboration.PeerContact>obiekt, który reprezentuje element równorzędny brać ma zmiany w jej właściwości, takie jak pseudonim skojarzone - zakresu aplikacji zostanie zmieniona na komputerze osoby kontaktowej peer - elementu równorzędnego przenosi do innego adresu IP w sieci — co klasa, która używa klasy ApplicationChangedEventArgs wymaga <xref:System.Security.Permissions.PermissionState>bez ograniczeń.</xref:System.Security.Permissions.PermissionState> </xref:System.Net.PeerToPeer.Collaboration.PeerContact> </xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged> Ten stan jest tworzone, gdy <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>konstruowania obiektu.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>"
  syntax:
    content: 'public class ApplicationChangedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> dla zostało zgłoszone zdarzenie."
  remarks: "Jeśli nie jest określony, wartością domyślną dla tej właściwości jest `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> Wystąpienie, które zostało zaktualizowane."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  id: PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera typ zmiany <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> który wystąpił."
  remarks: "Jeśli nie jest określony, wartością domyślną dla tej właściwości jest `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerChangeType PeerChangeType { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerChangeType
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerChangeType&quot;> </xref> Wartości wyliczenia, która określa typ zmiany, która została wykonana na <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> skojarzone z <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;></xref>skojarzone z <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera punktu końcowego, dla którego <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> informacje zostały zmienione."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> Zawierający punktu końcowego dla aplikacji, których informacje zostały zmienione. Chyba że jawnie określona, wartością domyślną dla wszystkich właściwości jest <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> dla typów referencyjnych i zero (0) dla właściwości typu <xref uid=&quot;langword_csharp_int&quot; name=&quot;int&quot; href=&quot;&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerChangeType
  nameWithType: PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
