### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "W tym artykule opisano zadania drukowania."
  remarks: "<xref:System.Printing.PrintTicket>Obiektu, który jest wartością elementu <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>właściwość, przechowuje wszystkie szczegółowe ustawienia zadania drukowania.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> Element nadrzędny PrintJobSettings, dodaje tylko opis.      > [!CAUTION] > Klas w ramach <xref:System.Printing>przestrzeni nazw nie są obsługiwane do użycia w ramach usługi systemu Windows lub aplikacji ASP.NET lub usługi.</xref:System.Printing> Podjęto próbę użycia tych klas z jednej z tych typów aplikacji może dać nieoczekiwane problemy, takie jak ograniczyć obsługi wyjątków wydajności i czasu wykonywania.       Jeśli chcesz wydrukuj z aplikacji formularzy systemu Windows, temacie <xref:System.Drawing.Printing>przestrzeni nazw.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Pobiera lub ustawia <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> obiekt, który zawiera wszystkie ustawienia szczegółowe zadania drukowania."
  remarks: "Ustawienie tej właściwości CurrentPrintTicket nie sprawdza, czy lub zmodyfikować określonej <xref:System.Printing.PrintTicket>dla danego <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket>  Jeśli to konieczne, użyj <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>metodę w celu utworzenia <xref:System.Printing.PrintQueue>-określonych <xref:System.Printing.PrintTicket>która jest prawidłowa dla danego drukarki.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "A <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> obiekt, który zawiera wszystkie szczegółowe informacje o zadaniu drukowania, takie jak liczba kopii do drukowania, i czy jest używana Obsługa zszywania lub dwustronny."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Pobiera lub ustawia opis zadania drukowania."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "<xref:System.String>Opisujący zadania drukowania, na przykład &quot;kwartalnych raportów.&quot;</xref:System.String>"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
