### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyInformationCollection
  id: PropertyInformationCollection
  children:
  - System.Configuration.PropertyInformationCollection.CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  - System.Configuration.PropertyInformationCollection.GetEnumerator
  - System.Configuration.PropertyInformationCollection.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.PropertyInformationCollection.Item(System.String)
  langs:
  - csharp
  name: PropertyInformationCollection
  nameWithType: PropertyInformationCollection
  fullName: System.Configuration.PropertyInformationCollection
  type: Class
  summary: "Zawiera kolekcję <xref href=&quot;System.Configuration.PropertyInformation&quot;> </xref> obiektów. Ta klasa nie może być dziedziczona."
  remarks: "Kolekcja zawiera obiekt PropertyInformationCollection <xref:System.Configuration.PropertyInformation>obiektów.</xref:System.Configuration.PropertyInformation> A <xref:System.Configuration.PropertyInformation>obiekt zawiera szczegółowe informacje o poszczególnych atrybut w konfiguracji.</xref:System.Configuration.PropertyInformation> Obiekt PropertyInformationCollection pochodzi z skojarzony <xref:System.Collections.Specialized.NameObjectCollectionBase>obiektu.</xref:System.Collections.Specialized.NameObjectCollectionBase>"
  example:
  - "The following code example demonstrates how to use the PropertyInformationCollection class.  \n  \n [!code-cs[System.Configuration.PropertyInformation#14](~/add/codesnippet/csharp/t-system.configuration.p_0_1.cs)]\n [!code-vb[System.Configuration.PropertyInformation#14](~/add/codesnippet/visualbasic/t-system.configuration.p_0_1.vb)]"
  syntax:
    content: 'public sealed class PropertyInformationCollection : System.Collections.Specialized.NameObjectCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.Specialized.NameObjectCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.Specialized.NameObjectCollectionBase.BaseAdd(System.String,System.Object)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseClear
  - System.Collections.Specialized.NameObjectCollectionBase.BaseGet(System.Int32)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseGet(System.String)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseGetAllKeys
  - System.Collections.Specialized.NameObjectCollectionBase.BaseGetAllValues
  - System.Collections.Specialized.NameObjectCollectionBase.BaseGetAllValues(System.Type)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseGetKey(System.Int32)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseHasKeys
  - System.Collections.Specialized.NameObjectCollectionBase.BaseRemove(System.String)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseRemoveAt(System.Int32)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseSet(System.Int32,System.Object)
  - System.Collections.Specialized.NameObjectCollectionBase.BaseSet(System.String,System.Object)
  - System.Collections.Specialized.NameObjectCollectionBase.Count
  - System.Collections.Specialized.NameObjectCollectionBase.IsReadOnly
  - System.Collections.Specialized.NameObjectCollectionBase.Keys
  - System.Collections.Specialized.NameObjectCollectionBase.OnDeserialization(System.Object)
  - System.Collections.Specialized.NameObjectCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.Specialized.NameObjectCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.Specialized.NameObjectCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net462
- uid: System.Configuration.PropertyInformationCollection.CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  id: CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: CopyTo(PropertyInformation[],Int32)
  nameWithType: PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
  fullName: System.Configuration.PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Kopiuje całą <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> kolekcji do jednowymiarowego zgodnego <xref:System.Array>, rozpoczynając od określonego indeksu tablicy docelowej.</xref:System.Array>"
  syntax:
    content: public void CopyTo (System.Configuration.PropertyInformation[] array, int index);
    parameters:
    - id: array
      type: System.Configuration.PropertyInformation[]
      description: "Jednowymiarowa <xref:System.Array>który jest miejscem docelowym elementów kopiowanych z <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> kolekcji.</xref:System.Array> <xref:System.Array>Musi mieć indeksowania liczony od zera.</xref:System.Array>"
    - id: index
      type: System.Int32
      description: "Liczony od zera indeks w `array` od rozpoczyna się kopiowanie które."
  overload: System.Configuration.PropertyInformationCollection.CopyTo*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>array</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The <>*> property of <code>array</code> is less than <>*> + <code>index</code>."
  platform:
  - net462
- uid: System.Configuration.PropertyInformationCollection.GetEnumerator
  id: GetEnumerator
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: PropertyInformationCollection.GetEnumerator()
  fullName: System.Configuration.PropertyInformationCollection.GetEnumerator()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera <xref:System.Collections.IEnumerator>obiektu, który jest używany do iterowania po to <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> kolekcji.</xref:System.Collections.IEnumerator>"
  syntax:
    content: public override System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: "<xref:System.Collections.IEnumerator>Obiektu, który jest używany do iterowania po to <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref>.</xref:System.Collections.IEnumerator>"
  overload: System.Configuration.PropertyInformationCollection.GetEnumerator*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PropertyInformationCollection.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Configuration.PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Wypełnia <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> obiektu o dane potrzebne do serializacji <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> wystąpienia."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> obiekt, który zawiera informacje wymagane do serializacji <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> wystąpienia."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>obiekt, który zawiera źródłowy i docelowy serializowanego strumienia skojarzonego z <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> wystąpienia.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.PropertyInformationCollection.GetObjectData*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>info</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.PropertyInformationCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: PropertyInformationCollection.Item(String)
  fullName: System.Configuration.PropertyInformationCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera <xref href=&quot;System.Configuration.PropertyInformation&quot;> </xref> obiektu w kolekcji na podstawie nazwy określonej właściwości."
  syntax:
    content: public System.Configuration.PropertyInformation this[string propertyName] { get; }
    parameters:
    - id: propertyName
      type: System.String
      description: "Nazwa atrybutu konfiguracji zawarte w <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> obiektu."
    return:
      type: System.Configuration.PropertyInformation
      description: "A <xref href=&quot;System.Configuration.PropertyInformation&quot;></xref> object."
  overload: System.Configuration.PropertyInformationCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Specialized.NameObjectCollectionBase
  isExternal: false
  name: System.Collections.Specialized.NameObjectCollectionBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.PropertyInformationCollection.CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: CopyTo(PropertyInformation[],Int32)
  nameWithType: PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
  fullName: System.Configuration.PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
- uid: System.Configuration.PropertyInformation[]
  parent: System.Configuration
  isExternal: false
  name: PropertyInformation
  nameWithType: PropertyInformation
  fullName: System.Configuration.PropertyInformation[]
  spec.csharp:
  - uid: System.Configuration.PropertyInformation
    name: PropertyInformation
    nameWithType: PropertyInformation
    fullName: PropertyInformation[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.PropertyInformationCollection.GetEnumerator
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: PropertyInformationCollection.GetEnumerator()
  fullName: System.Configuration.PropertyInformationCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: System.Configuration.PropertyInformationCollection.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Configuration.PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.PropertyInformationCollection.Item(System.String)
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: Item(String)
  nameWithType: PropertyInformationCollection.Item(String)
  fullName: System.Configuration.PropertyInformationCollection.Item(String)
- uid: System.Configuration.PropertyInformation
  parent: System.Configuration
  isExternal: false
  name: PropertyInformation
  nameWithType: PropertyInformation
  fullName: System.Configuration.PropertyInformation
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.PropertyInformationCollection.CopyTo*
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: CopyTo
  nameWithType: PropertyInformationCollection.CopyTo
- uid: System.Configuration.PropertyInformationCollection.GetEnumerator*
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: PropertyInformationCollection.GetEnumerator
- uid: System.Configuration.PropertyInformationCollection.GetObjectData*
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: GetObjectData
  nameWithType: PropertyInformationCollection.GetObjectData
- uid: System.Configuration.PropertyInformationCollection.Item*
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: Item
  nameWithType: PropertyInformationCollection.Item
