### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAttribute
  id: EnvironmentPermissionAttribute
  children:
  - System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Security.Permissions.EnvironmentPermissionAttribute.All
  - System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  - System.Security.Permissions.EnvironmentPermissionAttribute.Read
  - System.Security.Permissions.EnvironmentPermissionAttribute.Write
  langs:
  - csharp
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute
  type: Class
  summary: "Zezwala na akcje zabezpieczeń dla <xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref> ma zostać zastosowany do kodu przy użyciu zabezpieczeń deklaratywnych. Ta klasa nie może być dziedziczona."
  remarks: "Zależy od zakresu deklaracji, która jest dozwolona <xref:System.Security.Permissions.SecurityAction>używany.</xref:System.Security.Permissions.SecurityAction>       Informacji o zabezpieczeniach deklaruje atrybutu zabezpieczeń są przechowywane w metadanych elementu docelowego atrybutu i jest dostępny przez system w czasie wykonywania. Atrybuty zabezpieczeń są używane tylko w przypadku zabezpieczenia deklaratywne. Zabezpieczenia imperatywne można użyć w klasie odpowiednie uprawnienia.       Nazwy zmiennych środowiskowych jest rozróżniana wielkość liter. Określono wiele nazwy zmiennych środowiskowych oddzielając nazwy przy użyciu <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Constructor | System.AttributeTargets.Method, AllowMultiple=true, Inherited=false)]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class EnvironmentPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Security.Permissions.EnvironmentPermissionAttribute&quot;> </xref> klasy z określonym <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref>."
  syntax:
    content: public EnvironmentPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: "Jeden z <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref> wartości."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code> action </code> Parametr nie jest prawidłową wartością <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref>."
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  id: All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Pełny dostęp zestawów zmiennych środowiskowych, określony przez wartość ciągu."
  remarks: "Nazwy zmiennych środowiskowych jest rozróżniana wielkość liter. Określono wiele nazwy zmiennych środowiskowych oddzielając nazwy przy użyciu <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: public string All { get; set; }
    return:
      type: System.String
      description: "Lista zmiennych środowiskowych dla pełny dostęp."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "Metoda get nie jest obsługiwana dla tej właściwości."
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Tworzy i zwraca nowy <xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref>."
  remarks: "Ta metoda powinna można wywołać tylko przez system zabezpieczeń nigdy przez kod aplikacji.       W czasie kompilacji atrybuty przekonwertować deklaracje zabezpieczeń do serializacji formularza w metadanych. Zabezpieczenia deklaracyjne danych w metadanych jest tworzona na podstawie ta metoda zwraca odpowiadającego atrybutowi uprawnień."
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: "<xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref> , Który odpowiada temu atrybutowi."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Pobiera lub ustawia dostęp do odczytu, określona przez ciąg wartości zmiennych środowiskowych."
  remarks: "Nazwy zmiennych środowiskowych jest rozróżniana wielkość liter. Określono wiele nazwy zmiennych środowiskowych oddzielając nazwy przy użyciu <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: public string Read { get; set; }
    return:
      type: System.String
      description: "Lista zmiennych środowiskowych dla dostępu do odczytu."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Pobiera lub ustawia dostęp do zapisu w określonym przez wartość ciągu zmiennych środowiskowych."
  remarks: "Nazwy zmiennych środowiskowych jest rozróżniana wielkość liter. Określono wiele nazwy zmiennych środowiskowych oddzielając nazwy przy użyciu <xref:System.IO.Path.PathSeparator>.</xref:System.IO.Path.PathSeparator>"
  syntax:
    content: public string Write { get; set; }
    return:
      type: System.String
      description: "Lista zmiennych środowiskowych dla dostępu do zapisu."
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission
  nameWithType: EnvironmentPermissionAttribute.CreatePermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
