### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  id: EnvironmentPermissionAccess
  children:
  - System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.Read
  - System.Security.Permissions.EnvironmentPermissionAccess.Write
  langs:
  - csharp
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
  type: Enum
  summary: "Określa dostęp do zmiennych środowiskowych."
  remarks: "To wyliczenie jest używany przez <xref:System.Security.Permissions.EnvironmentPermission>.</xref:System.Security.Permissions.EnvironmentPermission>      > [!NOTE] > NoAccess chociaż i AllAccess są wyświetlane w EnvironmentPermissionAccess, nie są prawidłowe jako parametr <xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>ponieważ opisują odpowiednio żadnych typów dostępu do zmiennych środowiska lub wszystkie typy dostępu do zmiennych środowiska i <xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>oczekuje typu dostępu do zmiennych jednym środowisku.</xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A> </xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>"
  syntax:
    content: >-
      [System.Flags]

      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentPermissionAccess
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  id: AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Uprawnienia odczytu i zapisu do zmiennych środowiskowych. AllAccess reprezentuje wiele wartości EnvironmentPermissionAccess i powoduje, że <xref:System.ArgumentException>stosowania jako <code> flag </code> parametr <xref:System.Security.Permissions.EnvironmentPermission.GetPathList*>metody, która oczekuje jednej wartości.</xref:System.Security.Permissions.EnvironmentPermission.GetPathList*> </xref:System.ArgumentException>"
  syntax:
    content: AllAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  id: NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Brak dostępu do zmiennych środowiskowych. NoAccess reprezentuje nie prawidłowe wartości EnvironmentPermissionAccess i powoduje, że <xref:System.ArgumentException>gdy jest używany jako parametr <xref:System.Security.Permissions.EnvironmentPermission.GetPathList*>, która oczekuje jednej wartości.</xref:System.Security.Permissions.EnvironmentPermission.GetPathList*> </xref:System.ArgumentException>"
  syntax:
    content: NoAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Określono dostęp tylko do odczytu do zmiennych środowiskowych. Zmiana, usuwanie i tworzenie zmiennych środowiskowych nie jest uwzględniony w tym poziom dostępu."
  syntax:
    content: Read
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Określony jest tylko do zapisu w zmiennych środowiskowych. Dostęp do zapisu obejmuje tworzenie i usuwanie zmiennych środowiskowych, a także zmiana wartości istniejącego. Odczytywanie zmienne środowiskowe nie jest uwzględniony w tym poziom dostępu."
  syntax:
    content: Write
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
