### YamlMime:ManagedReference
items:
- uid: System.Xml.Schema.XmlSchemaCompilationSettings
  id: XmlSchemaCompilationSettings
  children:
  - System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  - System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  langs:
  - csharp
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings
  type: Class
  summary: "Udostępnia opcje kompilacji schematu dla <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> Klasa ta klasa nie może być dziedziczona."
  remarks: "Klasa XmlSchemaCompilationSettings udostępnia opcje kompilacji schemat dla <xref:System.Xml.Schema.XmlSchemaSet>klasy.</xref:System.Xml.Schema.XmlSchemaSet> Na przykład <xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>właściwość określa, że <xref:System.Xml.Schema.XmlSchemaSet>naruszeń unikatowy cząstki autorstwa (UPA) należy sprawdzić, czy podczas schematów w <xref:System.Xml.Schema.XmlSchemaSet>są kompilowane.</xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>"
  syntax:
    content: public sealed class XmlSchemaCompilationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  id: '#ctor'
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Xml.Schema.XmlSchemaCompilationSettings&quot;> </xref> klasy."
  syntax:
    content: public XmlSchemaCompilationSettings ();
    parameters: []
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  id: EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "Pobiera lub ustawia wartość wskazującą czy <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> należy sprawdzić, czy naruszeń unikatowy cząstki autorstwa (UPA)."
  remarks: "Jeśli ustawiono właściwość EnableUpaCheck `false`, będzie przeprowadzana Walidacja zgodnie z następującymi regułami.      1.  Jeśli istnieje wybór między określonego typu i z symbolem wieloznacznym <xref:System.Xml.Schema.XmlSchemaSet>Wybierz jednoznacznie cząstki, jak przedstawiono w następujących schematów i przykłady Xml.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:any namespace=&quot;##any&quot;/>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `</xs:sequence>`W poniższych Xml `A` zostanie skojarzony element `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` w schemacie.       `<A>some text</A>`      1.  Jeśli istnieje wybór między dwoma elementami jednoznacznie, <xref:System.Xml.Schema.XmlSchemaSet>wpłynie na pierwszą.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot;/>`       `</xs:sequence>`W poniższych Xml `B` zostanie skojarzony element `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` w schemacie.       `<A/>`       `<B/>`"
  syntax:
    content: public bool EnableUpaCheck { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> należy sprawdzić, czy naruszeń unikatowy cząstki autorstwa (UPA); w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
