### YamlMime:ManagedReference
items:
- uid: System.Configuration.IntegerValidatorAttribute
  id: IntegerValidatorAttribute
  children:
  - System.Configuration.IntegerValidatorAttribute.#ctor
  - System.Configuration.IntegerValidatorAttribute.ExcludeRange
  - System.Configuration.IntegerValidatorAttribute.MaxValue
  - System.Configuration.IntegerValidatorAttribute.MinValue
  - System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute
  fullName: System.Configuration.IntegerValidatorAttribute
  type: Class
  summary: "Deklaratywnie nakazuje programu .NET Framework do sprawdzania poprawności liczby całkowitej we właściwości konfiguracji. Ta klasa nie może być dziedziczona."
  remarks: "Użyj atrybutu IntegerValidatorAttribute do dekoracji właściwości konfiguracji zleca .NET Framework do sprawdzania poprawności przy użyciu właściwości <xref:System.Configuration.IntegerValidator>obiektu i przekazywania do niej wartości parametrów decorating.</xref:System.Configuration.IntegerValidator>       Atrybuty IntegerValidatorAttribute może dotyczyć tylko dla typów właściwości."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the IntegerValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/t-system.configuration.i_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/t-system.configuration.i_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class IntegerValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Configuration.IntegerValidatorAttribute&quot;> </xref> klasy."
  remarks: "Ten konstruktor w oparte na atrybutach modelu są używane do zapewnienia, że wartość przypisana do właściwości powiązane jest liczbą całkowitą."
  example:
  - "The following example shows how to use the IntegerValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#5](~/add/codesnippet/visualbasic/m-system.configuration.i_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#5](~/add/codesnippet/csharp/m-system.configuration.i_2_1.cs)]"
  syntax:
    content: public IntegerValidatorAttribute ();
    parameters: []
  overload: System.Configuration.IntegerValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia wartość wskazującą, czy do dołączania lub wykluczania liczby całkowite z zakresu zdefiniowane przez <> </> *> i <> </> *> wartości właściwości."
  remarks: "Zakres jest inclusive <xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A>i <xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A>wartości właściwości.</xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A> </xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A> Gdy wartość właściwości ExcludeRange to `true`, dozwolone wartości są poza zakresem."
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/p-system.configuration.i_6_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/p-system.configuration.i_6_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli wartość musi być wyłączona; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.IntegerValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia wartość maksymalna dozwolona w przypadku właściwości."
  remarks: "Wartość właściwości MaxValue znajduje się w dozwolonym zakresem."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/p-system.configuration.i_3_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/p-system.configuration.i_3_1.cs)]"
  syntax:
    content: public int MaxValue { get; set; }
    return:
      type: System.Int32
      description: "Liczba całkowita, która wskazuje wartość maksymalną dozwoloną."
  overload: System.Configuration.IntegerValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wybrana wartość jest mniejsza niż <xref:System.Configuration.IntegerValidatorAttribute.MinValue*>.</xref:System.Configuration.IntegerValidatorAttribute.MinValue*>"
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia minimalny dozwolony dla właściwości."
  remarks: "Wartość właściwości MinValue znajduje się w dozwolonym zakresem."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/p-system.configuration.i_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/p-system.configuration.i_0_1.cs)]"
  syntax:
    content: public int MinValue { get; set; }
    return:
      type: System.Int32
      description: "Liczba całkowita, która wskazuje wartość minimalną dozwoloną."
  overload: System.Configuration.IntegerValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wybrana wartość jest większa niż <xref:System.Configuration.IntegerValidatorAttribute.MaxValue*>.</xref:System.Configuration.IntegerValidatorAttribute.MaxValue*>"
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera wystąpienie elementu <xref href=&quot;System.Configuration.IntegerValidator&quot;> </xref> klasy."
  remarks: "Właściwość ValidatorInstance służy do sprawdzania poprawności ciąg przez wywołanie jego <xref:System.Configuration.IntegerValidator.Validate%2A>metody.</xref:System.Configuration.IntegerValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#13](~/add/codesnippet/visualbasic/p-system.configuration.i_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#13](~/add/codesnippet/csharp/p-system.configuration.i_2_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> Wystąpienie modułu sprawdzania poprawności."
  overload: System.Configuration.IntegerValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.IntegerValidatorAttribute.#ctor*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
- uid: System.Configuration.IntegerValidatorAttribute.MinValue*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
