### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.RegexWorker
  id: RegexWorker
  children:
  - System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.RegexWorker.Item(System.String)
  - System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  langs:
  - csharp
  name: RegexWorker
  nameWithType: RegexWorker
  fullName: System.Web.Configuration.RegexWorker
  type: Class
  summary: "Używana wewnętrznie w czasie wykonywania przez <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;> </xref> i <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;> </xref> przeanalizować dane żądania i identyfikuje przeglądarki."
  syntax:
    content: public class RegexWorker
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  id: '#ctor(System.Web.HttpBrowserCapabilities)'
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: RegexWorker(HttpBrowserCapabilities)
  nameWithType: RegexWorker.RegexWorker(HttpBrowserCapabilities)
  fullName: System.Web.Configuration.RegexWorker.RegexWorker(HttpBrowserCapabilities)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.RegexWorker&quot;> </xref>."
  syntax:
    content: public RegexWorker (System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "<xref href=&quot;System.Web.Configuration.HttpCapabilitiesBase&quot;> </xref> Obiektu do skonfigurowania."
  overload: System.Web.Configuration.RegexWorker.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RegexWorker.Item(System.String)
  id: Item(System.String)
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: Item(String)
  nameWithType: RegexWorker.Item(String)
  fullName: System.Web.Configuration.RegexWorker.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Metoda dostępu do tej klasy."
  syntax:
    content: public string this[string key] { get; }
    parameters:
    - id: key
      type: System.String
      description: "Określony klucz."
    return:
      type: System.String
      description: "Wewnętrzny wartość skojarzoną z określonym<code>key</code>."
  overload: System.Web.Configuration.RegexWorker.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  id: ProcessRegex(System.String,System.String)
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: ProcessRegex(String,String)
  nameWithType: RegexWorker.ProcessRegex(String,String)
  fullName: System.Web.Configuration.RegexWorker.ProcessRegex(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w czasie wykonywania do określenia, czy wartość nagłówka żądania pasuje dowolnej funkcji wewnętrznej kolekcji przeglądarki."
  syntax:
    content: public bool ProcessRegex (string target, string regexExpression);
    parameters:
    - id: target
      type: System.String
      description: "Wartość możliwości z wewnętrznej kolekcji przeglądarki."
    - id: regexExpression
      type: System.String
      description: "Wartość nagłówka żądania."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli wartość nagłówka żądania zgodny z dowolnym z funkcji wewnętrznej kolekcji przeglądarek; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.RegexWorker.ProcessRegex*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: RegexWorker(HttpBrowserCapabilities)
  nameWithType: RegexWorker.RegexWorker(HttpBrowserCapabilities)
  fullName: System.Web.Configuration.RegexWorker.RegexWorker(HttpBrowserCapabilities)
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.Configuration.RegexWorker.Item(System.String)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: Item(String)
  nameWithType: RegexWorker.Item(String)
  fullName: System.Web.Configuration.RegexWorker.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: ProcessRegex(String,String)
  nameWithType: RegexWorker.ProcessRegex(String,String)
  fullName: System.Web.Configuration.RegexWorker.ProcessRegex(String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.RegexWorker.#ctor*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: RegexWorker
  nameWithType: RegexWorker.RegexWorker
- uid: System.Web.Configuration.RegexWorker.Item*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: Item
  nameWithType: RegexWorker.Item
- uid: System.Web.Configuration.RegexWorker.ProcessRegex*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: ProcessRegex
  nameWithType: RegexWorker.ProcessRegex
