### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComContractsSection
  id: ComContractsSection
  children:
  - System.ServiceModel.Configuration.ComContractsSection.#ctor
  - System.ServiceModel.Configuration.ComContractsSection.ComContracts
  - System.ServiceModel.Configuration.ComContractsSection.Properties
  langs:
  - csharp
  name: ComContractsSection
  nameWithType: ComContractsSection
  fullName: System.ServiceModel.Configuration.ComContractsSection
  type: Class
  summary: "Reprezentuje sekcję konfiguracji, który zawiera elementy dla określenia nazwy przestrzeni nazw i kontraktu dla kontraktu integracji COM +. Ta klasa nie może być dziedziczona."
  remarks: "Kontrakty usług integracji COM + są obecnie ograniczone do przestrzeni nazw &quot;http://tempuri.org&quot;, a Nazwa kontraktu pochodzi od obsługi interfejsu COM. Można jednak określić alternatywne przy użyciu `comContracts` sekcji w pliku konfiguracji. Na przykład można użyć następującej konfiguracji do określenia nazwy przestrzeni nazw i kontraktu dla kontraktu usługi [!code-cs [XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] podczas inicjowania usługi określonej nazwy przestrzeni nazw i kontraktu są stosowane do opisów wygenerowanego usługi.       Ta sekcja jest pusta, inicjowanie usługi zastosowanie domyślną nazwę przestrzeni nazw i kontraktu pobranych z pomocniczych identyfikatora interfejsu COM"
  syntax:
    content: 'public sealed class ComContractsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.ComContractsSection&quot;> </xref> klasy."
  syntax:
    content: public ComContractsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  id: ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera wszystkie COM + integration kontraktów usług określone w sekcji."
  syntax:
    content: public System.ServiceModel.Configuration.ComContractElementCollection ComContracts { get; }
    return:
      type: System.ServiceModel.Configuration.ComContractElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.ComContractElementCollection&quot;> </xref> zawierający wszystkie COM + integration kontraktów usług określone w sekcji."
  overload: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Configuration.ComContractsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ComContractElementCollection
  nameWithType: ComContractElementCollection
  fullName: System.ServiceModel.Configuration.ComContractElementCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection
  nameWithType: ComContractsSection.ComContractsSection
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
