### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "Określa identyfikator domeny aplikacji, które implementację buforu służy do interakcji z środowisku hosta."
  remarks: "A [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] środowisku hosta, takich jak ASP.NET, można użyć interfejsu IApplicationIdentifier do definiowania ciągów, które zidentyfikować domeny poszczególnych aplikacji. W środowisku hosta implementuje interfejs IApplicationIdentifier. Ten interfejs jest następnie udostępniana <xref:System.Runtime.Caching.ObjectCache>implementacje za pośrednictwem <xref:System.Runtime.Caching.ObjectCache.Host%2A>Właściwości.</xref:System.Runtime.Caching.ObjectCache.Host%2A> </xref:System.Runtime.Caching.ObjectCache>       Implementacja pamięci podręcznej używa tego odwołania, aby uzyskać identyfikator domeny aplikacji. W programie ASP.NET implementacje pamięci podręcznej skonstruować identyfikatory liczników wydajności pamięci podręcznej za pomocą identyfikatora aplikacji. Zapewnia to nazwy wydajności wystąpień liczników, które można rozróżnić między domenami aplikacji uruchomionej wielu domen aplikacji."
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net462
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "Pobiera identyfikator domeny aplikacji."
  remarks: "Metoda GetApplicationId jest zwykle implementowany przez [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] środowisku hosta, aby można było utworzyć identyfikator aplikacji <xref:System.Runtime.Caching.ObjectCache>implementacji.</xref:System.Runtime.Caching.ObjectCache> A <xref:System.Runtime.Caching.ObjectCache>Implementacja używa tych informacji do identyfikowania domeny aplikacji, które jest aktualnie uruchomione.</xref:System.Runtime.Caching.ObjectCache>       Na przykład w programie ASP.NET pamięci podręcznej używa identyfikatora aplikacji do skonstruowania identyfikatory liczników wydajności pamięci podręcznej. Pamięć podręczna wywołuje metodę GetApplicationId, która jest zaimplementowana przez środowisko hosta i hosta zwraca identyfikator. Zapewnia to nazwy wydajności wystąpień liczników, które można rozróżnić między domenami aplikacji uruchomionej wielu domen aplikacji."
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "Unikatowy identyfikator bieżącej domeny aplikacji."
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
