### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.IServerWebConfig
  id: IServerWebConfig
  children:
  - System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: IServerWebConfig
  nameWithType: IServerWebConfig
  fullName: System.EnterpriseServices.Internal.IServerWebConfig
  type: Interface
  summary: "Tworzy plik Web.config dla aplikacji z obsługą protokołu SOAP modelu COM + i dodaje wpisy składnika do pliku dla interfejsów COM publikowaną w aplikacji."
  remarks: "Interfejs IServerWebConfig jest wykonywane tylko przez <xref:System.EnterpriseServices.Internal.ServerWebConfig>klasy i jest używany tylko w infrastrukturę programu .NET Framework.</xref:System.EnterpriseServices.Internal.ServerWebConfig> Zamiast implementowania interfejsu lub tworzenia wystąpienia obiektu interfejsu IServerWebConfig, użyj <xref:System.EnterpriseServices.Internal.Publish>klasy, która implementuje <xref:System.EnterpriseServices.Internal.IComSoapPublisher>interfejsu.</xref:System.EnterpriseServices.Internal.IComSoapPublisher> </xref:System.EnterpriseServices.Internal.Publish>       IServerWebConfig jest używana wewnętrznie przez program .NET Framework. Nie trzeba używać go bezpośrednio w kodzie."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("6261e4b5-572a-4142-a2f9-1fe1a0c97097")]

      public interface IServerWebConfig
  implements: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Dodaje elementy XML w pliku Web.config dla interfejsu COM publikowaną w aplikacji z obsługą protokołu SOAP modelu COM +."
  remarks: "Zobacz <xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A>metodę szczegóły implementacji.</xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A> Jednak nie należy wywołać `AddElement` metody bezpośrednio."
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string Mode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Ścieżka do istniejącego pliku Web.config."
    - id: AssemblyName
      type: System.String
      description: "Nazwa zestawu zawierającego typ dodawany."
    - id: TypeName
      type: System.String
      description: "Nazwa typu dodawany."
    - id: ProgId
      type: System.String
      description: "Identyfikator programowy typu dodawany."
    - id: Mode
      type: System.String
      description: "Stałą typu string, który odpowiada nazwie elementu członkowskiego z <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> wyliczenia, który wskazuje, jak dobrze znane obiekty została aktywowana."
    - id: Error
      type: System.String
      description: "Ciąg, do którego mogą być zapisywane komunikat o błędzie."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Tworzy plik Web.config dla aplikacji z obsługą protokołu SOAP modelu COM +, plik jest gotowy do elementy XML dodane dla interfejsów COM publikowana."
  remarks: "Zobacz <xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A>metodę szczegóły implementacji.</xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A> Jednak nie należy wywołać `Create` bezpośrednio."
  syntax:
    content: public void Create (string FilePath, string FileRootName, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Folder, w którym można utworzyć pliku konfiguracji."
    - id: FileRootName
      type: System.String
      description: "Wartość ciągu, do której można dodać rozszerzenia konfiguracji (na przykład plik Web.config w sieci Web)."
    - id: Error
      type: System.String
      description: "Ciąg, do którego mogą być zapisywane komunikat o błędzie."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: IServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create
  nameWithType: IServerWebConfig.Create
