### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderCollection
  id: SettingsProviderCollection
  children:
  - System.Configuration.SettingsProviderCollection.#ctor
  - System.Configuration.SettingsProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.SettingsProviderCollection.Item(System.String)
  langs:
  - csharp
  name: SettingsProviderCollection
  nameWithType: SettingsProviderCollection
  fullName: System.Configuration.SettingsProviderCollection
  type: Class
  summary: "Reprezentuje kolekcję dostawców ustawień aplikacji."
  remarks: "Klasa SettingsProviderCollection jest proste rozszerzenie <xref:System.Configuration.Provider.ProviderCollection>klasy do zapewnienia miejsca <xref:System.Configuration.SettingsProvider>obiektów.</xref:System.Configuration.SettingsProvider> </xref:System.Configuration.Provider.ProviderCollection>       Do <xref:System.Configuration.ApplicationSettingsBase>tej kolekcji, aby zarządzać dostawcami ustawienia skojarzone z każdym z jego właściwości ustawień aplikacji za pośrednictwem <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> używa klasy</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: 'public class SettingsProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  platform:
  - net462
- uid: System.Configuration.SettingsProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsProviderCollection
  langs:
  - csharp
  name: SettingsProviderCollection()
  nameWithType: SettingsProviderCollection.SettingsProviderCollection()
  fullName: System.Configuration.SettingsProviderCollection.SettingsProviderCollection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsProviderCollection&quot;> </xref> klasy."
  remarks: "To jest niejawnie dostarczonego konstruktora domyślnego."
  syntax:
    content: public SettingsProviderCollection ();
    parameters: []
  overload: System.Configuration.SettingsProviderCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.SettingsProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: SettingsProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.SettingsProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Dodaje nowego dostawcę ustawień do kolekcji."
  remarks: "<xref:System.Configuration.Provider.ProviderBase.Name%2A>Właściwość <xref:System.Configuration.SettingsProvider>jest używany jako klucz magazynu.</xref:System.Configuration.SettingsProvider> </xref:System.Configuration.Provider.ProviderBase.Name%2A>      > [!CAUTION] > Chociaż jeden ma metody Add <xref:System.Configuration.Provider.ProviderBase>parametr jest zgodny z podpisem tej samej metody w klasie podstawowej <xref:System.Configuration.Provider.ProviderCollection>, tej metody spowoduje zgłoszenie wyjątku, jeśli `provider` parametru nie jest typu <xref:System.Configuration.SettingsProvider>.</xref:System.Configuration.SettingsProvider> </xref:System.Configuration.Provider.ProviderCollection> </xref:System.Configuration.Provider.ProviderBase>"
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: "A <xref href=&quot;System.Configuration.Provider.ProviderBase&quot;> </xref> do dodania do kolekcji."
  overload: System.Configuration.SettingsProviderCollection.Add*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code> provider </code> Parametru nie jest typu <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref>.       - lub - <> </> *> właściwości parametru dostawcy ma wartość null lub pusty ciąg.       - lub - dostawcy ustawień o takim samym <> </> *> już istnieje w kolekcji."
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "Kolekcja jest tylko do odczytu."
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>provider</code> parameter is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.SettingsProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.SettingsProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: SettingsProviderCollection.Item(String)
  fullName: System.Configuration.SettingsProviderCollection.Item(String)
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera dostawcę ustawienia w kolekcji, który odpowiada nazwie określonej."
  remarks: "Możesz wprowadzić <xref:System.Configuration.SettingsProviderCollection>tylko do odczytu za pomocą <xref:System.Configuration.Provider.ProviderCollection.SetReadOnly%2A>metody.</xref:System.Configuration.Provider.ProviderCollection.SetReadOnly%2A> </xref:System.Configuration.SettingsProviderCollection> Jednak jest on nieprawidłowy metod takich jak <xref:System.Configuration.SettingsProviderCollection.Add%2A>, <xref:System.Configuration.Provider.ProviderCollection.Remove%2A>, i <xref:System.Configuration.Provider.ProviderCollection.Clear%2A>od kolekcji programu.</xref:System.Configuration.Provider.ProviderCollection.Clear%2A> </xref:System.Configuration.Provider.ProviderCollection.Remove%2A> </xref:System.Configuration.SettingsProviderCollection.Add%2A>"
  syntax:
    content: public System.Configuration.SettingsProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "A <xref:System.String>zawierający przyjazna nazwa dostawcy ustawień.</xref:System.String>"
    return:
      type: System.Configuration.SettingsProvider
      description: "Jeśli znaleziono <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> którego nazwa odpowiada określonej przez parametr name; w przeciwnym razie <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingsProviderCollection.Item*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>name</code> parameter is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "Kolekcja jest tylko do odczytu, ustawiając tę wartość."
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.SettingsProviderCollection.#ctor
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: SettingsProviderCollection()
  nameWithType: SettingsProviderCollection.SettingsProviderCollection()
  fullName: System.Configuration.SettingsProviderCollection.SettingsProviderCollection()
- uid: System.Configuration.SettingsProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: SettingsProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.SettingsProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.SettingsProviderCollection.Item(System.String)
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: SettingsProviderCollection.Item(String)
  fullName: System.Configuration.SettingsProviderCollection.Item(String)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderCollection.#ctor*
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: SettingsProviderCollection
  nameWithType: SettingsProviderCollection.SettingsProviderCollection
- uid: System.Configuration.SettingsProviderCollection.Add*
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Add
  nameWithType: SettingsProviderCollection.Add
- uid: System.Configuration.SettingsProviderCollection.Item*
  parent: System.Configuration.SettingsProviderCollection
  isExternal: false
  name: Item
  nameWithType: SettingsProviderCollection.Item
