### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSetting
  id: SpecialSetting
  children:
  - System.Configuration.SpecialSetting.ConnectionString
  - System.Configuration.SpecialSetting.WebServiceUrl
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
  type: Enum
  summary: "Określa kategorię specjalne ustawienie właściwości ustawień aplikacji."
  remarks: "Wyliczenie SpecialSetting definiuje zestaw kategorii specjalne, które są stosowane do właściwości ustawień aplikacji przy użyciu klasy ttribute.      > [!CAUTION] > Domyślny dostawca ustawień <xref:System.Configuration.LocalFileSettingsProvider>, nie szyfrowanie lub inny sposób ochrony parametry połączenia.</xref:System.Configuration.LocalFileSettingsProvider> Proste przechowuje ustawienia tego typu w oddzielnej `<connectionstrings>` sekcji w pliku konfiguracyjnym odpowiedniej."
  syntax:
    content: public enum SpecialSetting
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.ConnectionString
  id: ConnectionString
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Właściwość konfiguracji reprezentuje ciąg połączenia zazwyczaj danych można przechowywać lub zasobu sieciowego."
  syntax:
    content: ConnectionString
    return:
      type: System.Configuration.SpecialSetting
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  id: WebServiceUrl
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Właściwość konfiguracji reprezentuje Uniform Resource Locator (URL) do usługi sieci Web."
  syntax:
    content: WebServiceUrl
    return:
      type: System.Configuration.SpecialSetting
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SpecialSetting.ConnectionString
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
