### YamlMime:ManagedReference
items:
- uid: System.Configuration.IdnElement
  id: IdnElement
  children:
  - System.Configuration.IdnElement.#ctor
  - System.Configuration.IdnElement.Enabled
  - System.Configuration.IdnElement.Properties
  langs:
  - csharp
  name: IdnElement
  nameWithType: IdnElement
  fullName: System.Configuration.IdnElement
  type: Class
  summary: "Zawiera ustawienia konfiguracji dla międzynarodowej domeny nazwę (IDN) przetwarzania w &lt;xref:System.Uri?displayProperty=fullName&gt; klasy."
  remarks: "Istniejące <xref:System.Uri?displayProperty=fullName>klasa została rozszerzona, aby zapewnić obsługę dla identyfikatorów zasobów międzynarodowych (IRI) oparte na specyfikacji RFC 3987.</xref:System.Uri?displayProperty=fullName> Bieżąca liczba użytkowników nie będą widzieć wszystkie zmiany z zachowaniem .NET Framework 2.0, chyba że jawnie włączyć IRI. Dzięki temu zgodność aplikacji we wcześniejszych wersjach programu .NET Framework.       Ustawienie konfiguracji IdnElement pośrednio jest kontrolowany przez <xref:System.Configuration.IriParsingElement>Ustawienie konfiguracji przetwarzanie IRI formantów w <xref:System.Uri?displayProperty=fullName>klasie.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> Przetwarzanie IRI musi być włączona dla przetwarzania w celu umożliwienia IDN. Po wyłączeniu przetwarzania IRI przetwarzania IDN zostanie ustawiona do ustawienie domyślne, których zachowanie programu .NET Framework 2.0 jest używany dla zgodności i nazwy IDN nie są używane.       Atrybut międzynarodowych nazw domen (IDN) tylko formanty przetwarzania IDN. Domyślnie odbywa się wszystkie inne IRI przetwarzania (na przykład normalizacji znaków).       Ustawienie konfiguracji dla IdnElement zostaną odczytane raz po pierwszym <xref:System.Uri?displayProperty=fullName>klasy jest tworzony.</xref:System.Uri?displayProperty=fullName> Zmiany ustawień konfiguracji po tym czasie są ignorowane.       Aby uzyskać więcej informacji na temat obsługi IRI zobacz sekcję uwag dla <xref:System.Uri?displayProperty=fullName>klasy.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: 'public sealed class IdnElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.IdnElement.#ctor
  id: '#ctor'
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: IdnElement()
  nameWithType: IdnElement.IdnElement()
  fullName: System.Configuration.IdnElement.IdnElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> klasy."
  remarks: "Ten konstruktor tworzy <xref:System.Configuration.IdnElement>wystąpienie</xref:System.Configuration.IdnElement>"
  syntax:
    content: public IdnElement ();
    parameters: []
  overload: System.Configuration.IdnElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IdnElement.Enabled
  id: Enabled
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: Enabled
  nameWithType: IdnElement.Enabled
  fullName: System.Configuration.IdnElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera lub ustawia wartość <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> ustawienia konfiguracji."
  remarks: "Międzynarodowa nazwa domeny (IDN) atrybutu tylko formanty IDN przetwarzania. Wszystkie inne przetwarzanie międzynarodowej identyfikatory zasobów (IRI) (na przykład znak normalizacji) jest realizowane domyślnie.       Ustawienie konfiguracji <xref:System.Configuration.IdnElement>pośrednio jest kontrolowany przez <xref:System.Configuration.IriParsingElement?displayProperty=fullName>Ustawienie konfiguracji, które kontroluje IRI przetwarzania w <xref:System.Uri?displayProperty=fullName>klasie.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement?displayProperty=fullName> </xref:System.Configuration.IdnElement> Przetwarzanie IRI musi być włączona dla przetwarzania w celu umożliwienia IDN. Po wyłączeniu przetwarzania IRI przetwarzania IDN zostanie ustawiona do ustawienie domyślne, których zachowanie programu .NET Framework 2.0 jest używany dla zgodności i nazwy IDN nie są używane.       Ustawienie konfiguracji <xref:System.Configuration.IdnElement>zostaną odczytane raz po pierwszym <xref:System.Uri?displayProperty=fullName>klasy jest tworzony.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IdnElement> Zmiany ustawień konfiguracji po tym czasie są ignorowane.       Aby uzyskać więcej informacji na temat obsługi IRI zobacz sekcję uwag dla <xref:System.Uri?displayProperty=fullName>klasy.</xref:System.Uri?displayProperty=fullName>"
  syntax:
    content: public UriIdnScope Enabled { get; set; }
    return:
      type: System.UriIdnScope
      description: "A <xref href=&quot;System.UriIdnScope&quot;> </xref> zawiera bieżące ustawienia konfiguracji dla przetwarzania IDN."
  overload: System.Configuration.IdnElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IdnElement.Properties
  id: Properties
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: Properties
  nameWithType: IdnElement.Properties
  fullName: System.Configuration.IdnElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Configuration.IdnElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.IdnElement.#ctor
  parent: System.Configuration.IdnElement
  isExternal: false
  name: IdnElement()
  nameWithType: IdnElement.IdnElement()
  fullName: System.Configuration.IdnElement.IdnElement()
- uid: System.Configuration.IdnElement.Enabled
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Enabled
  nameWithType: IdnElement.Enabled
  fullName: System.Configuration.IdnElement.Enabled
- uid: System.UriIdnScope
  parent: System
  isExternal: false
  name: UriIdnScope
  nameWithType: UriIdnScope
  fullName: System.UriIdnScope
- uid: System.Configuration.IdnElement.Properties
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Properties
  nameWithType: IdnElement.Properties
  fullName: System.Configuration.IdnElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.IdnElement.#ctor*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: IdnElement
  nameWithType: IdnElement.IdnElement
- uid: System.Configuration.IdnElement.Enabled*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Enabled
  nameWithType: IdnElement.Enabled
- uid: System.Configuration.IdnElement.Properties*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Properties
  nameWithType: IdnElement.Properties
