### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultSettingValueAttribute
  id: DefaultSettingValueAttribute
  children:
  - System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  - System.Configuration.DefaultSettingValueAttribute.Value
  langs:
  - csharp
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute
  fullName: System.Configuration.DefaultSettingValueAttribute
  type: Class
  summary: "Określa wartość domyślną dla właściwości ustawień aplikacji."
  remarks: "> [!IMPORTANT]> DefaultSettingValueAttribute można stosować do indywidualnych ustawień właściwości; jest on nieprawidłowy w zastosowaniu tego atrybutu do klasy ustawień całej aplikacji.       Różne ustawienia dostawcy mogą mieć różne wymagania i ograniczenia na użycie DefaultSettingValueAttribute. Na przykład <xref:System.Configuration.LocalFileSettingsProvider>nie wymaga tego atrybutu, a następnie spowoduje zastąpienie żadnych wartości dostarczonej przez tego atrybutu, jeśli istnieją wartości — domyślna lub zmodyfikowane przez użytkownika — znajdujących się już w magazynie danych.</xref:System.Configuration.LocalFileSettingsProvider>       DefaultSettingValueAttribute wymaga się, że wartość domyślna może być reprezentowany jako ciąg. W związku z tym ustawień za pomocą serializacji XML nie może mieć wartości domyślnej określony za pomocą tego atrybutu. Niektórzy dostawcy mogą zdecydować się na brak obsługi wielu schematów serializacji, które można określić podczas kompilowania przy użyciu <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute>      > [!CAUTION] > Określony przez atrybut wartości domyślne są przechowywane jako zwykły tekst w wynikowe skompilowanego pliku .exe lub .dll. Dlatego te wartości domyślne są z założenia niezabezpieczone."
  example:
  - "The following code example demonstrates the use of the DefaultSettingValueAttribute applied to three of the four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The first three of these form properties have default values associated with them.  \n  \n The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.d_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.d_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class DefaultSettingValueAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje wystąpienie klasy <xref href=&quot;System.Configuration.DefaultSettingValueAttribute&quot;> </xref> klasy."
  remarks: "Podany ciąg musi mieć wartość, która jest zgodna z mechanizmem serializacji dostępne skojarzone z typem właściwości. Na przykład, jeśli właściwość jest typu <xref:System.Drawing.Color>, a następnie `value` z `&quot;Azure&quot;` będzie ważny.</xref:System.Drawing.Color>      > [!CAUTION] > Określony przez atrybut wartości domyślne są przechowywane jako zwykły tekst w wynikowe skompilowanego pliku .exe lub .dll. Dlatego te wartości domyślne są z założenia niezabezpieczone."
  syntax:
    content: public DefaultSettingValueAttribute (string value);
    parameters:
    - id: value
      type: System.String
      description: "A <xref:System.String>reprezentujący wartość domyślna właściwości.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  id: Value
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera wartość domyślną dla właściwości ustawień aplikacji."
  remarks: "Wartość właściwości jest ustawiona <xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>konstruktora.</xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>       Ustawienie dostawcy może obsługiwać wiele schematów serializacji, które można określić z <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute>"
  syntax:
    content: public string Value { get; }
    return:
      type: System.String
      description: "A <xref:System.String>reprezentujący wartość domyślna właściwości.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute
- uid: System.Configuration.DefaultSettingValueAttribute.Value*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
