### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  id: PeerApplicationCollection
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  langs:
  - csharp
  name: PeerApplicationCollection
  nameWithType: PeerApplicationCollection
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  type: Class
  summary: "Reprezentuje kontener dla <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> elementów. Wystąpienie tego typu zwracanego przez <xref:System.Net.PeerToPeer.Collaboration.ContactManager.GetContacts*>metody statycznej.</xref:System.Net.PeerToPeer.Collaboration.ContactManager.GetContacts*>"
  remarks: "Brak konstruktorów publicznych są zdefiniowane dla tej klasy."
  syntax:
    content: 'public class PeerApplicationCollection : System.Collections.ObjectModel.Collection<System.Net.PeerToPeer.Collaboration.PeerApplication>'
  inheritance:
  - System.Collections.ObjectModel.Collection`1
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  id: InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: InsertItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Wstawia nowy <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> element do <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplicationCollection&quot;> </xref> pod określony indeks lub klucz."
  remarks: '`Null`elementy nie są dozwolone.'
  syntax:
    content: protected override void InsertItem (int index, System.Net.PeerToPeer.Collaboration.PeerApplication item);
    parameters:
    - id: index
      type: System.Int32
      description: "Liczony od zera indeks elementu do zamiany"
    - id: item
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "Nowa wartość dla elementu o określonym indeksie."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  id: SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: SetItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.SetItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(Int32,PeerApplication)
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Zastępuje <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> pod określonym indeksem."
  remarks: '`Null`elementy nie są dozwolone.'
  syntax:
    content: protected override void SetItem (int index, System.Net.PeerToPeer.Collaboration.PeerApplication item);
    parameters:
    - id: index
      type: System.Int32
      description: "Liczony od zera indeks elementu do zamiany."
    - id: item
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "Nowa wartość elementu pod określonym indeksem."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  id: ToString
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: ToString()
  nameWithType: PeerApplicationCollection.ToString()
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString()
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Zwraca <xref:System.String>reprezentujący bieżącą wartość <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> obiektu rozdzielonych przecinkami.</xref:System.String>"
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "A <xref:System.String>reprezentujący bieżącą wartość <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> w <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplicationCollection&quot;> </xref>, rozdzielonych przecinkami.</xref:System.String>"
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.ObjectModel.Collection`1
  isExternal: false
  name: System.Collections.ObjectModel.Collection<System.Net.PeerToPeer.Collaboration.PeerApplication>
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: InsertItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(Int32,PeerApplication)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: SetItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.SetItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(Int32,PeerApplication)
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: ToString()
  nameWithType: PeerApplicationCollection.ToString()
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: InsertItem
  nameWithType: PeerApplicationCollection.InsertItem
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: SetItem
  nameWithType: PeerApplicationCollection.SetItem
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: ToString
  nameWithType: PeerApplicationCollection.ToString
