### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs
  id: DeploymentProgressChangedEventArgs
  children:
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  langs:
  - csharp
  name: DeploymentProgressChangedEventArgs
  nameWithType: DeploymentProgressChangedEventArgs
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs
  type: Class
  summary: "Reprezentuje dane postępu zgłaszane w operacji asynchronicznej."
  remarks: "Ta klasa zawiera właściwości, które opisują postępu <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, i <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>zdarzeń.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Nie wszystkie właściwości w tej klasie dotyczą każdego zdarzenia.       <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A>i <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A>reprezentują całkowita liczba bajtów pobrane do daty i łączna liczba bajtów w operacji pobierania odpowiednio; są one stosowane do wszystkich trzech zdarzeń.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A> <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>nazwy grupy plików odpowiadającą bieżącej <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>zdarzenia i <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A>odzwierciedla bieżący etap operacji pobierania.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/t-system.deployment.appl_5_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: 'public class DeploymentProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  id: BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera liczbę bajtów już pobranych przez tę operację."
  remarks: "Aby uzyskać <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, właściwość BytesCompleted odwołuje się do pobierania manifestu rozmieszczenia.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Aby uzyskać <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, właściwość odwołuje się do postęp pobierania aktualizacji całej dołączone pliki manifesty zestawów i danych.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> Aby uzyskać <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, właściwość odwołuje się do całego zestawu plików, które są częścią grupy o nazwie postęp pobierania.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/c5260b60-c259-429d-9763-_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesCompleted { get; }
    return:
      type: System.Int64
      description: "<xref:System.Int64>Już reprezentujący dane przesyłane w bajtach.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  id: BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera całkowitą liczbę bajtów w operacji pobierania."
  remarks: "Aby uzyskać <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, właściwość BytesTotal odwołuje się do pobierania manifestu rozmieszczenia.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Aby uzyskać <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, właściwość odwołuje się do postęp pobierania aktualizacji całej dołączone pliki manifesty zestawów i danych.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> Aby uzyskać <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, właściwość odwołuje się do całego zestawu plików, które są częścią grupy o nazwie postęp pobierania.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_3_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesTotal { get; }
    return:
      type: System.Int64
      description: "<xref:System.Int64>Reprezentujący całkowity rozmiar w bajtach pobraniu.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera nazwę grupy plików, pobierania."
  remarks: "Możesz zainicjować wielu wywołań <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A>i Pobierz jednocześnie wiele grup plików.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A> Grupy można określić, które zdarzenia wywołania zwrotne odpowiadają grupę."
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_4_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: "A <xref:System.String>zawierającą nazwę grupy plików, jeśli zdarzenie wystąpiło w wyniku wywołania <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*>; w przeciwnym razie ciąg o zerowej długości.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*> </xref:System.String>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera akcję, która jest w trakcie wykonywania procesu."
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_11_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> wartości, podając, jakie element lub elementy operacja jest obecnie pobierania."
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
