### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  id: PeerApplicationLaunchInfo
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  langs:
  - csharp
  name: PeerApplicationLaunchInfo
  nameWithType: PeerApplicationLaunchInfo
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  type: Class
  summary: "Reprezentuje informacje uruchamiania wymagane przez <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> który zainicjował w odpowiedzi na zaproszenie współpracy elementów równorzędnych."
  remarks: "Aplikacja może sprawdzać <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>i <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A>Właściwości tej klasy, aby uzyskać informacje specyficzne dla zaproszenia, który zainicjował uruchamiania aplikacji.</xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A> </xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>       Dostęp do tej klasy wymaga <xref:System.Security.Permissions.PermissionState> <xref:System.Security.Permissions.PermissionState>.</xref:System.Security.Permissions.PermissionState> </xref:System.Security.Permissions.PermissionState> Ten stan jest tworzone, gdy <xref:System.Net.PeerToPeer.Collaboration.Peer>rozpoczyna sesję współpracy.</xref:System.Net.PeerToPeer.Collaboration.Peer>"
  syntax:
    content: public class PeerApplicationLaunchInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  id: Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera lub ustawia zdefiniowanym przez aplikację dane binarne skojarzone z <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> zaproszenia."
  remarks: "Ten obiekt blob danych jest dowolnej postaci i są dostarczane przez obiekt wywołujący.  Maksymalna ilość danych, które można podać to 4096 bajtów.       Dane nie może być `null`."
  syntax:
    content: public byte[] Data { get; }
    return:
      type: System.Byte[]
      description: "Tablica bajtów, które zawierającego dane skojarzone z <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> zaproszenia."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  id: Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "GET lub set skojarzone z odpowiedzią na komunikat <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> zaproszenia."
  remarks: "Maksymalna długość komunikatu to 255 znaków Unicode. Chyba że jawnie określona, wartością domyślną dla wszystkich właściwości jest `null` dla typów odwołań."
  syntax:
    content: public string Message { get; }
    return:
      type: System.String
      description: "Wiadomość SMS skojarzone z <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerInvitationResponse&quot;> </xref> do <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> zaproszenia."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera lub ustawia <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> dla której wysłano zaproszenie."
  remarks: "Chyba że jawnie określona, wartością domyślną dla wszystkich właściwości jest `null` dla typów odwołań."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> Dla którego <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> zaproszenie zostało wysłane."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera lub ustawia <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> która wysłała zaproszenie."
  remarks: "Chyba że jawnie określona, wartością domyślną dla wszystkich właściwości jest `null` dla typów odwołań."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> Która wysłała zaproszenie."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Pobiera lub ustawia <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> z którego <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> zaproszenie zostało wysłane."
  remarks: "Chyba że jawnie określona, wartością domyślną dla wszystkich właściwości jest `null` dla typów odwołań."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> z której wysłano zaproszenie."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
