### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "Określa, czy właściwości ustawień aplikacji ma wspólne wartości dla wszystkich użytkowników aplikacji. Ta klasa nie może być dziedziczona."
  remarks: "Właściwości ustawień aplikacji ma zakres, w którym jest oparty na poziomie użytkownika lub aplikacji. Jak oznacza kategorie właściwości ustawień z zakresu aplikacji przedstawia wartości jednolitego wszyscy użytkownicy aplikacji, natomiast zakresu użytkownika właściwości są wyposażone w dedykowane wartości dla poszczególnych użytkowników aplikacji.       Atrybutu ApplicationScopedSettingAttribute wskazuje, że właściwość należy traktować jako ustawienie na poziomie aplikacji, że decyzje dotyczące odpowiedniego magazynu należy odpowiednio przez dostawcę ustawień.       Atrybut zakres jest wymagany dla każdej właściwości ustawień. Jeśli właściwość nie została zastosowana z obu atrybutu ApplicationScopedSettingAttribute ani <xref:System.Configuration.UserScopedSettingAttribute>, właściwość nie jest rozpoznawany przez dostawcę ustawień — nie jest serializowany.</xref:System.Configuration.UserScopedSettingAttribute> Nieprawidłowy, jest jednak zastosowanie obu atrybutów w tej samej właściwości. Takie próba spowoduje, że <xref:System.Configuration.ConfigurationErrorsException>zostanie wygenerowany.</xref:System.Configuration.ConfigurationErrorsException>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;> </xref> klasy."
  remarks: "Każda właściwość ustawienia aplikacji muszą być stosowane z atrybutem pojedynczy zakres, w celu rozpoznana, a serializowany przez dostawcę ustawień."
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
