### YamlMime:ManagedReference
items:
- uid: System.Windows.BaseValueSource
  id: BaseValueSource
  children:
  - System.Windows.BaseValueSource.Default
  - System.Windows.BaseValueSource.DefaultStyle
  - System.Windows.BaseValueSource.DefaultStyleTrigger
  - System.Windows.BaseValueSource.ImplicitStyleReference
  - System.Windows.BaseValueSource.Inherited
  - System.Windows.BaseValueSource.Local
  - System.Windows.BaseValueSource.ParentTemplate
  - System.Windows.BaseValueSource.ParentTemplateTrigger
  - System.Windows.BaseValueSource.Style
  - System.Windows.BaseValueSource.StyleTrigger
  - System.Windows.BaseValueSource.TemplateTrigger
  - System.Windows.BaseValueSource.Unknown
  langs:
  - csharp
  name: BaseValueSource
  nameWithType: BaseValueSource
  fullName: System.Windows.BaseValueSource
  type: Enum
  summary: "Określa źródło system właściwości zależności określonej wartości właściwości."
  remarks: "To wyliczenie jest używana przez właściwość w <xref:System.Windows.ValueSource>struktury, która z kolei są uzyskiwane przez wywołanie metody <xref:System.Windows.DependencyPropertyHelper.GetValueSource%2A>metody dla właściwości zależności w szczególności.</xref:System.Windows.DependencyPropertyHelper.GetValueSource%2A> </xref:System.Windows.ValueSource>       Każda wartość to wyliczanie wskazuje, że określonego aspektu ogólnych [!INCLUDE[TLA2#tla_winclient](~/add/includes/tla2sharptla-winclient-md.md)] właściwości system był odpowiedzialny za określenie wartość efektywna niektórych zależności wartości właściwości w obiekcie określonej zależności. Aby dowiedzieć się więcej o [!INCLUDE[TLA2#tla_winclient](~/add/includes/tla2sharptla-winclient-md.md)] właściwości systemu i pierwszeństwa, w których właściwość każdego aspektu działania systemu, zobacz [pierwszeństwo wartość właściwości zależności](~/add/includes/ajax-current-ext-md.md).       Wartość domyślna nie jest wartością domyślną wyliczenia."
  syntax:
    content: public enum BaseValueSource
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Default
  id: Default
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Default
  nameWithType: BaseValueSource.Default
  fullName: System.Windows.BaseValueSource.Default
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest wartością domyślną, zgodnie z definicją w metadanych właściwości."
  syntax:
    content: Default
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.DefaultStyle
  id: DefaultStyle
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: DefaultStyle
  nameWithType: BaseValueSource.DefaultStyle
  fullName: System.Windows.BaseValueSource.DefaultStyle
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest z metody ustawiającej w domyślnym stylu. Domyślny styl pochodzi z bieżącego motywu."
  syntax:
    content: DefaultStyle
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.DefaultStyleTrigger
  id: DefaultStyleTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: DefaultStyleTrigger
  nameWithType: BaseValueSource.DefaultStyleTrigger
  fullName: System.Windows.BaseValueSource.DefaultStyleTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest od wyzwalacza w domyślnym stylu. Domyślny styl pochodzi z bieżącego motywu."
  syntax:
    content: DefaultStyleTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.ImplicitStyleReference
  id: ImplicitStyleReference
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ImplicitStyleReference
  nameWithType: BaseValueSource.ImplicitStyleReference
  fullName: System.Windows.BaseValueSource.ImplicitStyleReference
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest odwołanie niejawne (styl został oparty na typie wykrytych lub na podstawie typu). Ta wartość jest zwracany wyłącznie dla właściwości stylu, nie dla właściwości, które są ustawiane za pomocą metody ustawiające lub wyzwalacze takie style."
  syntax:
    content: ImplicitStyleReference
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Inherited
  id: Inherited
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Inherited
  nameWithType: BaseValueSource.Inherited
  fullName: System.Windows.BaseValueSource.Inherited
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest wartość poprzez dziedziczenie wartości właściwości."
  syntax:
    content: Inherited
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Local
  id: Local
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Local
  nameWithType: BaseValueSource.Local
  fullName: System.Windows.BaseValueSource.Local
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest lokalnie ustawione wartości."
  syntax:
    content: Local
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.ParentTemplate
  id: ParentTemplate
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ParentTemplate
  nameWithType: BaseValueSource.ParentTemplate
  fullName: System.Windows.BaseValueSource.ParentTemplate
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Na podstawie szablonu nadrzędnego używany przez element opiera się źródło."
  syntax:
    content: ParentTemplate
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.ParentTemplateTrigger
  id: ParentTemplateTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ParentTemplateTrigger
  nameWithType: BaseValueSource.ParentTemplateTrigger
  fullName: System.Windows.BaseValueSource.ParentTemplateTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest wartość na podstawie wyzwalacza z szablonu nadrzędnego utworzenia elementu."
  syntax:
    content: ParentTemplateTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Style
  id: Style
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Style
  nameWithType: BaseValueSource.Style
  fullName: System.Windows.BaseValueSource.Style
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest z elementu style setter stylu z systemem innym niż motywu."
  syntax:
    content: Style
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.StyleTrigger
  id: StyleTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: StyleTrigger
  nameWithType: BaseValueSource.StyleTrigger
  fullName: System.Windows.BaseValueSource.StyleTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest oparte na wyzwalacza wartość stylu-theme."
  syntax:
    content: StyleTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.TemplateTrigger
  id: TemplateTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: TemplateTrigger
  nameWithType: BaseValueSource.TemplateTrigger
  fullName: System.Windows.BaseValueSource.TemplateTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło jest wartość na podstawie wyzwalacza w szablonie, który jest ze stylu-theme."
  syntax:
    content: TemplateTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Unknown
  id: Unknown
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Unknown
  nameWithType: BaseValueSource.Unknown
  fullName: System.Windows.BaseValueSource.Unknown
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Źródło nie jest znany. Jest to wartość domyślna."
  syntax:
    content: Unknown
    return:
      type: System.Windows.BaseValueSource
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.BaseValueSource.Default
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Default
  nameWithType: BaseValueSource.Default
  fullName: System.Windows.BaseValueSource.Default
- uid: System.Windows.BaseValueSource
  parent: System.Windows
  isExternal: false
  name: BaseValueSource
  nameWithType: BaseValueSource
  fullName: System.Windows.BaseValueSource
- uid: System.Windows.BaseValueSource.DefaultStyle
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: DefaultStyle
  nameWithType: BaseValueSource.DefaultStyle
  fullName: System.Windows.BaseValueSource.DefaultStyle
- uid: System.Windows.BaseValueSource.DefaultStyleTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: DefaultStyleTrigger
  nameWithType: BaseValueSource.DefaultStyleTrigger
  fullName: System.Windows.BaseValueSource.DefaultStyleTrigger
- uid: System.Windows.BaseValueSource.ImplicitStyleReference
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ImplicitStyleReference
  nameWithType: BaseValueSource.ImplicitStyleReference
  fullName: System.Windows.BaseValueSource.ImplicitStyleReference
- uid: System.Windows.BaseValueSource.Inherited
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Inherited
  nameWithType: BaseValueSource.Inherited
  fullName: System.Windows.BaseValueSource.Inherited
- uid: System.Windows.BaseValueSource.Local
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Local
  nameWithType: BaseValueSource.Local
  fullName: System.Windows.BaseValueSource.Local
- uid: System.Windows.BaseValueSource.ParentTemplate
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ParentTemplate
  nameWithType: BaseValueSource.ParentTemplate
  fullName: System.Windows.BaseValueSource.ParentTemplate
- uid: System.Windows.BaseValueSource.ParentTemplateTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ParentTemplateTrigger
  nameWithType: BaseValueSource.ParentTemplateTrigger
  fullName: System.Windows.BaseValueSource.ParentTemplateTrigger
- uid: System.Windows.BaseValueSource.Style
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Style
  nameWithType: BaseValueSource.Style
  fullName: System.Windows.BaseValueSource.Style
- uid: System.Windows.BaseValueSource.StyleTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: StyleTrigger
  nameWithType: BaseValueSource.StyleTrigger
  fullName: System.Windows.BaseValueSource.StyleTrigger
- uid: System.Windows.BaseValueSource.TemplateTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: TemplateTrigger
  nameWithType: BaseValueSource.TemplateTrigger
  fullName: System.Windows.BaseValueSource.TemplateTrigger
- uid: System.Windows.BaseValueSource.Unknown
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Unknown
  nameWithType: BaseValueSource.Unknown
  fullName: System.Windows.BaseValueSource.Unknown
