### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidatorAttribute
  id: SubclassTypeValidatorAttribute
  children:
  - System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  - System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute
  fullName: System.Configuration.SubclassTypeValidatorAttribute
  type: Class
  summary: "Deklaratywnie nakazuje programu .NET Framework do sprawdzania poprawności dla właściwości konfiguracji. Ta klasa nie może być dziedziczona."
  remarks: "Możesz użyć <xref:System.Configuration.IntegerValidatorAttribute>atrybut do dekoracji właściwości konfiguracji.</xref:System.Configuration.IntegerValidatorAttribute> To jest poinstruować programu .NET Framework, można sprawdzić poprawności właściwości przy użyciu atrybutu SubclassTypeValidatorAttribute i przekazywania do niej wartość decorating parametrów.       Atrybuty SubclassTypeValidatorAttribute może dotyczyć tylko dla typów właściwości."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SubclassTypeValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: System.Configuration.SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SubclassTypeValidatorAttribute&quot;> </xref> klasy."
  remarks: "Ten konstruktor służy oparte na atrybutach modelu do upewnij się, że wartość przypisana do właściwości powiązane jest klasą podstawową."
  syntax:
    content: public SubclassTypeValidatorAttribute (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: "Typ klasy podstawowej."
  overload: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  id: BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera typ bazowy obiektu sprawdzania poprawności."
  syntax:
    content: public Type BaseClass { get; }
    return:
      type: System.Type
      description: "Typ podstawowy obiekt sprawdzania poprawności."
  overload: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera moduł weryfikacji wystąpienie atrybutu."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Bieżący <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> wystąpienia."
  overload: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: System.Configuration.SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
