### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpListenerTimeoutsElement
  id: HttpListenerTimeoutsElement
  children:
  - System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  - System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  - System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  - System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  - System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  - System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  - System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  - System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  langs:
  - csharp
  name: HttpListenerTimeoutsElement
  nameWithType: HttpListenerTimeoutsElement
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement
  type: Class
  summary: "Reprezentuje <xref href=&quot;System.Net.HttpListener&quot;> </xref> element limitów czasu w pliku konfiguracji. Ta klasa nie może być dziedziczona."
  remarks: "Element limitów czasu definiuje dafault granicach limitu czasu połączenia dla <xref:System.Net.HttpListener>wystąpienia.</xref:System.Net.HttpListener>"
  syntax:
    content: 'public sealed class HttpListenerTimeoutsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: HttpListenerTimeoutsElement()
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Net.Configuration.HttpListenerTimeoutsElement&quot;> </xref> klasy."
  syntax:
    content: public HttpListenerTimeoutsElement ();
    parameters: []
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  id: DrainEntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera w sekundach czas dozwolony dla <xref href=&quot;System.Net.HttpListener&quot;> </xref> do opróżnienia treści jednostki podtrzymania połączenia."
  remarks: "Keep-Alive połączenia i po aplikacji wysłał odpowiedź na żądanie i przed żądaniem całkowicie Odebrano treść jednostki <xref:System.Net.HttpListener>uruchamia opróżnianie pozostałej części treści jednostki do innego potencjalnie potokowe żądania od klienta.</xref:System.Net.HttpListener> Jeśli czas do opróżnienia pozostałych treści jednostki przekracza dozwolony okres jest upłynął limit czasu połączenia."
  syntax:
    content: public TimeSpan DrainEntityBody { get; }
    return:
      type: System.TimeSpan
      description: "Zwraca <xref:System.TimeSpan>.</xref:System.TimeSpan>       W sekundach czas dozwolony dla <xref href=&quot;System.Net.HttpListener&quot;> </xref> do opróżnienia treści jednostki podtrzymania połączenia."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  id: EntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera w sekundach czas dozwolony dla treści jednostki żądania do celu."
  remarks: "<xref:System.Net.HttpListener>Włącza ten czasomierz, gdy żądanie zawiera treść jednostki.</xref:System.Net.HttpListener> Wygaśnięciu czasomierza początkowo ma ustawioną wartość skonfigurowana. Gdy <xref:System.Net.HttpListener>odbiera oznaczeń dodatkowe dane na żądanie, następuje zresetowanie czasomierza umożliwiają połączenie inny interwał.</xref:System.Net.HttpListener>"
  syntax:
    content: public TimeSpan EntityBody { get; }
    return:
      type: System.TimeSpan
      description: "Zwraca <xref:System.TimeSpan>.</xref:System.TimeSpan>       Czas w sekundach, dozwolone dla treści jednostki żądania do celu."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  id: HeaderWait
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera w sekundach czas dozwolony dla <xref href=&quot;System.Net.HttpListener&quot;> </xref> przeanalizować nagłówka żądania."
  remarks: "Tego limitu czasu są wymuszane tylko po pierwsze żądanie połączenia jest kierowany do <xref:System.Net.HttpListener>.</xref:System.Net.HttpListener>       System nie może określić kolejki żądań lub grupy adresów URL, żądanie z którym skojarzony jest dopóki przeanalizowaniu nagłówki. W związku z tym <xref:System.Net.HttpListener>wymusza domyślnie <xref:System.Net.HttpListenerTimeoutManager.HeaderWait%2A>czasomierza na pierwsze żądanie połączenia.</xref:System.Net.HttpListenerTimeoutManager.HeaderWait%2A> </xref:System.Net.HttpListener> Kolejne żądania połączenia Keep-Alive użyje wartości ustawionej tej właściwości."
  syntax:
    content: public TimeSpan HeaderWait { get; }
    return:
      type: System.TimeSpan
      description: "Zwraca <xref:System.TimeSpan>.</xref:System.TimeSpan>       W sekundach czas dozwolony dla <xref href=&quot;System.Net.HttpListener&quot;> </xref> przeanalizować nagłówka żądania."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  id: IdleConnection
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera w sekundach czas dozwolony dla bezczynnego połączenia."
  remarks: "Tego limitu czasu są wymuszane tylko po pierwsze żądanie połączenia jest kierowany do <xref:System.Net.HttpListener>.</xref:System.Net.HttpListener>       System nie może określić kolejki żądań lub grupy adresów URL, żądanie z którym skojarzony jest dopóki przeanalizowaniu nagłówki. W związku z tym <xref:System.Net.HttpListener>wymusza domyślnie <xref:System.Net.HttpListenerTimeoutManager.IdleConnection%2A>czasomierza na pierwsze żądanie połączenia.</xref:System.Net.HttpListenerTimeoutManager.IdleConnection%2A> </xref:System.Net.HttpListener> Kolejne żądania połączenia Keep-Alive użyje wartości ustawionej tej właściwości."
  syntax:
    content: public TimeSpan IdleConnection { get; }
    return:
      type: System.TimeSpan
      description: "Zwraca <xref:System.TimeSpan>.</xref:System.TimeSpan>       Czas w sekundach, dozwolone dla bezczynnego połączenia."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  id: MinSendBytesPerSecond
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera stopa minimalna wysyłania w bajtach na sekundę, dla odpowiedzi."
  syntax:
    content: public long MinSendBytesPerSecond { get; }
    return:
      type: System.Int64
      description: "Zwraca <xref:System.Int64>.</xref:System.Int64>       Minimalna szybkość wysyłania, w bajtach na sekundę, dla odpowiedzi."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  id: RequestQueue
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  langs:
  - csharp
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Pobiera czas w sekundach, dozwoloną dla żądania w kolejce żądań przed <xref href=&quot;System.Net.HttpListener&quot;> </xref> przejmuje on."
  syntax:
    content: public TimeSpan RequestQueue { get; }
    return:
      type: System.TimeSpan
      description: "Zwraca <xref:System.TimeSpan>.</xref:System.TimeSpan>       Czas w sekundach, dozwoloną dla żądania w kolejce żądań przed <xref href=&quot;System.Net.HttpListener&quot;> </xref> przejmuje on."
  overload: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HttpListenerTimeoutsElement()
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HttpListenerTimeoutsElement()
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
  fullName: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.#ctor*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HttpListenerTimeoutsElement
  nameWithType: HttpListenerTimeoutsElement.HttpListenerTimeoutsElement
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.DrainEntityBody*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: DrainEntityBody
  nameWithType: HttpListenerTimeoutsElement.DrainEntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.EntityBody*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: EntityBody
  nameWithType: HttpListenerTimeoutsElement.EntityBody
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.HeaderWait*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: HeaderWait
  nameWithType: HttpListenerTimeoutsElement.HeaderWait
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.IdleConnection*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: IdleConnection
  nameWithType: HttpListenerTimeoutsElement.IdleConnection
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.MinSendBytesPerSecond*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: MinSendBytesPerSecond
  nameWithType: HttpListenerTimeoutsElement.MinSendBytesPerSecond
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.Properties*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HttpListenerTimeoutsElement.Properties
- uid: System.Net.Configuration.HttpListenerTimeoutsElement.RequestQueue*
  parent: System.Net.Configuration.HttpListenerTimeoutsElement
  isExternal: false
  name: RequestQueue
  nameWithType: HttpListenerTimeoutsElement.RequestQueue
