### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthenticationCredentials
  id: FormsAuthenticationCredentials
  children:
  - System.Web.Configuration.FormsAuthenticationCredentials.#ctor
  - System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  - System.Web.Configuration.FormsAuthenticationCredentials.Properties
  - System.Web.Configuration.FormsAuthenticationCredentials.Users
  langs:
  - csharp
  name: FormsAuthenticationCredentials
  nameWithType: FormsAuthenticationCredentials
  fullName: System.Web.Configuration.FormsAuthenticationCredentials
  type: Class
  summary: "Określa poświadczenia użytkownika dla aplikacji ASP.NET, korzystających z uwierzytelniania opartego na formularzu."
  remarks: "Klasa FormsAuthenticationCredentials umożliwia programowo modyfikacji i dostępu `credentials` elementu `forms` sekcji `authentication` sekcji pliku konfiguracji. Ten typ jest częścią grupy, która zawiera <xref:System.Web.Configuration.FormsAuthenticationConfiguration>, <xref:System.Web.Configuration.FormsAuthenticationUserCollection>i <xref:System.Web.Configuration.FormsAuthenticationUser>typów.</xref:System.Web.Configuration.FormsAuthenticationUser> </xref:System.Web.Configuration.FormsAuthenticationUserCollection> </xref:System.Web.Configuration.FormsAuthenticationConfiguration> Z wyjątkiem typu kolekcji wszystkich innych bezpośrednio wpływa na podstawowych tagów konfiguracji.      > [!NOTE] > FormsAuthenticationCredentials można zapisać informacji w sekcji pliku konfiguracji zgodnie z ograniczeniami zdefiniowany przez <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> pokrewne Komunikat o błędzie wygenerowane przez analizator spowoduje próbę zapisu w pliku konfiguracji na poziomie nie są dozwolone w hierarchii. Jednak można użyć tej klasy można odczytać informacji o konfiguracji na dowolnym poziomie w hierarchii. Dla bezpieczeństwa i skalowalność zaleca się użyć repozytorium zewnętrznego, takie jak bazy danych, aby zachować poświadczeń użytkowników."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `credentials` section, which can also be accessed as members of the FormsAuthenticationCredentials class.  \n  \n The following configuration file example shows how to specify values declaratively for the `credentials` section.  \n  \n```  \n<credentials passwordFormat=\"SHA1\">  \n  <user name=\"aspnetuser1\"  \n    password=\"5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8\"/>  \n  <user name=\"aspnetuser2\"  \n    password=\"E38AD214943DAAD1D64C102FAEC29DE4AFE9DA3D\"/>  \n</credentials>  \n```  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security, it is recommended that you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (http://msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n The following code example demonstrates how to use the FormsAuthenticationCredentials class.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#1](~/add/codesnippet/visualbasic/t-system.web.configurati_12_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#1](~/add/codesnippet/csharp/t-system.web.configurati_12_1.cs)]"
  syntax:
    content: 'public sealed class FormsAuthenticationCredentials : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: FormsAuthenticationCredentials()
  nameWithType: FormsAuthenticationCredentials.FormsAuthenticationCredentials()
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.FormsAuthenticationCredentials()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.FormsAuthenticationCredentials&quot;> </xref> klasy."
  remarks: ''
  example:
  - "The following code example shows how to create a <xref:System.Web.Configuration.FormsAuthenticationCredentials> object.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#2](~/add/codesnippet/visualbasic/m-system.web.configurati_2_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#2](~/add/codesnippet/csharp/m-system.web.configurati_2_1.cs)]"
  syntax:
    content: public FormsAuthenticationCredentials ();
    parameters: []
  overload: System.Web.Configuration.FormsAuthenticationCredentials.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  id: PasswordFormat
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: PasswordFormat
  nameWithType: FormsAuthenticationCredentials.PasswordFormat
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia format hasła."
  remarks: ''
  example:
  - "The following code example shows how to access the PasswordFormat property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationCredentials> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/visualbasic/p-system.web.configurati_386_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/csharp/p-system.web.configurati_386_1.cs)]"
  syntax:
    content: public System.Web.Configuration.FormsAuthPasswordFormat PasswordFormat { get; set; }
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "Jeden z <xref href=&quot;System.Web.Configuration.FormsAuthPasswordFormat&quot;> </xref> wartości."
  overload: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Properties
  id: Properties
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: Properties
  nameWithType: FormsAuthenticationCredentials.Properties
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.FormsAuthenticationCredentials.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Users
  id: Users
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: Users
  nameWithType: FormsAuthenticationCredentials.Users
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Users
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera nazwy użytkowników i hasła poświadczeń."
  remarks: ''
  example:
  - "The following code example shows how to use the Users property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationCredentials> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#4](~/add/codesnippet/visualbasic/p-system.web.configurati_181_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#4](~/add/codesnippet/csharp/p-system.web.configurati_181_1.cs)]"
  syntax:
    content: public System.Web.Configuration.FormsAuthenticationUserCollection Users { get; }
    return:
      type: System.Web.Configuration.FormsAuthenticationUserCollection
      description: "A <xref href=&quot;System.Web.Configuration.FormsAuthenticationUserCollection&quot;> </xref> zawierający nazwy użytkowników i hasła poświadczeń."
  overload: System.Web.Configuration.FormsAuthenticationCredentials.Users*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FormsAuthenticationCredentials.#ctor
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: FormsAuthenticationCredentials()
  nameWithType: FormsAuthenticationCredentials.FormsAuthenticationCredentials()
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.FormsAuthenticationCredentials()
- uid: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: PasswordFormat
  nameWithType: FormsAuthenticationCredentials.PasswordFormat
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
- uid: System.Web.Configuration.FormsAuthPasswordFormat
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthPasswordFormat
  nameWithType: FormsAuthPasswordFormat
  fullName: System.Web.Configuration.FormsAuthPasswordFormat
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Properties
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationCredentials.Properties
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Users
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Users
  nameWithType: FormsAuthenticationCredentials.Users
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Users
- uid: System.Web.Configuration.FormsAuthenticationUserCollection
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthenticationUserCollection
  nameWithType: FormsAuthenticationUserCollection
  fullName: System.Web.Configuration.FormsAuthenticationUserCollection
- uid: System.Web.Configuration.FormsAuthenticationCredentials.#ctor*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: FormsAuthenticationCredentials
  nameWithType: FormsAuthenticationCredentials.FormsAuthenticationCredentials
- uid: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: PasswordFormat
  nameWithType: FormsAuthenticationCredentials.PasswordFormat
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Properties*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationCredentials.Properties
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Users*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Users
  nameWithType: FormsAuthenticationCredentials.Users
