### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadManager
  id: IApplicationPreloadManager
  children:
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  langs:
  - csharp
  name: IApplicationPreloadManager
  nameWithType: IApplicationPreloadManager
  fullName: System.Web.Hosting.IApplicationPreloadManager
  type: Interface
  summary: "Udostępnia metody używane do wywołania tej funkcji wstępnego ładowania aplikacji w programie ASP.NET [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("AE54F424-71BC-4da5-AA2F-8C0CD53496FC")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadManager
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  id: SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Wywoływane przez [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] powiadomiono ASP.NET, czy należy wstępnie załadowanych aplikacji."
  syntax:
    content: public void SetApplicationPreloadState (string context, string appId, bool enabled);
    parameters:
    - id: context
      type: System.String
      description: "Kontekst aplikacji."
    - id: appId
      type: System.String
      description: "Unikatowy identyfikator aplikacji."
    - id: enabled
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Aby wskazać, że aplikacja powinna załadowane; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  id: SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Wywołania [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] Aby uzyskać informacje, które jest wymagane w celu wstępnego załadowania aplikacji."
  remarks: "Usługi IIS wywołują ASP.NET za pośrednictwem tego interfejsu, podając odwołanie do obiektu, który implementuje <xref:System.Web.Hosting.IApplicationPreloadUtil>interfejsu.</xref:System.Web.Hosting.IApplicationPreloadUtil> Program ASP.NET używa interfejsu później przeprowadzić wywołanie zwrotne do usług IIS, aby uzyskać informacje wstępnego ładowania dla poszczególnych aplikacji."
  syntax:
    content: public void SetApplicationPreloadUtil (System.Web.Hosting.IApplicationPreloadUtil preloadUtil);
    parameters:
    - id: preloadUtil
      type: System.Web.Hosting.IApplicationPreloadUtil
      description: "Dojście do niezarządzanego interfejsu w [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] ASP.NET tego wywołania można uzyskać informacji o."
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
- uid: System.Web.Hosting.IApplicationPreloadUtil
  parent: System.Web.Hosting
  isExternal: false
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil
