### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.ChannelPoolSettings
  id: ChannelPoolSettings
  children:
  - System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  - System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  langs:
  - csharp
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings
  fullName: System.ServiceModel.Channels.ChannelPoolSettings
  type: Class
  summary: "Określa przydziały dla kanałów, które należą do puli kanałów używanych przez punkt końcowy usługi."
  remarks: "Przydziały są używane jako mechanizm zasad zapobiegających zużycie zasobów nadmierne. Zapobiegają one przez ataków typu odmowa usługi (DOS), które są złośliwe lub przypadkowe. Podczas ustawiania kanału przydziały w niestandardowym kanale, należy użyć tej klasy.       ChannelPoolSettings określa trzy przydziały:- <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>określić maksymalny przedział czasu, dla którego kanałów w puli może być bezczynne, zanim zostanie zamknięty.</xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>określić przedział czasu, po którym kanał, gdy zwrócony do puli, jest zamknięty.</xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>Aby określić maksymalną liczbę kanałów, które mogą być przechowywane w puli dla każdego zdalnego punktu końcowego.</xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>"
  syntax:
    content: public class ChannelPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Channels.ChannelPoolSettings&quot;> </xref> klasy."
  remarks: "Ustaw wartości domyślne są:- <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>: 2 minut.</xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>: 10 minut.</xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>: 10 kanałów.</xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>       Te wartości domyślnych przydziału są oparte na konserwatywnie niewielkie alokacji zasobów, które są odpowiednie dla środowisk projektowych oraz instalacji małe scenariusze. Administratorzy usługi przejrzeć przydziały kanału i dostrajania poszczególne wartości przydziału, jeśli instalacja kończy się zasoby lub połączeń są ograniczeni niezależnie od dostępności dodatkowych zasobów."
  syntax:
    content: public ChannelPoolSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Pobiera lub ustawia maksymalny przedział czasu, dla którego kanałów w puli może być bezczynne, zanim zostanie zamknięty."
  remarks: "Przydział IdleTimeout umożliwia ograniczenie liczby ataków typu odmowa usługi (DOS) na serwerze, które są oparte na zajmowania zasobów przez dłuższy czas. Na komputerze klienckim ustawienie poprawną wartość może zwiększyć niezawodność nawiązywać połączenia z usługą. Wartość domyślna jest oparta na konserwatywnie niewielkie alokacji zasobów. Jest ona odpowiednia dla Środowisko deweloperskie i scenariusze małych instalacji. Administratorzy usługi powinni sprawdzić wartość, jeśli instalacja kończy się zasoby lub połączeń są ograniczeni niezależnie od dostępności dodatkowych zasobów."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "<xref:System.TimeSpan>, Który określa maksymalny przedział czasu, dla którego kanałów w puli może być bezczynne, zanim zostanie zamknięty.</xref:System.TimeSpan> Wartość domyślna to 2 minuty."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wartość jest mniejsza niż zero lub większa niż T:System.Int32.MaxValue w milisekundach."
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Pobiera lub ustawia okres istnienia kanału, po upływie którego jest ono zamknięte."
  remarks: "Przydział LeaseTimeout służy do integracji z usługą równoważenia obciążenia i poprawa niezawodności. Wartość domyślna jest oparta na zachowawcze alokacji zasobów. Jest ona odpowiednia dla Środowisko deweloperskie i scenariusze małych instalacji. Administratorzy usługi powinni sprawdzić wartość, jeśli instalacja kończy się zasoby lub połączeń są ograniczeni niezależnie od dostępności dodatkowych zasobów."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>, który określa okres istnienia kanału, po upływie którego jest ono zamknięte.</xref:System.TimeSpan> Wartość domyślna to 10 minut."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wartość jest mniejsza od zera."
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  id: MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Pobiera lub ustawia maksymalną liczbę kanałów nawiązywania połączenia zdalne punkty końcowe, które mogą być inicjowane przez usługę."
  remarks: "Przydział MaxOutboundChannelsPerEndpoint Ustawia limity pamięci podręcznej na serwerze i kliencie i jest używany do poprawy niezawodności. Wartość domyślna jest oparta na konserwatywnie niewielkie alokacji zasobów, które jest odpowiednie dla środowiska programowania i scenariusze instalacji małych. Administratorzy usługi powinni sprawdzić wartość, jeśli instalacja kończy się zasoby lub połączeń są ograniczeni niezależnie od dostępności dodatkowych zasobów."
  syntax:
    content: public int MaxOutboundChannelsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Dodatnia liczba całkowita, która określa maksymalną liczbę kanałów do zdalnego punktu końcowego w puli, który może być inicjowane przez usługę. Wartość domyślna to 10 kanałów."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Wartość jest mniejsza od zera."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings.ChannelPoolSettings
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
