### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.AppSettingsExpressionEditor
  id: AppSettingsExpressionEditor
  children:
  - System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  - System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  - System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  langs:
  - csharp
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor
  type: Class
  summary: "Udostępnia właściwości i metod do oceny i edytowania wyrażenie ustawienie aplikacji w pliku konfiguracji w czasie projektowania."
  remarks: "Jest pochodną klasy AppSettingsExpressionEditor <xref:System.Web.UI.Design.ExpressionEditor>klasy i udostępnia implementację dla oceny i kojarzenie odwołanie do ustawienia aplikacji z właściwości formantu w czasie projektowania.</xref:System.Web.UI.Design.ExpressionEditor> Na przykład można powiązać wartości właściwości formantu wyrażenie ustawienie aplikacji `AppSettings:mySettingKeyName`, co oznacza, że ustawiono wartość właściwości formantu przy użyciu `mySettingKeyName` wartość w `appSettings` sekcji pliku konfiguracji sieci Web.       Host wizualnego projektanta, takich jak [!INCLUDE[vsprvslong](~/add/includes/ajax-current-ext-md.md)], używa klasy AppSettingsExpressionEditor, aby wybrać ustawienie aplikacji z `appSettings` sekcji konfiguracji, a następnie oblicza wyrażenie wybranego dla renderowania w czasie projektowania.       Po przejściu do <xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A>Właściwości formantu w siatce właściwości czasu projektowania, Projektant wizualny Wyświetla okno dialogowe zestawu wyrażeń, które zapewniają wartość czasu wykonywania właściwości formantu.</xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A> Można wybrać typ wyrażenia na podstawie listy prefiksu wyrażenia. Po wybraniu **AppSettings** prefiksu wyrażenia z listy visual host projektanta używa skojarzony <xref:System.Web.UI.Design.ExpressionEditorSheet>obiekt, aby zapewnić funkcje edycji czasu projektowania `appSettings` wyrażeń i używa metody AppSettingsExpressionEditor do oceny i przekonwertować ciągu wyrażenia oparte na składni wyrażenia ustawienie aplikacji.</xref:System.Web.UI.Design.ExpressionEditorSheet> Na podstawie wyniku obliczane wyrażenie visual host projektanta przypisanie wartości właściwości, które mają być renderowane na powierzchni projektu kontroli.       <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>Właściwość dla obiekt AppSettingsExpressionEditor zwraca ciąg `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> <xref:System.Web.Compilation.AppSettingsExpressionBuilder>Klasy jest skojarzone z prefiksu wyrażenia `AppSettings` i implementacji AppSettingsExpressionEditor.</xref:System.Web.Compilation.AppSettingsExpressionBuilder>       <xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A>Metody ocenia wyrażenie ciągu ustawienia aplikacji wejściowej.</xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A> <xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>Metoda zwraca <xref:System.Web.UI.Design.ExpressionEditorSheet>wdrożenia, który umożliwia wprowadzanie i edytowanie wyrażeń ustawienie aplikacji.</xref:System.Web.UI.Design.ExpressionEditorSheet> </xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>"
  example:
  - "The following code example demonstrates how to bind the <xref:System.Web.UI.WebControls.HyperLink.NavigateUrl%2A> property of a <xref:System.Web.UI.WebControls.HyperLink> control to an application setting expression using the AppSettingsExpressionEditor object.  \n  \n1.  In a Web Forms project, add `MyHyperLinkSetting` to the `<appSettings>` section of the web.config file.  \n  \n     [!code-xml[ControlsUsingExpressions#5](~/add/codesnippet/xml/t-system.web.ui.design.a_1.xml)]  \n  \n2.  On a Web Forms page, add a <xref:System.Web.UI.WebControls.HyperLink> control.  \n  \n3.  For the `Hyperlink` control, in Properties, click **Expressions**, and then click the ellipsis button (**...**).  \n  \n     The `<Hyperlinkname>`**Expression** dialog box appears.  \n  \n4.  Under **Bindable properties**, click **NavigateUrl**, in the **Expression type** list, click **AppSettings**, and then under **Expression properties**, in the **AppSetting** box, type **MyHyperLinkSetting**.  \n  \n The visual designer uses the AppSettingsExpressionEditor to assign the expression for the `NavigateUrl` property.  \n  \n The following aspx source shows an example of a property value set using an application setting expression.  \n  \n [!code-vb[ControlsUsingExpressions#2](~/add/codesnippet/visualbasic/t-system.web.ui.design.a_2.aspx)]\n [!code-cs[ControlsUsingExpressions#2](~/add/codesnippet/csharp/t-system.web.ui.design.a_2.aspx)]\n [!code-xml[ControlsUsingExpressions#2](~/add/codesnippet/xml/t-system.web.ui.design.a_2.xml)]"
  syntax:
    content: 'public class AppSettingsExpressionEditor : System.Web.UI.Design.ExpressionEditor'
  inheritance:
  - System.Object
  - System.Web.UI.Design.ExpressionEditor
  implements: []
  inheritedMembers:
  - System.Web.UI.Design.ExpressionEditor.ExpressionPrefix
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.String,System.IServiceProvider)
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.Type,System.IServiceProvider)
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  id: '#ctor'
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  type: Constructor
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.UI.Design.AppSettingsExpressionEditor&quot;> </xref> klasy."
  remarks: "Wystąpienie <xref:System.Web.UI.Design.AppSettingsExpressionEditor>Klasa jest skonfigurowana przez klasę podstawową razem z <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>ustawioną właściwość `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> </xref:System.Web.UI.Design.AppSettingsExpressionEditor>"
  syntax:
    content: public AppSettingsExpressionEditor ();
    parameters: []
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  id: EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Oblicza wyrażenie ciągu ustawienia aplikacji i zawiera wartość czasu projektowania dla właściwości formantu."
  remarks: "Metoda EvaluateExpression wyszukuje określoną przez ustawienie aplikacji `expression`, a następnie zwraca wartość ustawienia aplikacji.       Projektant wizualny używa metody EvaluateExpression do oceny wyrażenia ustawienia aplikacji i podaj wartość czasu projektowania dla właściwości skojarzonym formancie. Projektant wizualny wywołuje metodę EvaluateExpression z ciągiem wyrażenia, a wynik obliczane wyrażenie jest używane do przypisywania formantu wartości właściwości, które mają być renderowane na powierzchni projektu.       W czasie wykonywania, używa analizatora strony <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>i <xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A>metody odpowiadającego <xref:System.Web.Compilation.AppSettingsExpressionBuilder>implementacji można obliczyć wyrażenia i podaj wartość czasu wykonywania właściwości skojarzonym formancie.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>"
  syntax:
    content: public override object EvaluateExpression (string expression, object parseTimeData, Type propertyType, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Aplikacji ustawienie wyrażenia ciągu w celu oceny. `expression`nie ma <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> prefiksu wyrażenia."
    - id: parseTimeData
      type: System.Object
      description: "Obiekt zawierający dodatkowe informacje podczas analizowania, oceny `expression`."
    - id: propertyType
      type: System.Type
      description: "Typ właściwości formantu."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "Implementacja dostawcy usługi dostarczone przez hosta projektanta, używany do uzyskania dodatkowych usług czasu projektowania."
    return:
      type: System.Object
      description: "Zawiera odwołanie do obiektu <code> expression </code>, jeśli Obliczanie wyrażenia zakończyło się pomyślnie; w przeciwnym razie <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  id: GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Zwraca wyrażenie arkusza edytora wyrażeń ustawienie aplikacji."
  remarks: "Metoda GetExpressionEditorSheet zwraca prosty edytor implementacji arkusza używa jednego ciągu wejściowego do tworzenia wyrażenia."
  syntax:
    content: public override System.Web.UI.Design.ExpressionEditorSheet GetExpressionEditorSheet (string expression, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Ciąg wyrażenia, ustaw dla właściwości formantu, używaną do inicjalizacji arkusza edytora wyrażeń. `expression`nie ma <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> prefiksu wyrażenia."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "Implementacja dostawcy usługi dostarczone przez hosta projektanta, używany do uzyskania dodatkowych usług czasu projektowania."
    return:
      type: System.Web.UI.Design.ExpressionEditorSheet
      description: "<xref href=&quot;System.Web.UI.Design.ExpressionEditorSheet&quot;> </xref> Implementację, która definiuje właściwości wyrażenie ustawienia aplikacji."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.ExpressionEditor
  isExternal: false
  name: System.Web.UI.Design.ExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
- uid: System.Web.UI.Design.ExpressionEditorSheet
  parent: System.Web.UI.Design
  isExternal: false
  name: ExpressionEditorSheet
  nameWithType: ExpressionEditorSheet
  fullName: System.Web.UI.Design.ExpressionEditorSheet
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet
