### YamlMime:ManagedReference
items:
- uid: System.Configuration.IPersistComponentSettings
  id: IPersistComponentSettings
  children:
  - System.Configuration.IPersistComponentSettings.LoadComponentSettings
  - System.Configuration.IPersistComponentSettings.ResetComponentSettings
  - System.Configuration.IPersistComponentSettings.SaveComponentSettings
  - System.Configuration.IPersistComponentSettings.SaveSettings
  - System.Configuration.IPersistComponentSettings.SettingsKey
  langs:
  - csharp
  name: IPersistComponentSettings
  nameWithType: IPersistComponentSettings
  fullName: System.Configuration.IPersistComponentSettings
  type: Interface
  summary: "Definiuje standardowych funkcji formantów lub bibliotek, które przechowują i pobierają ustawienia aplikacji."
  remarks: "Zazwyczaj można dodać obsługę ustawienia aplikacji do aplikacji przez utworzenie klasy otoki ustawienia, która jest pochodną <xref:System.Configuration.ApplicationSettingsBase>, a następnie dodaj specjalne właściwości do tej klasy.</xref:System.Configuration.ApplicationSettingsBase> Jednak ta metoda nie wystarczająco hermetyzować ustawienia aplikacji dla formantu tak, aby jego kontenera jest chroniony przed szczegóły. Interfejs użyciu elementu IPersistComponentSettings zapewnia aplikacji z interfejsem standardowa do przekazywania żądań zmiany stanu ustawienia aplikacji do modułu biblioteki, składnika lub kontrolki. Czasu projektowania narzędzi również są zależne od prawidłowego zarządzania formanty i składniki w tym interfejsie."
  syntax:
    content: public interface IPersistComponentSettings
  implements: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings
  id: LoadComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: LoadComponentSettings()
  nameWithType: IPersistComponentSettings.LoadComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.LoadComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Odczytuje formantu ustawienia aplikacji do ich odpowiednich właściwości i aktualizuje stan formantu."
  remarks: "Ogólnie rzecz biorąc, metoda LoadComponentSettings wykonuje dwie operacje niezbędne:-ta powoduje, że każde wystąpienie ustawień aplikacji zawarte przez formant do odświeżenia wartości właściwości ustawień aplikacji zwykle przez wywołanie metody ich <xref:System.Configuration.ApplicationSettingsBase.Reload%2A>metody.</xref:System.Configuration.ApplicationSettingsBase.Reload%2A>      -Zgodnie z wymaganiami aktualizuje tych właściwości ogólnych, które są zależne od tych ustawień wczytywanych właściwości. Na przykład, jeśli zawiera klasy ustawienia `location` ustawienia właściwości LoadComponentSettings powinien upewnij się, że kontrolki <xref:System.Windows.Forms.Control.Location%2A>Właściwości jest aktualizowana w celu odzwierciedlenia ustawienie wczytywanych.</xref:System.Windows.Forms.Control.Location%2A>"
  syntax:
    content: public void LoadComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.LoadComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings
  id: ResetComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: ResetComponentSettings()
  nameWithType: IPersistComponentSettings.ResetComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.ResetComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Resetuje właściwości ustawień kontroli aplikacji do wartości domyślnych."
  remarks: "Implementacja metody ResetComponentSettings zwykle wymaga <xref:System.Configuration.ApplicationSettingsBase.Reset%2A>metody dla każdego wystąpienia klasy ustawienia aplikacji zawiera.</xref:System.Configuration.ApplicationSettingsBase.Reset%2A>"
  syntax:
    content: public void ResetComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.ResetComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings
  id: SaveComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SaveComponentSettings()
  nameWithType: IPersistComponentSettings.SaveComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.SaveComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Utrzymuje właściwości ustawień kontroli aplikacji."
  remarks: "Metoda SaveComponentSettings zapisuje wartości właściwości ustawień kontroli aplikacji do magazynu danych. Dane magazynu i serializacja techniki używanych przez metodę zależy od ustawień dostawcy skojarzonego z każdej klasy ustawień za pośrednictwem <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> Wybór dostawcy ustawień można zastąpić przy użyciu <xref:System.Configuration.ISettingsProviderService>interfejsu.</xref:System.Configuration.ISettingsProviderService>      > [!NOTE] > Jeśli <xref:System.Configuration.IPersistComponentSettings.SaveSettings%2A>właściwość jest `true`, kontrolki powinny wywoływać SaveComponentSettings jego własnej <xref:System.Windows.Forms.Control.Dispose%2A>metody, aby automatycznie przechowywania danych konfiguracji formantu przed zakończeniem aplikacji.</xref:System.Windows.Forms.Control.Dispose%2A> </xref:System.Configuration.IPersistComponentSettings.SaveSettings%2A>"
  syntax:
    content: public void SaveComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.SaveComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SaveSettings
  id: SaveSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
  fullName: System.Configuration.IPersistComponentSettings.SaveSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera lub ustawia wartość wskazującą, czy formant automatycznie ma utrwalić ustawienia właściwości aplikacji."
  remarks: "Jeśli formant zawiera dane konfiguracji, zazwyczaj będzie zachować te dane w odpowiedzi na jawnym wywołaniem <xref:System.Configuration.IPersistComponentSettings.SaveComponentSettings%2A>metody lub czasami niejawnie podczas formantu <xref:System.Windows.Forms.Control.Dispose%2A>wywołania metody.</xref:System.Windows.Forms.Control.Dispose%2A> </xref:System.Configuration.IPersistComponentSettings.SaveComponentSettings%2A> Właściwość SaveSettings Określa, czy formant automatycznie będzie się powtarzał jego dane konfiguracji po jej usunięciu.       Wartość domyślna SaveSettings zależy od implementacji formantu. Dokumentacja dla kontrolki powinna wskazywać, czy używa ustawienia aplikacji, jakie dane jest trwały i jest wartością domyślną właściwości SaveSettings."
  example:
  - "The following code example shows the proper way for a control to check the value of the SaveSettings property before it attempts to automatically persist its configuration data.  \n  \n `protected override void Dispose( bool disposing ) {`  \n  \n `if(disposing) {`  \n  \n `try {`  \n  \n `if (SaveSettings) {`  \n  \n `SaveComponentSettings();`  \n  \n `}`  \n  \n `}`  \n  \n `finally {`  \n  \n `//...`  \n  \n `}`  \n  \n `}`"
  syntax:
    content: public bool SaveSettings { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli formant ma automatycznie utrwalić stanu; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.IPersistComponentSettings.SaveSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SettingsKey
  id: SettingsKey
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
  fullName: System.Configuration.IPersistComponentSettings.SettingsKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Pobiera lub ustawia wartość klucz Ustawienia aplikacji dla bieżącego wystąpienia formantu."
  remarks: "Właściwość SettingsKey służy do odróżniania grupy właściwości ustawień aplikacji, gdy istnieje wiele wystąpień tej samej klasy otoki. Na przykład jeśli formant zawiera klasy otoki skojarzony, następnie umieszczenie wiele wystąpień tej samej kontrolki w tej samej aplikacji zazwyczaj powodują wiele wystąpień klasy otoki. Ustawienia klucz jest wymagany tylko wtedy, gdy dane konfiguracyjne różni się na zasadzie poszczególnych wystąpień; na przykład lokalizacja dynamicznie określonym położeniem kontrolki.       Mają zastosowanie następujące reguły ogólne użycie SettingsKey:-formantu, takie jak dowolnej klasy może zawierać zero lub więcej klasy ustawienia aplikacji, pochodną <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> Każda klasa ustawień zawiera własną <xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>właściwość, co pomaga odróżnić wiele wystąpień tej klasy.</xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>      -Formant Rozdziel jej dane na wystąpienie i jego danych udostępnionych klasom różne ustawienia.      — Dla formantu o żadnych danych konfiguracji poszczególnych wystąpień `get` powinna domyślnie akcesor właściwości SettingsKey <xref:System.Windows.Forms.Control.Name%2A>formantu.</xref:System.Windows.Forms.Control.Name%2A> W większości przypadków nazwa formantu jest unikatowa w obrębie aplikacji. Jeśli formant zawiera tylko udostępnione dane konfiguracji `get` powinna domyślnie `null`.      - `set` Metody dostępu dla tej właściwości powinny być implementowane w celu rozróżnienia między klasami ustawień zawierająca poszczególnych wystąpień i dane konfiguracji udostępnionej. Dla każdej klasy ustawienia zawierającego dane dotyczące poszczególnych wystąpień `set` należy po prostu przekazywanego do <xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>Właściwości klasy ustawienia.</xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName> Dla klas ustawienia zawierające danych udostępnionych `set` powinien nie wykonuj akcji dla tej klasy ustawienia."
  syntax:
    content: public string SettingsKey { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>zawierający klucz Ustawienia dla bieżącego wystąpienia formantu.</xref:System.String>"
  overload: System.Configuration.IPersistComponentSettings.SettingsKey*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: LoadComponentSettings()
  nameWithType: IPersistComponentSettings.LoadComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.LoadComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: ResetComponentSettings()
  nameWithType: IPersistComponentSettings.ResetComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.ResetComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveComponentSettings()
  nameWithType: IPersistComponentSettings.SaveComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.SaveComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.SaveSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
  fullName: System.Configuration.IPersistComponentSettings.SaveSettings
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IPersistComponentSettings.SettingsKey
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
  fullName: System.Configuration.IPersistComponentSettings.SettingsKey
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: LoadComponentSettings
  nameWithType: IPersistComponentSettings.LoadComponentSettings
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: ResetComponentSettings
  nameWithType: IPersistComponentSettings.ResetComponentSettings
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveComponentSettings
  nameWithType: IPersistComponentSettings.SaveComponentSettings
- uid: System.Configuration.IPersistComponentSettings.SaveSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
- uid: System.Configuration.IPersistComponentSettings.SettingsKey*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
