### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedProviderSettings
  id: ProtectedProviderSettings
  children:
  - System.Configuration.ProtectedProviderSettings.#ctor
  - System.Configuration.ProtectedProviderSettings.Properties
  - System.Configuration.ProtectedProviderSettings.Providers
  langs:
  - csharp
  name: ProtectedProviderSettings
  nameWithType: ProtectedProviderSettings
  fullName: System.Configuration.ProtectedProviderSettings
  type: Class
  summary: "Reprezentuje grupę elementów konfiguracji, które Skonfiguruj dostawców dla <xref uid=&quot;langword_csharp_&lt;configProtectedData&gt;&quot; name=&quot;&lt;configProtectedData&gt;&quot; href=&quot;&quot;> </xref> sekcji konfiguracji."
  syntax:
    content: 'public class ProtectedProviderSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.ProtectedProviderSettings.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedProviderSettings
  langs:
  - csharp
  name: ProtectedProviderSettings()
  nameWithType: ProtectedProviderSettings.ProtectedProviderSettings()
  fullName: System.Configuration.ProtectedProviderSettings.ProtectedProviderSettings()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.ProtectedProviderSettings&quot;> </xref> klasy."
  syntax:
    content: public ProtectedProviderSettings ();
    parameters: []
  overload: System.Configuration.ProtectedProviderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedProviderSettings.Properties
  id: Properties
  parent: System.Configuration.ProtectedProviderSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ProtectedProviderSettings.Properties
  fullName: System.Configuration.ProtectedProviderSettings.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> kolekcja reprezentująca właściwości dostawcy danych konfiguracji chronionych."
  remarks: "Użyj <xref:System.Configuration.ProtectedProviderSettings.Providers%2A>Właściwość właściwości dostawcy, aby uzyskać dostęp do chronionych danych konfiguracji.</xref:System.Configuration.ProtectedProviderSettings.Providers%2A>"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> reprezentujący właściwości dostawcy danych konfiguracji chronionych."
  overload: System.Configuration.ProtectedProviderSettings.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedProviderSettings.Providers
  id: Providers
  parent: System.Configuration.ProtectedProviderSettings
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedProviderSettings.Providers
  fullName: System.Configuration.ProtectedProviderSettings.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera kolekcję <xref href=&quot;System.Configuration.ProviderSettings&quot;> </xref> obiekty reprezentujące właściwości dostawcy danych konfiguracji chronionych."
  remarks: "Ta właściwość służy do dostępu do właściwości dostawców dla danych chronionych konfiguracji zamiast <xref:System.Configuration.ProtectedProviderSettings.Properties%2A>Właściwości.</xref:System.Configuration.ProtectedProviderSettings.Properties%2A>"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "Kolekcja <xref href=&quot;System.Configuration.ProviderSettings&quot;> </xref> obiekty reprezentujące właściwości dostawcy danych konfiguracji chronionych."
  overload: System.Configuration.ProtectedProviderSettings.Providers*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.ProtectedProviderSettings.#ctor
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: ProtectedProviderSettings()
  nameWithType: ProtectedProviderSettings.ProtectedProviderSettings()
  fullName: System.Configuration.ProtectedProviderSettings.ProtectedProviderSettings()
- uid: System.Configuration.ProtectedProviderSettings.Properties
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Properties
  nameWithType: ProtectedProviderSettings.Properties
  fullName: System.Configuration.ProtectedProviderSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ProtectedProviderSettings.Providers
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Providers
  nameWithType: ProtectedProviderSettings.Providers
  fullName: System.Configuration.ProtectedProviderSettings.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Configuration.ProtectedProviderSettings.#ctor*
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: ProtectedProviderSettings
  nameWithType: ProtectedProviderSettings.ProtectedProviderSettings
- uid: System.Configuration.ProtectedProviderSettings.Properties*
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Properties
  nameWithType: ProtectedProviderSettings.Properties
- uid: System.Configuration.ProtectedProviderSettings.Providers*
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Providers
  nameWithType: ProtectedProviderSettings.Providers
