### YamlMime:ManagedReference
items:
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute
  id: SettingsAllowAnonymousAttribute
  children:
  - System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  - System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  - System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute
  type: Class
  summary: "Określa, czy można ustawić właściwości profilu lub dostępne dla użytkowników anonimowych."
  remarks: "Klasa SettingsAllowAnonymousAttribute jest używana do identyfikowania, czy właściwości wdrożenia profilu niestandardowego, jest dostępny, jeśli użytkownik jest anonimowy użytkownik. Aby uzyskać informacje na temat włączania Identyfikacja anonimowa zobacz dokumentację dla elementu konfiguracji.       Jeśli SettingsAllowAnonymousAttribute nie jest określona dla właściwości profilu, dostęp anonimowy właściwości profilu jest niedozwolone.       Implementacji niestandardowego profilu jest klasa, która dziedziczy <xref:System.Web.Profile.ProfileBase>klasę abstrakcyjną i definiuje właściwości profilu użytkownika, które nie są określone w elemencie konfiguracji.</xref:System.Web.Profile.ProfileBase> Można określić typ niestandardowy profil użytkownika w pliku Web.config aplikacji z `inherits` atrybut elementu konfiguracji, jak pokazano w poniższym przykładzie.       `<configuration>`       `<connectionStrings>`       `<add`       `name=&quot;SqlServices&quot;`       `connectionString=&quot;Data Source=localhost;Integrated Security=SSPI;Initial Catalog=aspnetdb;&quot; />`       `</connectionStrings>`       `<system.web>`       `<authentication mode=&quot;Forms&quot; >`       `<forms`       `loginUrl=&quot;login.aspx&quot;`       `name=&quot;.ASPXFORMSAUTH&quot; />`       `</authentication>`       `<authorization>`       `<deny users=&quot;?&quot; />`       `</authorization>`       `<profile inherits=&quot;Samples.AspNet.Profile.EmployeeProfile&quot;`       `defaultProvider=&quot;SqlProvider&quot;>`       `<providers>`       `<clear />`       `<add`       `name=&quot;SqlProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Sample&quot;/>`       `<add`       `name=&quot;EmployeeInfoProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Employee Info&quot;/>`       `</providers>`       `<properties>`       `<add name=&quot;GarmentSize&quot; />`       `</properties>`       `</profile>`       `</system.web>`       `</configuration>`"
  example:
  - "The following code example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/t-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/t-system.web.profile.set_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsAllowAnonymousAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Profile.SettingsAllowAnonymousAttribute&quot;> </xref> klasy i określa, czy zezwolić na dostęp anonimowy do właściwości skojarzony profil."
  remarks: "<xref:System.Web.Profile.SettingsAllowAnonymousAttribute>Klasa jest używana w celu stwierdzenia, czy właściwości wdrożenia profilu niestandardowego, jest dostępny, jeśli użytkownik jest anonimowy użytkownik.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute> Aby uzyskać informacje na temat włączania Identyfikacja anonimowa Zobacz element konfiguracji.       Jeśli nie <xref:System.Web.Profile.SettingsAllowAnonymousAttribute>określona dla właściwości profilu, anonimowy dostęp do właściwości profilu nie jest dozwolona.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute>       Implementacji niestandardowego profilu jest klasa, która dziedziczy <xref:System.Web.Profile.ProfileBase>klasę abstrakcyjną i definiuje właściwości profilu użytkownika, które nie są określone w elemencie konfiguracji.</xref:System.Web.Profile.ProfileBase>"
  example:
  - "The following example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> class to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application. For an example of a configuration file that specifies a custom profile implementation, see the <xref:System.Web.Profile.SettingsAllowAnonymousAttribute> class overview.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/m-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/m-system.web.profile.set_1.vb)]"
  syntax:
    content: public SettingsAllowAnonymousAttribute (bool allow);
    parameters:
    - id: allow
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli dostęp mają użytkownicy anonimowi właściwości profilu skojarzone; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  id: Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Pobiera wartość wskazującą, czy skojarzonej właściwości wdrożenia profilu niestandardowego jest dostępna, jeśli użytkownik jest anonimowy użytkownik."
  syntax:
    content: public bool Allow { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli dostęp mają użytkownicy anonimowi właściwości profilu skojarzone; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  id: IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Pobiera wartość wskazującą czy <xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>właściwość jest ustawiona na wartość domyślną.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>"
  syntax:
    content: public override bool IsDefaultAttribute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli <xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>właściwość jest ustawiona na wartość domyślną; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>"
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute
