### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement
  id: NetMsmqSecurityElement
  children:
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  langs:
  - csharp
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement
  type: Class
  summary: "Klasa NetMsmqSecurityElement hermetyzuje dostępne funkcje zabezpieczeń usługi MSMQ, korzystając z <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  remarks: "Obiekty tego typu są tworzone przez utworzenie wystąpienia <xref:System.ServiceModel.NetMsmqBinding>powiązania.</xref:System.ServiceModel.NetMsmqBinding> Następnie można ten obiekt odwołania wszystkich różnych ustawień zabezpieczeń związane z <xref:System.ServiceModel.NetMsmqBinding>powiązania.</xref:System.ServiceModel.NetMsmqBinding>"
  syntax:
    content: 'public sealed class NetMsmqSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.NetMsmqSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.NetMsmqSecurityElement&quot;> </xref> klasy."
  syntax:
    content: public NetMsmqSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> wystąpienia, z którym skojarzony jest <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  remarks: "<xref:System.ServiceModel.MessageSecurityOverMsmq>Wystąpienia hermetyzuje ustawienia zabezpieczeń wiadomości SOAP.</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  syntax:
    content: public System.ServiceModel.Configuration.MessageSecurityOverMsmqElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
      description: "<xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> Wystąpienia, z którym skojarzony jest <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> wystąpienia, z którym skojarzony jest <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  remarks: "Ta właściwość określa typ zabezpieczeń używanych przez skojarzony `NetMsmqBinding`. Poniżej przedstawiono listę dozwolonych wartości:- `None` -zabezpieczeń nie będą używane.      - `Transport` -TLS będą używane.      - `Message` -Będą używane zabezpieczenia na poziomie wiadomości.      - `Both` — Zarówno oparta na komunikatach zabezpieczeń transportu zabezpieczeń i będą używane."
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "<xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> Wystąpienia, z którym skojarzony jest <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera <xref href=&quot;System.ServiceModel.Configuration.MsmqTransportSecurityElement&quot;> </xref> element, który jest skojarzony z <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  remarks: "Ta właściwość umożliwia dostęp do ustawień zabezpieczeń transportu Msmq."
  syntax:
    content: public System.ServiceModel.Configuration.MsmqTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.MsmqTransportSecurityElement
      description: "<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> Wystąpienia, z którym skojarzony jest <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> powiązania."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.NetMsmqSecurityElement()
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
