### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Reprezentuje metodę, która będzie obsługiwać <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> zdarzeń."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>Zdarzenie wystąpi, gdy ustawienia są pobierane z dostawcą.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> To zdarzenie uruchamiane jeden raz dla każdego dostawcy."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
