### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocation
  id: ConfigurationLocation
  children:
  - System.Configuration.ConfigurationLocation.OpenConfiguration
  - System.Configuration.ConfigurationLocation.Path
  langs:
  - csharp
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
  type: Class
  summary: "Reprezentuje <xref uid=&quot;langword_csharp_location&quot; name=&quot;location&quot; href=&quot;&quot;> </xref> elementu w pliku konfiguracji."
  remarks: "Wystąpienie klasy ConfigurationLocation reprezentuje pojedynczy `location` elementu w pliku konfiguracji. Lokalizacje są używane do określenia ustawień konfiguracyjnych, które mają zastosowanie tylko do określonego zasobu, na przykład określonej strony, plik lub podkatalogu w aplikacji sieci Web. Umożliwia uzyskanie ścieżkę klasy ConfigurationLocation i <xref:System.Configuration.Configuration>obiekt, który ma zastosowanie do określonego zasobu.</xref:System.Configuration.Configuration>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and then the locations defined in the configuration are displayed.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_22_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_22_1.cs)]"
  syntax:
    content: public class ConfigurationLocation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  id: OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Tworzy wystąpienie obiektu konfiguracji."
  syntax:
    content: public System.Configuration.Configuration OpenConfiguration ();
    parameters: []
    return:
      type: System.Configuration.Configuration
      description: "Obiekt konfiguracji."
  overload: System.Configuration.ConfigurationLocation.OpenConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.Path
  id: Path
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera ścieżkę względną do zasobów, których ustawienia konfiguracji są reprezentowane przez to <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref> obiektu."
  remarks: "Jest ścieżką, która jest zwracana przez właściwość ścieżka względem katalogu głównego witryny sieci Web.      > [!NOTE] > Właściwość Path może zawierać rozdzielana przecinkami lista ścieżek, do których stosuje się ustawienia konfiguracji."
  example:
  - "The following code example shows how to access the Path property and display the value returned to the console.  \n  \n [!code-vb[ConfigurationLocationCollection#2](~/add/codesnippet/visualbasic/p-system.configuration.c_38_1.vb)]\n [!code-cs[ConfigurationLocationCollection#2](~/add/codesnippet/csharp/p-system.configuration.c_38_1.cs)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: "Ścieżka względna do zasobów, których ustawienia konfiguracji są reprezentowane przez to <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref>."
  overload: System.Configuration.ConfigurationLocation.Path*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Configuration.ConfigurationLocation.Path
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration
  nameWithType: ConfigurationLocation.OpenConfiguration
- uid: System.Configuration.ConfigurationLocation.Path*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
