### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  id: BrowserCapabilitiesFactoryBase
  children:
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  langs:
  - csharp
  name: BrowserCapabilitiesFactoryBase
  nameWithType: BrowserCapabilitiesFactoryBase
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  type: Class
  summary: "Klasy podstawowej, z którego jest klasa BrowserCapabilitiesFactoryBase <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;> </xref> pochodzi. Jest ono używane wewnętrznie w czasie wykonywania przez system konfiguracji do tworzenia wystąpień specyficzne dla żądania <xref href=&quot;System.Web.Configuration.HttpCapabilitiesBase&quot;> </xref> klasy publicznie dostępne za pośrednictwem platformy ASP.NET — wewnętrzne <xref uid=&quot;langword_csharp_Request.Browser&quot; name=&quot;Request.Browser&quot; href=&quot;&quot;> </xref> właściwości."
  remarks: "W pliku .browser należy zdefiniować możliwości przeglądarki. Można użyć domyślnej hierarchii w pliku .browser lub utworzyć niestandardowe hierarchię, aby zdefiniować możliwości przeglądarki."
  syntax:
    content: public class BrowserCapabilitiesFactoryBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: BrowserCapabilitiesFactoryBase()
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie przez system konfiguracji do utworzenia nowego wystąpienia tej klasy."
  syntax:
    content: public BrowserCapabilitiesFactoryBase ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  id: BrowserElements
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie przez system konfiguracji do reprezentowania zbierania informacji dotyczących różnych możliwości przeglądarki."
  syntax:
    content: protected System.Collections.IDictionary BrowserElements { get; }
    return:
      type: System.Collections.IDictionary
      description: "Słownik możliwości przeglądarki."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  id: ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w czasie wykonywania w celu skonfigurowania <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> obiektu."
  syntax:
    content: public virtual void ConfigureBrowserCapabilities (System.Collections.Specialized.NameValueCollection headers, System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: headers
      type: System.Collections.Specialized.NameValueCollection
      description: "Kolekcja nagłówków żądania."
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> Obiektu."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  id: ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w czasie wykonywania można skonfigurować niestandardowe hierarchie możliwości przeglądarki."
  remarks: "W pliku .browser należy zdefiniować możliwości przeglądarki. Można użyć domyślnej hierarchii w pliku .browser lub utworzyć niestandardowe hierarchię, aby zdefiniować możliwości przeglądarki. Metoda ConfigureCustomCapabilities przetwarza niestandardowych hierarchii. Musi zawierać niestandardowe hierarchii `parentID` wartość w `browser` elementu."
  syntax:
    content: public virtual void ConfigureCustomCapabilities (System.Collections.Specialized.NameValueCollection headers, System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: headers
      type: System.Collections.Specialized.NameValueCollection
      description: "Kolekcja nagłówków żądania."
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "Obiekt, który określa możliwości przeglądarki."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  id: IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: IsBrowserUnknown(HttpCapabilitiesBase)
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie przez system konfiguracji do określenia, czy przeglądarka reprezentowany przez określony <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> obiekt nie ma dostępnych kart."
  syntax:
    content: protected bool IsBrowserUnknown (System.Web.Configuration.HttpCapabilitiesBase browserCaps);
    parameters:
    - id: browserCaps
      type: System.Web.Configuration.HttpCapabilitiesBase
      description: "<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> Obiektu."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli reprezentowanego browser nie ma dostępnych kart; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  id: MatchedHeaders
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie przez system konfiguracji do reprezentowania kolekcję wartości nagłówka żądania."
  syntax:
    content: protected System.Collections.IDictionary MatchedHeaders { get; }
    return:
      type: System.Collections.IDictionary
      description: "Kolekcja nagłówków żądania."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  id: PopulateBrowserElements(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: PopulateBrowserElements(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie przez system konfiguracji do wypełniania kolekcji opartych na przeglądarce obsługiwane możliwości przeglądarki."
  syntax:
    content: protected virtual void PopulateBrowserElements (System.Collections.IDictionary dictionary);
    parameters:
    - id: dictionary
      type: System.Collections.IDictionary
      description: "Kolekcja par klucz/wartość reprezentujący możliwości przeglądarki."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  id: PopulateMatchedHeaders(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: PopulateMatchedHeaders(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie przez system konfiguracji do wypełniania kolekcji opartych na przeglądarce obsługiwanych nagłówków żądania."
  syntax:
    content: protected virtual void PopulateMatchedHeaders (System.Collections.IDictionary dictionary);
    parameters:
    - id: dictionary
      type: System.Collections.IDictionary
      description: "Kolekcja par klucz/wartość reprezentujący możliwości przeglądarki."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserCapabilitiesFactoryBase()
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: IsBrowserUnknown(HttpCapabilitiesBase)
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpCapabilitiesBase
  parent: System.Web.Configuration
  isExternal: false
  name: HttpCapabilitiesBase
  nameWithType: HttpCapabilitiesBase
  fullName: System.Web.Configuration.HttpCapabilitiesBase
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateBrowserElements(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateMatchedHeaders(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserCapabilitiesFactoryBase
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureBrowserCapabilities
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureCustomCapabilities
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: IsBrowserUnknown
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateBrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateMatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders
