### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer
  id: IRemoteWebConfigurationHostServer
  children:
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  langs:
  - csharp
  name: IRemoteWebConfigurationHostServer
  nameWithType: IRemoteWebConfigurationHostServer
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer
  type: Interface
  summary: "Używana wewnętrznie w celu obsługi dostępu zdalnego do danych konfiguracji."
  remarks: "Podstawowa klasa, z którego <xref:System.Web.Configuration.RemoteWebConfigurationHostServer>rozszerza.</xref:System.Web.Configuration.RemoteWebConfigurationHostServer>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("A99B591A-23C6-4238-8452-C7B0E895063D")]

      public interface IRemoteWebConfigurationHostServer
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  id: DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Warunkowo szyfruje i odszyfrowuje wartość ciągu odwołuje się <code> xmlString </code> parametru."
  syntax:
    content: public string DoEncryptOrDecrypt (bool doEncrypt, string xmlString, string protectionProviderName, string protectionProviderType, string[] parameterKeys, string[] parameterValues);
    parameters:
    - id: doEncrypt
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Aby zaszyfrować; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> do odszyfrowania."
    - id: xmlString
      type: System.String
      description: "XML do zaszyfrowanie lub odszyfrowanie."
    - id: protectionProviderName
      type: System.String
      description: "Dostawca używany do ochrony danych konfiguracji."
    - id: protectionProviderType
      type: System.String
      description: "<xref:System.Type>Dostawcy ochrony.</xref:System.Type>"
    - id: parameterKeys
      type: System.String[]
      description: "Klucze następujące parametry opcjonalne dla dostawcy ochrony."
    - id: parameterValues
      type: System.String[]
      description: "Wartości parametrów dla dostawcy ochrony."
    return:
      type: System.String
      description: "Ciąg zawierający zaszyfrowanych lub odszyfrowanych wartość z <code> xmlString </code>."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  id: GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w celu obsługi dostępu zdalnego do danych konfiguracji."
  syntax:
    content: public byte[] GetData (string fileName, bool getReadTimeOnly, out long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Ścieżka do pliku konfiguracji zdalnego można uzyskać dostęp."
    - id: getReadTimeOnly
      type: System.Boolean
      description: "Wartość logiczna określająca czy tylko `readTime` jest zwracany."
    - id: readTime
      type: System.Int64
      description: "Czas ostatniego dostępu do pliku."
    return:
      type: System.Byte[]
      description: "<xref uid=&quot;langword_csharp_array&quot; name=&quot;array&quot; href=&quot;&quot;> </xref> Z 8-bitowych liczb całkowitych bez znaku (w bajtach) zawierającego dane konfiguracji."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  id: GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera szczegóły w pliku konfiguracji."
  syntax:
    content: public void GetFileDetails (string name, out bool exists, out long size, out long createDate, out long lastWriteDate);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa pliku."
    - id: exists
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli plik istnieje; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: size
      type: System.Int64
      description: "Rozmiar pliku."
    - id: createDate
      type: System.Int64
      description: "Data utworzenia pliku."
    - id: lastWriteDate
      type: System.Int64
      description: "Data ostatniego zapisany plik."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  id: GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w celu obsługi dostępu zdalnego do danych konfiguracji."
  syntax:
    content: public string GetFilePaths (int webLevel, string path, string site, string locationSubPath);
    parameters:
    - id: webLevel
      type: System.Int32
      description: "Poziom pliku konfiguracji."
    - id: path
      type: System.String
      description: "Ścieżka do pliku konfiguracji zdalnego można uzyskać dostęp."
    - id: site
      type: System.String
      description: "Ścieżka do komputera zdalnego."
    - id: locationSubPath
      type: System.String
      description: "Ścieżka podrzędna lokalizacji pliku konfiguracji."
    return:
      type: System.String
      description: "Połączony ciąg reprezentujący ścieżkę pliku konfiguracji."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  id: WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w celu obsługi dostępu zdalnego do danych konfiguracji."
  syntax:
    content: public void WriteData (string fileName, string templateFileName, byte[] data, ref long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Ścieżka do pliku konfiguracji zdalnego można uzyskać dostęp."
    - id: templateFileName
      type: System.String
      description: "Plik ma zduplikowane atrybuty pliku z."
    - id: data
      type: System.Byte[]
      description: "Dane do zapisania."
    - id: readTime
      type: System.Int64
      description: "Czas ostatniego dostępu do pliku."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData
  nameWithType: IRemoteWebConfigurationHostServer.GetData
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData
  nameWithType: IRemoteWebConfigurationHostServer.WriteData
