### YamlMime:ManagedReference
items:
- uid: System.Configuration.OverrideMode
  id: OverrideMode
  children:
  - System.Configuration.OverrideMode.Allow
  - System.Configuration.OverrideMode.Deny
  - System.Configuration.OverrideMode.Inherit
  langs:
  - csharp
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
  type: Enum
  summary: "Określa zachowanie zastąpienie elementu konfiguracji dla elementów konfiguracji w katalogach podrzędnych."
  remarks: "Użyj wartości wyliczenia OverrideMode, aby ustawić <xref:System.Configuration.SectionInformation.OverrideMode%2A>Właściwość <xref:System.Configuration.SectionInformation>klasy.</xref:System.Configuration.SectionInformation> </xref:System.Configuration.SectionInformation.OverrideMode%2A> Aby programowo określić zachowanie zastąpienie element konfiguracji lub grupy można ustawić tej właściwości. Aby ustawić deklaratywnie zachowanie zastąpienie dla wszystkich elementów konfiguracji wewnątrz elementu, użyj `allowOverride` atrybutu. <xref:System.Configuration.SectionInformation.OverrideMode%2A>Właściwości zapewnia większą kontrolę nad elementów wewnątrz `location` elementu.</xref:System.Configuration.SectionInformation.OverrideMode%2A>"
  syntax:
    content: public enum OverrideMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Allow
  id: Allow
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ustawienia konfiguracji elementu lub grupa może zostać przesłonięta przez ustawienia konfiguracji, które znajdują się w katalogach podrzędnych."
  syntax:
    content: Allow
    return:
      type: System.Configuration.OverrideMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Deny
  id: Deny
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ustawienia konfiguracji elementu lub grupy nie mogą zostać zastąpione przez ustawienia konfiguracji, które znajdują się w katalogach podrzędnych."
  syntax:
    content: Deny
    return:
      type: System.Configuration.OverrideMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Inherit
  id: Inherit
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ustawienia konfiguracji elementu lub grupy, zostanie ona zastąpiona ustawienia konfiguracji, które znajdują się w katalogach podrzędnych, jeśli jawnie dozwolone przez element nadrzędny bieżącego elementu konfiguracji lub grupy. Określono uprawnień, aby zastąpić przy użyciu <xref uid=&quot;langword_csharp_OverrideMode&quot; name=&quot;OverrideMode&quot; href=&quot;&quot;> </xref> atrybutu."
  syntax:
    content: Inherit
    return:
      type: System.Configuration.OverrideMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.OverrideMode.Allow
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Deny
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
- uid: System.Configuration.OverrideMode.Inherit
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
