### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  id: XmlFormatExtensionPrefixAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  type: Class
  summary: "Określa przestrzeń nazw XML i prefiks przestrzeni nazw XML do użycia na potrzeby rozszerzenie formatu opisu usługi w ramach opisu usługi. Ta klasa nie może być dziedziczona."
  remarks: "Rozszerzenie formatu opisu usługi rozszerza, jak jest generowany opisu usługi dla usługi XML sieci Web utworzony za pomocą programu ASP.NET. W szczególności rozszerzenie formatu opisu usługi dodaje elementów XML do opisu usługi. Jest to przydatne, gdy rozszerzenie SOAP korzysta z wbudowanej Uruchom po stronie klienta i serwera usługi XML sieci Web jako informacji na temat rozszerzeń protokołu SOAP nie znajduje się w opisie usługi. Jeśli dodasz informacji na temat rozszerzenie SOAP w opisie usługi, klient może interpretować należy uruchomić określone rozszerzenie SOAP. Przykładem rozszerzenie SOAP, który musi zostać uruchomiony na kliencie i serwerze jest rozszerzenie SOAP szyfrowania. Jeśli rozszerzenie SOAP szyfrowania jest uruchamiany na serwerze tylko koduje zwracanych wartości przed ich wysłaniem do klienta, klient musi mieć rozszerzenie SOAP systemem można odszyfrować komunikatu protokołu SOAP. W przeciwnym razie klienta nie można przetworzyć wartości zwracanej.       Aby utworzyć rozszerzenie formatu opisu usługi, wykonaj następujące kroki: 1.  Tworzenie klasy, która jest pochodną <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>      2.  Zastosuj <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>do klasy i określ punkty rozszerzenia, na które należy uruchomić rozszerzenie formatu opisu usługi.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Opcjonalnie można zastosować <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>do klasy i określ element członkowski w klasie, który działa jako nowy punkt rozszerzenia.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>      4.  Opcjonalnie można zastosować XmlFormatExtensionPrefixAttribute do klasy i określ prefiks przestrzeni nazw XML, który ma zostać skojarzony z elementów XML wygenerowanych przez rozszerzenie formatu opisu usługi.      5.  Skonfiguruj rozszerzenie formatu opisu usługi do uruchomienia w ramach `serviceDescriptionFormatExtensionTypes` sekcji pliku konfiguracji."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_2_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_2_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]

      public sealed class XmlFormatExtensionPrefixAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> klasy."
  syntax:
    content: public XmlFormatExtensionPrefixAttribute ();
    parameters: []
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> klasy ustawienia przestrzeni nazw XML i prefiks przestrzeni nazw XML dla rozszerzenie formatu opisu usługi."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/31a2fbe2-95e2-473f-8282-_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/31a2fbe2-95e2-473f-8282-_1.vb)]
  syntax:
    content: public XmlFormatExtensionPrefixAttribute (string prefix, string ns);
    parameters:
    - id: prefix
      type: System.String
      description: "Prefiks przestrzeni nazw XML skojarzone z rozszerzenie formatu opisu usługi."
    - id: ns
      type: System.String
      description: "Przestrzeń nazw XML, skojarzone z rozszerzenie formatu opisu usługi."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  id: Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Pobiera lub ustawia obszar nazw XML skojarzone z rozszerzenie formatu opisu usługi."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_4_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_4_1.vb)]
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "Przestrzeń nazw XML, skojarzone z rozszerzenie formatu opisu usługi."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  id: Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Pobiera lub ustawia prefiks przestrzeni nazw XML, które są skojarzone z rozszerzenie formatu opisu usługi."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_0_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_0_1.vb)]
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "Prefiks przestrzeni nazw XML skojarzone z rozszerzenie formatu opisu usługi."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
