### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TagMapInfo
  id: TagMapInfo
  children:
  - System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  - System.Web.Configuration.TagMapInfo.Equals(System.Object)
  - System.Web.Configuration.TagMapInfo.GetHashCode
  - System.Web.Configuration.TagMapInfo.MappedTagType
  - System.Web.Configuration.TagMapInfo.Properties
  - System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Web.Configuration.TagMapInfo.TagType
  langs:
  - csharp
  name: TagMapInfo
  nameWithType: TagMapInfo
  fullName: System.Web.Configuration.TagMapInfo
  type: Class
  summary: "Zawiera znacznik pojedynczą konfiguracją ponowne mapowanie instrukcji. Ta klasa nie może być dziedziczona."
  remarks: "Klasa TagMapInfo umożliwia ponowne mapowanie typy tagów w czasie kompilacji. To ponowne mapowanie powoduje, że typ zmapowane do użycia zamiast oryginalny typ znaczników dla wszystkich stron i formantów w aplikacji ASP.NET w zakresie pliku konfiguracji.       <xref:System.Web.Configuration.TagMapCollection>Klasa umożliwia programowo modyfikacji i dostępu `tagMapping` podsekcji z `pages` sekcji pliku konfiguracji.</xref:System.Web.Configuration.TagMapCollection> W ramach `tagMappings` podsekcji, można dodawać i usuwać mapowania między typami tag, określając w pełni kwalifikowane nazwy silnego typu.      > [!NOTE] > W odróżnieniu od innych atrybuty i kolekcje w programie `pages` sekcji tag ponowne mapowanie ma nie pasującego dyrektywy strony ASP.NET."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for several properties of the TagMapInfo class.  \n  \n```  \n<system.web>  \n  <pages>  \n    <tagMapping>  \n      <add  \n        tagType=  \n          \"System.Web.UI.WebControls.WebParts.WebPartManager\"  \n        mappedTagType=  \n          \"Microsoft.Sharepoint.WebPartPartManager,   \n           MSPS.Web.dll, Version='2.0.0.0'\"   \n      />  \n    </tagMapping>  \n  </pages>  \n</system.web>  \n```  \n  \n The following code example shows how to use the <xref:System.Web.Configuration.TagMapCollection> class to programmatically modify tag-mapping settings. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#17](~/add/codesnippet/csharp/t-system.web.configurati_73_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_73_1.vb)]"
  syntax:
    content: 'public sealed class TagMapInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: TagMapInfo(String,String)
  nameWithType: TagMapInfo.TagMapInfo(String,String)
  fullName: System.Web.Configuration.TagMapInfo.TagMapInfo(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.TagMapInfo&quot;> </xref> klasy oparte na wartości właściwości przekazany."
  remarks: ''
  example:
  - "The following code example shows how to use the TagMapInfo constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#42](~/add/codesnippet/csharp/m-system.web.configurati_25_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#42](~/add/codesnippet/visualbasic/m-system.web.configurati_25_1.vb)]"
  syntax:
    content: public TagMapInfo (string tagTypeName, string mappedTagTypeName);
    parameters:
    - id: tagTypeName
      type: System.String
      description: "Pełna nazwa typu dla tagu, który jest on mapowany ponownie."
    - id: mappedTagTypeName
      type: System.String
      description: "Nazwa typu, do którego tagu jest mapowany ponownie, oraz szczegóły dotyczące obsługi."
  overload: System.Web.Configuration.TagMapInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: TagMapInfo.Equals(Object)
  fullName: System.Web.Configuration.TagMapInfo.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Porównuje to wystąpienie do innego obiektu."
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: "Obiekt do porównania."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli obiekty są jednakowe; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.TagMapInfo.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: TagMapInfo.GetHashCode()
  fullName: System.Web.Configuration.TagMapInfo.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Zwraca wartość skrótu dla bieżącego wystąpienia."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Wartość skrótu dla bieżącego wystąpienia."
  overload: System.Web.Configuration.TagMapInfo.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.MappedTagType
  id: MappedTagType
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
  fullName: System.Web.Configuration.TagMapInfo.MappedTagType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia nazwę typu, do którego jest mapowany ponownie tagu."
  remarks: "Ponowne mapowanie tag występuje w czasie kompilacji. To ponowne mapowanie spowoduje, że typ zamapowanych (określoną przez właściwość MappedTagType) można użyć zamiast oryginalny typ znacznika (określonego przez <xref:System.Web.Configuration.TagMapInfo.TagType%2A>Właściwości) dla wszystkich stron i formantów w aplikacji ASP.NET w zakresie pliku konfiguracji.</xref:System.Web.Configuration.TagMapInfo.TagType%2A>      > [!NOTE] > Wartość pustego ciągu dla tej właściwości spowoduje, że system konfiguracji do zgłoszenia wyjątku podczas serializowany jest obiekt."
  example:
  - "The following code example shows how to use the MappedTagType property. It is part of a larger example for the <xref:System.Web.Configuration.PagesSection> type.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string MappedTagType { get; set; }
    return:
      type: System.String
      description: "Nazwa typu, do którego jest mapowany ponownie tagu. Wartość domyślna to ciąg pusty."
  overload: System.Web.Configuration.TagMapInfo.MappedTagType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.Properties
  id: Properties
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: Properties
  nameWithType: TagMapInfo.Properties
  fullName: System.Web.Configuration.TagMapInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.TagMapInfo.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  id: SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: TagMapInfo.SerializeElement(XmlWriter,Boolean)
  fullName: System.Web.Configuration.TagMapInfo.SerializeElement(XmlWriter,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override bool SerializeElement (System.Xml.XmlWriter writer, bool serializeCollectionKey);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "Do dodania."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "Do dodania."
    return:
      type: System.Boolean
      description: "Do dodania."
  overload: System.Web.Configuration.TagMapInfo.SerializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.TagType
  id: TagType
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: TagType
  nameWithType: TagMapInfo.TagType
  fullName: System.Web.Configuration.TagMapInfo.TagType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia nazwę oryginalnego typu tag, który jest on mapowany ponownie."
  remarks: "Ponowne mapowanie tag występuje w czasie kompilacji. To ponowne mapowanie powoduje mapowany typ (określonego przez <xref:System.Web.Configuration.TagMapInfo.MappedTagType%2A>Właściwości) do użycia zamiast oryginalny typ znacznika (określoną przez właściwość typu tag) dla wszystkich stron i formantów w aplikacji ASP.NET w zakresie pliku konfiguracji.</xref:System.Web.Configuration.TagMapInfo.MappedTagType%2A>      > [!NOTE] > Wartość pustego ciągu dla tej właściwości spowoduje, że system konfiguracji do zgłoszenia wyjątku podczas serializowany jest obiekt."
  example:
  - "The following code example shows how to use the TagType property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string TagType { get; set; }
    return:
      type: System.String
      description: "Nazwa oryginalnego typu dla tagu, który jest on mapowany ponownie."
  overload: System.Web.Configuration.TagMapInfo.TagType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagMapInfo(String,String)
  nameWithType: TagMapInfo.TagMapInfo(String,String)
  fullName: System.Web.Configuration.TagMapInfo.TagMapInfo(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TagMapInfo.Equals(System.Object)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Equals(Object)
  nameWithType: TagMapInfo.Equals(Object)
  fullName: System.Web.Configuration.TagMapInfo.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.TagMapInfo.GetHashCode
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: GetHashCode()
  nameWithType: TagMapInfo.GetHashCode()
  fullName: System.Web.Configuration.TagMapInfo.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.TagMapInfo.MappedTagType
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
  fullName: System.Web.Configuration.TagMapInfo.MappedTagType
- uid: System.Web.Configuration.TagMapInfo.Properties
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Properties
  nameWithType: TagMapInfo.Properties
  fullName: System.Web.Configuration.TagMapInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: TagMapInfo.SerializeElement(XmlWriter,Boolean)
  fullName: System.Web.Configuration.TagMapInfo.SerializeElement(XmlWriter,Boolean)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.Web.Configuration.TagMapInfo.TagType
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagType
  nameWithType: TagMapInfo.TagType
  fullName: System.Web.Configuration.TagMapInfo.TagType
- uid: System.Web.Configuration.TagMapInfo.#ctor*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagMapInfo
  nameWithType: TagMapInfo.TagMapInfo
- uid: System.Web.Configuration.TagMapInfo.Equals*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Equals
  nameWithType: TagMapInfo.Equals
- uid: System.Web.Configuration.TagMapInfo.GetHashCode*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: GetHashCode
  nameWithType: TagMapInfo.GetHashCode
- uid: System.Web.Configuration.TagMapInfo.MappedTagType*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
- uid: System.Web.Configuration.TagMapInfo.Properties*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Properties
  nameWithType: TagMapInfo.Properties
- uid: System.Web.Configuration.TagMapInfo.SerializeElement*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: SerializeElement
  nameWithType: TagMapInfo.SerializeElement
- uid: System.Web.Configuration.TagMapInfo.TagType*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagType
  nameWithType: TagMapInfo.TagType
