### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  id: HttpTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.HttpTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy
  - System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType
  - System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm
  langs:
  - csharp
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
  type: Class
  summary: "Reprezentuje element konfiguracji, który określa parametry uwierzytelniania dla transportu HTTP. Ta klasa nie może być dziedziczona."
  syntax:
    content: 'public sealed class HttpTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  langs:
  - csharp
  name: HttpTransportSecurityElement()
  nameWithType: HttpTransportSecurityElement.HttpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.HttpTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.HttpTransportSecurityElement&quot;> </xref> klasy."
  syntax:
    content: public HttpTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HttpTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: HttpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia typ poświadczeń klienta mają być używane do uwierzytelniania."
  syntax:
    content: public System.ServiceModel.HttpClientCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.HttpClientCredentialType
      description: "Typ poświadczeń klienta mają być używane do uwierzytelniania."
  overload: System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  langs:
  - csharp
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;> </xref> wystąpienia, który zawiera ustawienia konfiguracji do użycia na potrzeby rozszerzonej ochrony dla sesji."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement ExtendedProtectionPolicy { get; }
    return:
      type: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
      description: "<xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;> </xref> Wystąpienia, który zawiera ustawienia konfiguracji do użycia na potrzeby rozszerzonej ochrony dla sesji."
  overload: System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType
  id: ProxyCredentialType
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  langs:
  - csharp
  name: ProxyCredentialType
  nameWithType: HttpTransportSecurityElement.ProxyCredentialType
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia typ poświadczeń klienta służący do uwierzytelniania serwera proxy."
  syntax:
    content: public System.ServiceModel.HttpProxyCredentialType ProxyCredentialType { get; set; }
    return:
      type: System.ServiceModel.HttpProxyCredentialType
      description: "Typ poświadczeń klienta służący do uwierzytelniania serwera proxy."
  overload: System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm
  id: Realm
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  langs:
  - csharp
  name: Realm
  nameWithType: HttpTransportSecurityElement.Realm
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera lub ustawia obszar uwierzytelniania dla uwierzytelniania podstawowego lub szyfrowanego."
  remarks: "Obszar uwierzytelniania to ciąg, który zawiera co najmniej nazwę hosta wykonywania uwierzytelniania. Można również określić zbiór użytkowników, które ma dostęp.       Użytkownik może zapytania obszaru uwierzytelniania, aby zrozumieć, co kilka możliwych nazw użytkowników i haseł można użyć."
  syntax:
    content: public string Realm { get; set; }
    return:
      type: System.String
      description: "Obszar uwierzytelniania. Wartość domyślna to &quot;&quot;."
  overload: System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: HttpTransportSecurityElement()
  nameWithType: HttpTransportSecurityElement.HttpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.HttpTransportSecurityElement()
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: HttpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.HttpClientCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: HttpClientCredentialType
  nameWithType: HttpClientCredentialType
  fullName: System.ServiceModel.HttpClientCredentialType
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  parent: System.Security.Authentication.ExtendedProtection.Configuration
  isExternal: false
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: HttpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: ProxyCredentialType
  nameWithType: HttpTransportSecurityElement.ProxyCredentialType
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType
- uid: System.ServiceModel.HttpProxyCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: HttpProxyCredentialType
  nameWithType: HttpProxyCredentialType
  fullName: System.ServiceModel.HttpProxyCredentialType
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: Realm
  nameWithType: HttpTransportSecurityElement.Realm
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: HttpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ExtendedProtectionPolicy*
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: HttpTransportSecurityElement.Properties
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.ProxyCredentialType*
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: ProxyCredentialType
  nameWithType: HttpTransportSecurityElement.ProxyCredentialType
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement.Realm*
  parent: System.ServiceModel.Configuration.HttpTransportSecurityElement
  isExternal: false
  name: Realm
  nameWithType: HttpTransportSecurityElement.Realm
