### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAs
  id: SettingsSerializeAs
  children:
  - System.Configuration.SettingsSerializeAs.Binary
  - System.Configuration.SettingsSerializeAs.ProviderSpecific
  - System.Configuration.SettingsSerializeAs.String
  - System.Configuration.SettingsSerializeAs.Xml
  langs:
  - csharp
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
  type: Enum
  summary: "Określa schemat serializacji, używany do przechowywania ustawień aplikacji."
  remarks: "SettingsSerializeAsenumeration służy do określania mechanizmu serializacji używane przez dostawcę ustawienia aplikacji, aby utrwalić wartości właściwości ustawień aplikacji. Na przykład ttribute używa tego wyliczenia w jego konstruktora na żądanie, że właściwość lub grupę właściwości być utrwalona za pomocą mechanizmu serializacji określonego."
  syntax:
    content: public enum SettingsSerializeAs
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Binary
  id: Binary
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Właściwość ustawień jest szeregowana, za pomocą serializacji obiektu binarnego."
  syntax:
    content: Binary
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  id: ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Dostawca ustawień ma niejawne informacji na temat właściwości lub jej typu i wybiera odpowiedni mechanizm szeregowania. Często używane do szeregowania niestandardowego."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.String
  id: String
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Właściwość ustawień jest szeregowana jako zwykły tekst."
  syntax:
    content: String
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAs.Xml
  id: Xml
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Właściwość ustawień jest szeregowana jako kodu XML za pomocą serializacji XML."
  syntax:
    content: Xml
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsSerializeAs.Binary
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
- uid: System.Configuration.SettingsSerializeAs.String
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
- uid: System.Configuration.SettingsSerializeAs.Xml
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
