### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs
  id: DownloadProgressChangedEventArgs
  children:
  - System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  - System.Deployment.Application.DownloadProgressChangedEventArgs.State
  - System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  langs:
  - csharp
  name: DownloadProgressChangedEventArgs
  nameWithType: DownloadProgressChangedEventArgs
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs
  type: Class
  summary: "Udostępnia dane dla <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadProgressChanged&quot;> </xref> zdarzeń."
  remarks: "W aplikacji konsoli ponieważ zdarzenia są przypisane do wątków z puli wątków może pojawić się poza kolejnością, aktualizacja postępu zdarzenia do kolejnych zdarzeń, przedstawiający zmniejszanie w porównaniu do poprzednich zdarzeń. Nie będą widzieć takiego zachowania w aplikacji formularzy systemu Windows, ponieważ zdarzeń w formularzach systemu Windows są przetwarzane sekwencyjnie poza kolejki komunikatów w wątku interfejsu użytkownika."
  example:
  - "The following code example demonstrates the use of DownloadProgressChangedEventArgs in the context of an application that uses <xref:System.Deployment.Application.InPlaceHostingManager> to download and install a ClickOnce application programmatically.  \n  \n [!code-vb[System.Deployment.Application.InPlaceHostingManager#1](~/add/codesnippet/visualbasic/InPlaceHostingManagerProjectVB/Form1.vb#1)]\n [!code-cs[System.Deployment.Application.InPlaceHostingManager#1](~/add/codesnippet/csharp/InPlaceHostingManagerProject/Form1.cs#1)]"
  syntax:
    content: 'public class DownloadProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  id: BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera liczbę bajtów pobrana na komputer lokalny."
  syntax:
    content: public long BytesDownloaded { get; }
    return:
      type: System.Int64
      description: "<xref:System.Int64>Reprezentujący liczbę pobrane bajtów.</xref:System.Int64>"
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera stan postępu pobierania."
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> wartości opisujące jest pobierany część aplikacji ClickOnce."
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  id: TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera całkowitą liczbę bajtów dla operacji pobierania."
  syntax:
    content: public long TotalBytesToDownload { get; }
    return:
      type: System.Int64
      description: "<xref:System.Int64>Reprezentujący całkowity rozmiar w bajtach pobraniu.</xref:System.Int64>"
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
