### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsProtectionEnum
  id: FormsProtectionEnum
  children:
  - System.Web.Configuration.FormsProtectionEnum.All
  - System.Web.Configuration.FormsProtectionEnum.Encryption
  - System.Web.Configuration.FormsProtectionEnum.None
  - System.Web.Configuration.FormsProtectionEnum.Validation
  langs:
  - csharp
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
  type: Enum
  summary: "Określa typ szyfrowania, jeśli istnieją, aby używać plików cookie."
  remarks: "W przypadku wybrania wszystkich wartości system używa algorytmu sprawdzania poprawności danych skonfigurowane na podstawie [machineKey Element (schemat ustawień programu ASP.NET)](http://msdn.microsoft.com/en-us/4b5699a9-bc21-4c4a-85f1-8b3b8ebd2d46) tagu. Jest to wartość domyślna i zalecana wartość.       Jeśli wybierzesz opcję Brak, pliki cookie mogą być narażone na ataki w postaci zwykłego tekstu.       Jeśli wybierzesz opcję sprawdzania poprawności, plik cookie jest tworzony przy użyciu weryfikacji przez połączenie klucza weryfikacji przy użyciu danych pliku cookie, obliczenie kodu uwierzytelniania wiadomości (MAC) i dołączenie MAC do wychodzącego pliku cookie."
  example:
  - "The following code example shows how to use the FormsProtectionEnum enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationConfiguration> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/visualbasic/t-system.web.configurati_72_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/csharp/t-system.web.configurati_72_1.cs)]"
  syntax:
    content: public enum FormsProtectionEnum
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.All
  id: All
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że aplikacja korzysta z zarówno weryfikacji i szyfrowania danych w celu ochrony plików cookie. Ta opcja używa algorytmu skonfigurowanego sprawdzania poprawności danych (na podstawie <xref uid=&quot;langword_csharp_machineKey&quot; name=&quot;machineKey&quot; href=&quot;&quot;> </xref> elementu). Triple-DES (3DES) używany do szyfrowania, jeśli jest dostępna, a jeśli klucz jest co najmniej 48 bajtów. <xref uid=&quot;langword_csharp_All&quot; name=&quot;All&quot; href=&quot;&quot;></xref>Wartość domyślna to (i zalecana) wartość."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  id: Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że pliki cookie są szyfrowane przy użyciu algorytmu&3;DES lub DES, ale nie jest przeprowadzana weryfikacja danych na pliki cookie. Pliki cookie używane w ten sposób mogą być narażone na ataki zabezpieczeń wybrany w postaci zwykłego tekstu."
  syntax:
    content: Encryption
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.None
  id: None
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że szyfrowanie i weryfikacja są wyłączone dla witryn, które używają plików cookie tylko na potrzeby personalizacji i w związku z tym mają mniejsze wymagania dotyczące zabezpieczeń. Nie zaleca się używania plików cookie w ten sposób; jest jednak najmniej obciążający zasoby sposób włączania personalizacji przy użyciu programu .NET Framework."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  id: Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że aplikacja korzysta schemat weryfikacji, aby sprawdzić, czy zawartość zaszyfrowanego pliku cookie nie została zmieniona podczas przesyłania. Plik cookie jest tworzony przez połączenie klucza weryfikacji przy użyciu danych pliku cookie, obliczenie kodu uwierzytelniania wiadomości (MAC) i dołączenie MAC do wychodzącego pliku cookie."
  syntax:
    content: Validation
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsProtectionEnum.All
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
- uid: System.Web.Configuration.FormsProtectionEnum
  parent: System.Web.Configuration
  isExternal: false
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
- uid: System.Web.Configuration.FormsProtectionEnum.None
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
