### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  id: DownloadApplicationCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  langs:
  - csharp
  name: DownloadApplicationCompletedEventArgs
  nameWithType: DownloadApplicationCompletedEventArgs
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  type: Class
  summary: "Udostępnia dane dla <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadApplicationCompleted&quot;> </xref> zdarzeń."
  syntax:
    content: 'public class DownloadApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  id: LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera ścieżkę pliku dziennika ClickOnce."
  syntax:
    content: public string LogFilePath { get; }
    return:
      type: System.String
      description: "Ścieżka pliku dziennika ClickOnce."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  id: ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera zawartość pliku .appref ms, który można uruchomić tej aplikacji ClickOnce."
  remarks: 'Ta właściwość zawiera tekstu niestandardowego instalatora może zapisywać do pliku .appref ms, można uruchomić tej aplikacji ClickOnce. ClickOnce tworzy plik uruchamiania podczas instalacji aplikacji ClickOnce, która jest dostępna w trybie offline, z wyjątkiem aplikacji, które obejmują `<customUX>` elementu. Niestandardowy Instalator można utworzyć skrótu do uruchamiania aplikacji ClickOnce, która zawiera `<customUX>` elementu przez zapisywanie tekstu w tej właściwości do nowego pliku .appref ms w formacie Unicode. Aby uzyskać więcej informacji, zobacz [ \&lt; punktu wejścia\&gt; Element](../Topic/%3CentryPoint%3E%20Element%20\(ClickOnce%20Application\).md) i [wskazówki: Tworzenie niestandardowego Instalatora dla aplikacji ClickOnce](~/add/includes/ajax-current-ext-md.md).'
  syntax:
    content: public string ShortcutAppId { get; }
    return:
      type: System.String
      description: "Zawartość pliku .appref ms."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
