### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ServerWebConfig
  id: ServerWebConfig
  children:
  - System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  - System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: ServerWebConfig
  nameWithType: ServerWebConfig
  fullName: System.EnterpriseServices.Internal.ServerWebConfig
  type: Class
  summary: "Tworzy plik Web.config dla aplikacji z obsługą protokołu SOAP modelu COM +. Można również dodać wpisów składnika do pliku dla interfejsów COM publikowaną w aplikacji."
  remarks: "Klasa ServerWebConfig jest używana do utworzenia pliku Web.config podczas tworzenia wirtualnego katalogu głównego w Internet informacji Services (IIS) 6.0 dla aplikacji z obsługą protokołu SOAP modelu COM +. Elementy XML ona również dodać do pliku Web.config dla interfejsów składników dodawany do aplikacji.       ServerWebConfig jest używana wewnętrznie przez program .NET Framework. Nie trzeba używać go bezpośrednio w kodzie."
  syntax:
    content: 'public class ServerWebConfig : System.EnterpriseServices.Internal.IServerWebConfig'
  inheritance:
  - System.Object
  implements:
  - System.EnterpriseServices.Internal.IServerWebConfig
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.EnterpriseServices.Internal.ServerWebConfig&quot;> </xref> klasy."
  syntax:
    content: public ServerWebConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Dodaje elementy XML w pliku Web.config dla interfejsu COM publikowaną w aplikacji z obsługą protokołu SOAP modelu COM +."
  remarks: "Dla określonego typu metody AddElement dodaje do pliku Web.config `<wellknown>` i `<activated>` elementy jako elementy podrzędne `<service>` element z poniższe wyrażenie XPath: `/configuration/system.runtime.remoting/application/service` `AssemblyName`, `TypeName`, `ProgId`, i `WkoMode` parametry są włączone do wartości atrybutów dwa elementy dodane.       Nie należy bezpośrednio wywoływać AddElement. Zamiast tego wywołać <xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>metody.</xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string WkoMode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Ścieżka istniejącego pliku Web.config."
    - id: AssemblyName
      type: System.String
      description: "Nazwa zestawu zawierającego typ dodawany."
    - id: TypeName
      type: System.String
      description: "Nazwa typu dodawany."
    - id: ProgId
      type: System.String
      description: "Identyfikator programowy typu dodawany."
    - id: WkoMode
      type: System.String
      description: "Stałą typu string, który odpowiada nazwie elementu członkowskiego z <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> wyliczenia, który wskazuje, jak dobrze znane obiekty została aktywowana."
    - id: Error
      type: System.String
      description: "Ciąg, do którego mogą być zapisywane komunikat o błędzie."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Tworzy plik Web.config dla aplikacji z obsługą protokołu SOAP modelu COM +, plik jest gotowy do elementy XML dodane dla interfejsów COM publikowana."
  remarks: "Metody Create tworzy plik Web.config, który zawiera hierarchię dla pustego elementu z poniższe wyrażenie XPath: ```   /configuration/system.runtime.remoting/application/service   ``` zamiast tworzenia wystąpienia <xref:System.EnterpriseServices.Internal.ServerWebConfig>klas obiektów i wywoływania bezpośrednio, Utwórz wywołania <xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A>metody.</xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A> </xref:System.EnterpriseServices.Internal.ServerWebConfig>"
  syntax:
    content: public void Create (string FilePath, string FilePrefix, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Folder, w którym można utworzyć pliku konfiguracji."
    - id: FilePrefix
      type: System.String
      description: "Wartość ciągu &quot;Web&quot;, do którego jest dodawany rozszerzenia konfiguracji."
    - id: Error
      type: System.String
      description: "Ciąg, do którego mogą być zapisywane komunikat o błędzie."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig
  nameWithType: ServerWebConfig.ServerWebConfig
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: ServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create
  nameWithType: ServerWebConfig.Create
