### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidatorAttribute
  id: CallbackValidatorAttribute
  children:
  - System.Configuration.CallbackValidatorAttribute.#ctor
  - System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  - System.Configuration.CallbackValidatorAttribute.Type
  - System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute
  fullName: System.Configuration.CallbackValidatorAttribute
  type: Class
  summary: "Określa <xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref> obiekt do użycia w celu weryfikacji kodu. Ta klasa nie może być dziedziczona."
  remarks: "Klasa atrybutu CallbackValidatorAttribute udostępnia skojarzenia między <xref:System.Configuration.CallbackValidator>obiektu i kod do sprawdzania poprawności.</xref:System.Configuration.CallbackValidator> Klasa CallbackValidatorAttribute pochodzi od <xref:System.Configuration.ConfigurationValidatorAttribute>klasy.</xref:System.Configuration.ConfigurationValidatorAttribute>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class CallbackValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.CallbackValidatorAttribute&quot;> </xref> klasy."
  syntax:
    content: public CallbackValidatorAttribute ();
    parameters: []
  overload: System.Configuration.CallbackValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  id: CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia nazwę metody wywołania zwrotnego."
  syntax:
    content: public string CallbackMethodName { get; set; }
    return:
      type: System.String
      description: "Nazwa metody do wywołania."
  overload: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.Type
  id: Type
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia typ modułu weryfikacji."
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "<xref:System.Type>Bieżącego wystąpienia atrybutu modułu sprawdzania poprawności.</xref:System.Type>"
  overload: System.Configuration.CallbackValidatorAttribute.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera wystąpienie modułu sprawdzania poprawności."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Bieżący <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> wystąpienia."
  overload: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Wartość <xref:System.Configuration.CallbackValidatorAttribute.Type*>jest właściwość <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>.</xref:System.Configuration.CallbackValidatorAttribute.Type*>"
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName*>Do publiczną metodą static void z jednym parametrem obiektu nie ustawiono właściwości.</xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName*>"
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CallbackValidatorAttribute.Type
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidatorAttribute.#ctor*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
- uid: System.Configuration.CallbackValidatorAttribute.Type*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
