### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BindingCollectionElement
  id: BindingCollectionElement
  children:
  - System.ServiceModel.Configuration.BindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  - System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  - System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(System.String)
  - System.ServiceModel.Configuration.BindingCollectionElement.GetDefault
  - System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  langs:
  - csharp
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: System.ServiceModel.Configuration.BindingCollectionElement
  type: Class
  summary: "Reprezentuje sekcję konfiguracji, który zawiera kolekcję elementów, wiązania, z których każdy zawiera opis aspektu jak punkt końcowy komunikuje się z innych punktów końcowych, wbudowanego, spójnie w fabryki kanałów na kliencie i odbiornik kanału usługi."
  syntax:
    content: 'public abstract class BindingCollectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: BindingCollectionElement()
  nameWithType: BindingCollectionElement.BindingCollectionElement()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Configuration.BindingCollectionElement&quot;> </xref> klasy."
  syntax:
    content: protected BindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BindingCollectionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  id: BindingName
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: BindingName
  nameWithType: BindingCollectionElement.BindingName
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera nazwę powiązania."
  syntax:
    content: public string BindingName { get; }
    return:
      type: System.String
      description: "Unikatowa nazwa powiązania."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.BindingName*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Nie znaleziono nazwę kolekcji bieżącej konfiguracji.       - lub - nie można odnaleźć nazwy sekcji konfiguracji."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  id: BindingType
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: BindingType
  nameWithType: BindingCollectionElement.BindingType
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera typ powiązania."
  syntax:
    content: public abstract Type BindingType { get; }
    return:
      type: System.Type
      description: "A <xref:System.Type>zawierający typ powiązania.</xref:System.Type>"
  overload: System.ServiceModel.Configuration.BindingCollectionElement.BindingType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  id: ConfiguredBindings
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: ConfiguredBindings
  nameWithType: BindingCollectionElement.ConfiguredBindings
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera wszystkie elementy konfiguracji powiązania w tej kolekcji."
  syntax:
    content: public abstract System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement> ConfiguredBindings { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.IBindingConfigurationElement}
      description: "Wszystkie powiązania elementy konfiguracji w tej kolekcji."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(System.String)
  id: ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: ContainsKey(String)
  nameWithType: BindingCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Określa, czy powiązanie istnieje w kolekcji przy użyciu określonej nazwy."
  syntax:
    content: public abstract bool ContainsKey (string name);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa powiązania można znaleźć."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli kolekcja zawiera powiązanie z określonym <code> name </code>; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: BindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Pobiera wiązanie domyślne używane."
  syntax:
    content: protected abstract System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: "A <xref:System.ServiceModel.Channels.Binding>obiekt, który reprezentuje powiązanie domyślnej.</xref:System.ServiceModel.Channels.Binding>"
  overload: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  id: TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: TryAdd(String,Binding,Configuration)
  nameWithType: BindingCollectionElement.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(String,Binding,Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Dodaje określone powiązanie do kolekcji."
  syntax:
    content: protected abstract bool TryAdd (string name, System.ServiceModel.Channels.Binding binding, System.Configuration.Configuration config);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa powiązania do dodania."
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "A <xref:System.ServiceModel.Channels.Binding>obiekt, który reprezentuje powiązanie, które ma zostać dodana.</xref:System.ServiceModel.Channels.Binding>"
    - id: config
      type: System.Configuration.Configuration
      description: "Ustawienia konfiguracji tego powiązania."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli operacja zakończyła się pomyślnie; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.BindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingCollectionElement()
  nameWithType: BindingCollectionElement.BindingCollectionElement()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingCollectionElement()
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingName
  nameWithType: BindingCollectionElement.BindingName
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingType
  nameWithType: BindingCollectionElement.BindingType
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ConfiguredBindings
  nameWithType: BindingCollectionElement.ConfiguredBindings
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.IBindingConfigurationElement}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<IBindingConfigurationElement>
  nameWithType: ReadOnlyCollection<IBindingConfigurationElement>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.IBindingConfigurationElement
    name: IBindingConfigurationElement
    nameWithType: IBindingConfigurationElement
    fullName: IBindingConfigurationElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ContainsKey(String)
  nameWithType: BindingCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: BindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: TryAdd(String,Binding,Configuration)
  nameWithType: BindingCollectionElement.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(String,Binding,Configuration)
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.BindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement.BindingCollectionElement
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingName*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingName
  nameWithType: BindingCollectionElement.BindingName
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingType*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingType
  nameWithType: BindingCollectionElement.BindingType
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ConfiguredBindings
  nameWithType: BindingCollectionElement.ConfiguredBindings
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ContainsKey
  nameWithType: BindingCollectionElement.ContainsKey
- uid: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: BindingCollectionElement.GetDefault
- uid: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: TryAdd
  nameWithType: BindingCollectionElement.TryAdd
