### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationIDAttribute
  id: ApplicationIDAttribute
  children:
  - System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  - System.EnterpriseServices.ApplicationIDAttribute.Value
  langs:
  - csharp
  name: ApplicationIDAttribute
  nameWithType: ApplicationIDAttribute
  fullName: System.EnterpriseServices.ApplicationIDAttribute
  type: Class
  summary: "Określa identyfikator aplikacji (jako identyfikator GUID) dla tego zestawu. Ta klasa nie może być dziedziczona."
  remarks: "ApplicationIDAttribute ma identyfikator GUID w jego konstruktora. W przypadku rejestracji składników w zestawie są zainstalowane w aplikacji o danym identyfikatorze."
  example:
  - "The following code example demonstrates the use of the ApplicationIDAttribute type.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/csharp/t-system.enterpriseservi_14_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/visualbasic/t-system.enterpriseservi_14_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIDAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.EnterpriseServices.ApplicationIDAttribute
  langs:
  - csharp
  name: ApplicationIDAttribute(String)
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute(String)
  fullName: System.EnterpriseServices.ApplicationIDAttribute.ApplicationIDAttribute(String)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.EnterpriseServices.ApplicationIDAttribute&quot;> </xref> klasy, określając identyfikator GUID reprezentujący identyfikator aplikacji dla aplikacji COM +."
  remarks: ''
  example:
  - "The following code example demonstrates how to create a new <xref:System.EnterpriseServices.ApplicationIDAttribute>.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#1](~/add/codesnippet/csharp/m-system.enterpriseservi_17_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#1](~/add/codesnippet/visualbasic/m-system.enterpriseservi_17_1.vb)]"
  syntax:
    content: public ApplicationIDAttribute (string guid);
    parameters:
    - id: guid
      type: System.String
      description: "Identyfikator GUID skojarzony z aplikacją COM +."
  overload: System.EnterpriseServices.ApplicationIDAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationIDAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationIDAttribute.Value
  fullName: System.EnterpriseServices.ApplicationIDAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Pobiera identyfikator GUID aplikacji COM +."
  remarks: "Wartość jest ustawiana przez konstruktora przy użyciu identyfikatora GUID przekazany jako parametr."
  example:
  - "The following code example demonstrates how to get the value of an `ApplicationID` attribute's Value property.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/csharp/p-system.enterpriseservi_3_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/visualbasic/p-system.enterpriseservi_3_1.vb)]"
  syntax:
    content: public Guid Value { get; }
    return:
      type: System.Guid
      description: "Identyfikator GUID reprezentujący aplikacji COM +."
  overload: System.EnterpriseServices.ApplicationIDAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: ApplicationIDAttribute(String)
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute(String)
  fullName: System.EnterpriseServices.ApplicationIDAttribute.ApplicationIDAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationIDAttribute.Value
  fullName: System.EnterpriseServices.ApplicationIDAttribute.Value
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: ApplicationIDAttribute
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value*
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationIDAttribute.Value
