### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  id: ContractTypeNameElement
  children:
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor(System.String,System.String)
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  langs:
  - csharp
  name: ContractTypeNameElement
  nameWithType: ContractTypeNameElement
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  type: Class
  summary: "Reprezentuje element przepływu pracy, który identyfikuje według nazwy kontraktu usługi przepływu pracy są wyszukiwane."
  remarks: "Właściwość, która odwołuje się do zestawu kryteriów zwykle używana podczas wyszukiwania dla usługi jest nazwa typu kontraktu. Zestaw kryteriów lub umowy, jest to kolekcja operacji, które określają, jakie komunikuje się publicznie punktu końcowego. Każda operacja jest wymiany wiadomości. Na przykład komunikat żądania i komunikatu odpowiedzi skojarzona tworzą wymiany komunikatów żądania/odpowiedzi."
  syntax:
    content: 'public sealed class ContractTypeNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: ContractTypeNameElement()
  nameWithType: ContractTypeNameElement.ContractTypeNameElement()
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Discovery.Configuration.ContractTypeNameElement&quot;> </xref> klasy."
  syntax:
    content: public ContractTypeNameElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: ContractTypeNameElement(String,String)
  nameWithType: ContractTypeNameElement.ContractTypeNameElement(String,String)
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Discovery.Configuration.ContractTypeNameElement&quot;> </xref> przy użyciu nazwy typu określonego kontraktu i przestrzeni nazw."
  syntax:
    content: public ContractTypeNameElement (string name, string ns);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa typu kontraktu usługi przepływu pracy."
    - id: ns
      type: System.String
      description: "Nazwa przestrzeni nazw kontraktu usługi przepływu pracy."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  id: Name
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: Name
  nameWithType: ContractTypeNameElement.Name
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Pobiera lub ustawia nazwę typu kontraktu."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Nazwa alfanumeryczne."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  id: Namespace
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: Namespace
  nameWithType: ContractTypeNameElement.Namespace
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Pobiera lub ustawia obszar nazw typu kontraktu."
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "Nazwa alfanumeryczne."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: ContractTypeNameElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: ContractTypeNameElement()
  nameWithType: ContractTypeNameElement.ContractTypeNameElement()
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement()
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: ContractTypeNameElement(String,String)
  nameWithType: ContractTypeNameElement.ContractTypeNameElement(String,String)
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Name
  nameWithType: ContractTypeNameElement.Name
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Namespace
  nameWithType: ContractTypeNameElement.Namespace
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Properties
  nameWithType: ContractTypeNameElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: ContractTypeNameElement
  nameWithType: ContractTypeNameElement.ContractTypeNameElement
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Name
  nameWithType: ContractTypeNameElement.Name
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Namespace
  nameWithType: ContractTypeNameElement.Namespace
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Properties
  nameWithType: ContractTypeNameElement.Properties
