### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FcnMode
  id: FcnMode
  children:
  - System.Web.Configuration.FcnMode.Default
  - System.Web.Configuration.FcnMode.Disabled
  - System.Web.Configuration.FcnMode.NotSet
  - System.Web.Configuration.FcnMode.Single
  langs:
  - csharp
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
  type: Enum
  summary: "Określa zachowanie powiadomienia o zmianie pliku (FCN) w aplikacji."
  syntax:
    content: public enum FcnMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Default
  id: Default
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Dla każdego podkatalogu aplikacja tworzy obiekt, który monitoruje podkatalogu. Jest to zachowanie domyślne."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.FcnMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Disabled
  id: Disabled
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Powiadomienie o zmianie pliku jest wyłączona."
  syntax:
    content: Disabled
    return:
      type: System.Web.Configuration.FcnMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.NotSet
  id: NotSet
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Powiadomienie o zmianie pliku nie jest ustawiona, więc aplikacja tworzy obiekt, który monitoruje każdego podkatalogu. Jest to zachowanie domyślne."
  syntax:
    content: NotSet
    return:
      type: System.Web.Configuration.FcnMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Single
  id: Single
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Aplikacja tworzy jeden obiekt, aby monitorować katalogu głównego i używa tego obiektu do monitorowania poszczególnych podkatalogu."
  syntax:
    content: Single
    return:
      type: System.Web.Configuration.FcnMode
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FcnMode.Default
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
- uid: System.Web.Configuration.FcnMode
  parent: System.Web.Configuration
  isExternal: false
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
- uid: System.Web.Configuration.FcnMode.Disabled
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
- uid: System.Web.Configuration.FcnMode.NotSet
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
- uid: System.Web.Configuration.FcnMode.Single
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
