### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  id: ProcessModelComImpersonationLevel
  children:
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  langs:
  - csharp
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
  type: Enum
  summary: "Określa poziom uwierzytelniania zabezpieczeń COM."
  remarks: "Klasa ProcessModelComImpersonationLevel wylicza wartości do użycia podczas ustawiania <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>Właściwości.</xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>       Wartość domyślna to personifikacji."
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/csharp/t-system.web.configurati_52_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/visualbasic/t-system.web.configurati_52_1.vb)]"
  syntax:
    content: public enum ProcessModelComImpersonationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  id: Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, czy klient jest anonimowy do serwera. To pole jest stałą."
  remarks: "Serwer może personifikować klienta, ale token personifikacji nie będzie zawierać żadnych informacji."
  syntax:
    content: Anonymous
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Model DCOM określa poziom personifikacji. To pole jest stałą."
  remarks: "Model DCOM określa poziom personifikacji przy użyciu algorytmu jego normalnej negocjacji zabezpieczeń."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  id: Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że proces serwera może personifikować kontekst zabezpieczeń klienta, działając w imieniu klienta. To pole jest stałą."
  remarks: "Proces serwera może na inne serwery działają w imieniu klienta przy użyciu maskowanie wywołań wychodzących. Serwer może być kontekst zabezpieczeń klienta na innych komputerach dostęp do zasobów lokalnych i zdalnych jako klienta. Podczas procesu jest Personifikowanie klienta na tym poziomie, token personifikacji mogą być przekazywane przez dowolną liczbę granic komputera."
  syntax:
    content: Delegate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  id: Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że serwer może uzyskać tożsamości klienta. To pole jest stałą."
  remarks: "Serwer może personifikować klienta sprawdzania listę kontroli dostępu (ACL) kontroli dostępu, ale nie może uzyskać dostępu obiektów systemu jako klient."
  syntax:
    content: Identify
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  id: Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Określa, że proces serwera może personifikować kontekst zabezpieczeń klienta, działając w imieniu klienta. To pole jest stałą."
  remarks: "Ten poziom personifikacji można uzyskać dostępu do zasobów lokalnych, takich jak pliki. Podczas procesu jest Personifikowanie klienta na tym poziomie, token personifikacji mogą być przekazywane granicy tylko na jednym komputerze."
  syntax:
    content: Impersonate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
