### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.UpdateCheckInfo
  id: UpdateCheckInfo
  children:
  - System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  - System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  - System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  - System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  - System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  langs:
  - csharp
  name: UpdateCheckInfo
  nameWithType: UpdateCheckInfo
  fullName: System.Deployment.Application.UpdateCheckInfo
  type: Class
  summary: "Przedstawia szczegółowe informacje o aktualizacji uzyskanymi za pośrednictwem wywołania <xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>"
  remarks: "Z UpdateCheckInfo można zdecydować, czy uaktualnić na podstawie informacji o najnowszą wersję aplikacji ClickOnce. <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A>Zwraca wartość logiczną wskazującą, czy jest nowa aktualizacja w ogóle.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> <xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A>Właściwości zawiera numer wersji nowej wersji, podczas gdy <xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A>zapewnia najstarszą wersję, który użytkownik powinien mieć zainstalowany.</xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A> <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A>Określa, czy najnowsza wersja aktualizacji jest wymagany użytkownika.</xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> Na koniec <xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>wyraża łączny rozmiar aktualizacji.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>      > [!NOTE] > Dodaje visual Studio `<deploymentProvider>` element do manifestu tylko wtedy, gdy aplikacja jest skonfigurowana do sprawdzania dostępności aktualizacji, należy więc albo sprawdź **aplikacja ma sprawdzać dostępność aktualizacji** lub określić adres URL aktualizacji w **zaktualizować lokalizację** w [okno dialogowe aktualizacje aplikacji](http://msdn.microsoft.com/en-us/8eca8743-8e68-4d04-bfd5-4dc0a9b2934f)."
  example:
  - "The following code example uses <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/t-system.deployment.appl_8_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public class UpdateCheckInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera numer wersji najnowszej wersji niezainstalowana."
  remarks: "AvailableVersion służy do określenia, czy do zainstalowania aktualizacji na podstawie ich wagi aktualizacji. Na przykład, jeśli tylko <xref:System.Version.Build%2A>lub <xref:System.Version.Revision%2A>wersji właściwości zostały zmienione, aplikacja nie może być konieczne zaktualizowanie aż do otrzymania <xref:System.Version.Minor%2A>lub <xref:System.Version.Major%2A>zmiany właściwości.</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "<xref:System.Version>Wyrażanie główne i pomocnicze numerów kompilacji i poprawce najnowszej wersji.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera wartość wskazującą, czy aktualizacja musi być zainstalowana."
  remarks: "Podczas wdrażania aktualizacji musi spełniać aplikacja ClickOnce, można oznaczyć go jako wymagana aktualizacja sygnalizowania do aplikacji, czy należy uaktualnić natychmiast. Chcesz oznaczyć aplikacji, jeśli krytycznych aktualizacji zawiera najnowszą wersję lub jest niezgodna z formatów plików lub źródeł danych zaplecza używanych przez wcześniejsze wersji."
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_6_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli aktualizacja jest wymagana; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera minimalną wersją, użytkownik musi być zainstalowany na komputerze."
  remarks: "Aplikacje można pominąć wymagane aktualizacje, gdy użytkownik ma specjalne przydziału lub jest od komputera, tygodnie lub miesiące. Użyj parametru MinimumRequiredVersion, aby ustalić, czy użytkownik nie została uaktualniona aplikacji za pewien czas i brakuje co najmniej jednego z wymaganych aktualizacji."
  example:
  - "The following code example demonstrates displaying the MinimumRequiredVersion property to the user when there is a required update available.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "A <xref:System.Version>wyrażanie co najmniej wersję, do której użytkownik musi zainstalować.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Nie ma nowych wersji dostępny do zainstalowania."
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera informacje, czy dostępna jest aktualizacja niezainstalowana."
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_10_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli nowa wersja aplikacji jest dostępna; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Pobiera rozmiar dostępnych aktualizacji."
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "<xref:System.Int64>Opisujące rozmiar w bajtach dostępnej aktualizacji.</xref:System.Int64> Jeśli nie jest dostępna żadna aktualizacja, zwraca wartość 0."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
