### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingSectionGroup
  id: ScriptingSectionGroup
  children:
  - System.Web.Configuration.ScriptingSectionGroup.#ctor
  - System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  - System.Web.Configuration.ScriptingSectionGroup.WebServices
  langs:
  - csharp
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup
  fullName: System.Web.Configuration.ScriptingSectionGroup
  type: Class
  summary: "Reprezentuje sekcję konfiguracji dla ustawień skryptów. Ta klasa nie może być dziedziczona."
  remarks: "Użyj klasy ScriptingSectionGroup programowo ustawiania i pobierania wartości `scripting` sekcji pliku konfiguracji."
  syntax:
    content: 'public sealed class ScriptingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: ScriptingSectionGroup()
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup()
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptingSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.ScriptingSectionGroup&quot;> </xref> klasy."
  syntax:
    content: public ScriptingSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.ScriptingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  id: ScriptResourceHandler
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Pobiera <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;> </xref> obiekt, który jest określana na podstawie bieżącej konfiguracji systemu."
  remarks: "Użyj `ScriptingScriptResourceHandler` sekcji konfiguracji, aby określić, czy pliki skryptów są osadzone w pamięci podręcznej i skompresowane zasobów. Można włączyć lub wyłączyć kompresję i buforowanie przy użyciu <xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression%2A>i <xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching%2A>Właściwości.</xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching%2A> </xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression%2A>"
  syntax:
    content: public System.Web.Configuration.ScriptingScriptResourceHandlerSection ScriptResourceHandler { get; }
    return:
      type: System.Web.Configuration.ScriptingScriptResourceHandlerSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices
  id: WebServices
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
  fullName: System.Web.Configuration.ScriptingSectionGroup.WebServices
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Pobiera <xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;> </xref> obiekt, który jest określana na podstawie bieżącej konfiguracji systemu."
  syntax:
    content: public System.Web.Configuration.ScriptingWebServicesSectionGroup WebServices { get; }
    return:
      type: System.Web.Configuration.ScriptingWebServicesSectionGroup
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingSectionGroup.WebServices*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptingSectionGroup()
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup()
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptingSectionGroup()
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
  fullName: System.Web.Configuration.ScriptingSectionGroup.WebServices
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
