### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSavingEventHandler
  id: SettingsSavingEventHandler
  langs:
  - csharp
  name: SettingsSavingEventHandler
  nameWithType: SettingsSavingEventHandler
  fullName: System.Configuration.SettingsSavingEventHandler
  type: Delegate
  summary: "Reprezentuje metodę, która będzie obsługiwać <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsSaving&quot;> </xref> zdarzeń."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>Zdarzenie tuż przed grupy aplikacji, które ustawienia są trwałe, zazwyczaj podczas wykonywania <xref:System.Configuration.ApplicationSettingsBase.Save%2A>metody klasy otoki pochodną <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Save%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>"
  syntax:
    content: public delegate void SettingsSavingEventHandler(object sender, CancelEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
