### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.VirtualDirectoryMapping
  id: VirtualDirectoryMapping
  children:
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  - System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  - System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  - System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  - System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  langs:
  - csharp
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping
  fullName: System.Web.Configuration.VirtualDirectoryMapping
  type: Class
  summary: "Określa niestandardowy hierarchii katalog wirtualny dla aplikacji sieci Web. Ta klasa nie może być dziedziczona."
  syntax:
    content: public sealed class VirtualDirectoryMapping
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> klasy na podstawie dostarczonych parametrów."
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "Wartość ciągu, który określa bezwzględną ścieżkę do katalogu fizycznego."
    - id: isAppRoot
      type: System.Boolean
      description: "Wartość logiczna, która wskazuje, czy wirtualnego katalogu głównego aplikacji, aplikacji sieci Web."
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  id: '#ctor(System.String,System.Boolean,System.String)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> klasy na podstawie dostarczonych parametrów."
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot, string configFileBaseName);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "Wartość ciągu, który określa bezwzględną ścieżkę do katalogu fizycznego."
    - id: isAppRoot
      type: System.Boolean
      description: "Wartość logiczna, która wskazuje, czy wirtualnego katalogu głównego aplikacji, aplikacji sieci Web."
    - id: configFileBaseName
      type: System.String
      description: "Nazwa pliku konfiguracji."
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  id: ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia nazwę pliku konfiguracji."
  remarks: "Jeśli nazwa pliku konfiguracji nie jest określona, plik Web.config jest używany."
  syntax:
    content: public string ConfigFileBaseName { get; set; }
    return:
      type: System.String
      description: "Wartość, która wskazuje nazwę pliku konfiguracji."
  overload: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Wybrana wartość ma wartość null lub pustego ciągu (&quot;&quot;)."
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  id: IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia wartość wskazującą, czy katalog wirtualny powinien być traktowany jako katalog główny aplikacji."
  syntax:
    content: public bool IsAppRoot { get; set; }
    return:
      type: System.Boolean
      description: "Wartość, która wskazuje, czy katalog wirtualny powinien być traktowany jako katalog główny aplikacji."
  overload: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  id: PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera lub ustawia wartość, która określa pełną ścieżkę serwerową aplikacji sieci Web."
  syntax:
    content: public string PhysicalDirectory { get; set; }
    return:
      type: System.String
      description: "Wartość, która wskazuje pełną ścieżkę serwerową aplikacji sieci Web."
  overload: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Wybrana wartość jest nieprawidłowa lub nie powiedzie się wewnętrzny walidacji."
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  id: VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera wartość, która określa wirtualny katalog względem katalogu głównego serwera sieci Web."
  syntax:
    content: public string VirtualDirectory { get; }
    return:
      type: System.String
      description: "Wartość, która określa względne katalog aplikacji sieci Web."
  overload: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
