### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyValidationConverter
  id: MachineKeyValidationConverter
  children:
  - System.Web.Configuration.MachineKeyValidationConverter.#ctor
  - System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Web.Configuration.MachineKeyValidationConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: MachineKeyValidationConverter
  nameWithType: MachineKeyValidationConverter
  fullName: System.Web.Configuration.MachineKeyValidationConverter
  type: Class
  summary: "Udostępnia metody do konwersji <xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> obiektów do i z ciągów."
  remarks: >-
    > [!NOTE]

    >  The <xref:System.Security.Permissions.HostProtectionAttribute> attribute applied to this class has the following <xref:System.Security.Permissions.HostProtectionAttribute.Resources%2A> property value: <xref:System.Security.Permissions.HostProtectionResource>. The <xref:System.Security.Permissions.HostProtectionAttribute> does not affect desktop applications (which are typically started by double-clicking an icon, typing a command, or entering a URL in a browser). For more information, see the <xref:System.Security.Permissions.HostProtectionAttribute> class or [SQL Server Programming and Host Protection Attributes](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: 'public sealed class MachineKeyValidationConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidationConverter.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.MachineKeyValidationConverter
  langs:
  - csharp
  name: MachineKeyValidationConverter()
  nameWithType: MachineKeyValidationConverter.MachineKeyValidationConverter()
  fullName: System.Web.Configuration.MachineKeyValidationConverter.MachineKeyValidationConverter()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.MachineKeyValidationConverter&quot;> </xref> klasy."
  syntax:
    content: public MachineKeyValidationConverter ();
    parameters: []
  overload: System.Web.Configuration.MachineKeyValidationConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Web.Configuration.MachineKeyValidationConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: MachineKeyValidationConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Konwertuje ciąg na równoważne <xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> wartości."
  remarks: "Ta metoda zgłosi <xref:System.ArgumentException>wyjątek Jeśli `data` parametr odwołuje się do jednego z następujących ciągów: - SHA1 - MD5 - 3DES - AES</xref:System.ArgumentException>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Ten parametr nie jest używany."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Ten parametr nie jest używany."
    - id: data
      type: System.Object
      description: "Ciąg do przekonwertowania."
    return:
      type: System.Object
      description: "Odpowiednik <xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> wartości."
  overload: System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Dane nie jest jednym z oczekiwanym ciągów."
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidationConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Web.Configuration.MachineKeyValidationConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: MachineKeyValidationConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Web.Configuration.MachineKeyValidationConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Konwertuje <xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> wartość reprezentację ciągu tej wartości."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Ten parametr nie jest używany."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Ten parametr nie jest używany."
    - id: value
      type: System.Object
      description: "<xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> Do skonwertowania."
    - id: type
      type: System.Type
      description: "Ten parametr nie jest używany."
    return:
      type: System.Object
      description: "Ciąg reprezentujący <xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> wartości."
  overload: System.Web.Configuration.MachineKeyValidationConverter.ConvertTo*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code> value </code> Parametru nie jest jednym z oczekiwanej wartości."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code> value </code> Parametr nie jest <xref href=&quot;System.Web.Configuration.MachineKeyValidation&quot;> </xref> obiektu."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Web.Configuration.MachineKeyValidationConverter.#ctor
  parent: System.Web.Configuration.MachineKeyValidationConverter
  isExternal: false
  name: MachineKeyValidationConverter()
  nameWithType: MachineKeyValidationConverter.MachineKeyValidationConverter()
  fullName: System.Web.Configuration.MachineKeyValidationConverter.MachineKeyValidationConverter()
- uid: System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Web.Configuration.MachineKeyValidationConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: MachineKeyValidationConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Web.Configuration.MachineKeyValidationConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Web.Configuration.MachineKeyValidationConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: MachineKeyValidationConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Web.Configuration.MachineKeyValidationConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Configuration.MachineKeyValidationConverter.#ctor*
  parent: System.Web.Configuration.MachineKeyValidationConverter
  isExternal: false
  name: MachineKeyValidationConverter
  nameWithType: MachineKeyValidationConverter.MachineKeyValidationConverter
- uid: System.Web.Configuration.MachineKeyValidationConverter.ConvertFrom*
  parent: System.Web.Configuration.MachineKeyValidationConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: MachineKeyValidationConverter.ConvertFrom
- uid: System.Web.Configuration.MachineKeyValidationConverter.ConvertTo*
  parent: System.Web.Configuration.MachineKeyValidationConverter
  isExternal: false
  name: ConvertTo
  nameWithType: MachineKeyValidationConverter.ConvertTo
