### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebControlsSection
  id: WebControlsSection
  children:
  - System.Web.Configuration.WebControlsSection.#ctor
  - System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  - System.Web.Configuration.WebControlsSection.GetRuntimeObject
  - System.Web.Configuration.WebControlsSection.Properties
  langs:
  - csharp
  name: WebControlsSection
  nameWithType: WebControlsSection
  fullName: System.Web.Configuration.WebControlsSection
  type: Class
  summary: "Konfiguruje <xref uid=&quot;langword_csharp_webControls&quot; name=&quot;webControls&quot; href=&quot;&quot;> </xref> sekcji. Ta klasa nie może być dziedziczona."
  remarks: "Klasa WebControlsSection umożliwia programowo modyfikacji i dostępu `webControls` sekcji pliku konfiguracji.      > [!NOTE] > Program ASP.NET udostępnia współdzielonej lokalizacji dla klienta plików skryptów, gdy są one dostępne z wielu stron i w aplikacjach.  WebControlsSection może odczytywać i zapisywać informacje od i do sekcji pliku konfiguracji zgodnie z sekcji właściwości, <xref:System.Configuration.SectionInformation.AllowDefinition%2A>której wartość jest <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> pokrewne"
  example:
  - "The following code example shows how to obtain the WebControlsSection object from the configuration file associated with an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.WebControlsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_45_1.vb)]\n [!code-cs[System.Web.Configuration.WebControlsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_45_1.cs)]"
  syntax:
    content: 'public sealed class WebControlsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.WebControlsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: WebControlsSection()
  nameWithType: WebControlsSection.WebControlsSection()
  fullName: System.Web.Configuration.WebControlsSection.WebControlsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.WebControlsSection&quot;> </xref>."
  remarks: "Konstruktor WebControlsSection nie jest przeznaczona do użycia bezpośrednio w kodzie. Jest ona wywoływana przez system konfiguracji programu ASP.NET. Uzyskać wystąpienia <xref:System.Web.Configuration.WebControlsSection>przy użyciu <xref:System.Configuration.Configuration.GetSection%2A>metody.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.WebControlsSection>"
  syntax:
    content: public WebControlsSection ();
    parameters: []
  overload: System.Web.Configuration.WebControlsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  id: ClientScriptsLocation
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: ClientScriptsLocation
  nameWithType: WebControlsSection.ClientScriptsLocation
  fullName: System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Pobiera klienta skryptów lokalizacji."
  remarks: "Aby uzyskać więcej informacji o skrypty klienta i ich użycia, zapoznaj się [skrypt po stronie klienta w programie ASP.NET Web Pages](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following code example shows how to obtain the ClientScriptsLocation.  \n  \n [!code-vb[System.Web.Configuration.WebControlsSection#1](~/add/codesnippet/visualbasic/p-system.web.configurati_171_1.vb)]\n [!code-cs[System.Web.Configuration.WebControlsSection#1](~/add/codesnippet/csharp/p-system.web.configurati_171_1.cs)]"
  syntax:
    content: public string ClientScriptsLocation { get; }
    return:
      type: System.String
      description: "Lokalizacja skrypty klienta."
  overload: System.Web.Configuration.WebControlsSection.ClientScriptsLocation*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebControlsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: WebControlsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebControlsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: "Do dodania."
  overload: System.Web.Configuration.WebControlsSection.GetRuntimeObject*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebControlsSection.Properties
  id: Properties
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: Properties
  nameWithType: WebControlsSection.Properties
  fullName: System.Web.Configuration.WebControlsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.WebControlsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.WebControlsSection.#ctor
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: WebControlsSection()
  nameWithType: WebControlsSection.WebControlsSection()
  fullName: System.Web.Configuration.WebControlsSection.WebControlsSection()
- uid: System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: ClientScriptsLocation
  nameWithType: WebControlsSection.ClientScriptsLocation
  fullName: System.Web.Configuration.WebControlsSection.ClientScriptsLocation
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebControlsSection.GetRuntimeObject
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: WebControlsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebControlsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebControlsSection.Properties
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: Properties
  nameWithType: WebControlsSection.Properties
  fullName: System.Web.Configuration.WebControlsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebControlsSection.#ctor*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: WebControlsSection
  nameWithType: WebControlsSection.WebControlsSection
- uid: System.Web.Configuration.WebControlsSection.ClientScriptsLocation*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: ClientScriptsLocation
  nameWithType: WebControlsSection.ClientScriptsLocation
- uid: System.Web.Configuration.WebControlsSection.GetRuntimeObject*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: WebControlsSection.GetRuntimeObject
- uid: System.Web.Configuration.WebControlsSection.Properties*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: Properties
  nameWithType: WebControlsSection.Properties
