### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyNotFoundException
  id: SettingsPropertyNotFoundException
  children:
  - System.Configuration.SettingsPropertyNotFoundException.#ctor
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyNotFoundException
  nameWithType: SettingsPropertyNotFoundException
  fullName: System.Configuration.SettingsPropertyNotFoundException
  type: Class
  summary: "Zawiera wyjątek dla <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> obiektów, które nie zostały znalezione."
  remarks: "Ten wyjątek jest zgłaszany przez <xref:System.Configuration.SettingsBase>klasy podczas próby dostępu do właściwości według nazwy, ale każda właściwość nigdy nie został skojarzony z <xref:System.Configuration.SettingsBase>wystąpienia klasy lub dostawcy skonfigurowane dla właściwości nie zwrócił wartość, gdy żądanie załadowania danych właściwości.</xref:System.Configuration.SettingsBase> </xref:System.Configuration.SettingsBase>"
  syntax:
    content: 'public class SettingsPropertyNotFoundException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException()
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> klasy."
  syntax:
    content: public SettingsPropertyNotFoundException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(String)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> klasy, na podstawie dostarczonego parametru."
  syntax:
    content: public SettingsPropertyNotFoundException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Ciąg zawierający komunikat o wyjątku."
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> klasy oparte na podanych parametrów."
  syntax:
    content: protected SettingsPropertyNotFoundException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> Obiekt przechowujący dane zserializowanego obiektu dotyczące zgłaszanego wyjątku."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>Obiekt zawierający informacje kontekstowe dotyczące źródła lub miejsca docelowego w strumieniu serializowanym.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyNotFoundException
  langs:
  - csharp
  name: SettingsPropertyNotFoundException(String,Exception)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyNotFoundException&quot;> </xref> klasy oparte na podanych parametrów."
  syntax:
    content: public SettingsPropertyNotFoundException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Ciąg zawierający komunikat o wyjątku."
    - id: innerException
      type: System.Exception
      description: "Wyjątek będący przyczyną bieżącego wyjątku."
  overload: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException()
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException()
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(String)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException(String,Exception)
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
  fullName: System.Configuration.SettingsPropertyNotFoundException.SettingsPropertyNotFoundException(String,Exception)
- uid: System.Configuration.SettingsPropertyNotFoundException.#ctor*
  parent: System.Configuration.SettingsPropertyNotFoundException
  isExternal: false
  name: SettingsPropertyNotFoundException
  nameWithType: SettingsPropertyNotFoundException.SettingsPropertyNotFoundException
