### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.ChannelCacheSettings
  id: ChannelCacheSettings
  children:
  - System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  - System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  - System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  - System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  langs:
  - csharp
  name: ChannelCacheSettings
  nameWithType: ChannelCacheSettings
  fullName: System.ServiceModel.Activities.ChannelCacheSettings
  type: Class
  summary: "Reprezentuje ustawienia, które definiują operacyjne właściwości pamięci podręcznej kanału."
  remarks: ''
  example:
  - "The following example shows how to create a ChannelCacheSettings instance.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/t-system.servicemodel.ac_21_1.cs)]"
  syntax:
    content: public class ChannelCacheSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: ChannelCacheSettings()
  nameWithType: ChannelCacheSettings.ChannelCacheSettings()
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.ChannelCacheSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Tworzy nowe wystąpienie klasy <xref href=&quot;System.ServiceModel.Activities.ChannelCacheSettings&quot;> </xref> klasy."
  remarks: ''
  example:
  - "The following example shows how to create a <xref:System.ServiceModel.Activities.ChannelCacheSettings> instance.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/m-system.servicemodel.ac_8_1.cs)]"
  syntax:
    content: public ChannelCacheSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.ChannelCacheSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Pobiera maksymalny przedział czasu, dla którego obiekt może pozostawać bezczynny w pamięci podręcznej zanim zostanie usunięty."
  remarks: ''
  example:
  - "The following example shows how to set the IdleTimeout property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/p-system.servicemodel.ac_2_1.cs)]"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Interwał czasu."
  overload: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Pobiera przedział czasu, po którym obiekt zostanie usunięty z pamięci podręcznej."
  remarks: ''
  example:
  - "The following example shows how to set the LeaseTimeout property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/p-system.servicemodel.ac_6_1.cs)]"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Interwał czasu."
  overload: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  id: MaxItemsInCache
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Pobiera maksymalną liczbę obiektów, które mogą znajdować się w pamięci podręcznej."
  remarks: ''
  example:
  - "The following example shows how to set the MaxItemsInCache property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/p-system.servicemodel.ac_1_1.cs)]"
  syntax:
    content: public int MaxItemsInCache { get; set; }
    return:
      type: System.Int32
      description: "Maksymalna liczba obiektów."
  overload: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: ChannelCacheSettings()
  nameWithType: ChannelCacheSettings.ChannelCacheSettings()
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.ChannelCacheSettings()
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: ChannelCacheSettings
  nameWithType: ChannelCacheSettings.ChannelCacheSettings
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
