### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  id: TableLayoutSettingsTypeConverter
  children:
  - System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.#ctor
  - System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TableLayoutSettingsTypeConverter
  nameWithType: TableLayoutSettingsTypeConverter
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  type: Class
  summary: "Umożliwia ujednoliconego konwersji typów wartości do innych typów, a także do uzyskiwania dostępu do wartości domyślnych i podrzędnych."
  syntax:
    content: 'public class TableLayoutSettingsTypeConverter : System.ComponentModel.TypeConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  platform:
  - net462
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.#ctor
  id: '#ctor'
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  langs:
  - csharp
  name: TableLayoutSettingsTypeConverter()
  nameWithType: TableLayoutSettingsTypeConverter.TableLayoutSettingsTypeConverter()
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.TableLayoutSettingsTypeConverter()
  type: Constructor
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.Layout
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter&quot;> </xref> klasy."
  syntax:
    content: public TableLayoutSettingsTypeConverter ();
    parameters: []
  overload: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  langs:
  - csharp
  name: CanConvertFrom(ITypeDescriptorContext,Type)
  nameWithType: TableLayoutSettingsTypeConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.Layout
  summary: "Określa, czy ten konwerter można przekonwertować obiektu dla typu źródłowego danego na typ macierzysty tego konwertera."
  syntax:
    content: public override bool CanConvertFrom (System.ComponentModel.ITypeDescriptorContext context, Type sourceType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> Zapewnia kontekstu formatu."
    - id: sourceType
      type: System.Type
      description: "A <xref:System.Type>reprezentujący chcesz konwertować z typu.</xref:System.Type>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli ten konwerter można dokonać konwersji; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  langs:
  - csharp
  name: CanConvertTo(ITypeDescriptorContext,Type)
  nameWithType: TableLayoutSettingsTypeConverter.CanConvertTo(ITypeDescriptorContext,Type)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo(ITypeDescriptorContext,Type)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.Layout
  summary: "Zwraca wartość wskazującą, czy ten konwerter można przekonwertować obiektu na typ docelowy danego przy użyciu kontekstu."
  syntax:
    content: public override bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext context, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> Zapewnia kontekstu formatu."
    - id: destinationType
      type: System.Type
      description: "A <xref:System.Type>reprezentujący ma zostać przekonwertowany na typ.</xref:System.Type>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli ten konwerter można dokonać konwersji; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TableLayoutSettingsTypeConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.Layout
  summary: "Konwertuje dany obiekt typu konwertera przy użyciu określonego kontekstu i informacji o kulturze."
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> Zapewnia kontekstu formatu."
    - id: culture
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>Do użycia jako bieżącej kultury.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "<xref:System.Object>Do przekonwertowania.</xref:System.Object>"
    return:
      type: System.Object
      description: "<xref:System.Object>Reprezentujący wartość przekonwertowana.</xref:System.Object>"
  overload: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TableLayoutSettingsTypeConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms.Layout
  summary: "Konwertuje obiekt podanej wartości na określony typ przy użyciu określonego kontekstu i informacji o kulturze."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> Zapewnia kontekstu formatu."
    - id: culture
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>Do użycia jako bieżącej kultury.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "<xref:System.Object>Do przekonwertowania.</xref:System.Object>"
    - id: destinationType
      type: System.Type
      description: "<xref:System.Type>Można przekonwertować wartości parametru do.</xref:System.Type>"
    return:
      type: System.Object
      description: "<xref:System.Object>Reprezentujący wartość przekonwertowana.</xref:System.Object>"
  overload: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>destinationType</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
references:
- uid: System.ComponentModel.TypeConverter
  isExternal: false
  name: System.ComponentModel.TypeConverter
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.#ctor
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: TableLayoutSettingsTypeConverter()
  nameWithType: TableLayoutSettingsTypeConverter.TableLayoutSettingsTypeConverter()
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.TableLayoutSettingsTypeConverter()
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: CanConvertFrom(ITypeDescriptorContext,Type)
  nameWithType: TableLayoutSettingsTypeConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom(ITypeDescriptorContext,Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: CanConvertTo(ITypeDescriptorContext,Type)
  nameWithType: TableLayoutSettingsTypeConverter.CanConvertTo(ITypeDescriptorContext,Type)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo(ITypeDescriptorContext,Type)
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TableLayoutSettingsTypeConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TableLayoutSettingsTypeConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.#ctor*
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: TableLayoutSettingsTypeConverter
  nameWithType: TableLayoutSettingsTypeConverter.TableLayoutSettingsTypeConverter
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertFrom*
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: CanConvertFrom
  nameWithType: TableLayoutSettingsTypeConverter.CanConvertFrom
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.CanConvertTo*
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: CanConvertTo
  nameWithType: TableLayoutSettingsTypeConverter.CanConvertTo
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom*
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TableLayoutSettingsTypeConverter.ConvertFrom
- uid: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertTo*
  parent: System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TableLayoutSettingsTypeConverter.ConvertTo
