### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  id: WorkflowRuntimeServiceElement
  children:
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  langs:
  - csharp
  name: WorkflowRuntimeServiceElement
  nameWithType: WorkflowRuntimeServiceElement
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  type: Class
  summary: "Reprezentuje element konfiguracji dla usługi do dodania do aparatu wykonawczego workflow."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]WorkflowRuntimeServiceElement określa usługi hosta, który należy zainicjować i aktywowany przez aparat środowiska uruchomieniowego przepływu pracy. Odnosi się do usługi hosta określona w `Services`> w pliku konfiguracji. Ponieważ usługi określone w WorkflowRuntimeServiceElement zostaną zainicjowane przez aparat środowiska uruchomieniowego przepływu pracy musi mieć co najmniej jeden konstruktor, który pasuje do jednej z następujących czterech podpisów (aparatu wykonawczego workflow będzie podjąć próbę dopasowania tymi podpisami w podanej kolejności): Service(WorkflowRuntime runtime, NameValueCollection parameters) Service(WorkflowRuntime runtime) Service(NameValueCollection parameters) Service()"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowRuntimeServiceElement : System.Configuration.ConfigurationElement
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  id: '#ctor'
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: WorkflowRuntimeServiceElement()
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  type: Constructor
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement&quot;> </xref> klasy."
  remarks: "Jeśli używasz tego konstruktora, musisz jawnie ustawić <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type%2A>.</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type%2A>"
  syntax:
    content: public WorkflowRuntimeServiceElement ();
    parameters: []
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Wywoływane, gdy podczas deserializacji napotkano nieznany atrybut <xref href=&quot;System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement&quot;> </xref>."
  remarks: "Pary nazwa wartość, określony przez nazwę i wartość jest dodawana do <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A>kolekcji.</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A> Wszelkie atrybuty innych niż `type` określono w `add`> elementu `Services`> w pliku konfiguracji są dodawane jako pary nazwa wartość do <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A>kolekcji.</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A>"
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "Nazwa nierozpoznany atrybut."
    - id: value
      type: System.String
      description: "Wartość nierozpoznany atrybut."
    return:
      type: System.Boolean
      description: "Zawsze zwraca OnDeserializeUnrecognizedAttribute <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  id: Parameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Pobiera parametry dla tej usługi."
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Parameters { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "A <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> , który określa parametry dla usługi."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  id: Type
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Pobiera lub ustawia nazwę typu kwalifikowanego zestawu usługi."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Nazwa typu kwalifikowanego zestawu usługi."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Podejmowana jest próba Ustaw typ odwołanie o wartości null."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: WorkflowRuntimeServiceElement()
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: WorkflowRuntimeServiceElement
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
