### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  id: AssemblyVersionCompatibility
  children:
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  langs:
  - csharp
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
  type: Enum
  summary: "Definiuje różne typy zgodność wersji zestawu. Ta funkcja nie jest dostępna w wersji 1.0 programu .NET Framework."
  remarks: "`AssemblyVersionCompatibility`Definiuje zgodności zestawu z innymi wersjami tego samego zestawu, wskazując, jeśli nie można wykonać side-by-side z innymi wersjami (na przykład z powodu konfliktów za pośrednictwem sterownika urządzenia).       Jeśli określono nie zgodności, zestawu może być side-by-side w wszystkich zakresów.       Nie można bardziej szczegółowe względem dokładnie które poprzednich wersji jest niezgodny z side-by-side z zestawu. W związku z tym jeśli `AssemblyVersionCompatibility` jest określony, oznacza to zestaw jest z systemem innym niż side-by-side ze wszystkimi znać wersji. Jeśli nie zostanie określony, oznacza to side-by-side ze wszystkimi wersjami znane."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyVersionCompatibility
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  id: SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Zestaw nie można wykonać z innymi wersjami, jeśli są one wykonywane w tej samej domenie aplikacji."
  syntax:
    content: SameDomain
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  id: SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Zestaw nie można wykonać z innymi wersjami, jeśli są one wykonywane na tym samym komputerze."
  syntax:
    content: SameMachine
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  id: SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Zestaw nie można wykonać z innymi wersjami, jeśli są one wykonywane w ramach tego samego procesu."
  syntax:
    content: SameProcess
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
