### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadUtil
  id: IApplicationPreloadUtil
  children:
  - System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  - System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  langs:
  - csharp
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
  type: Interface
  summary: "Udostępnia metody używane do komunikacji z ASP.NET [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] podczas serwera wstępnie ładuje aplikację."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("940D8ADD-9E40-4475-9A67-2CDCDF57995C")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadUtil
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  id: GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  langs:
  - csharp
  name: GetApplicationPreloadInfo(String,Boolean,String,String[])
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  fullName: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Pobiera dane inicjowania jest wymagany w celu wstępnego załadowania aplikacji. Ta metoda jest wywoływana przez platformę ASP.NET."
  syntax:
    content: public void GetApplicationPreloadInfo (string context, out bool enabled, out string startupObjType, out string[] parametersForStartupObj);
    parameters:
    - id: context
      type: System.String
      description: "Kontekst aplikacji."
    - id: enabled
      type: System.Boolean
      description: "Po powrocie z tej metody zawiera <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref> aby wskazać, że aplikacja musi być wstępnie; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Ten parametr jest przekazywany jako niezainicjowany."
    - id: startupObjType
      type: System.String
      description: "Po powrocie z tej metody zawiera ciąg identyfikujący typ zarządzany, który jest częścią procesu wstępnego ładowania. Ten parametr jest przekazywany jako niezainicjowany."
    - id: parametersForStartupObj
      type: System.String[]
      description: "Gdy metoda zwróci wartość, zawiera dane, które zostaną przekazane do wstępnie typu. Ten parametr jest przekazywany jako niezainicjowany."
  overload: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  id: ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  langs:
  - csharp
  name: ReportApplicationPreloadFailure(String,Int32,String)
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  fullName: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Raporty, które wystąpił błąd podczas [!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)] podczas, gdy serwer został wstępnego ładowania aplikacji ASP.NET."
  syntax:
    content: public void ReportApplicationPreloadFailure (string context, int errorCode, string errorMessage);
    parameters:
    - id: context
      type: System.String
      description: "Kontekst aplikacji."
    - id: errorCode
      type: System.Int32
      description: "Kod błędu liczbowych."
    - id: errorMessage
      type: System.String
      description: "Tekst błędu."
  overload: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: GetApplicationPreloadInfo(String,Boolean,String,String[])
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  fullName: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: ReportApplicationPreloadFailure(String,Int32,String)
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  fullName: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo*
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: GetApplicationPreloadInfo
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure*
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: ReportApplicationPreloadFailure
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure
