### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  id: BrowserCapabilitiesCodeGenerator
  children:
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  type: Class
  summary: "Klasa BrowserCapabilitiesCodeGenerator jest używana wewnętrznie przez <xref uid=&quot;langword_csharp_aspnet_regbrowsers&quot; name=&quot;aspnet_regbrowsers&quot; href=&quot;&quot;> </xref> narzędzie do analizy plików definicji przeglądarki .browser i Dodaj przeglądarki do zbierania czasu wykonywania znanych przeglądarek zawarte w <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;> </xref> obiektu."
  remarks: "Ta klasa generuje kod źródłowy dla zestawu pod kątem <xref:System.Web.Configuration.BrowserCapabilitiesFactory>klasy, która w czasie wykonywania, tworzy żądanie dotyczące <xref:System.Web.Configuration.HttpCapabilitiesBase>obiektów publicznie można uzyskać dostęp za pomocą wewnętrznej ASP.NET `Request.Browser` właściwości.</xref:System.Web.Configuration.HttpCapabilitiesBase> </xref:System.Web.Configuration.BrowserCapabilitiesFactory>"
  syntax:
    content: public class BrowserCapabilitiesCodeGenerator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w celu utworzenia nowego wystąpienia <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;> </xref>."
  syntax:
    content: public BrowserCapabilitiesCodeGenerator ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  id: Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Używana wewnętrznie w celu koordynowania zachowanie tej klasy."
  remarks: "Ta metoda najpierw iterację w folderze &quot;Przeglądarki&quot;. Następnie wywołuje <xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A>, który ładuje i analizuje kod XML znajdujący się w kolekcji definicji przeglądarki plików i wstawia informacje w nim zawarte w wewnętrznej kolekcji przeglądarki.</xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A> A następnie wywołuje metody wewnętrznej, które generuje kompiluje kod źródłowy i rejestruje go jako zestawu w GAC pamięci podręcznej <xref:System.Web.Configuration.BrowserCapabilitiesFactory>obiektu.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> Jeśli to konieczne, ta metoda wywołuje metody wewnętrznej, który powoduje ponowne uruchomienie serwera sieci Web."
  syntax:
    content: public virtual void Create ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  id: ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ładuje i analizuje kod XML znajdujący się w kolekcji plików definicji przeglądarki i wstawia informacje w nim zawarte w wewnętrznej kolekcji przeglądarki."
  syntax:
    content: protected void ProcessBrowserFiles (bool useVirtualPath, string virtualDir);
    parameters:
    - id: useVirtualPath
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Aby użyć ścieżki wirtualnej; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: virtualDir
      type: System.String
      description: "Ścieżka do katalogu wirtualnego, który zawiera pliki definicji przeglądarki. Wartość domyślna to <xref:System.String>.</xref:System.String>"
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  exceptions:
  - type: System.Web.HttpParseException
    commentId: T:System.Web.HttpParseException
    description: "One of the browser-definition files does not have a root element named \"browsers\".  \n  \n \\- or -  \n  \n One of the browser-definition files fails to load."
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  id: Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Usuwa fabryki możliwości przeglądarki z globalnej pamięci podręcznej zestawów i jego silnej nazwy pliku klucza publicznego tokenu."
  remarks: "Ta metoda powoduje ponowne uruchomienie usługi sieci Web. Fabryka możliwości przeglądarki, po czym usunięto z pamięci podręcznej GAC i jego silnej nazwy pliku klucza publicznego token jest usuwany. Usługi sieci Web zostanie następnie ponownie ponownie, jeśli Dezinstalacja zakończy się powodzeniem."
  syntax:
    content: public bool Uninstall ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli fabryki funkcji przeglądarki został odinstalowany z globalnej pamięci podręcznej zestawów; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.HttpParseException
  parent: System.Web
  isExternal: false
  name: HttpParseException
  nameWithType: HttpParseException
  fullName: System.Web.HttpParseException
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create
  nameWithType: BrowserCapabilitiesCodeGenerator.Create
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall
