### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCaches
  id: IdentityModelCaches
  children:
  - System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  - System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches
  fullName: System.IdentityModel.Configuration.IdentityModelCaches
  type: Class
  summary: "Definiuje pamięci podręczne, które są skonfigurowane do wykrywania powtórzony tokeny i pamięci podręcznej sesji tokenów. Ta klasa nie może być dziedziczona."
  remarks: "Pobiera i ustawia skonfigurowany <xref:System.IdentityModel.Tokens.TokenReplayCache>i <xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>.</xref:System.IdentityModel.Tokens.SessionSecurityTokenCache> </xref:System.IdentityModel.Tokens.TokenReplayCache> `Caches` Właściwość <xref:System.IdentityModel.Configuration.IdentityConfiguration>klasy i <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration>Klasa jest wystąpieniem IdentityModelCaches.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration> </xref:System.IdentityModel.Configuration.IdentityConfiguration>"
  syntax:
    content: public sealed class IdentityModelCaches
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.Configuration.IdentityModelCaches&quot;> </xref> klasy."
  syntax:
    content: public IdentityModelCaches ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Pobiera lub ustawia <xref href=&quot;System.IdentityModel.Tokens.SessionSecurityTokenCache&quot;> </xref> używany do pamięci podręcznej <xref href=&quot;System.IdentityModel.Tokens.SessionSecurityToken&quot;> </xref>."
  syntax:
    content: public System.IdentityModel.Tokens.SessionSecurityTokenCache SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.SessionSecurityTokenCache
      description: "Skonfigurowanych sesji tokenu pamięć podręczna."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Próba ustawioną właściwość <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> występuje."
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Pobiera lub ustawia <xref href=&quot;System.IdentityModel.Tokens.TokenReplayCache&quot;> </xref> używany do określenia, czy tokeny są odtwarzane."
  syntax:
    content: public System.IdentityModel.Tokens.TokenReplayCache TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.TokenReplayCache
      description: "Pamięć podręczna skonfigurowanych powtórzeń tokenów."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Próba ustawioną właściwość <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> występuje."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Tokens.SessionSecurityTokenCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: SessionSecurityTokenCache
  fullName: System.IdentityModel.Tokens.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
- uid: System.IdentityModel.Tokens.TokenReplayCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: TokenReplayCache
  nameWithType: TokenReplayCache
  fullName: System.IdentityModel.Tokens.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches.IdentityModelCaches
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
