### YamlMime:ManagedReference
items:
- uid: System.Web.Management.WebApplicationLifetimeEvent
  id: WebApplicationLifetimeEvent
  children:
  - System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  - System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  - System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  langs:
  - csharp
  name: WebApplicationLifetimeEvent
  nameWithType: WebApplicationLifetimeEvent
  fullName: System.Web.Management.WebApplicationLifetimeEvent
  type: Class
  summary: "Reprezentuje znaczącego zdarzenia w okresie istnienia aplikacji."
  remarks: "Monitorowanie kondycji ASP.NET umożliwia pracownikom produkcyjnego i operacji zarządzania wdrożonej aplikacji sieci Web. <xref:System.Web.Management>Przestrzeń nazw zawiera typy kondycji zdarzenie odpowiedzialnych za tworzenie pakietów danych stanu kondycji aplikacji i typów dostawcy odpowiedzialna za przetwarzanie tych danych.</xref:System.Web.Management> Zawiera ona także pomocnicze typy, które pomagają w trakcie zarządzania zdarzenia kondycji.       Zdarzenia cykl życia aplikacji obejmują zdarzenia, takie jak uruchamiania aplikacji i zdarzeń zamknięcia systemu. Jeśli aplikacja zostanie zakończona, można określić dlaczego przez wyświetlanie pola komunikatu powiązanych zdarzeń.       W przypadku wystąpienia WebApplicationLifetimeEvent monitorowanie kondycji ASP.NET aktualizacje licznika wydajności zdarzenia okresu istnienia aplikacji. Zdarzenia te można rejestrować, dodając obiekt WebApplicationLifetimeEvent do `rules` podsekcji z `healthMonitoring` sekcji pliku konfiguracji, jak pokazano w poniższym przykładzie.      ```   <rules>     <add name=&quot;Application Events&quot;       eventName=&quot;Application Lifetime Events&quot;       provider=&quot;EventLogProvider&quot;       profile=&quot;Default&quot;       minInterval=&quot;00:01:00&quot; />   </rules>      ```Licznik wydajności zdarzenia okresu istnienia aplikacji zawiera łączną sumę wszystkich ASP.NET okres istnienia zdarzeń. Aby wyświetlić ten licznik wydajności w Monitorze systemu (PerfMon) w **Dodaj liczniki** wybierz okno **ASP.NET** z **obiekt wydajności** listy rozwijanej. Wybierz **zdarzenia okresu istnienia aplikacji** licznika wydajności, a następnie kliknij przycisk **Dodaj** przycisku. Aby uzyskać więcej informacji, zobacz &quot;Korzystanie z Monitora systemu (PerfMon) z aplikacjami ASP.NET&quot; na [MSDN](http://go.microsoft.com/fwlink/?linkid=37118). Jeśli zezwolisz na zdarzenia, które mają być rejestrowane przez standard <xref:System.Web.Management.EventLogWebEventProvider>, wyświetlać w Podglądzie zdarzeń, wybierając **aplikacji** dziennika</xref:System.Web.Management.EventLogWebEventProvider> Aby uzyskać więcej informacji, zobacz [Podgląd zdarzeń](http://go.microsoft.com/fwlink/?linkid=24845&clcid=0x409) w dokumentacji systemu Windows Server 2003 w witrynie TechNet.      > [!CAUTION] > Ponieważ obiekt WebApplicationLifetimeEvent jest zdarzenie dużych, rejestrowanie go obciąża i może spowolnić system. Może również spowodować inne zdarzenia zostaną zastąpione w przypadku liczby <xref:System.Web.Management.EventLogWebEventProvider>klasy z powodu dużej liczby zdarzeń i sposób rejestrowania działa zdarzeń.</xref:System.Web.Management.EventLogWebEventProvider>      > [!NOTE] > W większości przypadków będzie można korzystać z typów monitorowanie kondycji programu ASP.NET, zgodnie z implementacją i sterowania monitorowanie kondycji systemu, podając wartości w `healthMonitoring` sekcji konfiguracji. Można również pochodną typy monitorowanie kondycji, aby utworzyć własne niestandardowe zdarzenia i dostawców. Przykład tworzenia klasy pochodnej z klasy WebApplicationLifetimeEvent Zobacz przykład podane w tym temacie."
  example:
  - "The following code example shows how to derive from the WebApplicationLifetimeEvent class to create a custom event.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#1](~/add/codesnippet/visualbasic/t-system.web.management._24_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#1](~/add/codesnippet/csharp/t-system.web.management._24_1.cs)]  \n  \n The following configuration-file excerpt shows how to configure the `healthMonitoring` section of a configuration file to add the `SampleWebApplicationLifetimeEvent` code defined above to the ASP.NET health-monitoring system. To add the event to the system, you must define the event by adding a new entry to the `eventMappings` section and map the event to a provider by adding a new entry to the `rules` section.  \n  \n```  \n<healthMonitoring  \n  enabled=\"true\"  \n  heartBeatInterval=\"0\">  \n  \n    <eventMappings>  \n       <clear />  \n       <!-- Configure the application lifetime event -->  \n       <!-- object to handle the Web application events. -->  \n       <add name=\"SampleApplicationLifetimeEvents\"  \n         type=\"System.Web.Management.SampleWebApplicationLifetimeEvent,  \n         System.Web,Version=2.0.3600.0,  \n         Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a\" />  \n     </eventMappings>  \n  \n    <rules>  \n      <clear/>  \n       // Configure the connection between the   \n       // application lifetime event object   \n       // and the provider that must process it.  \n       <add name=\"Custom Application Events\"  \n         eventName=\"SampleApplicationLifetimeEvents\"  \n         provider=\"EventLogProvider\"  \n         profile=\"Default\"  \n         minInterval=\"00:01:00\" />  \n    </rules>  \n  \n</healthMonitoring>  \n```"
  syntax:
    content: 'public class WebApplicationLifetimeEvent : System.Web.Management.WebManagementEvent'
  inheritance:
  - System.Object
  - System.Web.Management.WebBaseEvent
  - System.Web.Management.WebManagementEvent
  implements: []
  inheritedMembers:
  - System.Web.Management.WebBaseEvent.ApplicationInformation
  - System.Web.Management.WebBaseEvent.EventCode
  - System.Web.Management.WebBaseEvent.EventDetailCode
  - System.Web.Management.WebBaseEvent.EventID
  - System.Web.Management.WebBaseEvent.EventOccurrence
  - System.Web.Management.WebBaseEvent.EventSequence
  - System.Web.Management.WebBaseEvent.EventSource
  - System.Web.Management.WebBaseEvent.EventTime
  - System.Web.Management.WebBaseEvent.EventTimeUtc
  - System.Web.Management.WebBaseEvent.FormatCustomEventDetails(System.Web.Management.WebEventFormatter)
  - System.Web.Management.WebBaseEvent.Message
  - System.Web.Management.WebBaseEvent.Raise
  - System.Web.Management.WebBaseEvent.Raise(System.Web.Management.WebBaseEvent)
  - System.Web.Management.WebBaseEvent.ToString
  - System.Web.Management.WebBaseEvent.ToString(System.Boolean,System.Boolean)
  - System.Web.Management.WebManagementEvent.ProcessInformation
  platform:
  - net462
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  id: '#ctor(System.String,System.Object,System.Int32)'
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: WebApplicationLifetimeEvent(String,Object,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Inicjuje <xref href=&quot;System.Web.Management.WebApplicationLifetimeEvent&quot;> </xref> przy użyciu podanych parametrów."
  remarks: "Ten konstruktor jest używana wewnętrznie przez system monitorowanie kondycji programu ASP.NET. Nigdy nie będzie go użyć do utworzenia wystąpienia <xref:System.Web.Management.WebApplicationLifetimeEvent>klasy, ale można wywołać konstruktora podczas implementowania własne typu zdarzenia, który dziedziczy z tej klasy.</xref:System.Web.Management.WebApplicationLifetimeEvent>      > [!NOTE] > WebApplicationLifetimeEvent Konstruktor nie jest przeznaczona do użycia bezpośrednio w kodzie. Jest ona wywoływana przez program ASP.NET. Można wywołać konstruktora WebApplicationLifetimeEvent w przypadku tworzenia klasy pochodnej z <xref:System.Web.Management.WebApplicationLifetimeEvent>klasy.</xref:System.Web.Management.WebApplicationLifetimeEvent>"
  example:
  - "The following code example shows how to use the WebApplicationLifetimeEvent in an ASP.NET custom health event. This code example is mainly intended to show the correct syntax to use.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#2](~/add/codesnippet/visualbasic/f6897152-ffc5-4ce1-a4ea-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#2](~/add/codesnippet/csharp/f6897152-ffc5-4ce1-a4ea-_1.cs)]"
  syntax:
    content: protected WebApplicationLifetimeEvent (string message, object eventSource, int eventCode);
    parameters:
    - id: message
      type: System.String
      description: "Komunikat skojarzony ze zdarzeniem."
    - id: eventSource
      type: System.Object
      description: "Obiekt, który jest źródłem zdarzenia."
    - id: eventCode
      type: System.Int32
      description: "Kod skojarzone ze zdarzeniem. Po zaimplementowaniu zdarzenia niestandardowego kodu zdarzenia musi być większa niż <xref href=&quot;System.Web.Management.WebEventCodes.WebExtendedBase&quot;> </xref>."
  overload: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  id: '#ctor(System.String,System.Object,System.Int32,System.Int32)'
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Inicjuje <xref href=&quot;System.Web.Management.WebApplicationLifetimeEvent&quot;> </xref> przy użyciu podanych parametrów."
  remarks: "Ten konstruktor jest używana wewnętrznie przez system monitorowanie kondycji programu ASP.NET. Nigdy nie będzie go użyć do utworzenia wystąpienia <xref:System.Web.Management.WebApplicationLifetimeEvent>klasy, ale można wywołać konstruktora podczas implementowania własne typu zdarzenia, który dziedziczy z tej klasy.</xref:System.Web.Management.WebApplicationLifetimeEvent>      > [!NOTE] > WebApplicationLifetimeEvent Konstruktor nie jest przeznaczona do użycia bezpośrednio w kodzie. Jest ona wywoływana przez program ASP.NET. Można wywołać konstruktora WebApplicationLifetimeEvent w przypadku tworzenia klasy pochodnej z <xref:System.Web.Management.WebApplicationLifetimeEvent>klasy.</xref:System.Web.Management.WebApplicationLifetimeEvent>"
  example:
  - "The following code example shows how to use the WebApplicationLifetimeEvent in an ASP.NET custom health event. This code example is mainly intended to show the correct syntax to use.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#3](~/add/codesnippet/visualbasic/d658829b-c5f1-4bb1-9080-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#3](~/add/codesnippet/csharp/d658829b-c5f1-4bb1-9080-_1.cs)]"
  syntax:
    content: protected WebApplicationLifetimeEvent (string message, object eventSource, int eventCode, int eventDetailCode);
    parameters:
    - id: message
      type: System.String
      description: "Komunikat skojarzony ze zdarzeniem."
    - id: eventSource
      type: System.Object
      description: "Obiekt, który jest źródłem zdarzenia."
    - id: eventCode
      type: System.Int32
      description: "Kod skojarzone ze zdarzeniem. Po zaimplementowaniu zdarzenia niestandardowego kodu zdarzenia musi być większa niż <xref href=&quot;System.Web.Management.WebEventCodes.WebExtendedBase&quot;> </xref>."
    - id: eventDetailCode
      type: System.Int32
      description: "<xref href=&quot;System.Web.Management.WebEventCodes&quot;> </xref> Wartość, która określa szczegółowe identyfikator zdarzenia."
  overload: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  id: IncrementPerfCounters
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: IncrementPerfCounters()
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters()
  fullName: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Używana wewnętrznie w celu zwiększenia liczniki wydajności."
  syntax:
    content: protected override void IncrementPerfCounters ();
    parameters: []
  overload: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Management.WebManagementEvent
  isExternal: false
  name: System.Web.Management.WebManagementEvent
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent(String,Object,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: IncrementPerfCounters()
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters()
  fullName: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters()
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters*
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: IncrementPerfCounters
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters
