### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.OutputCacheSettingsSection
  id: OutputCacheSettingsSection
  children:
  - System.Web.Configuration.OutputCacheSettingsSection.#ctor
  - System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  - System.Web.Configuration.OutputCacheSettingsSection.Properties
  langs:
  - csharp
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
  type: Class
  summary: "Konfiguruje ustawienia wyjściowej pamięci podręcznej stron aplikacji. Ta klasa nie może być dziedziczona."
  remarks: "Klasa OutputCacheSettingsSection umożliwia programowo modyfikacji i dostępu `outputCacheSettings` elementu `caching` sekcji w pliku konfiguracji. Ustawienia wyjściowej pamięci podręcznej definiowania zależności (relacje między elementy przechowywane w pamięci podręcznej i plików, buforowanie kluczy lub <xref:System.Web.Caching.CacheDependency>obiektów) używane w buforowanie danych wyjściowych, na przykład przez [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) dyrektywy lub przez <xref:System.Web.Configuration.OutputCacheProfile>.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Caching.CacheDependency>      > [!NOTE] > OutputCacheSettingsSection można zapisać informacji w sekcji pliku konfiguracji zgodnie z ograniczeniami określone przez sekcję właściwości, <xref:System.Configuration.SectionInformation.AllowDefinition%2A>której wartość jest <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> pokrewne Komunikat o błędzie wygenerowane przez analizator spowoduje próbę zapisu w pliku konfiguracji na poziomie nie są dozwolone w hierarchii. Jednak można użyć tej klasy można odczytać informacji o konfiguracji na dowolnym poziomie w hierarchii."
  example:
  - "The following code example shows how to obtain the OutputCacheSettingsSection object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_9_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_9_1.vb)]"
  syntax:
    content: 'public sealed class OutputCacheSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> klasy."
  remarks: "Konstruktor OutputCacheSettingsSection nie jest przeznaczona do użycia bezpośrednio w kodzie. Jest ona wywoływana przez system konfiguracji programu ASP.NET. Uzyskać wystąpienia <xref:System.Web.Configuration.OutputCacheSettingsSection>przy użyciu <xref:System.Configuration.Configuration.GetSection%2A>metody.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  syntax:
    content: public OutputCacheSettingsSection ();
    parameters: []
  overload: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  id: OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref>."
  remarks: "Właściwość OutputCacheProfiles umożliwia programowo dostępu `outputCacheProfiles` w pliku konfiguracji. Służy do modyfikowania właściwości OutputCacheProfiles `outputCacheProfiles` element programowo.       `outputCacheProfiles` Sekcja zawiera <xref:System.Web.Configuration.OutputCacheProfile>obiekty reprezentujące dane wyjściowe pamięci podręcznej ustawień, które mogą być używane przez stron w aplikacji.</xref:System.Web.Configuration.OutputCacheProfile>  Te ustawienia można stosować do stron przez ustawienie `CacheProfile` atrybutu [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) dyrektywy. Zastosuj profil do sterowania buforowaniem atrybutów, takich jak zależności, lokalizacja pamięci podręcznej i czas wygaśnięcia pamięci podręcznej.       [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) dyrektywy można zastąpić wszystkie ustawienia zawarty w <xref:System.Web.Configuration.OutputCacheProfile>z wyjątkiem <xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A>Właściwości.</xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A> </xref:System.Web.Configuration.OutputCacheProfile> To jest zapewnienie można włączyć lub wyłączyć <xref:System.Web.Configuration.OutputCacheProfile>bez konieczności modyfikowania dyrektywy na stronach, które może być zastąpiona go.</xref:System.Web.Configuration.OutputCacheProfile>"
  example:
  - "The following code example shows how to use the OutputCacheProfiles property.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/csharp/p-system.web.configurati_105_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_105_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheProfileCollection OutputCacheProfiles { get; }
    return:
      type: System.Web.Configuration.OutputCacheProfileCollection
      description: "A <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.OutputCacheProfile&quot;></xref> objects"
  overload: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  id: Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheProfileCollection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheProfileCollection
  nameWithType: OutputCacheProfileCollection
  fullName: System.Web.Configuration.OutputCacheProfileCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
