### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.ImeSentenceModeValues
  id: ImeSentenceModeValues
  children:
  - System.Windows.Input.ImeSentenceModeValues.Automatic
  - System.Windows.Input.ImeSentenceModeValues.Conversation
  - System.Windows.Input.ImeSentenceModeValues.DoNotCare
  - System.Windows.Input.ImeSentenceModeValues.None
  - System.Windows.Input.ImeSentenceModeValues.PhrasePrediction
  - System.Windows.Input.ImeSentenceModeValues.PluralClause
  - System.Windows.Input.ImeSentenceModeValues.SingleConversion
  langs:
  - csharp
  name: ImeSentenceModeValues
  nameWithType: ImeSentenceModeValues
  fullName: System.Windows.Input.ImeSentenceModeValues
  type: Enum
  summary: "Określa tryb konwersji zdanie wykonywane przez metodę wprowadzania."
  remarks: ''
  example:
  - "The following example demonstrates how to use the <xref:System.Windows.Input.InputMethod.ImeSentenceMode%2A> property.  \n  \n [!code-vb[languageManager#2](~/add/codesnippet/visualbasic/inputmanager/window1.xaml.vb#2)]\n [!code-cs[languageManager#2](~/add/codesnippet/csharp/inputmanager/Window1.xaml.cs#2)]"
  syntax:
    content: >-
      [System.Flags]

      public enum ImeSentenceModeValues
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.Automatic
  id: Automatic
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: Automatic
  nameWithType: ImeSentenceModeValues.Automatic
  fullName: System.Windows.Input.ImeSentenceModeValues.Automatic
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa używa metody konwersji zdanie automatycznie."
  syntax:
    content: Automatic
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.Conversation
  id: Conversation
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: Conversation
  nameWithType: ImeSentenceModeValues.Conversation
  fullName: System.Windows.Input.ImeSentenceModeValues.Conversation
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa używa konwersji zdanie stylu konwersacji."
  syntax:
    content: Conversation
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.DoNotCare
  id: DoNotCare
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: DoNotCare
  nameWithType: ImeSentenceModeValues.DoNotCare
  fullName: System.Windows.Input.ImeSentenceModeValues.DoNotCare
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa interesują służy metodę konwersji zdanie; tryb konwersji rzeczywiste zdania jest nieokreślony."
  syntax:
    content: DoNotCare
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.None
  id: None
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: None
  nameWithType: ImeSentenceModeValues.None
  fullName: System.Windows.Input.ImeSentenceModeValues.None
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa nie wykonuje żadnej konwersji zdanie."
  syntax:
    content: None
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.PhrasePrediction
  id: PhrasePrediction
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: PhrasePrediction
  nameWithType: ImeSentenceModeValues.PhrasePrediction
  fullName: System.Windows.Input.ImeSentenceModeValues.PhrasePrediction
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa używa frazy prognozowania zdanie konwersji."
  syntax:
    content: PhrasePrediction
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.PluralClause
  id: PluralClause
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: PluralClause
  nameWithType: ImeSentenceModeValues.PluralClause
  fullName: System.Windows.Input.ImeSentenceModeValues.PluralClause
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa używa klauzuli mnogiej zdanie konwersji."
  syntax:
    content: PluralClause
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeSentenceModeValues.SingleConversion
  id: SingleConversion
  parent: System.Windows.Input.ImeSentenceModeValues
  langs:
  - csharp
  name: SingleConversion
  nameWithType: ImeSentenceModeValues.SingleConversion
  fullName: System.Windows.Input.ImeSentenceModeValues.SingleConversion
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Metoda wejściowa używa pojedynczego Kanji/Hanja zdanie konwersji."
  syntax:
    content: SingleConversion
    return:
      type: System.Windows.Input.ImeSentenceModeValues
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.Input.ImeSentenceModeValues.Automatic
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: Automatic
  nameWithType: ImeSentenceModeValues.Automatic
  fullName: System.Windows.Input.ImeSentenceModeValues.Automatic
- uid: System.Windows.Input.ImeSentenceModeValues
  parent: System.Windows.Input
  isExternal: false
  name: ImeSentenceModeValues
  nameWithType: ImeSentenceModeValues
  fullName: System.Windows.Input.ImeSentenceModeValues
- uid: System.Windows.Input.ImeSentenceModeValues.Conversation
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: Conversation
  nameWithType: ImeSentenceModeValues.Conversation
  fullName: System.Windows.Input.ImeSentenceModeValues.Conversation
- uid: System.Windows.Input.ImeSentenceModeValues.DoNotCare
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: DoNotCare
  nameWithType: ImeSentenceModeValues.DoNotCare
  fullName: System.Windows.Input.ImeSentenceModeValues.DoNotCare
- uid: System.Windows.Input.ImeSentenceModeValues.None
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: None
  nameWithType: ImeSentenceModeValues.None
  fullName: System.Windows.Input.ImeSentenceModeValues.None
- uid: System.Windows.Input.ImeSentenceModeValues.PhrasePrediction
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: PhrasePrediction
  nameWithType: ImeSentenceModeValues.PhrasePrediction
  fullName: System.Windows.Input.ImeSentenceModeValues.PhrasePrediction
- uid: System.Windows.Input.ImeSentenceModeValues.PluralClause
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: PluralClause
  nameWithType: ImeSentenceModeValues.PluralClause
  fullName: System.Windows.Input.ImeSentenceModeValues.PluralClause
- uid: System.Windows.Input.ImeSentenceModeValues.SingleConversion
  parent: System.Windows.Input.ImeSentenceModeValues
  isExternal: false
  name: SingleConversion
  nameWithType: ImeSentenceModeValues.SingleConversion
  fullName: System.Windows.Input.ImeSentenceModeValues.SingleConversion
