### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyIsReadOnlyException
  id: SettingsPropertyIsReadOnlyException
  children:
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException
  nameWithType: SettingsPropertyIsReadOnlyException
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException
  type: Class
  summary: "Zawiera wyjątek dla tylko do odczytu <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> obiektów."
  remarks: "Ten wyjątek jest zgłaszany przez <xref:System.Configuration.SettingsBase>klasy podczas próby zmiany wartości <xref:System.Configuration.SettingsPropertyValue>oznaczonego jako tylko do odczytu.</xref:System.Configuration.SettingsPropertyValue> </xref:System.Configuration.SettingsBase>"
  syntax:
    content: 'public class SettingsPropertyIsReadOnlyException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException()
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasy."
  syntax:
    content: public SettingsPropertyIsReadOnlyException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(String)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasy oparte na podany parametr."
  syntax:
    content: public SettingsPropertyIsReadOnlyException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Ciąg zawierający komunikat o wyjątku."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasy oparte na podanych parametrów."
  syntax:
    content: protected SettingsPropertyIsReadOnlyException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> Obiekt przechowujący dane zserializowanego obiektu dotyczące zgłaszanego wyjątku."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>Obiekt zawierający informacje kontekstowe dotyczące źródła lub miejsca docelowego w strumieniu serializowanym.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(String,Exception)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.SettingsPropertyIsReadOnlyException&quot;> </xref> klasy na podstawie dostarczonych parametrów."
  syntax:
    content: public SettingsPropertyIsReadOnlyException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Ciąg zawierający komunikat o wyjątku."
    - id: innerException
      type: System.Exception
      description: "Wyjątek będący przyczyną bieżącego wyjątku."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException()
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(String)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(String,Exception)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException
