### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeConfigurationFileMap
  id: ExeConfigurationFileMap
  children:
  - System.Configuration.ExeConfigurationFileMap.#ctor
  - System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  - System.Configuration.ExeConfigurationFileMap.Clone
  - System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  - System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  - System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  langs:
  - csharp
  name: ExeConfigurationFileMap
  nameWithType: ExeConfigurationFileMap
  fullName: System.Configuration.ExeConfigurationFileMap
  type: Class
  summary: "Definiuje mapowanie pliku konfiguracji aplikacji .exe. Ta klasa nie może być dziedziczona."
  remarks: "Klasa ExeConfigurationFileMap umożliwia definiowanie hierarchii plików konfiguracji niestandardowej dla aplikacji .exe. Klasa ExeConfigurationFileMap można określić pojedynczą ścieżkę lub wiele ścieżek związane z plików konfiguracyjnych."
  example:
  - For an example that shows how to use this class, see the <xref:System.Configuration.ConfigurationManager.OpenMappedExeConfiguration%2A?displayProperty=fullName> method.
  syntax:
    content: 'public sealed class ExeConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigurationFileMap()
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap()
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> klasy."
  syntax:
    content: public ExeConfigurationFileMap ();
    parameters: []
  overload: System.Configuration.ExeConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigurationFileMap(String)
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> przy użyciu nazwy pliku konfiguracji określonej maszyny."
  remarks: "Ten konstruktor jest używany podczas przeznaczona dla wersji [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] wcześniejsza niż najnowsze jest zainstalowany na komputerze. Ten konstruktor można określić plik konfiguracji maszyny, która jest odpowiednia do wersji [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] , który ma być przeznaczona dla."
  syntax:
    content: public ExeConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "Nazwa pliku konfiguracji komputera, który zawiera pełną ścieżkę fizyczną (na przykład `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Configuration.ExeConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  id: Clone
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: ExeConfigurationFileMap.Clone()
  fullName: System.Configuration.ExeConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Tworzy kopię istniejącego <xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> obiektu."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "<xref href=&quot;System.Configuration.ExeConfigurationFileMap&quot;> </xref> Obiektu."
  overload: System.Configuration.ExeConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  id: ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia nazwę pliku konfiguracji."
  syntax:
    content: public string ExeConfigFilename { get; set; }
    return:
      type: System.String
      description: "Nazwa pliku konfiguracji."
  overload: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  id: LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia nazwę pliku konfiguracji dla użytkownika lokalnego."
  syntax:
    content: public string LocalUserConfigFilename { get; set; }
    return:
      type: System.String
      description: "Nazwa pliku konfiguracji."
  overload: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  id: RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Pobiera lub ustawia nazwę pliku konfiguracji dla użytkowników mobilnych."
  syntax:
    content: public string RoamingUserConfigFilename { get; set; }
    return:
      type: System.String
      description: "Nazwa pliku konfiguracji."
  overload: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap()
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap()
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap()
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap(String)
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: ExeConfigurationFileMap.Clone()
  fullName: System.Configuration.ExeConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.#ctor*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap
- uid: System.Configuration.ExeConfigurationFileMap.Clone*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: ExeConfigurationFileMap.Clone
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename*
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
