### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  id: SoapEnvelopeProcessingElement
  children:
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  type: Class
  summary: "Określa limit czasu, który ułatwia ograniczanie ataki przez przerywanie każde żądanie dłużej niż <xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>wartości właściwości.</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>"
  remarks: "Wartość limitu czasu jest zaznaczony przy każdym wywołaniu i <xref:System.Xml.XmlReader.Read%2A> <xref:System.Xml.XmlReader.MoveToContent%2A>.</xref:System.Xml.XmlReader.MoveToContent%2A> </xref:System.Xml.XmlReader.Read%2A>"
  syntax:
    content: 'public sealed class SoapEnvelopeProcessingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;> </xref> klasy."
  syntax:
    content: public SoapEnvelopeProcessingElement ();
    parameters: []
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;> </xref> przy użyciu dostarczonego <xref:System.Int32>wartość.</xref:System.Int32>"
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "Wartość limitu czasu."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  id: '#ctor(System.Int32,System.Boolean)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Pobiera lub ustawia limit czasu używany w celu określenia, czy zakończenie żądania, aby ograniczyć straty &quot;odmowa usługi&quot;."
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout, bool strict);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "Czas oczekiwania przed zakończeniem żądania do <> </> *> i <> </> *>."
    - id: strict
      type: System.Boolean
      description: "Czy należy zgłosić wyjątek, jeśli serializator napotka elementów lub atrybutów, które nie zostały w oryginalnym schematu. Aby uzyskać więcej informacji, zobacz <xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>Właściwości.</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  id: IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Pobiera lub ustawia wartość wskazującą, czy należy zgłosić wyjątek, jeśli element serializujący napotkał nieoczekiwany elementów lub atrybutów."
  remarks: "Ustaw dla właściwości IsStrict `true` Aby debugować współdziałanie scenariuszy. Zwykle, gdy <xref:System.Xml.Serialization.XmlSerializer>klasy spełnia element lub atrybut, który będzie zgłasza <xref:System.Xml.Serialization.XmlSerializer.UnknownNode>zdarzeń, aby kontynuować przetwarzania.</xref:System.Xml.Serialization.XmlSerializer.UnknownNode> </xref:System.Xml.Serialization.XmlSerializer> (To samo dotyczy kiedy <xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A>, <xref:System.Xml.Serialization.XmlElementAttribute.Order%2A>, lub <xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A>Właściwości są używane, ale dane są wysyłane poza kolejnością.)</xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A> Ustawienie właściwości IsStrict `true` powoduje, że usługi sieci Web wykonawczego do obsługi tego zdarzenia i zgłosić <xref:System.InvalidOperationException>zawierający listę oczekiwanych elementów i atrybutów.</xref:System.InvalidOperationException>      > [!NOTE] > Ponieważ dla wszystkich nieoczekiwane elementy i atrybuty nie są zgłaszane wyjątki, właściwość IsStrict nie powinno być stosowane na z wyjątkiem jako pomoc do debugowania. Na przykład nieoczekiwany `xml:lang` i `xml:space` atrybutów nie może spowodować wyjątek."
  syntax:
    content: public bool IsStrict { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Jeśli serializator usług sieci Web próbuje wykryć nieoczekiwany elementów lub atrybutów; w przeciwnym razie <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Wartość domyślna to <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Do dodania."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  id: ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Pobiera lub ustawia limit czasu używany w celu określenia, czy zakończenie żądania, aby ograniczyć straty &quot;odmowa usługi&quot;."
  syntax:
    content: public int ReadTimeout { get; set; }
    return:
      type: System.Int32
      description: "Czas oczekiwania przed zakończeniem żądania do <> </> *> i <> </> *>."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
