### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger
  id: ConfigurableForwardingLogger
  children:
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.#ctor
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource)
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown
  - Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity
  langs:
  - csharp
  name: ConfigurableForwardingLogger
  nameWithType: ConfigurableForwardingLogger
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger
  type: Class
  summary: "Reprezentuje rejestratora, który przekazuje zdarzenia do rejestratora centralnego (np. ConsoleLogger) znajdującymi się w węźle nadrzędnym."
  syntax:
    content: 'public class ConfigurableForwardingLogger : Microsoft.Build.Framework.IForwardingLogger'
  inheritance:
  - System.Object
  implements:
  - Microsoft.Build.Framework.IForwardingLogger
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: ConfigurableForwardingLogger()
  nameWithType: ConfigurableForwardingLogger.ConfigurableForwardingLogger()
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.ConfigurableForwardingLogger()
  type: Constructor
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Konstrukcje rejestratora."
  syntax:
    content: public ConfigurableForwardingLogger ();
    parameters: []
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector
  id: BuildEventRedirector
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: BuildEventRedirector
  nameWithType: ConfigurableForwardingLogger.BuildEventRedirector
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector
  type: Property
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Pobiera lub ustawia właściwość, która określa, jak komunikaty rejestratora centralnego rejestratora węzeł, do przodu."
  syntax:
    content: public Microsoft.Build.Framework.IEventRedirector BuildEventRedirector { get; set; }
    return:
      type: Microsoft.Build.Framework.IEventRedirector
      description: "Zwraca wartość właściwości, która określa, jak komunikaty rejestratora centralnego rejestratora węzeł, do przodu."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  id: ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: ForwardToCentralLogger(BuildEventArgs)
  nameWithType: ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
  type: Method
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Przesyła rejestratora centralnego tego zdarzenia."
  syntax:
    content: protected virtual void ForwardToCentralLogger (Microsoft.Build.Framework.BuildEventArgs e);
    parameters:
    - id: e
      type: Microsoft.Build.Framework.BuildEventArgs
      description: "Zdarzenie, które mają być przekazywane."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource)
  id: Initialize(Microsoft.Build.Framework.IEventSource)
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Initialize(IEventSource)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource)
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(IEventSource)
  type: Method
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Podpisuje się rejestratora konsoli do rejestrowania zdarzeń danej kompilacji."
  syntax:
    content: public virtual void Initialize (Microsoft.Build.Framework.IEventSource eventSource);
    parameters:
    - id: eventSource
      type: Microsoft.Build.Framework.IEventSource
      description: "Źródła zdarzeń dla zdarzeń kompilacji."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  id: Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Initialize(IEventSource,Int32)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
  type: Method
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Zdarzenia kompilacji oznaki zapasowej rejestratora konsoli dla wszystkich."
  syntax:
    content: public void Initialize (Microsoft.Build.Framework.IEventSource eventSource, int nodeCount);
    parameters:
    - id: eventSource
      type: Microsoft.Build.Framework.IEventSource
      description: "Źródła zdarzeń dla zdarzeń kompilacji."
    - id: nodeCount
      type: System.Int32
      description: "Liczba węzłów.  Nie jest używany."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId
  id: NodeId
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: NodeId
  nameWithType: ConfigurableForwardingLogger.NodeId
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId
  type: Property
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Pobiera lub ustawia identyfikator węzła."
  syntax:
    content: public int NodeId { get; set; }
    return:
      type: System.Int32
      description: "Zwraca identyfikator węzła."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters
  id: Parameters
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Parameters
  nameWithType: ConfigurableForwardingLogger.Parameters
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters
  type: Property
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Pobiera lub ustawia przełącznik, który określa, czy pominąć dane wyjściowe, błędy i ostrzeżenia podsumowanie na końcu kompilacji."
  syntax:
    content: public string Parameters { get; set; }
    return:
      type: System.String
      description: "Zwraca przełącznik, który określa, czy pominąć dane wyjściowe, błędy i ostrzeżenia podsumowanie na końcu kompilacji."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown
  id: Shutdown
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Shutdown()
  nameWithType: ConfigurableForwardingLogger.Shutdown()
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown()
  type: Method
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Wywoływana, gdy aparat kompilacji jest zakończone z tym rejestratora."
  syntax:
    content: public virtual void Shutdown ();
    parameters: []
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity
  id: Verbosity
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Verbosity
  nameWithType: ConfigurableForwardingLogger.Verbosity
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity
  type: Property
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Logging
  summary: "Pobiera lub ustawia poziom szczegółowości do pokazania w dzienniku zdarzeń."
  syntax:
    content: public Microsoft.Build.Framework.LoggerVerbosity Verbosity { get; set; }
    return:
      type: Microsoft.Build.Framework.LoggerVerbosity
      description: "Zwraca poziom szczegółowości do pokazania w dzienniku zdarzeń."
  overload: Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.#ctor
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: ConfigurableForwardingLogger()
  nameWithType: ConfigurableForwardingLogger.ConfigurableForwardingLogger()
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.ConfigurableForwardingLogger()
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: BuildEventRedirector
  nameWithType: ConfigurableForwardingLogger.BuildEventRedirector
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector
- uid: Microsoft.Build.Framework.IEventRedirector
  parent: Microsoft.Build.Framework
  isExternal: false
  name: IEventRedirector
  nameWithType: IEventRedirector
  fullName: Microsoft.Build.Framework.IEventRedirector
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: ForwardToCentralLogger(BuildEventArgs)
  nameWithType: ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
- uid: Microsoft.Build.Framework.BuildEventArgs
  parent: Microsoft.Build.Framework
  isExternal: false
  name: BuildEventArgs
  nameWithType: BuildEventArgs
  fullName: Microsoft.Build.Framework.BuildEventArgs
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource)
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Initialize(IEventSource)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource)
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(IEventSource)
- uid: Microsoft.Build.Framework.IEventSource
  parent: Microsoft.Build.Framework
  isExternal: false
  name: IEventSource
  nameWithType: IEventSource
  fullName: Microsoft.Build.Framework.IEventSource
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Initialize(IEventSource,Int32)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: NodeId
  nameWithType: ConfigurableForwardingLogger.NodeId
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Parameters
  nameWithType: ConfigurableForwardingLogger.Parameters
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Shutdown()
  nameWithType: ConfigurableForwardingLogger.Shutdown()
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown()
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Verbosity
  nameWithType: ConfigurableForwardingLogger.Verbosity
  fullName: Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity
- uid: Microsoft.Build.Framework.LoggerVerbosity
  parent: Microsoft.Build.Framework
  isExternal: false
  name: LoggerVerbosity
  nameWithType: LoggerVerbosity
  fullName: Microsoft.Build.Framework.LoggerVerbosity
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.#ctor*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: ConfigurableForwardingLogger
  nameWithType: ConfigurableForwardingLogger.ConfigurableForwardingLogger
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.BuildEventRedirector*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: BuildEventRedirector
  nameWithType: ConfigurableForwardingLogger.BuildEventRedirector
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.ForwardToCentralLogger*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: ForwardToCentralLogger
  nameWithType: ConfigurableForwardingLogger.ForwardToCentralLogger
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Initialize*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Initialize
  nameWithType: ConfigurableForwardingLogger.Initialize
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.NodeId*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: NodeId
  nameWithType: ConfigurableForwardingLogger.NodeId
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Parameters*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Parameters
  nameWithType: ConfigurableForwardingLogger.Parameters
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Shutdown*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Shutdown
  nameWithType: ConfigurableForwardingLogger.Shutdown
- uid: Microsoft.Build.Logging.ConfigurableForwardingLogger.Verbosity*
  parent: Microsoft.Build.Logging.ConfigurableForwardingLogger
  isExternal: false
  name: Verbosity
  nameWithType: ConfigurableForwardingLogger.Verbosity
