### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.FindAppConfigFile
  id: FindAppConfigFile
  children:
  - Microsoft.Build.Tasks.FindAppConfigFile.#ctor
  - Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  - Microsoft.Build.Tasks.FindAppConfigFile.Execute
  - Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  - Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  - Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  langs:
  - csharp
  name: FindAppConfigFile
  nameWithType: FindAppConfigFile
  fullName: Microsoft.Build.Tasks.FindAppConfigFile
  type: Class
  summary: "Umożliwia znalezienie pliku app.config w podanych listy."
  remarks: "Findappconfigfile — dodano również <xref:Microsoft.Build.Tasks.FindAppConfigFile.TargetPath%2A>metadanych.</xref:Microsoft.Build.Tasks.FindAppConfigFile.TargetPath%2A>"
  syntax:
    content: 'public class FindAppConfigFile : Microsoft.Build.Tasks.TaskExtension'
  inheritance:
  - System.Object
  - Microsoft.Build.Utilities.Task
  - Microsoft.Build.Tasks.TaskExtension
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.TaskExtension.Log
  - Microsoft.Build.Utilities.Task.BuildEngine
  - Microsoft.Build.Utilities.Task.BuildEngine2
  - Microsoft.Build.Utilities.Task.BuildEngine3
  - Microsoft.Build.Utilities.Task.BuildEngine4
  - Microsoft.Build.Utilities.Task.HelpKeywordPrefix
  - Microsoft.Build.Utilities.Task.HostObject
  - Microsoft.Build.Utilities.Task.TaskResources
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: FindAppConfigFile()
  nameWithType: FindAppConfigFile.FindAppConfigFile()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.FindAppConfigFile()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Inicjuje nowe wystąpienie <xref href=&quot;Microsoft.Build.Tasks.FindAppConfigFile&quot;> </xref> klasy."
  syntax:
    content: public FindAppConfigFile ();
    parameters: []
  overload: Microsoft.Build.Tasks.FindAppConfigFile.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  id: AppConfigFile
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: AppConfigFile
  nameWithType: FindAppConfigFile.AppConfigFile
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Pobiera lub ustawia pierwszy dopasowanego elementu na liście, jeśli istnieją."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem AppConfigFile { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem
      description: "Pierwszy element pasującego znaleziona na liście lub <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> przypadku nieznalezienia Brak pasujących elementów."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.Execute
  id: Execute
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: Execute()
  nameWithType: FindAppConfigFile.Execute()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.Execute()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Umożliwia znalezienie pliku konfiguracji aplikacji."
  remarks: "Najpierw wykonać wygląda w specyfikacji całego elementu; oznacza to najpierw szuka plików app.config bezpośrednio w folderze projektu. Jeśli się nie powiedzie, następnie go powraca do plików app.config w dowolnym miejscu w projekcie."
  syntax:
    content: public override bool Execute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>we wszystkich przypadkach."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.Execute*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  id: PrimaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: PrimaryList
  nameWithType: FindAppConfigFile.PrimaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Pobiera lub ustawia listę głównych do przeszukiwania."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem[] PrimaryList { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: "Lista podstawowego do przeszukiwania."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  id: SecondaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: SecondaryList
  nameWithType: FindAppConfigFile.SecondaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Pobiera lub ustawia listę dodatkowej do przeszukiwania."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem[] SecondaryList { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: "Lista dodatkowej do przeszukiwania."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  id: TargetPath
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: TargetPath
  nameWithType: FindAppConfigFile.TargetPath
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Pobiera lub ustawia wartość do dodania jako TargetPath metadanych."
  syntax:
    content: public string TargetPath { get; set; }
    return:
      type: System.String
      description: "TargetPath metadanych."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.Build.Tasks.TaskExtension
  isExternal: false
  name: Microsoft.Build.Tasks.TaskExtension
- uid: Microsoft.Build.Tasks.FindAppConfigFile.#ctor
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: FindAppConfigFile()
  nameWithType: FindAppConfigFile.FindAppConfigFile()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.FindAppConfigFile()
- uid: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: AppConfigFile
  nameWithType: FindAppConfigFile.AppConfigFile
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
- uid: Microsoft.Build.Framework.ITaskItem
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem
- uid: Microsoft.Build.Tasks.FindAppConfigFile.Execute
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: Execute()
  nameWithType: FindAppConfigFile.Execute()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.Execute()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: PrimaryList
  nameWithType: FindAppConfigFile.PrimaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
- uid: Microsoft.Build.Framework.ITaskItem[]
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem[]
  spec.csharp:
  - uid: Microsoft.Build.Framework.ITaskItem
    name: ITaskItem
    nameWithType: ITaskItem
    fullName: ITaskItem[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: SecondaryList
  nameWithType: FindAppConfigFile.SecondaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
- uid: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: TargetPath
  nameWithType: FindAppConfigFile.TargetPath
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.FindAppConfigFile.#ctor*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: FindAppConfigFile
  nameWithType: FindAppConfigFile.FindAppConfigFile
- uid: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: AppConfigFile
  nameWithType: FindAppConfigFile.AppConfigFile
- uid: Microsoft.Build.Tasks.FindAppConfigFile.Execute*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: Execute
  nameWithType: FindAppConfigFile.Execute
- uid: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: PrimaryList
  nameWithType: FindAppConfigFile.PrimaryList
- uid: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: SecondaryList
  nameWithType: FindAppConfigFile.SecondaryList
- uid: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: TargetPath
  nameWithType: FindAppConfigFile.TargetPath
