### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  id: ConfigurableForwardingLogger
  children:
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.#ctor
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource)
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown
  - Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity
  langs:
  - csharp
  name: ConfigurableForwardingLogger
  nameWithType: ConfigurableForwardingLogger
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  type: Class
  summary: "Reprezentuje ConfigurableForwardingLogger rejestratora wstępnie metalowych przekazującego, gdy tworzenie projektów w systemie wiele procesów lub wielordzeniowych. Aby uzyskać więcej informacji, zobacz [zapisywanie rejestratorów procesorów uwzględniających](~/add/includes/ajax-current-ext-md.md)."
  remarks: "Można użyć podanego ConfigurableForwardingLogger, lub można utworzyć własne niestandardowe przekazywania rejestratorów."
  syntax:
    content: 'public class ConfigurableForwardingLogger : Microsoft.Build.Framework.IForwardingLogger'
  inheritance:
  - System.Object
  implements:
  - Microsoft.Build.Framework.IForwardingLogger
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.#ctor
  id: '#ctor'
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: ConfigurableForwardingLogger()
  nameWithType: ConfigurableForwardingLogger.ConfigurableForwardingLogger()
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ConfigurableForwardingLogger()
  type: Constructor
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Inicjuje nowe wystąpienie <xref href=&quot;Microsoft.Build.BuildEngine.ConfigurableForwardingLogger&quot;> </xref> klasy."
  syntax:
    content: public ConfigurableForwardingLogger ();
    parameters: []
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector
  id: BuildEventRedirector
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: BuildEventRedirector
  nameWithType: ConfigurableForwardingLogger.BuildEventRedirector
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector
  type: Property
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Pobiera lub ustawia, czy aparat kompilacji umożliwia rejestratorów węzła do przesyłania dalej komunikatów do rejestratora centralnego."
  syntax:
    content: public Microsoft.Build.Framework.IEventRedirector BuildEventRedirector { get; set; }
    return:
      type: Microsoft.Build.Framework.IEventRedirector
      description: "<xref href=&quot;Microsoft.Build.Framework.IEventRedirector&quot;> </xref> Obiektu do niego przekazywać zdarzeń."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  id: ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: ForwardToCentralLogger(BuildEventArgs)
  nameWithType: ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
  type: Method
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Przekazuje określonego zdarzenia do rejestratora centralnego."
  syntax:
    content: protected virtual void ForwardToCentralLogger (Microsoft.Build.Framework.BuildEventArgs e);
    parameters:
    - id: e
      type: Microsoft.Build.Framework.BuildEventArgs
      description: "Argumenty zdarzeń."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource)
  id: Initialize(Microsoft.Build.Framework.IEventSource)
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Initialize(IEventSource)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource)
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(IEventSource)
  type: Method
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Pozyskuje rejestratora konsoli do wszystkich zdarzeń kompilacji."
  syntax:
    content: public virtual void Initialize (Microsoft.Build.Framework.IEventSource eventSource);
    parameters:
    - id: eventSource
      type: Microsoft.Build.Framework.IEventSource
      description: "<xref href=&quot;Microsoft.Build.Framework.IEventSource&quot;> </xref> Obiekt dostarczający zdarzenia kompilacji."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  id: Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Initialize(IEventSource,Int32)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
  type: Method
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Pozyskuje rejestratora konsoli do wszystkich zdarzeń kompilacji."
  syntax:
    content: public void Initialize (Microsoft.Build.Framework.IEventSource eventSource, int nodeCount);
    parameters:
    - id: eventSource
      type: Microsoft.Build.Framework.IEventSource
      description: "<xref href=&quot;Microsoft.Build.Framework.IEventSource&quot;> </xref> Obiekt dostarczający zdarzenia kompilacji."
    - id: nodeCount
      type: System.Int32
      description: "Identyfikator węzła źródła zdarzenia."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId
  id: NodeId
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: NodeId
  nameWithType: ConfigurableForwardingLogger.NodeId
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId
  type: Property
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Pobiera lub ustawia Unikatowy identyfikator węzła, do której jest dołączona rejestratora."
  syntax:
    content: public int NodeId { get; set; }
    return:
      type: System.Int32
      description: "Unikatowy identyfikator węzła."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters
  id: Parameters
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Parameters
  nameWithType: ConfigurableForwardingLogger.Parameters
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters
  type: Property
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Pobiera lub ustawia parametry dla ConfigurableForwardingLogger."
  remarks: "Rejestratora konsoli przyjmuje jeden parametr pominąć dane wyjściowe błędów i ostrzeżeń podsumowania na końcu kompilacji."
  syntax:
    content: public string Parameters { get; set; }
    return:
      type: System.String
      description: "Ciąg reprezentujący parametry rejestratora."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown
  id: Shutdown
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Shutdown()
  nameWithType: ConfigurableForwardingLogger.Shutdown()
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown()
  type: Method
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Zamyka rejestratora przekazywania można konfigurować."
  syntax:
    content: public virtual void Shutdown ();
    parameters: []
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity
  id: Verbosity
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  langs:
  - csharp
  name: Verbosity
  nameWithType: ConfigurableForwardingLogger.Verbosity
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity
  type: Property
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Pobiera lub ustawia poziom szczegółowości do pokazania w dzienniku zdarzeń."
  remarks: "Rejestratora konsoli przyjmuje jeden parametr pominąć dane wyjściowe błędów i ostrzeżeń podsumowania na końcu kompilacji."
  syntax:
    content: public Microsoft.Build.Framework.LoggerVerbosity Verbosity { get; set; }
    return:
      type: Microsoft.Build.Framework.LoggerVerbosity
      description: "<xref href=&quot;Microsoft.Build.Framework.LoggerVerbosity&quot;> </xref> wartość wyliczenia."
  overload: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.#ctor
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: ConfigurableForwardingLogger()
  nameWithType: ConfigurableForwardingLogger.ConfigurableForwardingLogger()
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ConfigurableForwardingLogger()
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: BuildEventRedirector
  nameWithType: ConfigurableForwardingLogger.BuildEventRedirector
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector
- uid: Microsoft.Build.Framework.IEventRedirector
  parent: Microsoft.Build.Framework
  isExternal: false
  name: IEventRedirector
  nameWithType: IEventRedirector
  fullName: Microsoft.Build.Framework.IEventRedirector
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger(Microsoft.Build.Framework.BuildEventArgs)
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: ForwardToCentralLogger(BuildEventArgs)
  nameWithType: ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger(BuildEventArgs)
- uid: Microsoft.Build.Framework.BuildEventArgs
  parent: Microsoft.Build.Framework
  isExternal: false
  name: BuildEventArgs
  nameWithType: BuildEventArgs
  fullName: Microsoft.Build.Framework.BuildEventArgs
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource)
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Initialize(IEventSource)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource)
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(IEventSource)
- uid: Microsoft.Build.Framework.IEventSource
  parent: Microsoft.Build.Framework
  isExternal: false
  name: IEventSource
  nameWithType: IEventSource
  fullName: Microsoft.Build.Framework.IEventSource
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(Microsoft.Build.Framework.IEventSource,System.Int32)
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Initialize(IEventSource,Int32)
  nameWithType: ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize(IEventSource,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: NodeId
  nameWithType: ConfigurableForwardingLogger.NodeId
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Parameters
  nameWithType: ConfigurableForwardingLogger.Parameters
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Shutdown()
  nameWithType: ConfigurableForwardingLogger.Shutdown()
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown()
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Verbosity
  nameWithType: ConfigurableForwardingLogger.Verbosity
  fullName: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity
- uid: Microsoft.Build.Framework.LoggerVerbosity
  parent: Microsoft.Build.Framework
  isExternal: false
  name: LoggerVerbosity
  nameWithType: LoggerVerbosity
  fullName: Microsoft.Build.Framework.LoggerVerbosity
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.#ctor*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: ConfigurableForwardingLogger
  nameWithType: ConfigurableForwardingLogger.ConfigurableForwardingLogger
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.BuildEventRedirector*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: BuildEventRedirector
  nameWithType: ConfigurableForwardingLogger.BuildEventRedirector
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.ForwardToCentralLogger*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: ForwardToCentralLogger
  nameWithType: ConfigurableForwardingLogger.ForwardToCentralLogger
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Initialize*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Initialize
  nameWithType: ConfigurableForwardingLogger.Initialize
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.NodeId*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: NodeId
  nameWithType: ConfigurableForwardingLogger.NodeId
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Parameters*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Parameters
  nameWithType: ConfigurableForwardingLogger.Parameters
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Shutdown*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Shutdown
  nameWithType: ConfigurableForwardingLogger.Shutdown
- uid: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger.Verbosity*
  parent: Microsoft.Build.BuildEngine.ConfigurableForwardingLogger
  isExternal: false
  name: Verbosity
  nameWithType: ConfigurableForwardingLogger.Verbosity
