### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  id: ProjectLoadSettings
  children:
  - Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  - Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  - Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  - Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  langs:
  - csharp
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
  type: Enum
  summary: "Flagi sterujące ładowania projektu."
  remarks: "Jest to &quot;flags&quot; enum, umożliwiając przyszłych ustawienia mają zostać dodane w sposób dodawania, bez podziału."
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectLoadSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  id: Default
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: Default
  nameWithType: ProjectLoadSettings.Default
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Normalne obciążenie. Jest to domyślne ustawienie."
  syntax:
    content: Default
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  id: IgnoreMissingImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Ignoruj nieistniejącej obiektów docelowych plików podczas oceny projektu."
  syntax:
    content: IgnoreMissingImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  id: RecordDuplicateButNotCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: RecordDuplicateButNotCircularImports
  nameWithType: ProjectLoadSettings.RecordDuplicateButNotCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Wskazuje, który importuje Importy zduplikowane, ale nie cykliczne, w tym na `ImportsIncludingDuplicates` właściwość powinny być rejestrowane."
  syntax:
    content: RecordDuplicateButNotCircularImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  id: RejectCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: RejectCircularImports
  nameWithType: ProjectLoadSettings.RejectCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Wskazuje, że wyjątek zostanie zgłoszony, gdy wykryte zostaną wszystkie Importy cykliczne"
  syntax:
    content: RejectCircularImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: Default
  nameWithType: ProjectLoadSettings.Default
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  parent: Microsoft.Build.Evaluation
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: RecordDuplicateButNotCircularImports
  nameWithType: ProjectLoadSettings.RecordDuplicateButNotCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: RejectCircularImports
  nameWithType: ProjectLoadSettings.RejectCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
