### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Execution.ProjectInstanceSettings
  id: ProjectInstanceSettings
  children:
  - Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  - Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  - Microsoft.Build.Execution.ProjectInstanceSettings.None
  langs:
  - csharp
  name: ProjectInstanceSettings
  nameWithType: ProjectInstanceSettings
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings
  type: Enum
  summary: "Zawiera ustawienia sterujące tworzenia wystąpienia projektu."
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectInstanceSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  id: Immutable
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  langs:
  - csharp
  name: Immutable
  nameWithType: ProjectInstanceSettings.Immutable
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Execution
  summary: "Utworzenie wystąpienia niezmienne projektu."
  syntax:
    content: Immutable
    return:
      type: Microsoft.Build.Execution.ProjectInstanceSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  id: ImmutableWithFastItemLookup
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  langs:
  - csharp
  name: ImmutableWithFastItemLookup
  nameWithType: ProjectInstanceSettings.ImmutableWithFastItemLookup
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Execution
  summary: "Utwórz niezmienne wystąpienie projektu z tabeli, która zwiększa wydajność wyszukiwania."
  syntax:
    content: ImmutableWithFastItemLookup
    return:
      type: Microsoft.Build.Execution.ProjectInstanceSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.None
  id: None
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  langs:
  - csharp
  name: None
  nameWithType: ProjectInstanceSettings.None
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.None
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Execution
  summary: "Utwórz wystąpienie projektu bez opcji."
  syntax:
    content: None
    return:
      type: Microsoft.Build.Execution.ProjectInstanceSettings
      description: "Do dodania."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  isExternal: false
  name: Immutable
  nameWithType: ProjectInstanceSettings.Immutable
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
- uid: Microsoft.Build.Execution.ProjectInstanceSettings
  parent: Microsoft.Build.Execution
  isExternal: false
  name: ProjectInstanceSettings
  nameWithType: ProjectInstanceSettings
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  isExternal: false
  name: ImmutableWithFastItemLookup
  nameWithType: ProjectInstanceSettings.ImmutableWithFastItemLookup
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.None
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  isExternal: false
  name: None
  nameWithType: ProjectInstanceSettings.None
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.None
